### ISSUE TITLE
Building dependencies fails

### ISSUE THREAD

**Issue by jklmnn** [Nheko-Reborn/nheko#10]
When building with dependencies mtxclient fails to build.

### System:

- Nheko version: 6ab12b2f6d876327ebd4cb91c4143066e6367f29 and a671bd62c49947cc4b4b8eb980a06501f497a400
- Installation method: local build
- Operating System: Debian Stretch
- Qt version: 5.7.1
- C++ compiler: GCC 6.3
- Desktop Environment: KDE Plasma 5.8.6

### Actual behavior

Running the commands from the readme:
```
cmake -Hdeps -B.deps
cmake --build .deps
```
The second command fails with
```
/.../nheko/.deps/build/mtxclient/lib/crypto/client.cpp: In function ‘std::__cxx11::string mtx::crypto::base642bin(const string&)’:
/.../nheko/.deps/build/mtxclient/lib/crypto/client.cpp:611:42: error: ‘sodium_base64_VARIANT_ORIGINAL’ was not declared in this scope
                                          sodium_base64_VARIANT_ORIGINAL);
                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/.../nheko/.deps/build/mtxclient/lib/crypto/client.cpp:611:72: error: ‘sodium_base642bin’ was not declared in this scope
                                          sodium_base64_VARIANT_ORIGINAL);
                                                                        ^
/.../nheko/.deps/build/mtxclient/lib/crypto/client.cpp: In function ‘std::__cxx11::string mtx::crypto::bin2base64(const string&)’:
/.../nheko/.deps/build/mtxclient/lib/crypto/client.cpp:626:63: error: ‘sodium_base64_VARIANT_ORIGINAL’ was not declared in this scope
           create_buffer(sodium_base64_encoded_len(bin.size(), sodium_base64_VARIANT_ORIGINAL));
                                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/.../nheko/.deps/build/mtxclient/lib/crypto/client.cpp:626:93: error: ‘sodium_base64_encoded_len’ was not declared in this scope
           create_buffer(sodium_base64_encoded_len(bin.size(), sodium_base64_VARIANT_ORIGINAL));
                                                                                             ^
/.../nheko/.deps/build/mtxclient/lib/crypto/client.cpp:632:57: error: ‘sodium_bin2base64’ was not declared in this scope
                           sodium_base64_VARIANT_ORIGINAL);
                                                         ^
CMakeFiles/matrix_client.dir/build.make:110: recipe for target 'CMakeFiles/matrix_client.dir/lib/crypto/client.cpp.o' failed
```

### Expected behavior

Nheko and all its dependencies compile.

### Steps to reproduce

```
git clone https://github.com/Nheko-Reborn/nheko.git && cd nheko && cmake -Hdeps -B.deps && cmake --build .deps 
```

### Logs

https://pastebin.com/ZxNHS1Uq

**Comment by jklmnn** [comment]
Debian Buster doesn't seem to be affected.

**Comment by redsky17** [comment]
Can you tell me what version of libsodium you have installed?  And when you installed it, did you install libsodium or libsodium-dev?

**Comment by jklmnn** [comment]
I have installed:
 - libsodium-dev in version 1.0.11-2
 - libsodium18 in version 1.0.11-2
Installing libsodium23 and libsodium-dev in version 1.0.16-2~bpo9+1 fixed the error.
Although I would have expected cmake to catch this earlier with a dependency error instead of a build error.

**Comment by jklmnn** [comment]
Also I get an error that my boost is too old although I have run `cmake -Hdeps -B.deps -DUSE_BUNDLED_BOOST=ON`. Is there something I need to supply to `cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=.deps/usr` for it to find the bundled boost?
Sorry for scope creeping this issue, but I don't want to open a new one for each minor issue I encounter.

**Comment by redsky17** [comment]
For the libsodium issue, it sounds like there is a minimum version requirement then.  I can definitely incorporate that in the cmake script once I figure out what version that is.  It'll end up as an issue on Nheko-Reborn/mtxclient rather than nheko itself.

Regarding the boost issue, could you share your build log when you use `-DUSE_BUNDLED_BOOST=ON`?  Typically, when I want to use the bundled boost, I leave that flag off altogether instead of specifying on.  I'm not sure if the build script checks the value of the flag, just that the flag was provided in the first place.

**Comment by jklmnn** [comment]
I tried both, using the flag and leaving it, both yields the same result. The build dep log is [here](https://pastebin.com/090R2cB2) (call was `git clone https://github.com/Nheko-Reborn/nheko.git && cd nheko && cmake -Hdeps -B.deps && cmake --build .deps`).
When calling `cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=.deps/usr` afterwards I get
```
-- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is GNU 6.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Found LMDB: /usr/include  
Build type set to 'Release'
-- Version: 0.6.2-6ab12b2
CMake Error at /usr/share/cmake-3.7/Modules/FindBoost.cmake:1831 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.62.0

  Boost include path: /usr/include

  Detected version of Boost is too old.  Requested version was 1.66 (or
  newer).
Call Stack (most recent call first):
  CMakeLists.txt:246 (find_package)


-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8") 
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.1.0j") 
-- Found OLM: /tmp/nheko/.deps/usr/include  
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29") 
-- Found cmark: /tmp/nheko/.deps/usr/include  
-- Configuring incomplete, errors occurred!
See also "/tmp/nheko/build/CMakeFiles/CMakeOutput.log".
See also "/tmp/nheko/build/CMakeFiles/CMakeError.log".
```
[CMakeError.log](https://github.com/Nheko-Reborn/nheko/files/2840982/CMakeError.log)
[CMakeOutput.log](https://github.com/Nheko-Reborn/nheko/files/2840983/CMakeOutput.log)

**Comment by redsky17** [comment]
I think the key component here is from your pastebin log:

```
CMake Warning at /usr/share/cmake-3.7/Modules/FindBoost.cmake:761 (message):
  Imported targets not available for Boost version 106800
```
Boost 1.68 requires CMake 3.13 or newer.  I think this is resulting in CMake somehow defaulting to an older version of Boost that it's compatible with, which doesn't work with nheko because it too old.  Could you update your CMake and try again?

It looks like I will need to update this line in CMakeLists
```
cmake_minimum_required(VERSION 3.1)
```

**Comment by redsky17** [comment]
From reading https://github.com/jedisct1/libsodium/blob/31ccbdec96aae4ecc705b0f7925cf0d092c49088/ChangeLog

It looks like the minimum required version of `libsodium` is `1.0.14` (That appears to be the version that adds `sodium_bin2base64' that is missing in your logs).  I'll be sure to update the cmake files to reflect this.

**Comment by jklmnn** [comment]
I have currently installed cmake 3.7.2-1. After upgrading to 3.13.2-1~bpo9+1 I rerun and the warning you pointed out seems to be missing from the [log](https://pastebin.com/KvWVLuDS). Yet when building nheko it still tries to use my system boost.

**Comment by redsky17** [comment]
Your log from building the dependencies looks good to me.  Can you share the log for the nheko build itself and the command you used to configure it?

**Comment by jklmnn** [comment]
The configure command is in the first line of the log (`git clone https://github.com/Nheko-Reborn/nheko.git && cd nheko && cmake -Hdeps -B.deps && cmake --build .deps`).
The build has the output:
```
$ cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=.deps/usr
Build type set to 'Release'
-- Version: 0.6.2-83d2d6d
CMake Error at /usr/share/cmake-3.13/Modules/FindBoost.cmake:2100 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.62.0

  Boost include path: /usr/include

  Detected version of Boost is too old.  Requested version was 1.66 (or
  newer).
Call Stack (most recent call first):
  CMakeLists.txt:250 (find_package)


-- Configuring incomplete, errors occurred!
See also "/tmp/nheko/build/CMakeFiles/CMakeOutput.log".
See also "/tmp/nheko/build/CMakeFiles/CMakeError.log".
```
[CMakeOutput.log](https://github.com/Nheko-Reborn/nheko/files/2845369/CMakeOutput.log)
[CMakeError.log](https://github.com/Nheko-Reborn/nheko/files/2845370/CMakeError.log)

**Comment by redsky17** [comment]
I've been playing around with this a little more.  Can you specify -DBOOST_ROOT=.deps/usr in the cmake command?  I think it should pick up the included boost version when you do that:

```
cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=.deps/usr -DBOOST_ROOT=.deps/usr
```

**Comment by jklmnn** [comment]
Thanks, that fixed it!
