### ISSUE TITLE
Display status message in user profile

### ISSUE THREAD

**Issue by maltee1** [Nheko-Reborn/nheko#1003]
### The Problem

Status messages now elide properly. But there is no option to see the full message, if you can't make the window any larger.

### The Solution

line-wrapped status messages should be shown in the user profile.

### Alternatives

show a popup of the status message upon tap.

### Happens in the latest version

- [X] Yes, this feature is still missing.

**Comment by deepbluev7** [comment]
While that is a good idea, maybe we should show the fulltext on hover too.

**Comment by LorenDB** [comment]
this was done in #1379
