### ISSUE TITLE
Image thumbnails sometimes get blurry and cropped

### ISSUE THREAD

**Issue by Linerly** [Nheko-Reborn/nheko#1004]
### Describe the bug

When I view an image, sometimes the image thumbnail gets blurry and cropped to a square, having to click the image to get a better look

### To Reproduce

1. View an image
2. See that it's either displayed fine or blurry and cropped

### What happened?

![Screenshot_20220320_171450](https://user-images.githubusercontent.com/47475676/159157668-3da0b132-f3d9-4da4-825d-2706dd6aa165.png)
![Screenshot_20220320_171520](https://user-images.githubusercontent.com/47475676/159157686-b3118da5-9123-403e-8a4b-f51e52fe1025.png)
![Screenshot_20220320_171617](https://user-images.githubusercontent.com/47475676/159157709-dce87e73-a5a9-4f0b-bcfd-857efa4427cc.png)

### Expected behavior

![Screenshot_20220320_171644](https://user-images.githubusercontent.com/47475676/159157724-6d4d8ebc-9667-4fba-889a-f87ad2decca3.png)

### Version

0.9.1-a307dc46

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Qt version

5.15.3

### C++ compiler

gcc 11.2.0

### Desktop Environment

KDE Plasma

### Did you use profiles?

- [X] Profiles used?

**Comment by deepbluev7** [comment]
This should have been fixed by https://github.com/Nheko-Reborn/nheko/commit/7a11b69f998553056b568d163c60aa635114fcd7

**Comment by Linerly** [comment]
I just updated to 0.9.2-15ff5dac, now the image thumbnails are displayed fine
