### ISSUE TITLE
Attachment encryption not compliant to spec

### ISSUE THREAD

**Issue by theCalcaholic** [Nheko-Reborn/nheko#1021]
## Description

*First of all, I'm reporting this on behalf of @Guest0x0, so I'm unaware of some specifics (Nheko version, system specs, etc.).*

According to Tulir, Nheko seems to be encrypting attachments in a non-spec-compliant way. This resulted in issues when bridging sent images.
For more details, see https://github.com/mautrix/telegram/issues/709

### To Reproduce

unknown (was reported by someone else)

But probably:

1. Install Nheko
2. Setup a mautrix Telegram bridge
3. Send some images

### Version

unknown

### Operating system

Linux

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment]
This was fixed already, please reopen if this actually happens with 0.9.2 or 0.9.3 still.
