### ISSUE TITLE
Autodiscovery failed

### ISSUE THREAD

**Issue by avdb13** [Nheko-Reborn/nheko#1023]
### Describe the bug

> Autodiscovery failed. Received malformed response.
I get this error message when trying to login with my account on my homeserver.

### To Reproduce

1. Open Nheko
2. Enter a username with a custom domain 

### Version

0.9.2

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc), Local build

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment]
Can you run it with --debug on the command line and share the log or alternatively tell me your homeserver?

**Comment by avdb13** [comment]
> Can you run it with --debug on the command line and share the log or alternatively tell me your homeserver?

gravitation.me

**Comment by deepbluev7** [comment]
That server returns 403 on .well-known/matrix/client. According to the spec, a client should show an error in that case: https://spec.matrix.org/latest/client-server-api/#well-known-uri

**Comment by avdb13** [comment]
Fixed by adding this to the NGINX handler listening on port 443. 
```
location /.well-known/matrix/client {
    return 200 '{"m.homeserver": {"base_url": "https://<matrix.example.com>"}}';
    default_type application/json;
    add_header Access-Control-Allow-Origin *;
}
```
