### ISSUE TITLE
Arrow keys stopped working in write message input field

### ISSUE THREAD

**Issue by linuxissuper** [Nheko-Reborn/nheko#1025]
### Describe the bug

Cannot use arrow keys anymore when writing a message.   
`ctrl` `a` also stopped working, maybe more keys/key combinations 

### To Reproduce

Just try to use the arrow keys when typing a message

### Version

0.9.3-f9942494

### Operating system

Linux

### Installation method

Flatpak nightly repo or download

### Desktop Environment

LXQt

### Did you use profiles?

- [X] Profiles used?

**Comment by deepbluev7** [comment]
Fixed
