### ISSUE TITLE
Sending a sticker results in crash

### ISSUE THREAD

**Issue by tastytea** [Nheko-Reborn/nheko#1026]
### Describe the bug

Sending a sticker crashed nheko. It is seemingly not reproducible. I can't post a backtrace because it is truncated…

`BFD: warning: /var/ram/core-nheko-1648614217-6-7218 is truncated: expected core file size >= 3418157056, found: 2087407616` (space on the partition was running out)

So it seems nheko was using over 3 GiB of memory… Not sure if that has something to do with the crash or if that is because *someone* posted several humongous animated images into the chat. 

### To Reproduce

I posted

```
{
    "content": {
        "body": "😂 Laughing little mole, with tears of joy",
        "info": {
            "h": 256,
            "mimetype": "image/webp",
            "size": 243804,
            "thumbnail_info": {
                "h": 256,
                "mimetype": "image/webp",
                "size": 243804,
                "w": 256
            },
            "thumbnail_url": "mxc://matrix.org/RqkwnBjUFhvHiGnoQmGjHDMg",
            "w": 256
        },
        "url": "mxc://matrix.org/RqkwnBjUFhvHiGnoQmGjHDMg"
    },
    "event_id": "$jiA1EhERgXKfg3_QjPB9Ov17YKZ-W8cGrkj0UgbyQVQ",
    "origin_server_ts": 1648614217377,
    "sender": "@tastytea:pixie.town",
    "type": "m.sticker",
    "unsigned": {
        "age": 35,
        "transaction_id": "mnlhpjOr0SGRJoBW7OzD2GEQhWfIjdMfn"
    }
}
```

### Version

0.9.3-6f0260d5

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Qt version

5.15.2

### C++ compiler

gcc-11.2.1 20220115

### Desktop Environment

n/a

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment]
Who would post several large images into a chat? That sounds rude... Aaaaanyway, I think I need a backtrace for this one.

**Comment by deepbluev7** [comment]
I think this is unrelated to sending a sticker, but instead was related to the animated image changing.

**Comment by deepbluev7** [comment]
I'm assuming this is fixed, since nobody complained about it in about a year :D
