### ISSUE TITLE
Typing / jumps to end of line

### ISSUE THREAD

**Issue by linuxissuper** [Nheko-Reborn/nheko#1027]
### Describe the bug

When I'm writing a message and I type a `/` , at the start of the input, then the cursor jumps to the end of the input field  
Then, when I move the cursor back, the first typed letter stays and all the following get inserted at the end of the input

### To Reproduce

Type something   
move cursor to start of input field   
press `/`
move cursor back to start and type something

### Version

0.9.3-82cdb483

### Operating system

Linux

### Installation method

Flatpak nightly repo or download

### Did you use profiles?

- [X] Profiles used?

**Comment by deepbluev7** [comment]
This was already fixed a few around the time you reported this, maybe slightly before or slightly after. You updated at a bad time I guess. Thanks for the report though!
