### ISSUE TITLE
Desktop UI - Register/Login do not display text with dark OS theme (MX Linux/Debian 11.3)

### ISSUE THREAD

**Issue by BanjoFox** [Nheko-Reborn/nheko#1028]
### Describe the bug

This is likely to be a corner case, but when running a dark theme on my MX Linux Desktop (Debian 11.3), the text on the black buttons for Register, and Login are also black.

Switching to a lighter theme, the text appears.  Screenshots are added.

INSTALLATION:
From the MX Linux repo (sudo apt install nheko)

### To Reproduce

Configure OS to Dark/Black theme
Open nheko (without logging in)
Check text visibility

Not ALL dark themes do this, but all themes affect visibility.

### Screenshots

-- Matcha Azul theme --
![nheko-Matcha_azul](https://user-images.githubusercontent.com/4459812/160893729-f88825ad-9310-46ed-8279-df8937859a67.png)
![nheko-white](https://user-images.githubusercontent.com/4459812/160892538-f5253e25-690b-46fd-b024-176687302703.png)

### Version

nheko/stable,now 0.8.0+really0.7.2-4 amd64 

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment]
Should be fixed since 0.9.2, your version is just really old.

**Comment by BanjoFox** [comment]
@deepbluev7 

That's good to know.
Guess I'll have to install Flatpak or build from source.
