### ISSUE TITLE
Clicking on the tray icon does not bring focus to Nheko's window when it is minimized

### ISSUE THREAD

**Issue by fpesari** [Nheko-Reborn/nheko#103]
Normally, clicking on a tray icon makes the program window visible (e.g. Telegram does it). And this works for Nheko as well, except when Nheko's window is minimized.

Clicking on the tray icon when Nheko is minimized makes Nheko reappear as a minimized window on the task bar. It does not make Nheko visible at all, which is the expected behavior.

I use LxQt, if this info can be useful.

**Comment by deepbluev7** [comment]
For me using KDE it behaves as follows:

- Without the minimize to try icon setting, it just closes
- With the setting on, clicking the tray icon removes the nheko window and also removes nheko from the task bar
- If nheko is minimized, it also removes it from the task bar, clicking the tray icon again makes nheko show again in the foreground.

It looks like I will need to test this on LxQt to reproduce that behaviour. Are you using the appimage? Have you compiled nheko yourself? A distro package? Version?

**Comment by fpesari** [comment]
I am using openSUSE, nheko 0.6.4 as packaged [here](https://build.opensuse.org/package/show/home:ecsos:messenger:matrix/nheko) (right now it does not build on OBS for some reason, probably some dependency, but it used to a few days ago)

**Comment by LorenDB** [comment]
@fpesari: it's been a while; could you verify if this is still an issue?

**Comment by fpesari** [comment]
Nope, not an issue anymore (on 0.11.1 and KDE Plasma but, if no regressions happened, there should be no problems on 0.11.3 as well).

**Comment by deepbluev7** [comment]
Thanks for testing! Yes, iirc I fixed that for 0.11.0.
