### ISSUE TITLE
Support for Stories (MSC3588)

### ISSUE THREAD

**Issue by Mikaela** [Nheko-Reborn/nheko#1038]
### The Problem

When I open a story room made with FluffyChat, I just see a read-only room and uploaded pictures without their captions.

### The Solution

* [ ] I would like to see stories in a UI similar to FluffyChat that when I opened a story room, it showed a single message at a time like a dia show. It would be best to check the FluffyChat.im implementation.

* [ ] Posting stories would be even  better

### Alternatives

The minimum I would like is to

* [ ] see story images and captions (which are visible through content body in view soruce of Element Web)

### Additional context

The spec proposal can be found from: https://github.com/matrix-org/matrix-spec-proposals/pull/3588

### Happens in the latest version

- [X] Yes, this feature is still missing.

**Comment by deepbluev7** [comment]
Can't you see the caption when hovering the file?

Otherwise I think full stories support is unlikely to happen in the near future, I never used such features and I do not intend to.

**Comment by Mikaela** [comment]
> Can't you see the caption when hovering the file?

Apparently I can see cropped captions that way, not the full text, so it doesn't help that much. I use stories several times a day.

**Comment by deepbluev7** [comment]
This MSC seems to be unsupported in all clients now, is this still a requested feature?

**Comment by Mikaela** [comment]
I guess I am withdrawing the request.

**Comment by vanyasem** [comment]
> This MSC seems to be unsupported in all clients now, is this still a requested feature?

Yep. The proposal was made by the developer of FluffyChat

The support for stories has been removed from FluffyChat as of [1.17.0](https://github.com/krille-chan/fluffychat/releases/tag/v1.17.0)

Stories were replaced with presence status messages in this pull request: https://github.com/krille-chan/fluffychat/pull/736

And the original proposal was never merged, and has been closed since
