### ISSUE TITLE
Open hyperlinks with custom programs

### ISSUE THREAD

**Issue by ElDifinitivo** [Nheko-Reborn/nheko#1039]
### The Problem

I hope this isn't too niche as most GUI programs I've used don't seem to have this, but the ability to be able to set a custom opener instead of xdg-open (Linux).

### The Solution

The default for software is to open hyperlinks in your browser; it's the expected behavior. However, it could be useful (for "power users" at least) who have separate setups to open URLs based on the URL mimetype/other criteria.

For example, I have a custom opener script that checks my `~/.mailcap` file so that any URL to direct images open up in `feh`, videos to `mpv`, pdfs to `zathura`, etc., with an additional parse prior so that for example imgur, gfycat links and the like open up in `mpv` instead of the browser.

This is an easy set-up for a custom opener when using any CLI apps with `alacritty`, and if others find this to be a good idea it could be something to look into.

### Happens in the latest version

- [X] Yes, this feature is still missing.

**Comment by ElDifinitivo** [comment]
I looked into it and it seems the best way is to create your own `.desktop` file that execs the custom opener, and setting that desktop file in `~/.config/mimeapps.list` as the default for `x-scheme-handler/http` and `https`.

Since this seems niche enough it may not warrant another look if the above is a good solution for anyone else wanting the same functionality.

**Comment by deepbluev7** [comment]
If you figure it out and want to share your solution, feel free to close this issue then. Maintaining such a handler in Nheko would probably be quite some effort, so some description of how people can easily use an alternative would be helpful. Although your current description is already quite helpful, I suppose.

**Comment by ElDifinitivo** [comment]
I can expand on the solution for sure. The current custom opener itself is somewhat of a mess as I wrote it years ago (a hobbyist and was still fairly new then), but I have plans to pretty much rewrite it and make it more consistent than it is in its current state (there are some edge cases that don't properly behave).

I'll edit this with a link to the revamped opener in the next few weeks (currently called `mimcap` as seen below), but below are the snippets for `~/.local/share/applications/<opener>.desktop` and `~/.config/mimeapps.list`

mimcap.desktop

```desktop
[Desktop Entry]
Type=Application
Name=mailcap opener
Exec=mimcap %u
StartupNotify=false
```

mimeapps.list

```
[Default Applications]
x-scheme-handler/http=mimcap.desktop
x-scheme-handler/https=mimcap.desktop
```

**Comment by deepbluev7** [comment]
thank you <3
