### ISSUE TITLE
nheko -v should not care if another instance is running

### ISSUE THREAD

**Issue by fpesari** [Nheko-Reborn/nheko#104]
Right now typing `nheko -v` when an instance of Nheko is running displays the "Another instance of Nheko is running" message box without actually displaying the version. It should print out the version on the terminal regardless if another instance is running or not, because the `-v` flag does not launch the GUI program.

**Comment by deepbluev7** [comment]
This should be easy to fix whenever someone touches #84 .

**Comment by Minoru** [comment]
As of 0.7.2, `nheko -v` prints out *nothing* if an instance is already running. A slightly different kind of broken, but broken still :)

**Comment by deepbluev7** [comment]
In those cases Nheko just activates the other Window, I guess.

**Comment by deepbluev7** [comment]
fixed in #736
