### ISSUE TITLE
Send image on Enter and cancel on Escape

### ISSUE THREAD

**Issue by loliconshik3** [Nheko-Reborn/nheko#1041]
### The Problem

When i try to send image from my clipboard i have one problem - i can't send it by pressing Enter key.
When i try to cancel this image - i can't do it by pressing Escape key. Why?

### The Solution

I want to send images on Enter and cancel it on Escape. Please.

### Additional context

![image](https://user-images.githubusercontent.com/69761732/162588369-6863a0be-be24-482e-9e49-71b49fd89892.png)

### Happens in the latest version

- [X] Yes, this feature is still missing.

**Comment by deepbluev7** [comment]
So the reason I am hesitant so far on adding send on enter is that I am not sure what should take priority, the message input or the media upload. We probably need to hide either one, so that people don't activate the wrong one by accident.
