### ISSUE TITLE
FR: Allow switching keyboard shortcuts for Send/New Line

### ISSUE THREAD

**Issue by ZoomRmc** [Nheko-Reborn/nheko#1044]
### The Problem

Matrix supports sending multiline messages, so to some users it's more convenient to use the standard key for entering a new line `Enter` and a modified key `Ctrl+Enter` to send a message.

This feature is available in Element and has historically been available in many IM programs.

### The Solution

Add an option to switch the bindings for these two actions.

### Happens in the latest version

- [X] Yes, this feature is still missing.

**Comment by sc0w** [comment]
I prefer the opposite, <kbd>enter</kbd> send message, and <kbd>control</kbd><kbd>enter</kbd> new line , like other apps does.

**Comment by ZoomRmc** [comment]
Thanks a lot!
