### ISSUE TITLE
question/feature request: http connection

### ISSUE THREAD

**Issue by BrainDamage** [Nheko-Reborn/nheko#105]
### System:
- Nheko version: 0.6.4
- Installation method: local build
- Operating System: arch linux

I have a small homeserver that I connect through a VPN, the server is not exposed to the internet nor is part of the federated network, so I don't want/need to setup a https certificate, my vpn is already a sufficient measure of defence.
When I try to connect to the homeserver using riot and the http protocol, everything works fine.
When I try to connect to my homeserver using nheko, I get a spinning wheel that stays there indefinetly.
my homeserver is reachable at the address http://alarmserver.local:8008 where alarmserver.local is a mdns address which is resolved correctly by my computer.
I've tried to put http://alarmserver.local:8008  and http://ip:8008 but nheko claims the address is not valid
If I enter just the dns and the port it lets me proceed, but it gets stuck into an infinite spinning wheel.
A quick check of stdout shows me
ssl3 ext invalid servername
Which makes me suspect it's attempting to forcibly using tls/ssl despite the lack of setup in my server.
Am I understanding correctly? If so, would it be possible to add an option to use plain http to connect?

**Comment by deepbluev7** [comment]
Yes, you are correct, that nheko currently doesn't allow plain http connections. I think I dropped support for them, because I had some issues with it. Http also has the issue, that if the user isn't made aware of it, he won't know, that his password was transferred unencrypted. So support could definitely be added, but it would need some looking into.

**Comment by deepbluev7** [comment]
See also: https://github.com/Nheko-Reborn/mtxclient/pull/19
