### ISSUE TITLE
Feature Request: Emoji Shortcodes

### ISSUE THREAD

**Issue by TheDrawingCoder-Gamer** [Nheko-Reborn/nheko#1052]
### The Problem

Transitioning from discord, I have memorized some emoji shortcodes. I'm disappointed that this shortcodes aren't present in nheko.

### The Solution

I would like shortcodes (or at the very least optional aliases) to be added to nheko. Discord ones would be nice, but customizable ones would work too.

### Happens in the latest version

- [X] Yes, this feature is still missing.

**Comment by deepbluev7** [comment]
We mostly haven't done that, since there are no good, freely available lists of shortcodes, that are kept up to date and easy to consume automatically.

**Comment by TheDrawingCoder-Gamer** [comment]
Would it be possible to at least expose a json or some config file?

**Comment by deepbluev7** [comment]
Currently emojis are a static configuration generated from this: https://github.com/Nheko-Reborn/nheko/blob/master/scripts/update_emoji.md

An alternative, which we considered, was allowing to configure custom emotes for text emoji like we did for image emoji, which is kinda like json, just stored server side.

**Comment by TheDrawingCoder-Gamer** [comment]
Ok. I can manually edit the file as well and rebuild. Would be lovely if there was an on the fly config tho ❤️

**Comment by TheDrawingCoder-Gamer** [comment]
Now that I think about it - discord and friends don't fully make short codes. Only commonly used emojis have shortcodes - otherwise they just trim & replace spaces. Perhaps doing something similar would work.

**Comment by deepbluev7** [comment]
I think you fixed that <3
