### ISSUE TITLE
Forced to re-log-in if DBUS isn't available on startup

### ISSUE THREAD

**Issue by TheBlueMatt** [Nheko-Reborn/nheko#1053]
### Describe the bug

If I run nheko without dbus running (cause its usually running in a container and I usually forget to say `dbus-run-session` before I write nheko) it'll complain that it can't connect to dbus to load secrets (totally expected). When I restart it with `dbus-run-session`, however, instead of seeing my chats I end up back at the login screen with the latest nheko data seemingly cleared.

### To Reproduce

1. Start nheko in an environment with no dbus, observe shutdown
2. Restart with dbus running, end up back at the login screen.

### Version

0.9.1-1-debian

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Did you use profiles?

- [ ] Profiles used?

**Comment by LorenDB** [comment]
@deepbluev7: I'm thinking this might have been fixed. Am I correct in thinking that?

**Comment by deepbluev7** [comment]
We show a dialog now, where you can cancel to fix your environment, which should be good enough for now.
