### ISSUE TITLE
variability of sending messages

### ISSUE THREAD

**Issue by 13werwolf13** [Nheko-Reborn/nheko#1057]
### The Problem

most instant messengers have a convenient ability to switch sending messages from enter to ctrl+enter.
it’s convenient, logical, and doesn’t make every time you remember “and how to do line break now”.

### The Solution

you must add to the settings a item that allows you to change the sending action of the message from enter to ctrl+enter

### Happens in the latest version

- [X] Yes, this feature is still missing.

**Comment by deepbluev7** [comment]
Duplicate of #1044 (and #788 is related)
