### ISSUE TITLE
Close current room via Escape

### ISSUE THREAD

**Issue by loliconshik3** [Nheko-Reborn/nheko#1059]
### The Problem

When i press Escape with opened room - it doesn't close this room, but when i just click on room with left mouse button - it close them. Why?

### The Solution

Add room closing via pressing Escape key, like in Telegram.

### Happens in the latest version

- [X] Yes, this feature is still missing.

**Comment by deepbluev7** [comment]
Duplicate of #1034 

We decided to use Ctrl-W, because Escape conflicts with cancelling and edit etc and that makes it annoying to use.
