### ISSUE TITLE
Feature request: connect to localhost (for pantalaimon)

### ISSUE THREAD

**Issue by pmwhite** [Nheko-Reborn/nheko#106]
Since the E2EE support is not perfect, I decided to try to use pantalaimon, which is a proxy that you run from localhost which handles all the E2EE stuff for the client.

https://github.com/matrix-org/pantalaimon

Right now Nheko understandably requires the homeserver domain to be valid, which disallows connecting to localhost.

**Comment by deepbluev7** [comment]
In theory this works now, but I haven't tested it.

**Comment by realyukii** [comment]
how to connect to localhost? I simply type `localhost` in the input field, but it can't connect? I tried to connect to `conduit`:

<img width="1066" height="600" alt="Image" src="https://github.com/user-attachments/assets/d4bd7d46-0416-44fa-aae3-b6da6677efb4" />

```
[reyuki@zero ~]$  ss -tlpn | grep -i conduit
LISTEN 0      1024                                   127.0.0.1:8000       0.0.0.0:*    users:(("conduit",pid=214411,fd=23))  
[reyuki@zero ~]$ 
```

**Comment by realyukii** [comment]
typing `127.0.0.1:8000` isn't work either.
