### ISSUE TITLE
Support more image formats (HEIF)

### ISSUE THREAD

**Issue by UgnilJoZ** [Nheko-Reborn/nheko#1070]
### The Problem

Hi! I noticed Nheko seems to have no support for images in HECV (HEIC) and in AVIF format:
![Bildschirmfoto vom 2022-05-03 02-16-44](https://user-images.githubusercontent.com/7910828/166345743-ce3d32f7-72e0-488f-a0d0-34894b723422.png)

### The Solution

It would be really nice to be able to view those types of images.

### Alternatives

Element and FluffyChat (only other clients I checked) have basic support for these images.

### Happens in the latest version

- [X] Yes, this feature is still missing.

**Comment by deepbluev7** [comment]
The image support for those is handled by qt image format plugins. You can install kimageformats to get support for those formats.

**Comment by UgnilJoZ** [comment]
I am using the `io.github.NhekoReborn.Nheko` Flathub package. Installing kimageformats on the host system seems not to work here.

**Comment by deepbluev7** [comment]
Yeah, it needs to be in the flatpak. I would have hoped those are already present in the KDE image, but seems like we need to install them ourselves.

**Comment by ser** [comment]
Hello, it looks that HEIC/HEIF image format is still not available in Nheko from flatpak. 

From my understanding it was fixed in Ubuntu with this bug:

https://bugs.launchpad.net/ubuntu/+source/kimageformats/+bug/1951278

So it's possible and requires just a proper flag during build configuration.

Can we overcome this problem in Nheko as well?

**Comment by deepbluev7** [comment]
The flag is passed here: https://github.com/Nheko-Reborn/nheko/blob/master/io.github.NhekoReborn.Nheko.yaml#L134

**Comment by ser** [comment]
OK, so why I can't see these images then?

**Comment by deepbluev7** [comment]
I don't know, maybe the plugin isn't loaded? You can try the QT_DEBUG_PLUGINS environment variable to see, if the plugin is found or not.

**Comment by ser** [comment]
I can't see anything meaningful with
```
QT_DEBUG_PLUGINS=1 flatpak run io.github.NhekoReborn.Nheko
```
Can I please ask you again if you really see these HEIC images using nheko on your desktop? Sorry for being annoying but 90% of images people send me are invisible which drives me crazy.
