### ISSUE TITLE
Privacy screen can't be disabled in latest Nheko master

### ISSUE THREAD

**Issue by lbeltrame** [Nheko-Reborn/nheko#1076]
### Describe the bug

Privacy screen activates after timeout, but it is not removed after interacting with the application again (the application itself remains functional).

### To Reproduce

1. Activate the privacy screen in settings
2. Leave Nheko idle (minimize) until the timeout expires
3. Activate the Nheko window

### What happened?

Privacy screen did not turn off and the whole main window was blurred.

### Expected behavior

Privacy screen should turn off when application is interacted with.

### Version

0.9.3-908f6215

### Operating system

macOS

### Installation method

macOS DMG file

### Did you use profiles?

- [ ] Profiles used?

**Comment by redsky17** [comment]
I noticed this yesterday on my MacBook and thought it might have been due to a recent OS update, but I guess not.  I’ll look into it.  Thanks for the report

**Comment by redsky17** [comment]
Fixed (partially) via [d130c96](https://github.com/Nheko-Reborn/nheko/commit/d130c961605e67c6771bfe78c3bb1b7e6205e3a8).  This only works for the main window, however.  Any rooms that are 'Opened Separately' via the new functionality Nico added don't currently have support for the Privacy Screen.

**Comment by redsky17** [comment]
When the build finishes, please try the new DMG.  It should fix your issue.  You can track build process here: https://nheko.im/nheko-reborn/nheko/-/pipelines/3139

When the 'codesign-macos' job finishes, there should be a new DMG available in the nightly channel on matrix.

**Comment by redsky17** [comment]
And now it works in all popped out windows via 7f2ae13c
