### ISSUE TITLE
Add copy room link function to context menu

### ISSUE THREAD

**Issue by linuxissuper** [Nheko-Reborn/nheko#1079]
### The Problem

Actually I don't know how I can find the room link with nheko

### The Solution

copy room link function in context menu, when right clicking on room   
e. g. Element:
![image](https://user-images.githubusercontent.com/74221543/169689468-f7ef68fd-c134-40e6-a9f4-d7e112bc9e02.png)

### Happens in the latest version

- [X] Yes, this feature is still missing.

**Comment by deepbluev7** [comment]
We should definitely add that. As a temporary workaround, you can create an event link and remove the event from it for now. Anyone implementing this might benefit from looking at how that works.
