### ISSUE TITLE
VoIP support

### ISSUE THREAD

**Issue by zack-emmert** [Nheko-Reborn/nheko#109]
While I know Nheko doesn't currently support Matrix VoIP, I'm wondering how much interest there is in adding it in the near future, and what needs to happen for it to be implemented.

**Comment by redsky17** [comment]
All of the VOIP stuff requires WebRTC as far as I'm aware.  While this support does exist in Qt, it would require us to bump the Qt version to 5.13 as a minimum.  This would cause issues with folks using older versions of Qt.  Not that we can't technically only enable VOIP for users with newer Qt runtimes.  It's definitely on our backlog of stuff to work on, but it will not be in the upcoming 0.7.0 release.

**Comment by ddobrev** [comment]
I will also use nheko if it supports VOIP with E2E, it would be [the only native desktop client to do so](https://matrix.org/clients-matrix/). Please add my vote.

**Comment by deepbluev7** [comment]
Since VOIP is pretty involved, if anyone want to pick it up, I would be happy to provide support, but otherwise don't expect this any time soon.

**Comment by adasauce** [comment]
Just dropping a note here as it's been mentioned in the riot room a lot.

If someone is looking to contribute this feature: there is no interest in embedding qt webengine, webkit, chromium, or any other browser to help handle WebRTC. nheko's raison d'être is escaping browser based matrix clients.

**Comment by Kommynct** [comment]
why should we enable people to use older versions of qt? shouldn't everyone be using the most recent version? why would should we care about the inconvenience of having to upgrade?
genuine questions, not me telling you what to do

**Comment by deepbluev7** [comment]
@Kommynct We want to support the latest version of Debian, Ubuntu and friends. That way it is easy to provide a PPA to install Nheko without using something like Flatpak, Snap or Appimage. That reduces memory and disk usage and is far easier to package in many cases. If we require a newer Qt version, than is available in those distros, anyone who wants to build, contribute or package Nheko on those platforms will need to install an additional Qt version. Unless there are big benefits, we want to avoid creating additional hurdles for potential contributors or packagers.

If there are reasons for bumping the Qt requirements, we can do it, but we won't, if it can be avoided. Also I think the WebRTC support in QT 5.13 is just via QtWebengine, which we don't want to depend on anyway.

**Comment by redsky17** [comment]
Nheko has official packages available on various distributions of Linux via their official repositories.  Those repositories don't always have up-to-date versions of Qt available.  Hence, if we make a hard requirement on 5.13 or newer, we would be alienating users on stable distributions that won't be updated to officially include new versions of Qt for years to come.  

Additionally, Qt WebEngine is basically no better than Electron.  So we don't even want to use it at all and will likely use Gstreamer instead.

**Comment by physkets** [comment]
> will likely use Gstreamer instead

Isn't [PipeWire](https://www.pipewire.org/) a better choice at this point?

**Comment by deepbluev7** [comment]
@physkets No, I don't think so. PipeWire is more like jack or pulseaudio, just also for video. This means, it won't do the video decoding part, handle WebRTC protocol, etc. You wouldn't use Pulseaudio to stream audio from multiple remote desktops on the internet or decode flac files. It is just used for routing audio on a system (which may include speakers on the LAN etc). PipeWire may be used in the backend, when we access the webcam/microphone/speakers, but GStreamer should handle that transparently, afaik. Also PipeWire is Linux only, so that wouldn't help us either on other platforms.

**Comment by ptman** [comment]
so this has seen some progress lately?

**Comment by deepbluev7** [comment]
Yeah, you can do voice calls now, when you have the correct GStreamer version, see #237 for more info.

**Comment by deepbluev7** [comment]
This is mostly done. Any remaining issues should be reported separately, I'd say.
