### ISSUE TITLE
Rework the pins UI

### ISSUE THREAD

**Issue by Midou36O** [Nheko-Reborn/nheko#1096]
### The Problem

The current pins UI looks like the telegram pins UI, it doesn't look good.
![image](https://user-images.githubusercontent.com/45198486/173579462-062c8756-bdf4-4c13-a990-fe8f88ae0500.png)

### The Solution

Rework the pins UI to make it a button that opens a new window to show pins (the Qt way like how [ripcord](https://cancel.fm/ripcord/) does it) or make it pop inside like how element does it (picture below)
![image](https://user-images.githubusercontent.com/45198486/173580325-9744573c-98c4-44f8-a010-4865a862d523.png)

### Happens in the latest version

- [X] Yes, this feature is still missing.

**Comment by deepbluev7** [comment]
No. Pin's should be shown in an obvious location. Otherwise they are useless (like currently in Element). That they currently don't fetch old events is a different bug :3

**Comment by deepbluev7** [comment]
(I might have closed it a bit quickly, but pinned messages won't be moving to some hidden sidebar. I use them as an extension of the topic and so they will stay below the topic :3)

**Comment by deepbluev7** [comment]
I don't like implementing options, that I don't use :3

You can already hide pins, if you want. The pins are just on a different side of the screen.

**Comment by Odyssey346** [comment]
Maybe do like Telegram and allow the user to "scroll" the pins instead? It would use less space.

**Comment by Midou36O** [comment]
> Maybe do like Telegram and allow the user to "scroll" the pins instead? It would use less space.

it does scroll actually, it's not visible, i just realised that

**Comment by Odyssey346** [comment]
> > Maybe do like Telegram and allow the user to "scroll" the pins instead? It would use less space.
> 
> it does scroll actually, the scroll bar not visible tho so you can't tell, i just realised that

In that case, make it compacter like Telegram. Then itd look good in my opinion

**Comment by deepbluev7** [comment]
Hm, on my screen the 200px it has are already quite narrow... I don't really know what percentage of the screen would be good for it?

**Comment by deepbluev7** [comment]
![grafik](https://user-images.githubusercontent.com/16312324/173926373-363f9e68-f0b8-4f6d-9ca2-6036b5d0461c.png)

**Comment by Midou36O** [comment]
![image](https://user-images.githubusercontent.com/45198486/173928320-ffaa747e-5406-481f-b181-4b669aa38e08.png)
this is the resolution i use for the window, it doesn't show the scroll bar at all

**Comment by deepbluev7** [comment]
(The stable windows release has no scrollbar because of a bug)

**Comment by Midou36O** [comment]
I'm running Gnome DE on linux

**Comment by deepbluev7** [comment]
Well, this affect all stable releases on all platforms (I misread your message)
