### ISSUE TITLE
QPainter::HighQualityAntialiasing is deprecated in Qt 5.14

### ISSUE THREAD

**Issue by Riesi** [Nheko-Reborn/nheko#110]
When I remove the deprecated antialiasing hint nheko builds fine.

### System:

- Nheko version: 0.7.0-dev (4bcb423b02ac6837bb05f8cb5c0677a28e7a9aac)
- Installation method: `yay -S nheko-git`
- Operating System: ArchLinux
- Qt version: 5.14.0
- C++ compiler: g++ (GCC) 9.2.0
- Desktop Environment: i3wm

### Actual behavior
Build fails due to deprecated antialiasing hint.
```
~/.cache/yay/nheko-git/src/nheko-git/src/ui/Painter.h:144:76: error: ‘QPainter::HighQualityAntialiasing’ is deprecated: Use Antialiasing instead [-Werror=deprecated-declarations]
  144 |                                                                  QPainter::HighQualityAntialiasing};
      |                                                                            ^~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/qt/QtGui/QPainter:1,
                 from ~/.cache/yay/nheko-git/src/nheko-git/src/CommunitiesListItem.h:5,
                 from ~/.cache/yay/nheko-git/src/nheko-git/src/CommunitiesListItem.cpp:1:
/usr/include/qt/QtGui/qpainter.h:93:9: note: declared here
   93 |         HighQualityAntialiasing Q_DECL_ENUMERATOR_DEPRECATED_X("Use Antialiasing instead") = 0x08,
      |         ^~~~~~~~~~~~~~~~~~~~~~~
```

### Steps to reproduce
Install/Build nheko-git on an up to date Arch installation with Qt 5.14.0

**Comment by deepbluev7** [comment]
I fixed that on the 0.7.0-dev branch in bcd97f2fb23fdf82cc33215661003eb6e121a5fc . I will remove the Werror by default soon too, but that is part of a bigger refactoring of the build system, so that will take a bit. I think -Werror should only be the default in development and CI builds.
