### ISSUE TITLE
Question: How to use SSO?

### ISSUE THREAD

**Issue by gibcheesepuffs** [Nheko-Reborn/nheko#1103]
I have an account on modular.mozilla.im. When I open nheko I cannot find a way to login with SSO.
![1](https://user-images.githubusercontent.com/17274550/175340149-7251c09a-09bf-42b4-9514-63d7f64cc41c.png)
![2](https://user-images.githubusercontent.com/17274550/175340163-54e40c9e-03ed-4922-8f4a-b25848b0f469.png)

**Comment by deepbluev7** [comment]
Enter a matrix id that ends in :mozilla.org, i.e. @a:mozilla.org

**Comment by gibcheesepuffs** [comment]
Thank you, it works now!
