### ISSUE TITLE
No number of notifications in space sidebar

### ISSUE THREAD

**Issue by gardenBanter** [Nheko-Reborn/nheko#1104]
### Describe the bug

The icons of rooms and DMs show a bubble containing number of notifications in the room, but the spaces sidebar doesn't do this for the spaces. This makes it very hard to figure out where your notification actually is when you're in multiple spaces.

### To Reproduce

1. Be member of several spaces
2. Receive notifications in rooms in them
3. Observe that there are notification bubbles for the rooms but not for the spaces

### Expected behavior

A space's icon should show a bubble containing the sum of the numbers of notifications in the rooms belonging to the space. 

### Version

0.9.3

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment]
See also #1062

**Comment by gardenBanter** [comment]
> See also #1062

Oh, seems more like a duplicate issue. Feel feel to close if you think this.

**Comment by deepbluev7** [comment]
More like you reported an issue that someone was already working on fixing :3

**Comment by LorenDB** [comment]
#1062 was merged
