### ISSUE TITLE
Empty space when right-clicking on a message

### ISSUE THREAD

**Issue by BlitDev** [Nheko-Reborn/nheko#1112]
### Describe the bug

When you right-click on any message, a piece of empty space is displayed on top.

### To Reproduce

1. Go to some chat
2. Right click on some message
3. See error

### Screenshots

![image](https://user-images.githubusercontent.com/79034202/177100270-05b107b4-7e29-4c2f-9984-961aeb3b5059.png)

### Version

0.9.3-65d58fe

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Desktop Environment

Arch linux with Xfce4 DE

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment]
Have you tried right clicking a message that is further up? It looks like the menu is scrolled down, which might be because of the screen dimensions.

**Comment by deepbluev7** [comment]
No, I didn't mean screensize, I meant that because the menu would intersect the bottom border of the screen, that the menu is moved up as well as scrollable and that causes the issue that there is empty space at the top. Which would be easy to verify by trying to open the menu further up in the timeline.

**Comment by BlitDev** [comment]
> 

![image](https://user-images.githubusercontent.com/79034202/177331148-ee18c9e7-028a-46a1-8129-1ab0b2656f6b.png)

**Comment by deepbluev7** [comment]
Thanks. This is about what I expect, the menu interacting badly with the screen boundaries. I don't think there is much we can do to fix that currently, since that requires the screen bounds to be properly set by Qt, but Qt6 should fix that.

**Comment by deepbluev7** [comment]
This should be fixed, but it would be great if someone could confirm once they use the qt6 nightly :)

**Comment by deepbluev7** [comment]
Please reopen if it isn't fixed on the master branch :)
