### ISSUE TITLE
Crash during new login

### ISSUE THREAD

**Issue by maxtar** [Nheko-Reborn/nheko#1113]
### Describe the bug

After trying to login the program crashed.

### To Reproduce

1. Start program
2. In window with "Register" "Login" button press "login".
3. Input userid on matrix.org server.
4. Press _Enter_ or click to _password_ field.

### What happened?

Program crashed.

### Expected behavior

Program loginned successfully.

### Version

nheko 0.7.2

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Desktop Environment

KDE

### Did you use profiles?

- [ ] Profiles used?

### Relevant log output

```shell
ssl3 ext invalid servername
ssl3 ext invalid servername
[2022-07-04 22:56:35.238] [ui] [info] jdenticon plugin not found.
[2022-07-04 22:56:35.244] [ui] [info] starting nheko 0.7.2
[2022-07-04 22:56:51.416] [net] [info] Autodiscovery: No .well-known.
[2022-07-04 22:57:00.739] [net] [info] Autodiscovery: Discovered 'https://matrix-client.matrix.org'
terminate called after throwing an instance of 'std::invalid_argument'
  what():  v1.1: invalid version
```

**Comment by deepbluev7** [comment]
See the pinned issue #957 , you need to update.

**Comment by maxtar** [comment]
This is the last version from repository.

**Comment by deepbluev7** [comment]
Well, the bug is already fixed. Either use the flatpak, build Nheko yourself or figure out how to get a newer version on your specific distro. Thank you for reporting it though, even if it is a duplicate!
