### ISSUE TITLE
change background color of current message hovering over

### ISSUE THREAD

**Issue by linuxissuper** [Nheko-Reborn/nheko#1117]
### The Problem

When I want to use the context menu, that appears when hovering over a message, it is sometimes hard to see, if I got the right one

### The Solution

Highlighting/changing the background color of the line currently under the cursor would make it easy to see

### Additional context

When hovering the last line
![image](https://user-images.githubusercontent.com/74221543/179344467-c641386d-8ac2-4a1c-8408-72273f1325cd.png)
When hovering the second line
![image](https://user-images.githubusercontent.com/74221543/179344488-31601114-c795-4e32-91b2-e50ca348128a.png)

### Happens in the latest version

- [X] Yes, this feature is still missing.

**Comment by deepbluev7** [comment]
https://user-images.githubusercontent.com/16312324/179351444-aea58b64-c5f1-4c55-b273-934307d189e1.mp4

**Comment by linuxissuper** [comment]
sorry, wasn't aware  
and also my system theme broke this 🙈

**Comment by deepbluev7** [comment]
No worries, it happens to all of us at some point :3
