### ISSUE TITLE
Flag to ignore SSL certificate checks

### ISSUE THREAD

**Issue by BurnyBoi** [Nheko-Reborn/nheko#1118]
### The Problem

I am attempting to use nheko within my LAN. my LAN's nginx instance pointing to my synapse uses a self-signed cert that is different than the one my domain uses. When attempting to login, I get the following errors in the UI and console respectively:

![Untitled](https://user-images.githubusercontent.com/41203525/179365744-6a1bfd4f-ac42-4ec2-8554-c13f79257443.png)

`[2022-07-16 13:29:49.656] [net] [error] Autodiscovery failed. Unknown error when requesting .well-known. 0 60`

I also have a plain http port for logging in within my LAN as well, and if I attempt to use that instead, I get this:

![Untitled2](https://user-images.githubusercontent.com/41203525/179365842-26758f1a-5179-4216-a015-bb75ce9b16ed.png)

`[2022-07-16 13:33:10.623] [crypto] [critical] failed to upload one time keys: (connection: SSL peer certificate or SSH remote key was not OK)`

### The Solution

Add a flag to ignore SSL certificate checks for the homeserver. There are times (like this) where cert checks are expected to fail, which is why most https clients have an option to conditionally ignore these checks.

### Alternatives

- Don't connect within the LAN (ew, unnecessary latency)
- Get a valid certificate for my domain within my LAN's nginx (can't for networking reasons I'd rather not ramble on about)
- Change Nheko to allow skipping connecting over https entirely when the user has typed an http homeserver address (use the http address typed for ALL connections, regardless of the domain in the MXID/well-known). Related: #105

### Happens in the latest version

- [X] Yes, this feature is still missing.

**Comment by BurnyBoi** [comment]
Looking at #626 , It seems like the curl env variables mentioned there would be what I need, but I'm struggling to understand from this documentation what exactly I should be setting. Assuming my domain name is `example.com` above, does anyone have an idea what I could set to get Nheko to work?

**Comment by deepbluev7** [comment]
You can disable certificate verification by adding this flag to your config file (in the global section): https://github.com/Nheko-Reborn/nheko/blob/master/src/UserSettingsPage.cpp#L154

You can also use http: urls to login, the problem why you are getting an error is actually that your local synapse returns a response telling Nheko to switch to https. I think you can disable that by setting your public base url appropriately.

**Comment by BurnyBoi** [comment]
@deepbluev7  I set `disable_certificate_verification` to true in my `~/.config/nheko/nheko.conf`, and when attempting to login again using https I'm getting this output:

```
[2022-07-16 16:09:30.061] [ui] [info] Restoring window size 958x1229
[2022-07-16 16:09:30.077] [ui] [info] WebRTC: initialised GStreamer 1.20.3
[2022-07-16 16:09:30.359] [ui] [info] jdenticon plugin not found.
[2022-07-16 16:09:30.755] [ui] [info] starting nheko 0.9.3-65d58fe
[2022-07-16 16:09:38.014] [net] [error] Autodiscovery failed. Unknown error when requesting .well-known. 0 60
[2022-07-16 16:09:52.495] [net] [error] Error requesting versions: (connection: SSL peer certificate or SSH remote key was not OK)
[2022-07-16 16:10:04.889] [net] [error] Error requesting versions: (connection: SSL peer certificate or SSH remote key was not OK)
```

If I attempt to use the http:// URL for my LAN like my screenshot above instead I get this:

```
[2022-07-16 16:11:47.806] [ui] [info] Restoring window size 958x1229
[2022-07-16 16:11:47.816] [ui] [info] WebRTC: initialised GStreamer 1.20.3
[2022-07-16 16:11:48.037] [ui] [info] jdenticon plugin not found.
[2022-07-16 16:11:48.320] [ui] [info] starting nheko 0.9.3-65d58fe
[2022-07-16 16:19:14.844] [net] [info] Login requested to use server: https://[REDACTED].com/
[2022-07-16 16:19:14.864] [db] [info] initializing LMDB
[2022-07-16 16:19:14.864] [ui] [info] Switching to chat page
[2022-07-16 16:19:14.936] [qml] [warning] qrc:/qml/ChatPage.qml:104:17: QML RoomList: Binding loop detected for property "implicitWidth" (qrc:/qml/ChatPage.qml:104, )
[2022-07-16 16:19:14.936] [qml] [warning] qrc:/qml/ChatPage.qml:104:17: QML RoomList: Binding loop detected for property "implicitWidth" (qrc:/qml/ChatPage.qml:104, )
[2022-07-16 16:19:14.999] [db] [info] database ready
[2022-07-16 16:19:14.999] [crypto] [info] creating new olm account
[2022-07-16 16:19:15.000] [crypto] [info] generating one time keys
[2022-07-16 16:19:15.021] [net] [warning] failed to retrieve own profile info
[2022-07-16 16:19:15.024] [net] [warning] Failed to retrieve backup version
[2022-07-16 16:19:15.024] [crypto] [critical] failed to upload one time keys: (connection: SSL peer certificate or SSH remote key was not OK)
[2022-07-16 16:19:15.031] [ui] [info] dropping to the login page: Failed to setup encryption keys. Server response:  0. Please try again later.
[2022-07-16 16:19:15.033] [db] [info] deleted cache files from disk
[2022-07-16 16:19:15.084] [db] [info] Storing secret 'pickle_secret' successful
[2022-07-16 16:19:16.992] [qml] [warning] QObject::killTimer: Timers cannot be stopped from another thread (:0, )
[2022-07-16 16:19:16.992] [qml] [warning] QObject::startTimer: Timers cannot be started from another thread (:0, )
```

I'm reading in the synapse sample config that `public_baseurl` should be what public facing users should type to access my server. Wouldn't I potentially break functionality for them if I set this to my LAN's http address instead?

**Comment by deepbluev7** [comment]
>  I set disable_certificate_verification to true in my ~/.config/nheko/nheko.conf, and when attempting to login again using https I'm getting this output:

It doesn't look like you put it in the right section? Did you put it at the very top of the config file in the first line?

> I'm reading in the synapse sample config that public_baseurl should be what public facing users should type to access my server. Wouldn't I potentially break functionality for them if I set this to my LAN's http address instead?

Sure, but this value makes Nheko switch to that url, which you can see is a https:// url. Nheko is just following the spec there.

**Comment by BurnyBoi** [comment]
It was already there set to false in the config file that was generated by nheko, so I just changed it to true:

```
[General]
disable_certificate_validation=true

[user]
alert_on_notification=false
animate_images_on_hover=false
automatically_share_keys_with_trusted_users=false
avatar_circles=true
bubbles_enabled=false
camera=
camera_frame_rate=
camera_resolution=
collapsed_spaces=@Invalid()
currentProfile=
decrypt_sidebar=true
desktop_notifications=true
emoji_font_family=emoji
font_family=
font_size=9
group_view=true
hidden_pins=@Invalid()
hidden_tags=@Invalid()
hidden_widgets=@Invalid()
markdown_enabled=true
microphone="M-Audio Fast Track at usb-0000:00:14.0-13, full speed"
minor_events=true
mobile_mode=false
online_key_backup=true
only_share_keys_with_verified_users=false
open_image_external=false
open_video_external=false
presence=AutomaticPresence
privacy_screen=false
privacy_screen_timeout=0
read_receipts=true
recent_reactions=@Invalid()
ringtone=Default
screen_share_frame_rate=5
screen_share_hide_cursor=false
screen_share_pip=true
screen_share_remote_video=false
sidebar\community_list_width=45
sidebar\room_list_width=218
small_avatars_enabled=false
sort_by_unread=true
theme=system
timeline\buttons=true
timeline\enlarge_emoji_only_msg=false
timeline\max_width=0
timeline\message_hover_highlight=false
typing_notifications=true
use_identicon=true
use_stun_server=false
window\start_in_tray=false
window\tray=false

[window]
height=1229
width=958
```

**Comment by deepbluev7** [comment]
Hm, that should work after restarting Nheko.

**Comment by deepbluev7** [comment]
(another alternative is of course always to just add the cert to your systems certificate store)

**Comment by BurnyBoi** [comment]
> (another alternative is of course always to just add the cert to your systems certificate store)

At this point that's probably worth looking into before trying anything further. Seems like a lot of headaches avoided if it works

**Comment by deepbluev7** [comment]
It's also just the proper solution in the first place, since it means you don't have to disable security features.

**Comment by chagai95** [comment]
Thx, just disabled the cert and it works now

**Comment by realyukii** [comment]
I tried to set `disable_certificate_validation=true` but still have same error message:

<img width="1066" height="600" alt="Image" src="https://github.com/user-attachments/assets/ef6c95a1-1de4-4fab-94e9-ba0aa6e0bb8b" />

```
[2025-08-19 12:17:06.672] [net] [error] Autodiscovery failed. Unknown error when requesting .well-known. (connection: SSL peer certificate or SSH remote key was not OK)
```

<img width="1066" height="600" alt="Image" src="https://github.com/user-attachments/assets/41e09402-9578-46d4-ab9e-429626459e37" />

```
[2025-08-19 12:18:20.564] [net] [info] Autodiscovery: Discovered 'https://localhost'
```

It was fine on cURL though:
```
[reyuki@zero ~]$  curl -k -v https://localhost:8000
* Host localhost:8000 was resolved.
* IPv6: ::1
* IPv4: 127.0.0.1
*   Trying [::1]:8000...
* connect to ::1 port 8000 from ::1 port 40888 failed: Connection refused
*   Trying 127.0.0.1:8000...
* ALPN: curl offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384 / X25519MLKEM768 / RSASSA-PSS
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=localhost
*  start date: Aug 19 05:11:04 2025 GMT
*  expire date: Aug 17 05:11:04 2035 GMT
*  issuer: CN=localhost
*  SSL certificate verify result: self-signed certificate (18), continuing anyway.
*   Certificate level 0: Public key type RSA (2048/112 Bits/secBits), signed using sha256WithRSAEncryption
* Connected to localhost (127.0.0.1) port 8000
* using HTTP/2
* [HTTP/2] [1] OPENED stream for https://localhost:8000/
* [HTTP/2] [1] [:method: GET]
* [HTTP/2] [1] [:scheme: https]
* [HTTP/2] [1] [:authority: localhost:8000]
* [HTTP/2] [1] [:path: /]
* [HTTP/2] [1] [user-agent: curl/8.15.0]
* [HTTP/2] [1] [accept: */*]
> GET / HTTP/2
> Host: localhost:8000
> User-Agent: curl/8.15.0
> Accept: */*
>
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* Request completely sent off
< HTTP/2 200
< content-type: text/plain; charset=utf-8
< content-security-policy: sandbox; default-src 'none'; script-src 'none'; plugin-types application/pdf; style-src 'unsafe-inline'; object-src 'self';
< vary: origin, access-control-request-method, access-control-request-headers
< access-control-allow-origin: *
< content-length: 19
< date: Tue, 19 Aug 2025 05:12:12 GMT
<
* Connection #0 to host localhost left intact
Hello from Conduit!
```
