### ISSUE TITLE
Improve DBus API by not sending icons with `rooms`

### ISSUE THREAD

**Issue by LordMZTE** [Nheko-Reborn/nheko#1124]
### The Problem

The DBus `im.nheko.Nheko.rooms` method is incredibly slow, taking multiple seconds to transmit all the data when many rooms are joined. This happens because the image data for the icons of **all** rooms is transmitted.

### The Solution

Change the `rooms` endpoint so it doesn't return icons and add a new endpoint that returns an icon given a room ID.

### Alternatives

¯\_(ツ)_/¯

### Additional context

This is very unfortunate when writing room switchers, as you end up leaving the user waiting for the rooms to show.

### Happens in the latest version

- [X] Yes, this feature is still missing.

**Comment by Cadair** [comment]
:+1: :100: Opening krunner is now distressingly slow.
