### ISSUE TITLE
[windows] duplicate start menu entries

### ISSUE THREAD

**Issue by ghost** [Nheko-Reborn/nheko#1127]
### Describe the bug

installer creates a start menu folder, then on run created a second entry outside the folder

### To Reproduce

1. install nheko on windows
2. allow start menu folder creation
3. run nheko
4. check start menu

### What happened?

duplicate entries in start menu

### Expected behavior

only one entry, either in a folder or not

### Screenshots

![screenshot_2022-07-23_154247](https://user-images.githubusercontent.com/99516846/180622239-0589a14d-530b-4362-aaf4-f95f91e6678a.png)

### Version

0.10.0-7df260f5

### Operating system

Windows

### Installation method

Windows download

### Did you use profiles?

- [ ] Profiles used?

**Comment by JeanPaulLucien** [comment]
Windows 7 and Nheko 0.10.2 are okay.

**Comment by LorenDB** [comment]
I'm going to speculate that old installers created a folder and newer installers aren't doing that. If so, that would explain the two different shortcuts? I don't have this problem either.

**Comment by ZeusOfTheCrows** [comment]
same issue on windows 10 after installing once then not updating; so it's not a disparity between two different installers. it's consistent with the casing in this issue as well: capitalised "Nheko" outside the folder, and lowercase "nheko" in a capitalised folder

**Comment by LorenDB** [comment]
OK, it appears that https://github.com/Nheko-Reborn/nheko/blob/master/deploy/installer/gui/installscript.qs#L16 and https://github.com/Nheko-Reborn/nheko/blob/master/deploy/installer/config.xml#L11 are creating the two conflicting entries, so removing one of those should fix the problem. @deepbluev7, I'm leaning towards creating a shortcut without a folder but I'd appreciate a +1 before actually making the PR :)

**Comment by deepbluev7** [comment]
This will be fixed with the msix, since we don't create any entries anymore :)
