### ISSUE TITLE
join room text doesnt not clearly identify the room to join

### ISSUE THREAD

**Issue by ghost** [Nheko-Reborn/nheko#1129]
### Describe the bug

when joining a room the dialog only shows the id not name of the room. searching shows the name not id. users cannot confirm the join with the given info

split this off from https://github.com/Nheko-Reborn/nheko/issues/1128 at request

### To Reproduce

1. search for a public room by name
2. choose to join the room
3. observe id in the confirmation dialog

### What happened?

id is presented for confirmation without room name

### Expected behavior

room name at least is clear in the confirmation. id can be there too but users expect the name to match their search selection

### Screenshots

![screenshot_2022-07-23_143336](https://user-images.githubusercontent.com/99516846/180782608-844b18f1-6722-4b28-8505-ad70d22717d0.png)

### Version

0.10.0-7df260f5

### Operating system

Windows

### Installation method

Windows download

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment]
Can you check if the latest nightly fixes this for you? :3
