### ISSUE TITLE
Mention and reply highlighting

### ISSUE THREAD

**Issue by DeskworkTrickster** [Nheko-Reborn/nheko#1136]
### The Problem

It is really hard to keep track on mentions and replies in the chat timeline.

### The Solution

I think there are three scenarios for highlighting:

1. Replies to messages in general: (Already implemented and fine as it is in my opinion)
2. Replies to messages I wrote: (There is no difference from general replies at the moment)
Keep the general idea of the highlighting, but extend it to the right side of the chat screen, so its visually different from other replies, that are not related to me.
3. Mentions that are important to me: (Not implemented at all at the moment.)
This relates to mentions like "at room" or "at me". Highlighting it the same way as replies to myself, would keep it simple and uniform.

Any thoughts on that topic are welcome of course.

### Alternatives

There is room for a better UX experience of course, but I think the way I described it above shouldn't be too hard and still deliver a lot of benefits.

### Additional context

A subset of this is mentioned here as well. #400 

### Happens in the latest version

- [X] Yes, this feature is still missing.

**Comment by DeskworkTrickster** [comment]
The concept should also work with "chat bubbles" enabled I think.

**Comment by Cadair** [comment]
Related to #400
