### ISSUE TITLE
[windows] New message popup has wrong text

### ISSUE THREAD

**Issue by evren320** [Nheko-Reborn/nheko#1137]
### Describe the bug

When new message arrives, popup has text like this:
%1 sent an encrypted message

Linux version has correct text, only windows version is affected.

### To Reproduce

Wait for new message popup appears, and see the wrong text.

### Version

0.10.0

### Operating system

Windows

### Installation method

Windows download

### Desktop Environment

KDE Plasma desktop

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment]
Can you check it if the nightly fixes it? (Currently still building)

**Comment by evren320** [comment]
how do i download newest nightly build? i just found a link that shows at most 29 jul 2022 build which still has the bug

**Comment by deepbluev7** [comment]
This one should do: https://matrix-static.neko.dev/room/!TshDrgpBNBDmfDeEGN:neko.dev/

**Comment by evren320** [comment]
> This one should do: https://matrix-static.neko.dev/room/!TshDrgpBNBDmfDeEGN:neko.dev/, needed to restart that service...
Links for 1 August are broken, gives following json response on click:
{"errcode":"M_NOT_FOUND","error":"Not found [b'neko.dev', b'hsOJVtEisorVkXzPUxHgCopJ']"}

**Comment by deepbluev7** [comment]
(I had to delete some media, which included all historical releases, since I ran out of disk space. Anything after august 1st should be fine though)
