### ISSUE TITLE
Nheko going on a crashing spree

### ISSUE THREAD

**Issue by vielkanka** [Nheko-Reborn/nheko#1140]
### Describe the bug

The first version of this bug I encountered was of me 
- downloading an audio file
- followed up by me trying to open that file in an external program (and failing)
- afterwards, I closed Nheko, and started it up again
- I had to redownload the audio file, except I couldn’t do that because, whenever I didn’t, Nheko would crash 
- It ended with me uninstalling Nheko

afterwards, every time I installed Nheko (which was either through Flatpak’s App Store, or through the terminal), I would be unable to log in, as every time I inputted my Matrix ID in, Nheko crashed. Registering a new account? Couldn’t do that either, since, even after I’d completed the Captcha, I couldn’t register, and had to do the Captcha again (and again and again and…you get what I mean)

### To Reproduce

1. Try installing audio file
2. Try opening it up in external program
4. Fail/See errors*
5. Close Nheko, and re-open
6. Try installing audio file again
7. Fail*
8. Delete Nheko 
9. Reinstall Nheko 
10. Try logging in (or registering a new account
11.  See error(s)
*not sure how you’d actually reproduce these. These are the best ideas I’ve got

### What happened?

Unable to log in without crashing
Unable to register
Unable to open audio file in external application

### Expected behavior

Log in, or register new account. 
Download and open up audio file in an external application

### Version

 Version 0.10.0

### Operating system

Linux

### Installation method

Flathub

### Desktop Environment

Cinnamon on Linux Mint

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment]
I believe this is fixed and if it isn't, we need a backtrace where it actually crashes.
