### ISSUE TITLE
libmatrix_client.so.0.7.0 not available only 0.8.0 OpenSuse Tumbleweed

### ISSUE THREAD

**Issue by merinleona** [Nheko-Reborn/nheko#1148]
nheko: error while loading shared libraries: libmatrix_client.so.0.7.0: cannot open shared object file: No such file or directory

I can only install 0.8.0 but Nheko needs 0.7.0 therefore I cannot use it. The thing is the newer libmatrix is from the same place as Nheko itself, so is there just an error in heko that it is looking for the wrong file?

**Comment by deepbluev7** [comment]
That's just a broken package, not our fault.

**Comment by LorenDB** [comment]
I'm on Tumbleweed and the nheko package is fine for me. I assume you are installing from network: messaging:matrix?

**Comment by merinleona** [comment]
> I'm on Tumbleweed and the nheko package is fine for me. I assume you are installing from network: messaging:matrix?

URL: https://download.opensuse.org/repositories/network:/messaging:/matrix/openSUSE_Tumbleweed/



> That's just a broken package, not our fault.

Sorry I thought you package those. Do you know who does so I can report this there?

**Comment by deepbluev7** [comment]
Nope, I have no idea who packages that, but if you look at the changelog of the rpm file, it should tell you who last modified it.

**Comment by LorenDB** [comment]
I have been packaging the last few and submitting them since the package maintainer seems to not see the new releases. However, I don't consider myself the maintainer.

**Comment by merinleona** [comment]
> I have been packaging the last few and submitting them since the package maintainer seems to not see the new releases. However, I don't consider myself the maintainer.

Could you add libmatrix 0.7 to network: messaging:matrix then?

**Comment by LorenDB** [comment]
The best solution would be to upgrade the nheko package to 0.10.0 ;)

**Comment by merinleona** [comment]
> The best solution would be to upgrade the nheko package to 0.10.0 ;)

That would totally work for me too, if the requirement for libmatrx updates with that version :D

**Comment by LorenDB** [comment]
The maintainer has updated the package to 0.10.0. Can you see if that works for you?

**Comment by merinleona** [comment]
Sadly no. Now I am getting a new error:

nheko: symbol lookup error: nheko: undefined symbol: _ZN3mtx6common15parse_relationsERKN8nlohmann16json_abi_v3_11_210basic_jsonISt3mapSt6vectorNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEblmdSaNS2_14adl_serializerES5_IhSaIhEEEE

**Comment by LorenDB** [comment]
Can you share the output of `zypper if libmatrix_client0_8_0`?

**Comment by merinleona** [comment]
I could but I updated libmatrix and it works now :)

**Comment by LorenDB** [comment]
Awesome!
