### ISSUE TITLE
Long lines of text (widget state keys) cluttering and expanding the top bar

### ISSUE THREAD

**Issue by foresto** [Nheko-Reborn/nheko#1154]
### Describe the bug

In some rooms, Nheko shows mysterious text below the Topic field in the room header.

The format of the text varies. Sometimes it looks like a Matrix room ID combined with other information. Other times it looks like this:  jitsi_@username:matrix.org_1234567890123

In some rooms, it appears just once on a single line. In others, the line repeats, with a scroll bar in cases with >= 3 lines. Some rooms don't show it at all.

### To Reproduce

1. Go to a room. (All mine are encrypted; I don't know if this makes a difference.)
2. Look for mysterious text in the room header, just below the room name and topic.
3. If it's not there, try other rooms until you find one with the text.

### What happened?

Extra lines of text with no obvious meaning are shown in the room header. They are distracting clutter, expanding the header to consume precious screen space, leaving less room for conversation text.

### Expected behavior

No mysterious junk using up screen space and distracting me.

### Screenshots

![nheko-mystery-header](https://user-images.githubusercontent.com/322134/184569313-3ccc4bf0-c1ce-4899-b1c2-4b14ab11170b.jpg)

### Version

0.10.0

### Operating system

Linux

### Installation method

Locally built flatpak using the Flathub .yaml file

### Qt version

5.15.2

### C++ compiler

whatever flatpak-builder 1.0.12 uses on debian stable (bullseye)

### Desktop Environment

KDE Plasma 5.20.5

### Did you use profiles?

- [ ] Profiles used?

**Comment by foresto** [comment]
Looking closer, I see that rooms with more than one of these strings are not repeating the same string after all; a number at the end is different for each one. That number turns out to be a unix timestamp, in milliseconds. Once I realized that, I was able to scroll back over a year or two of message history in Element, to see what happened at that date and time.

Turns out these mysterious strings are state_key values from old widget creation events. (Event type: "im.vector.modular.widgets") These rooms have never had an integration server, so I guess Element (Riot) must have created the events with some built-in widget feature. One of them is a link to an external web page that's totally unrelated to Matrix. The others look like Jitsi conference calls.

Is Nheko stuffing these state keys into the room's top bar because it wants to show placeholders for widgets that it can't handle?

**Comment by foresto** [comment]
Element doesn't show any of these widgets, so I dug through the timeline history of each relevant room. I found that every one of the widget creation events is followed by a matching removal event.

So, I think there are two issues here:

1. Nheko is wasting screen space a with long, cryptic, unexplained event ID string in the top bar for every widget it is aware of. This more than doubles the height of the top bar in some cases. Wouldn't a single icon/button be sufficient to indicate that unsupported widgets are present, perhaps with a pop-up explanation and list of the IDs if the user clicks it?
2. Nheko is not honoring widget removal events. It stuffs another cryptic ID string in the top bar for every widget that was ever created in the timeline. Wouldn't it be better to skip the ones that are no longer active?

**Comment by deepbluev7** [comment]
Yeah, when I changed how Nheko handles empty state events, I forgot to amend the widget code to ignore widgets without any values set.

**Comment by foresto** [comment]
Looks like this is fixed in the latest master, probably by 130e1b43fbc62eec1d3a5add8e15b1ef8863dcff. Thanks!

**Comment by deepbluev7** [comment]
Thanks for closing this, I completely forgot about it again :D
