### ISSUE TITLE
Can't see entire font family name

### ISSUE THREAD

**Issue by ChungZH** [Nheko-Reborn/nheko#1164]
### Describe the bug

Can't see entire font family name when I want to select a Font family.

### To Reproduce

1. Go to 'Settings'
2. Click on 'Font Family'
3. See error

### Screenshots

![image](https://user-images.githubusercontent.com/42088872/186311065-3705addc-6135-4155-8947-bbdf351cd94e.png)

### Version

0.10.0-7df260f5

### Operating system

Windows

### Installation method

Windows download

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment]
We can only fix that after the qt6 migration.
