### ISSUE TITLE
No close button when open separately

### ISSUE THREAD

**Issue by ChungZH** [Nheko-Reborn/nheko#1168]
### Describe the bug

No close button.

### To Reproduce

1. Right click on a chat
2. Click on 'Open separately'
3. See error

### Expected behavior

have a close button

### Screenshots

![image](https://user-images.githubusercontent.com/42088872/186545946-d97123af-1def-42a6-bd48-1a0931861706.png)

### Version

0.10.0-7df260f5

### Operating system

Windows

### Installation method

Windows download

### Did you use profiles?

- [ ] Profiles used?

**Comment by nico-famedly** [comment]
That's the good old "child windows don't get close button in some environments" bug again. (It does have a close button on my system)

**Comment by ChungZH** [comment]
Is it a bug of Qt? Btw, my os is Windows 11.

**Comment by deepbluev7** [comment]
Yes and no, some WMs just react to hints differently so we need to explicitly request a close button.

**Comment by deepbluev7** [comment]
That might fix it?
