### ISSUE TITLE
how to install gstreamer plugins for voice calls (dtls, srtp, webrtc)

### ISSUE THREAD

**Issue by Feedison** [Nheko-Reborn/nheko#1171]
I'm kinda new to Linux Ubuntu and I've never seen before matrix clients.
I tried to install dtls through pypi `pip install Dtls`
it gave me output 
```
Defaulting to user installation because normal site-packages is not writeable
Collecting Dtls
  Using cached Dtls-1.2.0.tar.gz (79 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-y4n1x44k/dtls_eb03828965294eb0911d61784e7d65c3/setup.py", line 53, in <module>
          long_description = open("README.md").read()
      FileNotFoundError: [Errno 2] No such file or directory: 'README.md'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
from the official page: dtls 1.2.0 has been tested on Ubuntu 16.10
what do I do?

**Comment by deepbluev7** [comment]
pip is the wrong package manager, install the dependencies via apt: https://packages.ubuntu.com/kinetic/nheko

Are those not enough? How did you install Nheko?

**Comment by Feedison** [comment]
> pip is the wrong package manager, install the dependencies via apt: https://packages.ubuntu.com/kinetic/nheko
> 
> Are those not enough? How did you install Nheko?

i did it through `sudo apt install nheko`, then I tried to voice call and it requires those plugins @deepbluev7

**Comment by Feedison** [comment]
i don't know what I did, but it started working.
