### ISSUE TITLE
Show power level of User in room on "Room User Profile" tab

### ISSUE THREAD

**Issue by NebulaOnion** [Nheko-Reborn/nheko#1173]
### The Problem

/

### The Solution

By clicking on the user profile picture on a room, the Power level should be displayed as a separate string, something like "Power Level: 100 (Admin)" or "Power Level: 50 (Mod)".

### Alternatives

I'm not aware of any alternative way of implementing this.

### Happens in the latest version

- [X] Yes, this feature is still missing.

**Comment by LorenDB** [comment]
We currently show an icon that indicates whether the user is regular, a mod, or an admin. If you hover over that, you get a tooltip showing the PL. I think that should probably be sufficient indication.
