### ISSUE TITLE
None of proposed fonts display all emojis correctly (Windows)

### ISSUE THREAD

**Issue by NicoPy** [Nheko-Reborn/nheko#1178]
### Describe the bug

On my machine (Windows 10), none of the fonts I can select displays emojis correctly.

### To Reproduce

1. Go to User Parameters
2. Select a emoji font

The choices I have :
![image](https://user-images.githubusercontent.com/8762261/188209840-67b6c90d-44d6-4d44-8dc2-34a8cc57d701.png)

### What happened?

Not all emoji are displayed:

![image](https://user-images.githubusercontent.com/8762261/188210243-87fade97-6c21-4238-a321-501a161cd472.png)

### Expected behavior

A font with all emojis should be selectable.

Is there a special one to use ?

### Version

0.10.0-7df260f5

### Operating system

Windows

### Installation method

Windows download

### Did you use profiles?

- [ ] Profiles used?

**Comment by redsky17** [comment]
This is more or less an issue with windows rather than nheko.  Windows ships a font that contains whatever Unicode standard related to emojis.  I’m not sure what windows 10 targets… maybe Unicode 13.0?  Microsoft can update this at their leisure (or not).  By contrast, we update emoji definitions every time there’s an update to the Unicode specification.  As a result, we often have emoji defined that don’t exist in the font that ships with windows.

If you want an emoji font that updates more regularly with the Unicode specification, I recommend looking into and installing Noto Color Emoji and selecting that in your drop down.

**Comment by NicoPy** [comment]
I agree that Windows should provide a decent font for emojis. 
However, when the OS can't do something it is the responsibility of the application to manage it. 
Other Matrix client applications do not have any problem with emojis since they manage them by themselves. 
For example, Element embeds the Noto font and the library to use it (the Noto font is not compatible with Windows font manager).

**Comment by redsky17** [comment]
We do not ship a font with nheko nor do we have any intentions of ever doing that (with a single caveat that we might need to at some point ship a reduced version of twemoji if that ever becomes the SAS key verification emoji standard, which is not the case right now).

Windows 10 absolutely supports the format that noto color emojis use as of the anniversary update: https://docs.microsoft.com/en-us/windows/win32/directwrite/color-fonts#what-kinds-of-color-fonts-does-windows-support (see the CBDT/CBLC section).

**Comment by NicoPy** [comment]
My bad for the font support. I read some obsolete information.
However, I discovered that Noto font is already installed on my machine but Nheko does not allow me to select it.

**Comment by redsky17** [comment]
> Noto font is already installed on my machine but Nheko does not allow me to select it.

It might have something to do with how we're querying the available fonts from Qt.  We are using https://doc.qt.io/qt-5/qfontdatabase.html#families, providing the `QFontDatabase::WritingSystem::Symbol` type as our filter.  So to me that implies that Noto Color Emoji doesn't report being a 'symbol' font on Windows.

Does it show up under the 'Font Family' dropdown at all?  If not, that to me implies that it's not being picked up by Qt's font database system on Windows for whatever reason.

**Comment by NicoPy** [comment]
Yes, I was just investigating this way. There are many Noto fonts available on the Internet. The one that was already installed on my machine is not declared as a _Symbol_ type font.
But there is something weird.
Here are the _symbol_ fonts installed on my system :
![image](https://user-images.githubusercontent.com/8762261/188235441-7dda033f-fce0-4ec3-88d4-423f3aff8dad.png)

And here the list I have in Nheko :
![image](https://user-images.githubusercontent.com/8762261/188236054-a75fed78-b8fa-4a59-b89b-f3aa5155eae0.png)

The two do not match. Maybe the filter is on more than just _Symbol_ ?

I have installed a correct Noto font for emojis : _[NotoColorEmoji_WindowsCompatible](https://github.com/googlefonts/noto-emoji/blob/main/fonts/NotoColorEmoji_WindowsCompatible.ttf)_.
Now, selecting _OpenSymbol_ or _Reem Kufi_ seems to be OK. All symbols seem to show correctly. That's very strange.
The _NotoColorEmoji_WindowsCompatible_ font does not appear in Nheko font selection.
The _Reem kufi_ font seems to not be a _Symbol_ font but it appears in Nheko font selection.

...

Ha, the `NotoColorEmoji_WindowsCompatible` font has been installed in `C:\Users\Nicolas\AppData\Local\Microsoft\Windows\Fonts`, not in `C:\Windows\Fonts`. That may explain why it does not appear in Nheko.

**Comment by NicoPy** [comment]
I now have uninstalled the _NotoColorEmoji_WindowsCompatible_ font from my system and the behaviour of Nheko is back to the original one.

**Comment by NicoPy** [comment]
Reinstalling the _NotoColorEmoji_WindowsCompatible_ font does not make the emoji display correctly again. So the other Noto font was of some importance here.

Forgot to say that _NotoColorEmoji_WindowsCompatible_ appears in the Nheko font selection list.

Another weird thing : _NotoColorEmoji_WindowsCompatible_ does not appear in `C:\Windows\Fonts` when installed for all users but it appears in Control Panel font management (I know, this is not Nheko business but is this of some importance here ?).
