### ISSUE TITLE
Nheko not launching on Arch/Artix

### ISSUE THREAD

**Issue by voltage-volkoz** [Nheko-Reborn/nheko#1179]
### Describe the bug

I have nheko and mtxclient from the AUR, the pgp key is locally signed after adding..
[home_digital_mystik_AUR_Arch]
Server = https://download.opensuse.org/repositories/home:/digital_mystik:/AUR/Arch/x86_64/
I cleared cache and configs for nheko, checked for update, nheko and mtxclient both seem to be updated, but nheko wont launch. nheko: error while loading shared libraries: libfmt.so.8: cannot open shared object file: No such file or directory

### What happened?

Recently i noticed Nheko wasn't launching (installed from the AUR), i added what I was supposed to in /etc/pacman.conf and got the key signed, I removed ~/.cache/nheko ~/.config/nheko ~/.local/share/nheko then did 'sudo pacman -Syu nheko' but still can not get Nheko to launch on Artix Linux, I do get an error saying "nheko: error while loading shared libraries: libfmt.so.8: cannot open shared object file: No such file or directory"

### Screenshots

![nheko](https://user-images.githubusercontent.com/56435468/188279404-9b7377bd-f4da-40ec-84eb-761122b14b28.png)

### Version

nheko-0.10.0-1

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Desktop Environment

KDE with Kwin

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment]
You need to rebuild Nheko after rebuilding spdlog. This is a packaging issue, talk to your package maintainer if they are building the package and not you.

**Comment by q234rty** [comment]
In particular you need to remove the unofficial repo [home_digital_mystik_AUR_Arch] and rebuild both coeurl and nheko from AUR: `paru/yay -Sa --rebuild coeurl nheko` should do the trick.

**Comment by voltage-volkoz** [comment]
> In particular you need to remove the unofficial repo [home_digital_mystik_AUR_Arch] and rebuild both coeurl and nheko from AUR: `paru/yay -Sa --rebuild coeurl nheko` should do the trick.

![rebuild](https://user-images.githubusercontent.com/56435468/188280237-b23b461f-cc82-4620-a6a9-874d6dfb6bc6.png)

**Comment by q234rty** [comment]
You procably need
```
paru/yay -Sa --rebuild coeurl
paru/yay -Sa --rebuild mtxclient
paru/yay -Sa --rebuild nheko
```
then.
(I remember mtxclient is not linked to libfmt but apparently I'm wrong)
