### ISSUE TITLE
Forwarding stickers doesn't work

### ISSUE THREAD

**Issue by q234rty** [Nheko-Reborn/nheko#1182]
### Describe the bug

Nheko doesn't seem to support forwarding stickers, for stickers the forward button is shown in the right click menu but it does nothing.

### To Reproduce

1. Try to forward a sticker.

### What happened?

Nothing happens.

### Expected behavior

The sticker is forwarded.

### Version

0.10.1-9b751fe6

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Qt version

5.15.6

### C++ compiler

gcc

### Desktop Environment

sway

### Did you use profiles?

- [X] Profiles used?

**Comment by JeanPaulLucien** [comment]
Windows 7, 0.10.2, confirms.
