### ISSUE TITLE
Newline after link (</a>\n) is not rendered as newline

### ISSUE THREAD

**Issue by heylix** [Nheko-Reborn/nheko#1192]
### Describe the bug

If you send the following message via hitting Shift+Enter, it gets rendered as two lines:

```json
    "content": {
        "body": "This is a message\nspanning two lines",
        "msgtype": "m.text"
    },
```

But if you send this:

```json
    "content": {
        "body": "here is a link https://mhanational.org/10-healthy-ways-release-rage\nand this doesn't get rendered in two lines",
        "format": "org.matrix.custom.html",
        "formatted_body": "here is a link <a href=\"https://mhanational.org/10-healthy-ways-release-rage\">https://mhanational.org/10-healthy-ways-release-rage</a>\nand this doesn't get rendered in two lines",
        "msgtype": "m.text"
    },
```

It gets rendered in a single line – even though the method of trying to create a newline in both messages (Shift+Enter) was the same, only that in one message the link was at the end of the line.

Maybe related to #757? Only that there it's the italic preventing a newline.

### To Reproduce

1. enter a sentence without a link and hit Shift+Enter in the middle
2. enter a sentence with a link right before hitting Shift+Enter
3. see the difference

### Expected behavior

Both methods of creating a newline with Shift+Enter should net the same results or rather be rendered the same way.

### Version

0.10.0-7df260f

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Desktop Environment

KDE with Kwin in X11

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment]
That's because one is sent as markdown and one is not. I don't think this is really a bug, it is just a weird behaviour of switching from text to markdown. How do you think this should behave?

**Comment by LorenDB** [comment]
This was fixed recently
