### ISSUE TITLE
Floating windows don't respect QT theme (or its lack)

### ISSUE THREAD

**Issue by asakura42** [Nheko-Reborn/nheko#1195]
### Describe the bug

I use `QT_QPA_PLATFORMTHEME=gtk2` but even with unset or `qt5ct` floating windows stay white on white in dark colorscheme.

I installed `nheko-git` from AUR.

### To Reproduce

1. Open Nheko
2. Set dark colorscheme
3. Press anything which triggers floating window to pop up

### Screenshots

![screenshot](https://c-v.sh/soundproofeighty.png)

### Version

0.10.1-d103f793

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment]
This is pretty weird, I can't reproduce it at all.

**Comment by deepbluev7** [comment]
I think this should be better on qt6 now, but we did have to add an explicit workaround.
