### ISSUE TITLE
Can't update ceph or ceph-libs from the AUR

### ISSUE THREAD

**Issue by voltage-volkoz** [Nheko-Reborn/nheko#1206]
### Describe the bug

Nheko no longer works and appears to need ceph and ceph-libs updated, but i can't rebuild the latest version of them because it aborts during installation.

### To Reproduce

.

### Screenshots

![ceph](https://user-images.githubusercontent.com/56435468/194776231-88c1b9cc-6b6e-4341-833a-3cede3e268fe.png)
![version](https://user-images.githubusercontent.com/56435468/194776397-f92e53de-d5c0-4c64-960c-5a334866bf7a.png)

### Version

Nheko 0.10.2-1 & ceph(libs) 15.2.17-1

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Desktop Environment

KDE with Kwin

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment]
Nothing in your output suggests this has to do anything with Nheko.

**Comment by deepbluev7** [comment]
Closing since no feedback was provided and that doesn't seem to be a Nheko issue.
