### ISSUE TITLE
please delete

### ISSUE THREAD

**Issue by ghost** [Nheko-Reborn/nheko#1208]

**Comment by ayunami2000** [comment]
I get this too. I guess it's fixed but not yet released?

**Comment by deepbluev7** [comment]
No, the fix was released quite a while ago. But 0.7.2 is a few years old and doesn't have it. The flatpak should work fine.

**Comment by ayunami2000** [comment]
Is there a way to install it without Flatpak (I need it installed within a docker container)

**Comment by deepbluev7** [comment]
You can use a distribution with a recent enough package or build it yourself, I guess.
