### ISSUE TITLE
Nheko is not installable in Parabola GNU/Linux due to missing dependency

### ISSUE THREAD

**Issue by jakubcze12** [Nheko-Reborn/nheko#1214]
### Describe the bug

Nheko can't be installed through AUR on Parabola GNU/Linux due to python2 package missing.

CLI output:

```
[jacob@libre-thinkpad ~]$ yay -S nheko
 -> Could not find all required packages:
        python2 (Wanted by: nheko -> asciidoc)
```

### To Reproduce

1. Go to '.CLI'
2. Type "yay -S nheko
3. read the output
5. See error

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

**Comment by deepbluev7** [comment]
asciidoc should not be a python2 dependency. Are you sure parabola is not doing some weird changes?

**Comment by deepbluev7** [comment]
Closing this for lack of info.
