### ISSUE TITLE
Requires application restart if changing desktop color theme

### ISSUE THREAD

**Issue by peterhoeg** [Nheko-Reborn/nheko#1220]
### Describe the bug

On KDE Plasma 5.26.2 (and all previous versions I've tried), changing between dark and light desktop themes requires a restart of nheko for it to use the new colours. All applications I'm running are all able to dynamically switch (some require a little help...)

### To Reproduce

1. Set KDE's theme to "breeze light"
2. Launch nheko and ensure that theme is set to "System"
3. Notice how nheko uses a light color theme/scheme
4. In KDE's settings, switch to "breeze dark"
5. All other applications adjust their colors, except nheko that still uses a light background
6. Close nheko 
7. Launch nheko again
8. Now nheko has the correct dark background

### What happened?

nheko does not respond to the color scheme change events.

### Expected behavior

It should change immediately without requiring a restart.

### Version

0.10.2

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Qt version

5.15.6

### Desktop Environment

Standard KDE Plasma 5.26.2 (wayland)

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment]
This probably requires a specific signal to listen to, so that we can refresh the rendering.

**Comment by peterhoeg** [comment]
That's how I'm handling it in emacs:

```elisp
  ;; listen for theme changes and act accordingly
  (dbus-register-signal
   :session
   "org.freedesktop.portal.Desktop"
   "/org/freedesktop/portal/desktop"
   "org.freedesktop.portal.Settings"
   "SettingChanged"
   ;; there used to be something really strange going on if we listened for
   ;; org.freedesktop.appearance color-scheme under KDE, where the returned value
   ;; (1 or 2) was completely random, so we looked for the KDE specific setting
   ;; instead. As of 2022-08 it looks like it's OK again
   (lambda (interface setting values)
     "Handler for FreeDesktop theme changes."
     (when (and (string= interface "org.freedesktop.appearance")
                (string= setting "color-scheme"))
       (theme--set-from-dbus-value (car values))))
```

**Comment by deepbluev7** [comment]
Thanks, that is helpful! It looks a bit flatpak specific, I am not sure if the portal is available everywhere?

**Comment by peterhoeg** [comment]
> It looks a bit flatpak specific, I am not sure if the portal is available everywhere?

Previously GNOME and KDE would publish changes on DBUS on a DE-specific path but fortunately it was agreed to start using the path in this spec instead. It doesn’t have any requirements on flatpak in any way.

I don’t know about other desktop environments and how they publish these types of changes, but starting with this at least solves GNOME and KDE.

**Comment by deepbluev7** [comment]
Fixed by using Qt6, see the other issues that duplicate this :)
