### ISSUE TITLE
Pressing Enter won't send the message

### ISSUE THREAD

**Issue by WiIIiamWei** [Nheko-Reborn/nheko#1232]
### Describe the bug

Pretty much self-explanatory. Enter, Ctrl+Enter, Shift+Enter, none would work. It's really inconvenient when sending a message.

### To Reproduce

It happens every time when sending a message. 

### Version

0.10.2-031a1295

### Operating system

Windows

### Installation method

Windows download

### Did you use profiles?

- [ ] Profiles used?

**Comment by q234rty** [comment]
I think this was fixed by https://github.com/Nheko-Reborn/nheko/pull/1186 so try the nightly builds in https://matrix-static.neko.dev/room/!TshDrgpBNBDmfDeEGN:neko.dev/ maybe?

**Comment by chenshaoju** [comment]
Sorry, I'm new here, and my English is not good.

How can I  download the nightly version? the URL looks old version of nheko (the year is 2021 from the web page), when I try to download it returns an error: Not found.

I joined the nightly chat room in nheko, but when I try to download the file, The download process looks like no response.

**Comment by q234rty** [comment]
@chenshaoju "The download process looks like no response" because there's no progress indication yet. Wait a few minutes and the file should appear in the chosen folder.

**Comment by chenshaoju** [comment]
@q234rty thanks for the reply.

I make a screen record, It looks like the windows nightly version is invalid.

When I download the win64 version, there is no network activity, but when I download flatpak version, the network usage is activated and the file is downloaded successfully.

![GIF 2022-12-18 14-03-26](https://user-images.githubusercontent.com/515763/208284186-d74048f7-ba7a-485d-9fdc-4d1f81758517.gif)

**Comment by q234rty** [comment]
@chenshaoju Well, you could always download it from [AppVeyor](https://ci.appveyor.com/project/redsky17/nheko/builds/45713559/artifacts)

**Comment by chenshaoju** [comment]
@q234rty Thank you, After downloading and using the newest nightly version, this issue has been fixed.

**Comment by ell1e** [comment]
This is actually broken for me on the latest flathub stable. Has this ever been looked into? Neither return nor shift+return works. I need to click the send button instead, and on a touch device even pressing the button won't work unless I hammer it 999 times with my finger until it suddenly lets me.
