### ISSUE TITLE
Unread message count can take a long time to disappear when visiting a room

### ISSUE THREAD

**Issue by antoyo** [Nheko-Reborn/nheko#1233]
### Describe the bug

Sometimes, when I visit a room, the unread message count can take a long time to disappear (it can take multiple minutes and/or multiple visits to the room).

### To Reproduce

As it doesn't always happen, it's hard to reproduce, but that would go along those lines:

1. Go to a room with unread messages.
2. Notice that the unread message count doesn't disappear immediately.

### What happened?

The unread message count should disappear as soon as the message is viewed.

### Expected behavior

The unread message count can stay visible for a long time.

### Version

nheko 0.10.2-d83124f

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Qt version

5.15.7+kde

### C++ compiler

gcc 12.2.0

### Desktop Environment

Sway

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment]
Nheko clears the unread count, once the server has acknowledged the read receipt. Is your connection very unstable or so, that the request could have failed?

**Comment by antoyo** [comment]
Oh, that would make sense: the server seems to have issues from time to time even though when it happens, I can receive messages (they are just not marked as read).

It's still something that I consider unconvenient: I like to know whether there are new messages in a channel so I know I will see new content when I visit it.
Also, I believe the system tray icon will keep its red dot (to indicate there are new notifications) in this case, which is unconvenient for the same reason. Do you think it would make sense to remove the red dot on the system tray icon even if the server has not acknowledged the read receipt?

For the unread message count, perhaps it could be an option so that the user can choose whether it disappears when viewed locally or acknowleged by the server.
What do you think?

**Comment by antoyo** [comment]
Another thing I noticed: it seems that if the window is not focused, it won't mark the message as read even though I had the window focused before the server acknowledged the read receipt.

I would find it more convenient if it could mark it as read if the window was unfocused before the read receipt was received. What do you think?

(I don't know if this is clear.)

**Comment by deepbluev7** [comment]
Are you sure you are not just confusing the 1s read delay, that Nheko adds, when you focus the window? That is there so that if you mouse passes the window, it doesn't mark stuff as read, that you didn't intend to.

**Comment by antoyo** [comment]
I'm not sure how Nheko works for that, but it seemed to me that it will never mark a message as read when it's not focused.
It's for sure hard to confirm because I don't know when it receives the read receipt, but it happened many times that the message was marked as read right after focusing (or rather, 1 second after focusing).

Is there anything in the code that prevents from marking a message as read when the window is not focused?

**Comment by deepbluev7** [comment]
Yes, we only mark messages as read, if you focus on the window, since background windows usually don't get the attention one would consider "reading" a message.

**Comment by antoyo** [comment]
Ok, so that seems to be my issue, then.

I believe it would make more sense that the client should register that the user saw the message when the window is focused and whenever it receives the read receipt, the client should mark the message as read even if it's unfocused (since the user focused the window and saw the message when focusing the window).

In other words, I believe that it would make more sense if it doesn't require the window to be focused at the same time as receiving the read receipt. If the focusing happens before the read receipt, I would find it convenient that the message is marked as read.

What do you think?

**Comment by antoyo** [comment]
Any thoughts on the above idea?

Since matrix.org freqently have networking issues, I believe it would be convenient to not require the message acknowledgement to only be taken into account when the window is focused.

Currently, I have to keep focusing the window many times until I get the server to acknowledge the message at the same time in order to hide the red dot (that indicates new messages) in the system tray icon.

**Comment by deepbluev7** [comment]
Well, Nheko should be marking the room as read whenever it receives a read receipt. It only might not send one, if the window is unfocused or if the sending of the read receipt failed because of a network issue, so I think your above idea is a bit misleading.

**Comment by antoyo** [comment]
I might not have been clear, so let me give you an example.
Currently, from my understanding, here's how it works:

 * I focus the window.
 * Send receipt is sent.
 * I unfocus the window.
 * Sent receipt is acknowledged.
 * (The message is not marked as read because the window is not focused.)
 * I focus the window.
 * The message is marked as read.

Does this look correct?

If so, here's what I'm suggesting:

 * I focus the window.
 * Send receipt is sent.
 * I unfocus the window.
 * Sent receipt is acknowledged.
 * The message is marked as read even if the window is not focused because it was focused before so we know the user saw the message.

Does it make sense?

**Comment by deepbluev7** [comment]
> Does this look correct?

No. Nheko sends the read receipt about 1 second after focusing the window. If the read receipt comes back from the server, the room is marked as read, no matter if the room is focused or not.

**Comment by antoyo** [comment]
> If the read receipt comes back from the server, the room is marked as read, no matter if the room is focused or not.

That doesn't seem to match my experience.
How could I help debug this?

**Comment by deepbluev7** [comment]
Probably modify the code with the appropriate print statements and see, where it mismatches your expectation?

**Comment by antoyo** [comment]
I don't know if it's related to my problem, but I started looking at the logs and did some tests.

I noticed something weird where Nheko only showed a new message when I moved the mouse over its window (which was unfocused the whole time).
Is this normal?

Here are the logs:
```
[2023-01-23 13:51:17.123] [net] [debug] sync completed: s364[…]
[2023-01-23 13:51:17.123] [crypto] [debug] Updated server key count 51 signed_curve25519, fallback keys supported: true, new fallback key: false
[2023-01-23 13:51:17.123] [db] [debug] saving '{"event_id":"$yv[…]","prev_batch":"s3[…]"}'
[2023-01-23 13:51:17.125] [ui] [debug] begin insert from 0 to 0
[2023-01-23 13:51:57.645] [net] [debug] sync completed: m3[…]
[2023-01-23 13:51:57.645] [crypto] [debug] Updated server key count 51 signed_curve25519, fallback keys supported: true, new fallback key: false
[2023-01-23 13:51:57.808] [net] [debug] sync completed: m3[…]
[2023-01-23 13:51:57.808] [crypto] [debug] Updated server key count 51 signed_curve25519, fallback keys supported: true, new fallback key: false
```

I sent the message at 13:51:17 and moved the mouse over Nheko's window at 13:51:57.

**Comment by deepbluev7** [comment]
The sync loop is entirely independent from the UI, so that sounds more like your server is just slow or you are correlating things, that are not in a causal relationship.

**Comment by antoyo** [comment]
> The sync loop is entirely independent from the UI, so that sounds more like your server is just slow or you are correlating things, that are not in a causal relationship.

No, I have 2 computers in front of me and the one I'm currently using sees the message, while the other one that I'm not using (so without mouse events) doesn't see the messages (even after +5 minutes, and they only show when I move the mouse).

It could be a Qt bug similar to this one: https://bugreports.qt.io/browse/QTBUG-12721?focusedCommentId=124507&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel (where one users mentioned seeing a similar issue on Linux).

I still haven't investigated more, so I don't have any more details.

**Comment by deepbluev7** [comment]
If the whole rendering freezes, that is not really our bug. That probably depends on your WM/compositor/whatever then and is either a Qt bug or a misconfiguration/bug in your WM.

**Comment by antoyo** [comment]
If it is indeed a bug of this kind, would that also affect the status tray icon?

**Comment by deepbluev7** [comment]
It depends on where in the stack the bug is. The tray icon is drawn by us, but possibly on a different timer/loop.

**Comment by antoyo** [comment]
I was on Wayland and I switched back to X.org and I haven't seen this issue anymore. It must have been a wayland compositor issue.
