### ISSUE TITLE
Nheko doesn't show unknown message types

### ISSUE THREAD

**Issue by Akira25** [Nheko-Reborn/nheko#1235]
### Describe the bug

When creating a poll in a room with the Element-client, it doesn't show up in nheko. There is no indication, that the message type is not implemented or whatever. That message won't be showed in the client anyway.

### To Reproduce

1. Create a poll with element in a public room
2. open room in nheko
3. See, that nheko doesn't display anything pointing out, there was a poll

### What happened?

Nheko seems to be working fine. But if nheko where my only client, there is no chance to see, that there was a poll.

### Expected behavior

If the message type of polls is not implemented by now, It would be great, to get the message displayed anyway. That way, the user can figure out, that there was a message and take some action to read it anyway. Current behaviour of showing nothing prevents this.

### Screenshots

![poll_1](https://user-images.githubusercontent.com/43141307/204823672-d13eba32-7c1f-47d8-8bea-886d73f51788.png)
Poll correctly displayed in Element

![poll_2](https://user-images.githubusercontent.com/43141307/204823746-965f927b-ad52-49e1-a20e-677004c6c598.png)
intransparently ommited polling message in nheko.

### Version

0.10.2

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Desktop Environment

KDE with Plasma.

### Did you use profiles?

- [ ] Profiles used?

**Comment by JeanPaulLucien** [comment]
Nheko 0.10.2 can't create polls.

**Comment by Akira25** [comment]
> Nheko 0.10.2 can't create polls.

Which is okay. But in my opinion it should give a hint, that there is a message, that it cannot handle. Otherwise it would have a negative effect on the communication. Not showing unknown message types can effectively have the same result as a message loss, which shouldn't happen in reliable communication.

**Comment by LorenDB** [comment]
I should point out that I am working on a fix for this.
