### ISSUE TITLE
Rooms disappear when you leave a space

### ISSUE THREAD

**Issue by MrRoy** [Nheko-Reborn/nheko#1238]
### Describe the bug

When you add a room to a space, and check the option to hide rooms in that space from other spaces, and you leave the space, you remain in the room, but the room can't be found anywhere unless searching directly for it

Workaround is to delete the hidden_tags line from the ~/.config/nheko/nheko.conf file

### To Reproduce

1. Create a space
2. Add a room to the new space
3. Check the "hide rooms with this tag or from this space by default
4. Leave the space

### What happened?

The rooms from that space can't be found anywhere

### Expected behavior

The rooms should appear in the default spce

### Version

0.10.2

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Qt version

5.15.5

### C++ compiler

gcc-11.3.0

### Desktop Environment

Hyprland

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment]
It is probably enough to just add all left rooms to this list in this function: https://github.com/Nheko-Reborn/nheko/blob/f440b411953c2aad752848390d67de7e75a2f1bc/src/Cache.cpp#L1793

But would need someone to test it.

**Comment by deepbluev7** [comment]
I think I fixed this.
