### ISSUE TITLE
reply widget doesn't go away after sending a reply

### ISSUE THREAD

**Issue by adasauce** [Nheko-Reborn/nheko#124]
### System:

- Nheko version: 0.7.0
- Installation method: built
- Operating System: arch
- Desktop Environment: plasma

### Actual behavior

after quote-replying to a message, the widget stays up but the next message does not get submitted as a reply to that message.

### Expected behavior

I'd expect the reply widget to close after sending the message with the reply attached to it.

### Steps to reproduce

- find message
- click reply button
- type reply
- hit enter
- ** notices reply context widget still showing **
- type another message
- hit enter
- ** notices it doesn't have the reply context like the first one but widget still hangs out **
- click close button on reply widget

### Logs

log from opening message -> replying -> replying twice -> closing widget.
```
[2020-02-20 11:28:51.681] [ui] [debug] after replacement: <redacted>
[2020-02-20 11:29:30.061] [qml] [warning] qrc:/qml/delegates/TextMessage.qml:4:2: Unable to assign [undefined] to QString (qrc:/qml/delegates/TextMessage.qml:4, )
```

**Comment by deepbluev7** [comment]
Yeah, red_sky is working on that :D

**Comment by adasauce** [comment]
side note, I was reading the code in TextInputWidget, and the reply should close when you press escape and the popup is visible.

this doesn't happen either.

perhaps its related to closeReply?

**Comment by deepbluev7** [comment]
Well, yeah, @redsky17 rewrote half the widget, but didn't remove the old one yet and wire it up right at all places. He'll finish it at some point.
