### ISSUE TITLE
(Feature Request) Provide statically compiled binaries

### ISSUE THREAD

**Issue by hardBSDk** [Nheko-Reborn/nheko#1240]
Flatpak is the only universal binary available, it brings [security concerns](https://flatkill.org/) and the user needs to install third-party app repository.

I saw that you had problems with AppImage.

I suggest you to use the Firefox/Tor approach to offer static binaries with the libraries included (to avoid library security flaws, a problem of shared dynamic libraries on all OSes).

[Firefox approach](https://www.mozilla.org/en-US/firefox/all/#product-desktop-release)

Other projects do this too (PPSPP, PlayOnLinux, Manyverse).

**Comment by q234rty** [comment]
> I suggest you to use the Firefox/Tor approach to offer static binaries with the libraries included (to avoid library security flaws, a problem of shared dynamic libraries on all OSes).

This doesn't "avoid" library security flaws, this only defers the responsibility of updating bundled libraries to the app developer, which is not as experienced as distro packagers or even flathub runtime maintainers.

**Comment by deepbluev7** [comment]
We already have a flatpak, why would be we go through the effort to create a static binary? It will have exactly the same or more issues than the AppImage currently has.

**Comment by hardBSDk** [comment]
> > I suggest you to use the Firefox/Tor approach to offer static binaries with the libraries included (to avoid library security flaws, a problem of shared dynamic libraries on all OSes).
> 
> This doesn't "avoid" library security flaws, this only defers the responsibility of updating insecure bundled libraries to the app developer, which is not as experienced as distro packagers or even flathub runtime maintainers to deal with this kind of situations.

The aplication is not affected by system shared libraries security flaws, due to isolation.

Flatpak offers his own libraries, but you have fake sandbox.

> We already have a flatpak, why would be we go through the effort to create a static binary? It will have exactly the same or more issues than the AppImage currently has.

Because Flatpak has fake sandbox.

**Comment by deepbluev7** [comment]
Flatpak has a proper sandbox that is better than no sandbox as AppImages or static binaries have, so that's not a valid argument.

**Comment by LorenDB** [comment]
If you really need a sandbox and refuse to use the Flatpak, I would suggest using something like Firejail to manually sandbox the AppImage.
