### ISSUE TITLE
Spoiler text should not be revealed in the message preview in the room list

### ISSUE THREAD

**Issue by WiIIiamWei** [Nheko-Reborn/nheko#1247]
### Describe the bug

The spoiler message is being revealed in the preview, which is not supposed to happen.

### To Reproduce

Happens when sending/receiving a spoiler message.

### Screenshots

![image](https://user-images.githubusercontent.com/37211959/208299904-2d22f50e-7b18-4af8-8d14-a7eb28995729.png)

### Version

0.10.2-f440b411

### Operating system

Windows

### Installation method

Flatpak nightly repo or download

### Desktop Environment

Windows 10 22H2

### Did you use profiles?

- [ ] Profiles used?

**Comment by Cadair** [comment]
This isn't really a bug with the way the room list is rendered (in theory) it's a bug with the sending client (which nheko also has), according to the spec:

> When sending a spoiler, clients SHOULD provide the fallback in the body as shown above (including the reason). The fallback SHOULD NOT include the text containing spoilers since body might show up in text-only clients or in notifications. To prevent spoilers showing up in such situations, clients are strongly encouraged to first upload the text containing spoilers to the media repository, then reference the mxc:// URI in a markdown-style link, as shown above.

So if a client followed this then there would not be a spoiler in the room list.
