### ISSUE TITLE
Direct Messages cannot be from the "+" menu

### ISSUE THREAD

**Issue by Sazu-bit** [Nheko-Reborn/nheko#1250]
### Describe the bug

The bug occurs where the direct message fails to start, does not spawn a DM does not close the creation dialog, does not collect $200.

### To Reproduce

1. Open Nheko and Login.
2. Go to "+" (Start a new chat)
3. Click "Start a Direct Chat"
4. Choose a user to invite
5. Leave encryption as normal
6. Click Start Direct Chat
7. Bug.

### What happened?

Upon clicking "Start Direct Chat" nothing happens. The button animates, but the dialog does not disappear. The DM does not spawn.

### Expected behavior

The DM spawns, view changes to DM then the dialog closes.

### Version

nheko 0.10.2-1a9f7860

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Qt version

5.15.7

### Desktop Environment

Manjaro w/Cinnamon

### Did you use profiles?

- [X] Profiles used?

**Comment by deepbluev7** [comment]
That seems to work fine here, are you sure the menu even opens for you? Because on Wayland it often does not.

**Comment by Sazu-bit** [comment]
Yes the menu event opens up but now the behavior has changed. I now get a confirmation dialog that I want to open up the DM. I click okay and then it crashes.

gotta build a debug version ---ugggggghhhhhh
