### ISSUE TITLE
Changing desktop environment cause logout and a new device id everytime.

### ISSUE THREAD

**Issue by patlefort** [Nheko-Reborn/nheko#1251]
### Describe the bug

Every time I change desktop environment, Nheko will forget last login and make me login again, generating a new device id. I then have to re-verify my device again.

### To Reproduce

1. Login.
2. Change desktop environment (KDE, Gnome, etc).
3. Open the application.

### What happened?

I get logged out.

### Expected behavior

It should remember my login regardless of desktop environment.

### Version

0.10.2

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Desktop Environment

KDE and Gnome

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment]
It is not that Nheko forgets the login credentials, they are just stored in secret storage and you are switching between desktop environments, that use different secret storages. You can fix that by having both environments use the same secret storage or at least telling Nheko to use the other one. Either by starting kwallet and telling Nheko you are using plasma or starting gnome keyring and telling Nheko you don't use Plasma. Hopefully that resolves itself once kwallet with freedesktop API support is widely available and you then don't need to fake, what DE you use.

**Comment by patlefort** [comment]
Should it not remember what was stored in the secret service of the DE used? They could have a separate device id and remember both, but nheko only wants to remember one.

**Comment by deepbluev7** [comment]
Well, the library we use doesn't do that, so we would need to implement it. However I just use the same secret storage across all the DEs I play with. You could also create separate profiles for each, using --profile=kde and --profile=gnome for example.

**Comment by patlefort** [comment]
I just remembered that I did configure my desktops to use the same secret storage (gnome-keyring) and yet the problem persist. Nheko is compiled with qtkeychain version 0.13.2 which should support gnome keychain. I'll have to dig deeper to understand what's going on.

**Comment by deepbluev7** [comment]
Problem is that qtkeychain looks at the PLASMA_SESSION and such variables to detect what secret storage you use, so you need to set that to a different value. See this code: https://github.com/frankosterfeld/qtkeychain/blob/master/keychain_unix.cpp#L50

**Comment by patlefort** [comment]
So based on that information, disabling kwallet was enough to make it use gnome keyring and now it's working. Thanks for the help.
