### ISSUE TITLE
How do I recover my encryption keys? 

### ISSUE THREAD

**Issue by jcelerier** [Nheko-Reborn/nheko#1252]
### Describe the bug

I did not log in to matrix for a long time (a year or so). When updating nheko and trying to connect again, it gave me an error regarding recovering my OLM keys on startup. What can I do to keep them safe and reconnect normally to my account?

### To Reproduce

1. Do not launch Nheko for a year or so
2. Update
3. Run it: the dialog show up on start

### Version

0.10.2.r178.gd78187b4-1

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Qt version

5.15

### C++ compiler

gcc 12

### Desktop Environment

KDE with i3 as the window manager (really, althouh on this one I'm accessing my computer running nheko over ssh -Y)

### Did you use profiles?

- [ ] Profiles used?

### Relevant log output

```shell
[2022-12-24 22:52:05.056] [crypto] [critical] failed to restore olm account: unpickle: BAD_ACCOUNT_KEY
[2022-12-24 22:52:05.056] [ui] [info] dropping to the login page: Échec de la restauration du compte OLM. Veuillez vous reconnecter.
[2022-12-24 22:52:24.021] [db] [warning] Storing secret 'pickle_secret' failed: Cannot create an item in a locked collection


(the text in french means: "failed to restore the OLM account. please reconnect" but I do not want to reconnect and loose my encrypted messages)
```

**Comment by deepbluev7** [comment]
The problem here was that for some reason your secret storage was locked, so Nheko couldn't store the database migration for the keys in it. I don't think you can recover from that.

**Comment by jcelerier** [comment]
:'( how can I make sure this never happens again?

**Comment by deepbluev7** [comment]
You can setup your secret storage to automatically unlock when logging in and if there is no database migration of those secrets happening in the background, the next release should also allow you to close Nheko before it signs you out.

**Comment by jcelerier** [comment]
> You can setup your secret storage 

is there a way to use nheko without one at all? e.g. no gnome-keyring or anything of the likes

**Comment by deepbluev7** [comment]
There is a hidden flag in the config file you can set to prevent usage of a keyring. That however disables encryption for the database, which significantly lowers security.

**Comment by jcelerier** [comment]
well, if I could go back in time and choose between not loosing my messages and having less security I'd choose the former 100% of the time haha. thanks, i'll look for the flag!
