### ISSUE TITLE
Could not connect to server; Keys outdated

### ISSUE THREAD

**Issue by toby63** [Nheko-Reborn/nheko#1254]
### Describe the bug

Whenever I start Nheko, a loading symbol appears and Nheko is basically unusable.
The log shows a problem with outdated Keys, see below.

While Element works correctly.

### To Reproduce

See above.

### What happened?

As I also happen to be the admin of the main server I use, I guess this is related to a combination of two problems:
1. There was some kind of sync problem before (2.), where a room did not correctly show new and changed or deleted messages.
2. There was a letsencrypt key update and after that the above described problem started.

### Expected behavior

I expect Nheko to start and be usable.

### Version

0.10.2-d78187b4 ; also tested with 0.10.2

### Operating system

Linux
Manjaro

### Installation method

Some repository [(AUR)](https://aur.archlinux.org/packages/nheko)

### Qt version

5.15.7

### Desktop Environment

KDE

### Did you use profiles?

- [ ] Profiles used?

### Relevant log output

```shell
# edited for privacy reasons:

[2022-12-28 22:34:48.698] [db] [info] Keys outdated for @[username]:[serverurl].info: [number] vs [number]
[2022-12-28 22:37:18.701] [net] [warning] failed to retrieve own profile info
[2022-12-28 22:37:18.701] [net] [warning] Failed to retrieve backup version
[2022-12-28 22:37:18.701] [crypto] [warning] failed to update one-time keys: (connection: Couldn't connect to server)
[2022-12-28 22:37:18.701] [net] [warning] failed to retrieve profile info for @[username]:[serverurl].info
[2022-12-28 22:37:18.702] [net] [warning] failed to query device keys: M_UNRECOGNIZED,0
[2022-12-28 22:37:18.702] [net] [warning] failed to query device keys: M_UNRECOGNIZED,0
[2022-12-28 22:37:18.702] [db] [info] Keys outdated for @[username]:[serverurl].info: [number] vs [number]
[2022-12-28 22:37:18.702] [qml] [warning] QObject: Cannot create children for a parent that is in a different thread.
(Parent is Cache(0x56003eb350a0), parent's thread is QThread(0x56003d1d2b80), current thread is QThread(0x7f0f240257e0) (:0, )
[2022-12-28 22:37:18.702] [net] [warning] failed to query device keys:  0
[2022-12-28 22:37:18.857] [net] [error] sync error: (connection: Couldn't connect to server)
[2022-12-28 22:39:48.695] [qml] [warning] QObject::killTimer: Timers cannot be stopped from another thread (:0, )
```

**Comment by toby63** [comment]
If it's useful, the server is the **Synapse Matrix homeserver** with version **1.74.0-1**.

Even if this is a problem on my end, could you tell me how to fix this?

**Comment by deepbluev7** [comment]
The error message you have shown seems unrelated, it seems like Nheko just can't connect at all to your server. There are a few things you could try:

- try connecting to your server via curl, i.e. `curl -vvv https://matrix.neko.dev/_matrix/client/versions`
- Try a different profile and show me the error messages for that, e.g. start Nheko with: `nheko --profile debugging` and try to sign in and send me the logs for it. You can get back to the default profile using `nheko --profile default`.

**Comment by toby63** [comment]
> The error message you have shown seems unrelated, it seems like Nheko just can't connect at all to your server. There are a few things you could try:
> 
>     * try connecting to your server via curl, i.e. `curl -vvv https://matrix.neko.dev/_matrix/client/versions`

Everything is normal.
Element can also connect normally.

>     * Try a different profile and show me the error messages for that, e.g. start Nheko with: `nheko --profile debugging` and try to sign in and send me the logs for it. You can get back to the default profile using `nheko --profile default`.

It shows the following error:
`[2022-12-29 00:19:56.134] [net] [error] Autodiscovery failed. Unknown error when requesting .well-known. 0 7`

I did not setup a .well-known file, but as I sucessfully logged in the first time (some months ago), it should still work or not?

**Comment by q234rty** [comment]
@toby63 What is your curl version? If it's 7.87.0 try curl-git from the AUR, there are some regressions on the curl side which are affecting nheko.

**Comment by toby63** [comment]
> @toby63 What is your curl version? If it's 7.87.0 try curl-git from the AUR, there are some regressions on the curl side which are affecting nheko.

A little bit late, but I can confirm that using curl-git helps.
Even though I had to use a new profile (my old profile somehow seems to be broken).

So for everyone experiencing this issue, the next version of curl (>7.87.0) should probably fix this, until then compiling curl from the git repo helps.
