### ISSUE TITLE
Indictate the profile being used in the tray right click menu

### ISSUE THREAD

**Issue by q234rty** [Nheko-Reborn/nheko#1256]
### The Problem

Currently with multiple nheko profiles and tray enabled it's hard to distinguish between different nheko instances on the tray.

### The Solution

Add a unclickable item to the right click menu of the tray icon that says the name of the profile being used.

### Alternatives

Somehow combine the avatar of the user logged into the profile and nheko's icon to form a new tray icon, however that won't help if these profiles are using the same avatar.

### Happens in the latest version

- [X] Yes, this feature is still missing.

**Comment by LorenDB** [comment]
I thought this was displayed in the titlebar? Unless somebody deleted that part, it should be there, because I recall writing it:D

**Comment by q234rty** [comment]
> I thought this was displayed in the titlebar? 

It is, but it doesn't help when trying to close a nheko instance from the tray.

**Comment by LorenDB** [comment]
Oh, true.

**Comment by q234rty** [comment]
Fixed by #1825
