### ISSUE TITLE
The `events` key in sync shouldn't be required

### ISSUE THREAD

**Issue by hifi** [Nheko-Reborn/nheko#1257]
### Describe the bug

Nheko fails to parse sync replies that don't have an empty list or even a null `events` key for all parts.

I'm not exactly sure which part of the reply it's complaining about but since the spec doesn't specify it as a _required_ key anywhere it should be gracefully ignored just like an empty or null list.

### To Reproduce

There's unfortunately no good repro since it only happens on homeservers (not Synapse) that don't include empty or null events lists but building a test case for it should be trivial if needed.

### What happened?

Sync gets stuck and doesn't work.

### Version

0.10.2-3a6a9054

### Operating system

Linux

### Installation method

Flatpak nightly repo or download

### Did you use profiles?

- [ ] Profiles used?

### Relevant log output

```shell
[2023-01-02 10:33:43.484] [net] [error] sync error: (parser: [json.exception.out_of_range.403] key 'events' not found: {"next_batch":"...
```

**Comment by deepbluev7** [comment]
To me the spec seems to list it as required though?

![image](https://user-images.githubusercontent.com/16312324/210239132-b6ef0e63-5a3d-4691-9932-44d930ef1168.png)

https://spec.matrix.org/v1.5/client-server-api/#get_matrixclientv3sync

In general Nheko usually accept the timeline and such to be missing, but if a timeline is provided, it needs to have an events key. I guess the same doesn't apply to account data, ephemeral events, state, presence and such though. However, why a homeserver doesn't leave out the whole field in that case is beyond me.

**Comment by deepbluev7** [comment]
We do seem to check if the events key is present in those cases though:

presence: https://github.com/Nheko-Reborn/mtxclient/blob/d187c63a27710fa87a44ab44d43b7cfa2023132a/lib/structs/responses/sync.cpp#L253
state: We seem to require it here.
ephemeral: https://github.com/Nheko-Reborn/mtxclient/blob/d187c63a27710fa87a44ab44d43b7cfa2023132a/lib/structs/responses/sync.cpp#L50
account data: https://github.com/Nheko-Reborn/mtxclient/blob/d187c63a27710fa87a44ab44d43b7cfa2023132a/lib/structs/responses/sync.cpp#L72
timeline: required by the spec and by us.

**Comment by hifi** [comment]
Indeed, missed that timeline has it required but otherwise no. I'll give the nightly a run once it updates, thanks!

**Comment by deepbluev7** [comment]
It probably won't be in the nightly until we bump the bundled mtxclient version, but I guess I will do that.

**Comment by deepbluev7** [comment]
There: https://github.com/Nheko-Reborn/nheko/commit/06723a473616229cef43fec9190deb64f1d11bf7

**Comment by hifi** [comment]
I built the commit and it seems sync is now working, thanks!
