### ISSUE TITLE
Area below community list doesn't follow dark theme

### ISSUE THREAD

**Issue by cloudrac3r** [Nheko-Reborn/nheko#126]
Ubuntu 19.10, nheko 0.7.0-a8cdc20, built manually, Qt 5.12.4 (?)

When nheko is set to dark theme, the bottom part of the communities panel below the community icons is white. I expected the communities panel to be entirely dark on dark theme.

- starting nheko in dark theme makes the bottom part of the communities panel appear white instead of dark
- changing to light theme and then back to dark makes the communities panel entirely dark (this is the appearance that I want)
- restarting nheko makes the panel appear dark/white again

Seems to only happen with the Qt theme is "fusion".

**Comment by deepbluev7** [comment]
Should be fixed now
