### ISSUE TITLE
Support DNS SRV record lookup at login time

### ISSUE THREAD

**Issue by a-munkres** [Nheko-Reborn/nheko#1265]
### The Problem

If, on the login screen, you enter into the "Matrix ID" field a user ID such as @username:domain.name, such that there exists an SRV record with the name _matrix._tcp.domain.name whose target is a hostname of a host that's running a Matrix homeserver for that domain name (such as "chat.domain.name", for example), then currently the value of the "Homeserver address" field will default to only "domain.name", **not** the "target" hostname contained in the Matrix SRV record for this domain name. (And you're likely to get an error such as "_The required endpoints were not found. Possibly not a Matrix server._", in a situation where there is a non-Matrix HTTP server running on the host whose hostname is just the domain name.)

In particular, the Matrix homeserver at Librem One (see [Wikipedia](https://en.wikipedia.org/wiki/Purism_(company)#Librem_One) for details about Librem One) is like I described above: Matrix user IDs for users registered there are of the form @username:librem.one, but the actual hostname of this homeserver is chat.librem.one (try tunning "dig SRV _matrix._tcp.librem.one" and then "dig A chat.librem.one" to confirm this), and therefore I needed to manually enter chat.librem.one into the "Homeserver address" field in nheko in order to log in.

### The Solution

When the user finishes entering in their user ID to the "Matrix ID" field on the login screen, nheko should run a DNS query to check whether an SRV record named _matrix._tcp._domain.name_ (where _domain.name_ is the part of the entered user ID following the : character) exists, and if it does, then nheko should make the "Homeserver address" field's default value be the target hostname contained in the SRV record it found by running that DNS query.

### Happens in the latest version

- [X] Yes, this feature is still missing.

**Comment by deepbluev7** [comment]
SRV lookups are only for the server side. Clients should never do them. Either fix the server or request a change in the matrix specification: https://github.com/matrix-org/matrix-spec-proposals

**Comment by Mikaela** [comment]
Note that Matrix Spec may be removing the entire SRV support https://github.com/matrix-org/matrix-spec-proposals/pull/3922
