### ISSUE TITLE
Some windows are 1px high by default

### ISSUE THREAD

**Issue by FoxMoss** [Nheko-Reborn/nheko#1266]
### Describe the bug

The a new window doesn't show up until I move it.

### To Reproduce

1. Click a button that opens a new window. ( eg: room directory, room setting).
2. That's it.

### What happened?

The new window doesn't render anything, instead preserving what was there on the previous frame. Once moved it updates properly.

### Expected behavior

The window to show it's content before moved.

### Screenshots

![Screenshot_2023-01-06_22-50-03](https://user-images.githubusercontent.com/46651354/211131937-2a57d974-9892-4099-85cc-1d6b68164aad.png)

### Version

0.9.1

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Desktop Environment

Xmonad on Linux Mint 21 x86_64

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment]
Could this be related to https://bugreports.qt.io/browse/QTBUG-93380 ?

Also 0.9.1 is really outdated and not really supported anymore. Can you reproduce that with a more recent version?

**Comment by FoxMoss** [comment]
okay so i updated and thats fixed but now popup windows(like the verify window) have a 1px width

**Comment by deepbluev7** [comment]
I feel like that too is an issue with upstream Qt, but who knows. I probably need to be able to reproduce that to fix it.

**Comment by deepbluev7** [comment]
Afaik that is fixed.
