### ISSUE TITLE
Distinguish between rooms and spaces in the room search dialogue

### ISSUE THREAD

**Issue by Cadair** [Nheko-Reborn/nheko#1269]
### The Problem

When you search for rooms & spaces there's no way to tell the difference between a room with the same name and avatar (which I have a few of).

### The Solution

Put some visual indicator which rooms in the search box are spaces.

### Happens in the latest version

- [X] Yes, this feature is still missing.

**Comment by LorenDB** [comment]
I think Element makes spaces have square avatars and rooms have round ones, but there should be a better solution than that. Maybe put a small icon next to the space?

**Comment by LorenDB** [comment]
The grid icon from https://fluenticons.co/

**Comment by deepbluev7** [comment]
Or the spacebar icon :p

**Comment by deepbluev7** [comment]
(I probably prefer the community icon)

**Comment by deepbluev7** [comment]
Spaces are now bold, someone else can come up with a better solution!
