### ISSUE TITLE
Nightlies page shows downloads from 2021

### ISSUE THREAD

**Issue by lbeltrame** [Nheko-Reborn/nheko#1271]
### Describe the bug

As the title says. Did the room address change?

### To Reproduce

N/A

### What happened?

N/A

### Expected behavior

N/A

### Version

N/A

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment]
Problem is that matrix-static seems to be broken right now. 5 minutes after restarting the service it does that. Probably won't be fixed until I have a proper replacement.

**Comment by atomdmac** [comment]
Is it possible to just use the artifacts from GitLab CI?
https://nheko.im/nheko-reborn/nheko/-/artifacts

**Comment by deepbluev7** [comment]
I deleted that page :)
