### ISSUE TITLE
Spaces feature compatible with Element Spaces

### ISSUE THREAD

**Issue by goliv04053** [Nheko-Reborn/nheko#1277]
### The Problem

NHeko does not have the Spaces function like the Element client.
https://element.io/blog/spaces-the-next-frontier/

### The Solution

Implementation of the function crosscompatible with Element.

### Happens in the latest version

- [X] Yes, this feature is still missing.

**Comment by Mikaela** [comment]
I don't understand this issue. Nheko has had spaces since a very long time ago, although they are called as communities here.

**Comment by deepbluev7** [comment]
Nheko has spaces and implements them as far as I am aware in accordance to the specification. If there are specific issues with it, please file issues about those specifically instead of making me guess, what is wrong.
