### ISSUE TITLE
v1.1: invalid version

### ISSUE THREAD

**Issue by narcisgarcia** [Nheko-Reborn/nheko#1280]
### Describe the bug

GUI opens and allows writing of login data. "Login" button does not react, and on some tries application breaks before reaching that submission button.

### To Reproduce

```
$ nheko 
```

### What happened?

```
ssl3 ext invalid servername
ssl3 ext invalid servername
[2023-01-12 14:55:38.844] [ui] [info] jdenticon plugin not found.
[2023-01-12 14:55:38.863] [ui] [info] starting nheko 0.7.2
[2023-01-12 14:55:55.526] [net] [info] Autodiscovery: Discovered 'https://chat.filik.eu:443'
terminate called after throwing an instance of 'std::invalid_argument'
  what():  v1.1: invalid version
```

### Expected behavior

GUI opens and allows writing of login data. "Login" button does not react, and on some tries application breaks before reaching that submission button.

### Version

Package 0.8.0+really0.7.2-4

### Operating system

Debian GNU/Linux 11/Stable (amd64)

### Installation method

Debian stable repository

### Desktop Environment

Gnome

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment]
0.7.2 was released in June 2020. Since then Matrix has changed their entire versioning schema. Because of a bug, Nheko tried to validate that and the error condition was handled incorrectly. Updating to a version released in the last year fixes that. See also #957
