### ISSUE TITLE
Feature: *place your title*

### ISSUE THREAD

**Issue by JeanPaulLucien** [Nheko-Reborn/nheko#1289]
### The Problem

https://github.com/Nheko-Reborn/nheko/issues/923
https://matrix.to/#/%21pspQSsaDtGGUEUOcxM%3Amatrix.org?via=matrix.org

### The Solution

If this is private room (invite only room) than just show text "Invite only room".

### Additional context

Oh, I had no idea for issue's title, please, fix it.

### Happens in the latest version

- [X] Yes, this feature is still missing.

**Comment by deepbluev7** [comment]
I don't really understand, what this issue is about. Please provide sufficient content when opening an issue. I won't follow random matrix links.

**Comment by JeanPaulLucien** [comment]
> Please provide sufficient content when opening an issue.

Screenshot in #923
