### ISSUE TITLE
constant 6/10% CPU usage since latest release

### ISSUE THREAD

**Issue by primalmotion** [Nheko-Reborn/nheko#1290]
### Describe the bug

When Nhoko is running, it continously consume 6% to 10% of CPU. This was not the case before the update. This happens on my laptop (flatpak) and my linux phone (flatpak too)

### To Reproduce

Launch Nheko
Do nothing
Watch it eat the CPU

### Version

0.11.0-linux

### Operating system

Linux

### Installation method

Flathub

### Desktop Environment

laptop: Hyprland, phone: Phosh

### Relevant log output

```shell
nothing relevant happens in the log while Nheko is consuming CPU
```

**Comment by primalmotion** [comment]
I confirm that by downgrading to 0.10.2 flatpak, the CPU usage is gone and Nheko is back to using close tp 0% when not in use

**Comment by foresto** [comment]
Maybe related to #1284?

**Comment by primalmotion** [comment]
I confirm this fixes the problem. Can we hope for a hotfix? because 10% CPU on a Linux phone basically means you loose half of the battery in an hour :)

**Comment by redsky17** [comment]
This is related to #1284.  If you can try the nightly flatpak to verify that it fixes the issue on your phone, that'd be great.  I'm planning on releasing a hotfix patch (0.11.1) tomorrow.

**Comment by primalmotion** [comment]
I wanted to try on the phone but it seems no recent arm build passed.

**Comment by primalmotion** [comment]
everything's fixed. thanks!
