### ISSUE TITLE
Squares instead the most part of emojies

### ISSUE THREAD

**Issue by JeanPaulLucien** [Nheko-Reborn/nheko#1295]
### Describe the bug

Title.

### To Reproduce

Just find emojies.

### What happened?

Squares instead emojies.

### Expected behavior

Emojies a visible.

### Version

0.10.2

### Operating system

Windows

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment]
You don't have an appropriate emoji font selected and because of a qt bug the wrong font gets selected. Nothing we can do there, please select an emoji font.

**Comment by JeanPaulLucien** [comment]
> You don't have

Seriously? Do you expect user will spend time to find a font for Emojis? No. Why should I do? It's default nheko's behavior.

**Comment by deepbluev7** [comment]
We already spent a lot of work on this workaround. It is a bug in upstream Qt and it needs to be fixed there to work properly by default.
