### ISSUE TITLE
Scroller is needed for room list

### ISSUE THREAD

**Issue by JeanPaulLucien** [Nheko-Reborn/nheko#1296]
### The Problem

There is no scroller in room list on Windows 7. You mouse wheel all time is terrible.

### The Solution

Make a scroller to list room list.

### Happens in the latest version

- [X] Yes, this feature is still missing.

**Comment by deepbluev7** [comment]
Look. If you waste my time opening duplicates of your own issues, I will just bulk close all your issues.

**Comment by JeanPaulLucien** [comment]
@deepbluev7 same. I waste time to write, make a screenshots, load my brain to think how to write in English. If you have not more Windows users it's not my problem and not reason to offence me.

**Comment by JeanPaulLucien** [comment]
@deepbluev7 let's try to find scroll bar together:
![hneko 0 10 2 - issue - 005](https://user-images.githubusercontent.com/24779886/213113827-f53c827a-0783-43c2-b33d-d829771b165a.jpg)

**Comment by deepbluev7** [comment]
Your issue is pretty much a duplicate of #1288, but you are right, I should have closed #1288 instead, since both talk about different solutions to the same issue, but #1288 is unimplementable without breaking scrolling the messages.

**Comment by JeanPaulLucien** [comment]
@deepbluev7 it's not different solution. Typical Windows GUI has scroll bar and supports Home, End, PgUp, PgDn buttons. It's common features for Windows software.

**Comment by deepbluev7** [comment]
Those buttons are already used for scrolling the messages list.
