### ISSUE TITLE
Long nicks and user IDs break GUI in room user list

### ISSUE THREAD

**Issue by JeanPaulLucien** [Nheko-Reborn/nheko#1297]
### Describe the bug

Tite.

### To Reproduce

Open user list in room

### What happened?

![hneko 0 10 2 - issue - 004](https://user-images.githubusercontent.com/24779886/213008468-3dc8a3d1-6fa7-4314-b904-2b3a715f41e7.jpg)

### Expected behavior

Not what happened.

### Version

0.10.2

### Operating system

Windows

### Did you use profiles?

- [ ] Profiles used?

**Comment by LorenDB** [comment]
This probably should just become elided. It also probably needs looked at in the read receipts dialog
