### ISSUE TITLE
Some fonts break GUI

### ISSUE THREAD

**Issue by JeanPaulLucien** [Nheko-Reborn/nheko#1298]
### Describe the bug

Title

### To Reproduce

Just scroll you room list to find a broken GUI or Room Explore.

### What happened?

See screenshot

### Screenshots

![hneko 0 10 2 - issue - 002](https://user-images.githubusercontent.com/24779886/213009009-0faf2cfe-2373-405d-aa6f-e9e498b9366c.jpg)

### Version

0.10.2

### Operating system

Windows 7

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment]
Please provide what exact font breaks the UI.

**Comment by redsky17** [comment]
If you're using a bitmap font, it's a Qt bug.  Otherwise, it would be good to know what kind of font you're using.

**Comment by JeanPaulLucien** [comment]
Default nheko fonts. It's not font. It's like some users use special symbols or styles for text (nick).
Title in this room breaks GUI: https://matrix.to/#/%23zjawiska.paranormalne%3Amatrix.org?via=matrix.org

**Comment by redsky17** [comment]
Just to clarify, Nheko doesn't ship any fonts.  We use whatever is installed on the system.  The default nheko uses, if you haven't overridden the font in nheko settings, is the result of `QFont().defaultFamily()` which is going to be your selected system font in windows (in this case).

**Comment by JeanPaulLucien** [comment]
![hneko 0 10 2 - issue - 006](https://user-images.githubusercontent.com/24779886/213570125-8132f2b1-576d-4dc2-aff6-3bf3b560fee2.jpg)
@redsky17 for me in settings Font family dropbox is totally white. So, I can't see font family title.

**Comment by JeanPaulLucien** [comment]
Oh, I changed font size. It's 13 for me.

**Comment by redsky17** [comment]
> @redsky17 for me in settings Font family dropbox is totally white. So, I can't see font family title.
Windows 7.

That implies that it is unset, which means you are using the Windows default.  I can say that the font from your screenshot looks like the same font my windows nheko is using, and I'm also using the system default.

> Oh, I changed font size. It's 13 for me.

I still can't reproduce this, even at size 13 font: 
![image](https://user-images.githubusercontent.com/962117/213582820-e40010fa-3b65-487e-b67a-3d61645652ca.png)

**Comment by JeanPaulLucien** [comment]
@redsky17 well, I have the last idea - it's because Cyrillic.
