### ISSUE TITLE
Confusing reaction UX

### ISSUE THREAD

**Issue by gabrc52** [Nheko-Reborn/nheko#1301]
### The Problem

When I hovered on messages, it showed a happy face followed by a sad face. I thought they reacted with happy face and sad face respectively, but the happy face is to react with _any_ emoji and the sad face to react with sad face. I was intrigued and accidentally reacted to someone's message with a sad face, which I hope wasn't noticed or didn't come out rude.

### The Solution

Instead of a happy face for the reaction icon, there should be a button that looks like a happy face with a plus sign so you know is to add a reaction.

For instance on Discord:
![image](https://user-images.githubusercontent.com/24363938/213362889-b4d470eb-6c00-43ae-a034-b2321b966f6f.png)

### Additional context

This is from the Windows version. I can test the Linux version to see if it happens too.

### Happens in the latest version

- [X] Yes, this feature is still missing.

**Comment by deepbluev7** [comment]
Wow. I never considered that, but you make a good point! And since our icon set has such an icon, that sounds like a reasonable solution. I guess it isn't confusing in the input bar and can stay just the emoji face there?

**Comment by gabrc52** [comment]
Yes, I think it's fine in the input bar, because there is no implication of adding a new emoji like messages which can have several reactions.

**Comment by gabrc52** [comment]
Amazing! Thanks for the really quick fix!

**Comment by deepbluev7** [comment]
No worries. After I saw the icon already exists for it in our font library and I had a really good laugh thinking about how someone could confuse the buttons, I just changed the 2 lines. Thank you for the report :3
