### ISSUE TITLE
Checks who is already in room and do not invite them

### ISSUE THREAD

**Issue by JeanPaulLucien** [Nheko-Reborn/nheko#1305]
### The Problem

If I try to invite user this user maybe in room already.

### The Solution

hneko checks users from the "Invite users to " list who is in room already, does not invite them and reports about that. Now nheko just reports: "Could not invite" at final step.

### Happens in the latest version

- [X] Yes, this feature is still missing.

**Comment by deepbluev7** [comment]
Sometimes Nheko might have cached different state than the server has. There is no harm in trying to invite anyway and the benefit is that it allows you to recover from some broken states.
