### ISSUE TITLE
Lucida Sans font family changes paddings and avatar sizes

### ISSUE THREAD

**Issue by JeanPaulLucien** [Nheko-Reborn/nheko#1306]
### Describe the bug

I changed font family to Lucida Sans. Scale = 1. Font size = 11. And after restart I have got increased paddings and avatars.

### To Reproduce

1. Select Lucida Sans font family.
2. Font size = 11.
3. Restart nheko.
4, Select Verdana font and restart nhake.
5. Compare (it should be okay now)

### What happened?

![hneko 0 10 2 - issue - 007 - room list](https://user-images.githubusercontent.com/24779886/213821366-7aa6ade5-c855-4a79-af59-dd756c6a8e13.jpg)
![hneko 0 10 2 - issue - 007 - spaces](https://user-images.githubusercontent.com/24779886/213821373-0cbc591f-28ac-4cb0-8b77-ae9f59eb7cb8.jpg)
![hneko 0 10 2 - issue - 007 - urls](https://user-images.githubusercontent.com/24779886/213821374-bd047b4a-f558-4ae9-ace9-59d1579160a4.jpg)

### Expected behavior

There is screenshot to compare: (https://github.com/Nheko-Reborn/nheko/issues/1298#issue-1537016109)

### Version

0.10.2

### Operating system

Windows

### Installation method

Windows download

### Did you use profiles?

- [ ] Profiles used?

**Comment by JeanPaulLucien** [comment]
I see only titles of font families, nothing to know that font is bitmap font or not. Option suggest about 200 font families. If there is the way to know what fonts is bitmap font, just disable it.

**Comment by deepbluev7** [comment]
Sizes are dependent on the font metrics. This is working as it should.
