### ISSUE TITLE
nheko formats wrong a forwarded messages inside Telegram.

### ISSUE THREAD

**Issue by JeanPaulLucien** [Nheko-Reborn/nheko#1307]
### Describe the bug

nheko formats wrong a forwarded messages inside Telegram.

### To Reproduce

You may using Telegram bridge forward message to your group in Telegram.
or
Using Nheko find a room with Telegram bridge, you should see forwared message.

### Version

0.10.2

### Operating system

Windows

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment]
Duplicate of #1167
