### ISSUE TITLE
HTML Escape Codes get incorrectly replaced in message preview

### ISSUE THREAD

**Issue by msrd0** [Nheko-Reborn/nheko#1310]
### Describe the bug

When I send a message that contains an HTML escape code inside backticks, it gets replaced with the character it stands for in message preview:

![Screenshot_2023-01-21-20-30-46](https://user-images.githubusercontent.com/7853372/213884054-ad767806-e27d-426e-a63e-336a8b46d2b3.png)

![Screenshot_2023-01-21-20-33-24](https://user-images.githubusercontent.com/7853372/213884065-1b729264-e677-44fe-a0bb-e577d284708d.png)

### To Reproduce

1. Open any chat
2. Send an html escape code in backticks

### What happened?

It got replaced.

### Expected behavior

It should not be replaced.

### Version

0.11.1-c13a9d3b

### Operating system

Linux

### Installation method

Local build

### Qt version

5.15.8+kde+r174-1

### C++ compiler

gcc (GCC) 12.2.1 20230111

### Desktop Environment

sway, xdg-desktop-portal-wlr, with XDG_CURRENT_DESKTOP=KDE env var

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment]
Should already be fixed on master.
