### ISSUE TITLE
Loading and loading animation are permanently, nheko tries to download previous room events.

### ISSUE THREAD

**Issue by JeanPaulLucien** [Nheko-Reborn/nheko#1311]
### Describe the bug

Loading and loading animation are permanently, nheko tries to download previous room events.

### To Reproduce

Room where you may reproduce the issue: #freenode_##russkij:matrix.org

### What happened?

Loading and loading animation are permanently, nheko tries to download previous room events.

### Expected behavior

Previous events are updloaded.

### Version

0.10.2

### Operating system

Windows

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment]
Irc rooms sometimes just take some time to load messages.
