### ISSUE TITLE
Another yet Unretrieved event

### ISSUE THREAD

**Issue by JeanPaulLucien** [Nheko-Reborn/nheko#1314]
### Describe the bug

Source:
```
{
  "content": {},
  "origin_server_ts": 1639046563780,
  "room_id": "!nbJtWwWYArHJybDIjg:matrix.org",
  "sender": "@angrycake:matrix.org",
  "type": "m.room.message",
  "unsigned": {
    "age": 35360027867
  },
  "event_id": "$7Xvo2s8PeUvjsP7Jd0RGF1hn5gOBq21JdhuX9uvbbdY",
  "user_id": "@angrycake:matrix.org",
  "age": 35360027867
}
```

### What happened?

Text 

> Unretrieved event

as message.
Before this use joined to room.
![hneko 0 10 2 - issue - 009](https://user-images.githubusercontent.com/24779886/213930685-4a62e77e-851e-4034-a0c5-be3cb29b80df.jpg)
After change information in profile.

### Expected behavior

I don't know.

### Version

0.10.2

### Operating system

Windows

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment]
That's not a valid event, so clients don't have to show that.

**Comment by JeanPaulLucien** [comment]
@deepbluev7 okay. It's empty sting in Element Desktop. But if somebody have send that and server accepted it's client issue or server. I don't know what client used this user. Could he abuse Nheko?

**Comment by deepbluev7** [comment]
Nheko shows invalid events as "unretrieved". Imo that is fine. In theory the server would ignore them, but that doesn't work with E2EE.
