### ISSUE TITLE
Error: Autodiscovery failed. Unknown error when requesting .well-known. 0 6

### ISSUE THREAD

**Issue by JeanPaulLucien** [Nheko-Reborn/nheko#1320]
### Describe the bug

```
[ui] [info] starting nheko 0.10.2-031a1295
[net] [error] Autodiscovery failed. Unknown error when requesting .well-known. 0 6
[net] [error] Autodiscovery failed. Unknown error when requesting .well-known. 0 6
[net] [error] Autodiscovery failed. Unknown error when requesting .well-known. 0 6
 [net] [info] Autodiscovery: Discovered 'https://matrix-client.matrix.org'
```

### To Reproduce

Logs.

### Version

0.10.2

### Operating system

Windows

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment]
This is not a bug. You simply can't find a valid server from a partial input.

**Comment by JeanPaulLucien** [comment]
> This is not a bug. You simply can't find a valid server from a partial input.

This was once, when I installed nheko and launch first time. It's strange.

**Comment by deepbluev7** [comment]
If you enter your server address, Nheko checks it for validity. I.e. if you type slowly matrix.org, it will check the servers m, ma, mat, matr, matri, matrix, matrix., matrix.o, matrix.or, matrix.org, depending on how long it takes you to type the next character. Nothing strange about it.

**Comment by JeanPaulLucien** [comment]
@deepbluev7 oh, why? There is mask for domains.

**Comment by deepbluev7** [comment]
because... you are still typing it? matrix.or could be a valid domain. matrix could be a local hostname.
