### ISSUE TITLE
Crypto: many same warnings: requested sesstion not found in room + handling key request event

### ISSUE THREAD

**Issue by JeanPaulLucien** [Nheko-Reborn/nheko#1322]
### Describe the bug

[warning] requested session not found in room: !qnScvQqCMaEnTZPSkX:matrix.org
[crypto] [warning] handling key request event

### To Reproduce

While don't have information.

### Version

0.10.2

### Operating system

Windows

### Did you use profiles?

- [ ] Profiles used?

### Relevant log output

```shell
[crypto] [warning] requested session not found in room: !qnScvQqCMaEnTZPSkX:matrix.org
[crypto] [warning] handling key request event: {
  "content": {
    "action": "request",
    "body": {
      "algorithm": "m.megolm.v1.aes-sha2",
      "room_id": "!qnScvQqCMaEnTZPSkX:matrix.org",
      "sender_key": ...,
      "session_id": ...
    },
    "request_id": ...,
    "requesting_device_id": ...
  },
  "sender": me,
  "type": "m.room_key_request"
}
```

**Comment by deepbluev7** [comment]
Those are warnings to help troubleshoot stuff for developers, not a bug. Please don't file bugs about stuff that is working as expected without describing why it should behave differently. Thanks.

**Comment by JeanPaulLucien** [comment]
@deepbluev7 I do not know what expect, I'm not product manager, project lead, technical director. If you don't know what to expect, stay it open, because somebody may collect more information.

**Comment by deepbluev7** [comment]
No, it won't stay open because it is not an error. Please only file issues about actual problems you encounter instead of developer logs. Thanks.
