### ISSUE TITLE
Many same warns: qrc:/qml/Avatar.qml:54:5: QML Image: ?? ??????? ???????? ??????????? ?? ??????????: image://colorimage/?#828284?radius=100 (qrc:/qml/Avatar.qml:54, )

### ISSUE THREAD

**Issue by JeanPaulLucien** [Nheko-Reborn/nheko#1328]
### Describe the bug

In my opinion something wrong with these strings.
```

fillMode: avatar.crop ? Image.PreserveAspectCrop : Image.PreserveAspectFit
source: avatar.url ? (avatar.url + "?radius=" + (Settings.avatarCircles ? 100 : 25) + ((avatar.crop) ? "" : "&scale")) : ""
```

### To Reproduce

1. Start nheko
2. Wait for ready to work.
3. Close nheko and check logs.

### Version

0.10.2

### Operating system

Windows

### Did you use profiles?

- [ ] Profiles used?

### Relevant log output

```
[db] [info] Invalidating self verification status
  [qml] [warning] QPainter::begin: Paint device returned engine == 0, type: 2 (:0, )
  [qml] [warning] QPainter::setCompositionMode: Painter not active (:0, )
  [qml] [warning] QPainter::end: Painter not active, aborted (:0, )
 5 x [qml] [warning] qrc:/qml/Avatar.qml:54:5: QML Image: ?? ??????? ???????? ??????????? ?? ??????????: image://colorimage/?#828284?radius=100 (qrc:/qml/Avatar.qml:54, )
 [net] [info] TURN server(s) retrieved from homeserver:
  [net] [info] username: ...
  [net] [info] ttl: 86400 seconds
 [net] [info] uri: turn:turn.matrix.org:3478?transport=udp
  [net] [info] uri: turn:turn.matrix.org:3478?transport=tcp
```

**Comment by deepbluev7** [comment]
How can I reproduce this? Does this happen on a specific page? Is any avatar actually missing? Does this happen on 0.11.0 or up?

**Comment by JeanPaulLucien** [comment]
Oh, I do nothing special. Only launch nheko and click on rooms in room list. Oh, I could not see logs while nheko was launched. There was not new strings in logs. New strings has added after closing.

**Comment by JeanPaulLucien** [comment]
@deepbluev7
I've added information "how to reproduce". It's also in 0.11.1
