### ISSUE TITLE
Clicking on notifications doesn't open Nheko

### ISSUE THREAD

**Issue by gabrc52** [Nheko-Reborn/nheko#1329]
### Describe the bug

When minimizing to tray, clicking on a notification doesn't unminimize Nheko from the tray

### To Reproduce

1. Go to settings and enable "Minimize to tray" and "Start to tray"
2. Restart Nheko
3. Get a notification
4. Click on the notification

### What happened?

Nheko focuses on the message, but you still have to click on the tray icon and click show

### Expected behavior

Nheko focuses on the message and the window is shown (like Signal)

### Version

0.11.1

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Desktop Environment

GNOME with Pop! tiling extension

### Did you use profiles?

- [ ] Profiles used?

### Relevant log output

```shell
Will provide if needed
```

### Backtrace

```shell
N/A
```

**Comment by deepbluev7** [comment]
Can you test, if this still happens with the latest version?

**Comment by gabrc52** [comment]
Yes, it happens on 0.11.1
