### ISSUE TITLE
Timeline width option is settings works strange

### ISSUE THREAD

**Issue by JeanPaulLucien** [Nheko-Reborn/nheko#1337]
### Describe the bug

Oh, width for timeline is very strange option. It needs to be refactored.
It's very strange option which I will use never.

### To Reproduce

1. Go to setting
2. Set option timeline width below under 101.
3. See result. No result.
4. Set option 101 or higher
5. See result. There is result.

### What happened?

0-100 - no effect. 101 and higher has effect.

### Expected behavior

Nobody needs timeline less than 150,

### Version

0.11.1

### Operating system

Windows

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment]
I don't care if you don't use the option, I use it. Stop spamming this repo with invalid issues. Thanks.
