### ISSUE TITLE
No way to research [net] [warning] Skipping device ... as its one time key has an invalid signature.

### ISSUE THREAD

**Issue by JeanPaulLucien** [Nheko-Reborn/nheko#1338]
### Describe the bug

Logger write device ID. There is no way to find user by device.

### To Reproduce

Just use.

### What happened?

No way to research warning's reasons.

### Expected behavior

Log collects UID.

### Version

0.11.1

### Operating system

Windows

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment]
The userid is logged a few lines above the message.
