### ISSUE TITLE
clickable link does not include )

### ISSUE THREAD

**Issue by mauke** [Nheko-Reborn/nheko#1346]
### Describe the bug

Someone mentioned the URL <https://perldoc.perl.org/UNIVERSAL#$obj-%3Eisa(-TYPE-)> in their message, which should have been all clickable, but nheko rendered it as

> [https://perldoc.perl.org/UNIVERSAL#$obj-%3Eisa(-TYPE-](https://perldoc.perl.org/UNIVERSAL#$obj-%3Eisa\(-TYPE-))

which breaks the page anchor.

### To Reproduce

1. Send a message containing `https://perldoc.perl.org/UNIVERSAL#$obj-%3Eisa(-TYPE-)`
2. Observe that the final `)` is not hyperlinked

### What happened?

`)` is not included in the link, which breaks it.

### Expected behavior

`)` should be treated as part of the URL to match the opening `(` that comes before.

### Version

0.11.1-3abb49c4

### Operating system

Linux

### Installation method

Local build

### Desktop Environment

GNOME

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment]
Yes, that happens because our regex is a regex. Pretty hard to fix without writing a better parser for links :)

**Comment by deepbluev7** [comment]
See also #483
