### ISSUE TITLE
Add periods to terminate non-user messages in the timeline

### ISSUE THREAD

**Issue by adasauce** [Nheko-Reborn/nheko#135]
go through and add periods to everything for consistency

update translations

**Comment by PC25** [comment]
I'd like to work on this. Can you give me indicate me what all counts as non-user message in the timeline? Also, what translations need updating?

**Comment by deepbluev7** [comment]
@PC25 If you look at the [message delegate](https://github.com/Nheko-Reborn/nheko/blob/master/resources/qml/delegates/MessageDelegate.qml), all the messages, that are not actually text sent by the user, are "non-user" messages. In this case only EmoteMessage, TextMessage and NoticeMessage aren't, I would say. As you can see their text comes from the functions in the timeline model, for example: https://github.com/Nheko-Reborn/nheko/blob/master/src/timeline/TimelineModel.cpp#L1482

As you can see all the messages inside the `tr()` are not terminated with a period. They should though. After that the translation files need updating, via `make update-translations`. This will mark a few of them as updated. Then you can translate them via weblate or manually via qtlinguist. It would probably be a good idea to at least update the english translation file.
