### ISSUE TITLE
Add reduced motion option

### ISSUE THREAD

**Issue by faithanalog** [Nheko-Reborn/nheko#1350]
### The Problem

Nheko currently features a lot of sliding transitions between screens. These sorts of animations are an accessibility hazard, causing motion sickness in people with vestibular disorders, people suffering from migraines, and other folks too. This motion sickness can range from mild and annoying (such as for myself) to severe and debilitating (as is the case with some friends I know).

### The Solution

These transitions should have a "Reduce Motion" setting to turn them off. This setting should likely also implicitly disable any emoji effects featuring motion.

It would be best if this setting was accessible immediately upon starting the application for the first time, so that a heavily impacted user does not need to experience motion on the way to the user preferences menu.

If you prefer to keep _some_ animation in place rather than turning them off entirely, a standard replacement for slide-transitions is "fade-in" transitions where a new scene increases from 0% to 100% opacity over top the old. For example, this is what iOS does for system-level UI transitions when reduced motion is turned on.

Additionally, synchronizing this setting to the graphical environment's setting would be nice to do if possible. I know that macOS features an OS-level "Reduce Motion" setting, but I'm unsure if equivalents exist for Windows or Linux. This is low priority, compared to having a way to turn it off at all.

### Happens in the latest version

- [X] Yes, this feature is still missing.

**Comment by deepbluev7** [comment]
Fade in would not be possible. We use a listview and scroll it to the side. Doing a fade would be way too much effort. Turning off the scroll animation otoh is trivial, just setting a duration of 0 here: https://doc.qt.io/qt-5/qml-qtquick-listview.html#highlightMoveDuration-prop  in this place: https://github.com/Nheko-Reborn/nheko/blob/master/resources/qml/components/AdaptiveLayout.qml#L125 should get rid of it (but I didn't test that).

I don't know how to access the OS settings for motion stuff. I think I saw a Qt bug about that once, but that might be the tricky part.

**Comment by deepbluev7** [comment]
(For turning off confetti and gif autoplay we already have separate options)

**Comment by faithanalog** [comment]
Turning off the scroll animation sounds like it'd do the trick.
