### ISSUE TITLE
Context Menus Don't Render Under the Mouse

### ISSUE THREAD

**Issue by Quinntyx** [Nheko-Reborn/nheko#1351]
### Describe the bug

When opening a context menu (such as by right-clicking, clicking the plus button, etc.) it spawns not underneath the mouse but rather somewhere else on the screen. The offset seems inconsistent depending on where the window is positioned on the screen. 

### To Reproduce

1. Open Nheko
2. click the + button
3. button menu doesn't spawn above the pause button as expected

### What happened?

When opening a context menu (such as by right-clicking, clicking the plus button, etc.) it spawns not underneath the mouse but rather somewhere else on the screen. The offset seems inconsistent depending on where the window is positioned on the screen. 

### Expected behavior

The menu should spawn above the button and/or under the mouse. 

### Screenshots

![image](https://user-images.githubusercontent.com/70780971/216742388-09bb91c9-24e4-4c38-bf7a-8d9a28bd7f79.png)
![image](https://user-images.githubusercontent.com/70780971/216742411-5d4452a3-4e37-439e-83cc-85b798bf18bb.png)

### Version

0.11.1-25fb193

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Qt version

5.15.8+kde+r178-1

### C++ compiler

gcc 12.2.1 20230111

### Desktop Environment

KDE + Bismuth Tiling Plugin

### Did you use profiles?

- [ ] Profiles used?

**Comment by q234rty** [comment]
Are you using wayland or X11? Do you have scaling enabled anywhere?

**Comment by FlareStormGaming** [comment]
X11. I have 150% global scale in KDE settings, but it feels unlikely that this is a Qt upstream bug because every other app's menus work fine... I'm not sure.

**Comment by q234rty** [comment]
```qml
import QtQuick 2.12
import QtQuick.Controls 2.15
import Qt.labs.platform 1.1 as Platform
Rectangle {
    id: page
    width: 320
    height: 480
    color: "lightgray"
    Button {
        id: okbutton
        text: "Ok"
        onClicked: messageContextMenu.open(okbutton)
        x: 50
        y: 100
    }

    Platform.Menu {
        id: messageContextMenu
        Platform.MenuItem {
            text: "Test"
        }
    }
}
```
Could you save the above to a .qml file and run `qmlscene-qt5` on it to see where the menu appears?
Also, what's your `pacman -Qi qt5-quickcontrols2` ?
