### ISSUE TITLE
Missing videoconvert (gst plugin) when trying to share screen

### ISSUE THREAD

**Issue by Sp00kaYTnT** [Nheko-Reborn/nheko#1352]
### Describe the bug

When I try to share my screen, it just says "Missing GStreamer plugins: videoconvert"

### To Reproduce

1. Open Nheko
2. Click the call button then press "screen"
3. Attempt to share screen

### What happened?

I try to share my screen by using the steps above, but says "Missing GStreamer plugins: videoconvert"

### Expected behavior

My screen to be shared.

### Screenshots

![screenshot 1](https://user-images.githubusercontent.com/45468029/216743630-76ffc5f4-0fd2-4683-b760-a9d556d037b5.png)
(sorry if this is kinda unreadable, my theme is a bit broken)
![screenshot 2](https://user-images.githubusercontent.com/45468029/216743634-74aa3a52-e1df-49ce-864a-33a05690c9e5.png)

### Version

0.11.1-25fb193

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Qt version

5.15.8

### C++ compiler

gcc 12.2.1 20230111

### Desktop Environment

bspwm

### Did you use profiles?

- [ ] Profiles used?

### Relevant log output

```shell
[2023-02-03 17:01:40.750] [ui] [error] Missing GStreamer plugins: videoconvert
```

**Comment by deepbluev7** [comment]
How did you install Nheko? Because you can just install that plugin in a lot of cases.

**Comment by Sp00kaYTnT** [comment]
I installed Nheko through the AUR, and I've also tried to install the gst plugins but to no avail.
