### ISSUE TITLE
Settings menu inaccessible after hiding Communities

### ISSUE THREAD

**Issue by opusforlife2** [Nheko-Reborn/nheko#1353]
### Describe the bug

I tried out the option to hide Communities from settings. Now I cannot access the app settings anymore, since the Settings button was below the Communities button, and the entire pane has been hidden.

I've tried deleting Nheko and all related folders I found in AppData, but the problem persists. Where does Nheko store its config file on Windows?

### To Reproduce

1. Go to Settings.
2. Disable Communities using the toggle.
3. Restart Nheko.

### Expected behavior

The Settings button should be accessible regardless of what GUI changes take place.

### Version

0.11.1 (can't access the settings menu haha)

### Operating system

Windows

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment]
can you show a screenshot? Because the settings button is NOT below the communities list. You probably just collapsed the roomlist by accident and need to drag it out.

**Comment by deepbluev7** [comment]
changing fonts or scale factor can cause this, since the collapse point depends on the font size.

**Comment by deepbluev7** [comment]
I think the bigger issue is that the UI just switches to narrow view on some font sizes/scale factors. Generically defending against that without making the sidebar lose the size you set it to have everytime you change a setting would be hard. Maybe a better way would be to make it more obvious, that the sidebars can be resized.

**Comment by cyberhardt** [comment]
happened to me too. installed it and the UI was zoomed in to oblivion, so I had to drag the room list to the right. I have 125% scale factor on my pc so that might be it. Still, I believe the configurations button should be accessible at all times...

**Comment by trueauracoral** [comment]
Yeah I got this same issue I set the font too high and now the settings button doesn't work I can't drag out the thing on the left to see settings
![image](https://github.com/user-attachments/assets/5d38caf5-0e1b-4fda-b32f-ab11231394ad)

**Comment by trueauracoral** [comment]
I fixed it all you have to do is drag it very fast in the top corner on the right side of your profile in that corner very fast and it will drag out.
