### ISSUE TITLE
Preinstall codecs on Windows

### ISSUE THREAD

**Issue by gabrc52** [Nheko-Reborn/nheko#1354]
### The Problem

Windows doesn't play videos or audios without installing the codecs first (see first FAQ item)

### The Solution

Have the Windows installer install the codecs for you automatically, via a checkbox that is ticked automatically. (Best we can do considering Windows has no concept of dependencies)

### Alternatives

Keep the FAQ item and have users automatically installed. This is not viable to easily recommend Nheko to friends or large groups of people.

### Happens in the latest version

- [X] Yes, this feature is still missing.

**Comment by deepbluev7** [comment]
Shipping the codecs with Nheko could be difficult. However, we don't need to, I think. Qt6 should work out of the box with common codecs by switching to more modern Windows APIs. If that doesn't help, we should revisit it then :3

**Comment by deepbluev7** [comment]
This should not be necessary anymore, since Qt6 uses a different media backend on Windows.
