### ISSUE TITLE
Fruquent lag due to db sync

### ISSUE THREAD

**Issue by foxB612** [Nheko-Reborn/nheko#1355]
### Describe the bug

Since this commit d8669ccf, Nheko lags frequently (about every few seconds) which interrupts typing and makes Nheko unusable. Reverting this commit solves the problem.

Nheko db is located in a btrfs partition on a hdd. I tried setting NOCOW on the db file with no luck. All my other apps work well though.

### To Reproduce

1. Open a room and keep typing.

### What happened?

Nheko freezes every few seconds.

### Expected behavior

The typing should be smooth.

### Version

0.11.1-0ab566dc

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Desktop Environment

i3wm

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment]
I mean, I am still not convinced, that this database corruption was actually because of us. I think it was rather an lmdb bug (by people using old lmdb versions) or just normal disk corruption. I am also quite annoyed by that lag and I think it might be fine to revert that commit... Sadly I had no way to reproduce that stuff so far.

**Comment by foxB612** [comment]
How about adding an option in the settings page? By default enable sync to prevent db corruption while users who are experiencing lag can choose to disable it.

**Comment by deepbluev7** [comment]
I thought about that, but if the change doesn't even help against corruption... maybe it is not worth having it at all :3

**Comment by foxB612** [comment]
Well, I was thinking of adding the workaround option if it would take a while to figure out whether to keep that commit or not. But it seems that not many people have lagging problem anyway (at least no similar report), so it's ok to not bother to add it ;)

**Comment by deepbluev7** [comment]
The lag mostly happens on systems like yours and mine, which use CoW based filesystems, that wouldn't have data corruption without the patch anyway, yes. But it does bother me :D

**Comment by klemensn** [comment]
OpenBSD/amd64 7.2 -current with FFS2 filesystems gets unusably slow due to nheko's fsync usage.
Reverting this commit restores usability.
