### ISSUE TITLE
Circular avatars despite enabling square avatars

### ISSUE THREAD

**Issue by u9000-Nine** [Nheko-Reborn/nheko#1360]
### Describe the bug

Nheko will display some avatars as circular, despite them being square and enabling square avatars. I belive this is a cache issue, because rooms and people I encountered for the first time after enabling square avatars do have square avatars.

Note that I am not talking about avatars where the image is actually circular because of transparency, but rather square/rectangular images that Nheko displays as circles. (You can check the difference by clicking into the user/room PFP, where Nheko displays it correctly.

### To Reproduce

1. Set Nheko to large circular avatars.
2. Join [Nheko avatar bug test](https://matrix.to/#/#nheko-avatar-bug-test:riot.firechicken.net).
3. Wait until the avatar appears and is circular.
4. Set Nheko to large square avatars.
5. Observe that the avatar is still circular.

### Screenshots

![circular room image in side bar](https://user-images.githubusercontent.com/70387230/218339691-f2715e08-5b09-4aec-b00e-3cdddd40e802.png)
![circular room image in room settings](https://user-images.githubusercontent.com/70387230/218339692-f9730e1b-53ec-4034-952a-0a526eab4554.png)
![square room image when opening the image](https://user-images.githubusercontent.com/70387230/218339694-a3796737-8ebc-4f91-a6bf-20acd92f5b8a.png)

### Version

0.11.1

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Desktop Environment

LXQT heavily riced to look like CDE

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment]
This should be fixed. There was a case where we stored the wrong files to disk.
