### ISSUE TITLE
Better handling of invalid commands

### ISSUE THREAD

**Issue by LorenDB** [Nheko-Reborn/nheko#1363]
### The Problem

When you try to use a command that doesn't exist (e.g. try sending `/test test`), nheko just eats the message without doing anything. This is not a good behavior since the user will lose whatever they just wrote with no explanation.

### The Solution

We could just treat unrecognized commands like a regular message and send everything.

### Alternatives

We could also try displaying a popup that tells the user that they have entered an invalid command and maybe gives some context about what will happen when they try to send the message (e.g. "/<command> is not recognized as a valid command. It will be sent as part of your message.")

### Happens in the latest version

- [X] Yes, this feature is still missing.

**Comment by Mikaela** [comment]
I prefer being asked whether to send anyway in case the typoed command contains something sensitive

**Comment by LorenDB** [comment]
Hmm, that's a good consideration.
