### ISSUE TITLE
Some threaded messages do not appear as such

### ISSUE THREAD

**Issue by hiiamboris** [Nheko-Reborn/nheko#1373]
### Describe the bug

Some threaded messages do not appear as such.
And any attempt to start a thread from such message results in all responses being "Failed" to send.

A particular example of a message that appears threaded in schildi.chat but not in nheko: https://matrix.to/#/%23red_red%3Agitter.im/%24jRfJlnaaOaB5GJFsZGyR_9_0TTpH0Zz1Ar-JzDeyl3M

Since I didn't know it is part of a thread, I tried to start one and answer but only got:
![](https://i.gyazo.com/af7db6702cc68d27a00db6b77f4c695f.png)

### To Reproduce

Study of the raw event should give enough info

### Screenshots

https://i.gyazo.com/4328a8693a7bd54d75487545a6bc9d86.png
https://i.gyazo.com/085350baf65c871d937138f5c08f57e2.jpg

### Version

0.11.1-02b900f8

### Operating system

Windows

### Installation method

Windows download

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment]
Yes, edited messages don't appear in threads right now (when sent from non-Nheko clients), since following a edit back up for every thread is fairly expensive. We can implement that, but I am still hoping the spec for that gets fixed.

**Comment by hiiamboris** [comment]
Another related issue is when you answer to a thread and later the thread's OP gets edited, it really messes it up :)
