### ISSUE TITLE
Add metadata and thumbnails to video uploads

### ISSUE THREAD

**Issue by adasauce** [Nheko-Reborn/nheko#138]
The lack of metadata in video uploads from nheko makes it so the video can't play on riot iOS, and it doesn't upload thumbnails, so the receiver is flying blind.

missing fields in received event:

 - duration: 0
 - h: 0 (video height)
 - w: 0 (video width)
   - thumbnail h: 0
   - thumbnail w: 0
   - thumbnail mimetype: ""
   - thumbnail size: 0
  - thumbnail url: ""
 - age field appears to be orders of magnitude different for files uploaded minutes apart between riot and nheko.

**Comment by deepbluev7** [comment]
Related to this issue, it would make sense to clean up the upload code a bit, as mentioned in #137.
