### ISSUE TITLE
Enhance file uploads by leveraging paste behaviour

### ISSUE THREAD

**Issue by adasauce** [Nheko-Reborn/nheko#139]
Currently there are two different flows for uploading files:

 1. using the :paperclip: button
 2. copy/paste a file into the text area

the first behaviour immediately uploads the file to the room, whereas the copy/paste method opens an interstitial window which previews the file and allows you to edit the filename that appears in the room before pressing the upload button to send it off.

the :paperclip: method should as well open the preview window before uploading to allow the user to edit metadata and preview the file about to be uploaded. I'm sure this will simplify some of the code and UX around uploads as well, to have a single path for everything to follow.

this also opens the door for a more feature rich file upload process to, for example:

 - videos: show a preview of videos and extract a frame for the thumbnail, or trimming a video to be shorter. 
 - images: crop, scale, rename, apply filters, strip exif options, etc
 - audio: trim clips, add metadata, change filename

**Comment by deepbluev7** [comment]
Additionally we should probably also improve the progress indicators for upload (and download)!

**Comment by Soundtoxin** [comment]
It would be nice to be able to select multiple files in the file picker as well.
