### ISSUE TITLE
Add shortcut to copy

### ISSUE THREAD

**Issue by yamanq** [Nheko-Reborn/nheko#1398]
### The Problem

When I need to copy a text selection in other programs, I highlight the text and then hit ctrl-c. This does not work on Nheko.

### The Solution

It would be nice if I could use ctrl-c in Nheko to copy selected text.

### Alternatives

Instead, I have to right-click and select "Copy". 

### Happens in the latest version

- [X] Yes, this feature is still missing.

**Comment by deepbluev7** [comment]
Hm, Ctrl-C and Cmd-C work fine on Linux on macOS... This isn't really a feature request, but rather a bug report.
