### ISSUE TITLE
Image modal stays up behind window after download

### ISSUE THREAD

**Issue by adasauce** [Nheko-Reborn/nheko#140]
### Describe the bug
The image preview modal stays up when you download an image, but brings the main window forward ahead of it. So if downloading a bunch of images, you end up with a stack of preview windows in the background.

### To Reproduce

1. click image
2. click :arrow_down: to download
3. see save dialog, choose location and file name
4. click save
5. see main window 
6. notice preview is still up behind it

goto: 1 and repeat for stack of previews 

### Expected behavior

1. click image
2. click :arrow_down: to download
3. see save dialog, choose location and file name
4. click save
5a. close preview, show window
5b. go back to preview
### System:

- Nheko version: 0.7.0-ee176de | Linux
- Installation method: running from IDE
- Operating System: Arch Linux
- Desktop Environment: KDE / Plasma

### Logs
nothing relevant logged

**Comment by deepbluev7** [comment]
I actually have the issue in reverse. The image modal seems to block the save location dialog on sway...
