### ISSUE TITLE
Support report messages

### ISSUE THREAD

**Issue by mpldr** [Nheko-Reborn/nheko#1410]
### The Problem

After being confronted with CSAM in a room, I would like to propose adding a way to report things… something like `/report [badness]` similar to how `/react` behaves.

### The Solution

Implement the existing message type: https://spec.matrix.org/v1.6/client-server-api/#reporting-content

### Happens in the latest version

- [X] Yes, this feature is still missing.

**Comment by deepbluev7** [comment]
Not that that report API only sends a message to YOUR server admin. It doesn't really work over federation. See also https://github.com/matrix-org/matrix-spec-proposals/pull/3843

**Comment by mpldr** [comment]
I agree that the current way it's handled is rather limited in its 
efficacy and how much it can do, since it's part of the spec and useful 
in cases like this I think it should still be supported though.

-- 
Moritz Poldrack
https://moritz.sh

**Comment by deepbluev7** [comment]
Yeah, just mentioning it for completeness :)
