### ISSUE TITLE
Drop-down menu goes off screen on sway

### ISSUE THREAD

**Issue by laleanor** [Nheko-Reborn/nheko#1412]
### Describe the bug

When using the sway compositor, the drop-down menu for joining a room or initiating a DM expands down from the bottom of the window and may go off-screen, rendering it unusable.

### To Reproduce

1. Start sway.
2. Open nheko in tiling mode in a blank workspace
3. Click the plus to the bottom left
4. Observe that the menu is mostly inaccessible because it is under the bottom of the screen

### What happened?

The menu expands downward off the bottom of the screen.

### Expected behavior

The menu is visible on screen in its entirety.

### Screenshots

![nheko-menu](https://user-images.githubusercontent.com/122235556/224538392-48623d2c-c008-4724-8656-3d8b2d34291f.png)

### Version

0.11.3

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Qt version

5.15.7

### C++ compiler

gcc-12.2.1_p20230121-r1

### Desktop Environment

sway (wayland compositor)

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment]
See https://bugreports.qt.io/browse/QTBUG-85297

In Qt5 fixing that does break KDE, so this is only fixed in Qt6.

**Comment by q234rty** [comment]
Pretty sure this is https://bugreports.qt.io/browse/QTBUG-87303 and is already fixed in the KDE Qt Patch Collection: https://invent.kde.org/qt/qt/qtwayland/-/merge_requests/70

**Comment by deepbluev7** [comment]
Ah, I didn't see that one. Needs a newer Qt5 then :)

**Comment by deepbluev7** [comment]
(Although let's hope they also pick https://bugreports.qt.io/browse/QTBUG-110623)
