### ISSUE TITLE
After clicking on chat history and typing, first keystroke is eaten and discarded

### ISSUE THREAD

**Issue by nyanpasu64** [Nheko-Reborn/nheko#1420]
### Describe the bug

If I focus chat history, then start typing, the first keystroke is discarded but focuses the "Write a message..." textbox, and the remaining ones are typed into the field.

### To Reproduce

1. Open a chat, and click on the history. If desired, scroll around and click more times.
2. Start typing characters.

### What happened?

The first character you type is discarded and focuses the chat box, and the next character is typed.

### Expected behavior

Either the first character should focus the chat box *and* be written there, or typing when the message history is focused should not focus the chat box.

### Version

0.11.3-d27e42de

### Operating system

Linux, Windows

### Installation method

Windows download, Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Desktop Environment

Windows 10, KDE Plasma X11

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment]
That's because we focus the chat input on unrecognized text inputs, which means we eat the first character, since we haven't found a way to do that without eating it.

**Comment by LorenDB** [comment]
Fixed

**Comment by nyanpasu64** [comment]
https://github.com/Nheko-Reborn/nheko/pull/1456 i assume

**Comment by LorenDB** [comment]
Yep
