### ISSUE TITLE
Verification window as opened by default have elements out of the window

### ISSUE THREAD

**Issue by Porkepix** [Nheko-Reborn/nheko#1422]
### Describe the bug

See the joined screenshot, when doing a session verification, some elements can appear out of the window as its opened at its default size.
This is a minor issue as globally the verification can still be done, but it'd be better not to have words partially out of the window, for polishing.

### To Reproduce

Do a session verification

### Screenshots

![Screenshot from 2023-03-18 15-31-46](https://user-images.githubusercontent.com/709500/226112636-7484c710-0721-4dc3-9243-4cb805d087e9.png)

### Version

0.11.3

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Qt version

5.15.8

### Desktop Environment

Gnome on Wayland

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment]
I can't reproduce this on the Qt6 branch. Please reopen, if you experience it there again.

**Comment by Porkepix** [comment]
So, are issues on Qt5 builds considered as invalid/not worth anymore?
If so, yeah, the one I use is built upon Qt5, and then I guess I'll have to wait for the maintainers to change the build to Qt6 ones, both for stable and master releases.

**Comment by deepbluev7** [comment]
The next release will be the Qt6 release. There won't be a Qt5 release anymore unless there is a critical security issue. As such, yes, if an issue happens only on an old version, but not on the current development branch, then I will close it. (Qt6 is on the master branch rn.)

**Comment by Porkepix** [comment]
> The next release will be the Qt6 release. There won't be a Qt5 release anymore unless there is a critical security issue. As such, yes, if an issue happens only on an old version, but not on the current development branch, then I will close it. (Qt6 is on the master branch rn.)

Then dunno if there's such a thing as dropping support for Qt5 and if it's still supposed to work, but AUR's `nheko-git` (that builds from master) is still using Qt5: https://aur.archlinux.org/packages/nheko-git ; but that's anyway up to the maintainer to update this; for my part I was running the stable release when I opened the issue.

**Comment by deepbluev7** [comment]
The nheko-git package also won't build the current master branch correctly, since it doesn't include the Qt6 dependencies. We don't support Qt5 and Qt6 at the same time, because we don't have the resources for that :)
