### ISSUE TITLE
nheko cannot join #podman:fedoraproject.org

### ISSUE THREAD

**Issue by unknowndevQwQ** [Nheko-Reborn/nheko#1423]
### Describe the bug

Nothing happens (including logs) when joining #podman:fedoraproject.org directly via "Join Chat Room", and when "Customize Master Server" in the "Chat Room Directory I can see podman when I fill in fedoraproject.org in the "Custom Host Server" section of the "Chat Room Directory", but the popup window after clicking join does not load the number of people and avatars.

### To Reproduce

1. Click on +
2. Click on Join the chat room
3. Type `#podman:fedoraproject.org` in the input box
4. Nothing happens.

### Version

nheko 0.11.3

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Did you use profiles?

- [ ] Profiles used?

### Relevant log output

```shell
[2023-03-19 12:37:57.654] [net] [error] Failed to retrieve rooms from mtxclient - M_UNKNOWN - Failed to fetch room list -
[2023-03-19 12:37:57.705] [net] [error] Failed to retrieve rooms from mtxclient - M_UNKNOWN - Failed to fetch room list -
[2023-03-19 12:38:16.924] [qml] [warning] qrc:/qml/dialogs/ConfirmJoinRoomDialog.qml:0: ReferenceError: input is not defined (qrc:/qml/dialogs/ConfirmJoinRoomDialog.qml:0, )
[2023-03-19 12:38:24.068] [qml] [warning] qrc:/qml/dialogs/ConfirmJoinRoomDialog.qml:0: ReferenceError: input is not defined (qrc:/qml/dialogs/ConfirmJoinRoomDialog.qml:0, )
```

**Comment by deepbluev7** [comment]
For me it is just that my server fails to join the room, so this does not seem to be Nheko's fault? Probably that room is just unjoinable or too big.

**Comment by unknowndevQwQ** [comment]
> For me it is just that my server fails to join the room, so this does not seem to be Nheko's fault? Probably that room is just unjoinable or too big.

Too big? What's going on?

**Comment by deepbluev7** [comment]
It is pretty common in Matrix that rooms are unjoinable. That usually is a server side issue, not a client one. Try joining the room in a different client. If it fails there too, it is not our fault :)

**Comment by unknowndevQwQ** [comment]
> It is pretty common in Matrix that rooms are unjoinable. That usually is a server side issue, not a client one. Try joining the room in a different client. If it fails there too, it is not our fault :)

The homeserver is matrix.catgirl.cloud, which can be joined normally when using https://app.element.io.

Also, I have a similar problem when trying to join #fedora:fedoraproject.org using nheko. Even though I have now successfully joined #fedora:fedoraproject.org and #podman:fedoraproject.org, nheko still does not show the new rooms I have joined.

**Comment by JeanPaulLucien** [comment]
@unknowndevQwQ 
I used Element Desktop to check room. I was kicked with reason "IRC Connection Failure". Nheko can't show this error.
