### ISSUE TITLE
Option to open nheko into "Direct chats" view/tab 

### ISSUE THREAD

**Issue by girlmaya** [Nheko-Reborn/nheko#1432]
### The Problem

I dont wanna see all rooms most of the time using nheko. first thing i do on launch is switch to direct chats view because it's overwhelming otherwise. I want this to be the default view for me 

### The Solution

An option under "sidebar"

### Happens in the latest version

- [X] Yes, this feature is still missing.

**Comment by deepbluev7** [comment]
Not sure if we would make such a specific option, but reopening the last selected sidebar element at startup might be a good compromise?

**Comment by girlmaya** [comment]
Yeah that works fine i think :)
