### ISSUE TITLE
how to hide the password that we read in ansible from Secrets Manager in the ado pipeline

### ISSUE THREAD

**Issue by vik0008** [Nheko-Reborn/nheko#1434]
i am reading the secrets from Secrets manager using ansible and setting them as password for user account, its all done via Azure devops pipeline, but the problem is password shows up in ADO tasks as plain text

**Comment by deepbluev7** [comment]
I have no idea, what you are talking about. Nheko doesn't even store the password in the secret storage and it has nothing to do with ansible or azure.
