### ISSUE TITLE
Support custom emotes in reactions

### ISSUE THREAD

**Issue by tux93** [Nheko-Reborn/nheko#1436]
### The Problem

Nheko allows to create Sticker packs that can also be used as Emotes, but it currently is not possible to use those as reaction.

If a Custom Emote is sent as reaction by another client, i.e. Cinny, instead of the Emote the mxc:// url is shown.
![image](https://user-images.githubusercontent.com/1749593/228671029-598597b2-5d42-42e1-ad21-13e1877c2175.png)

### The Solution

- Show Custom Emotes in the reaction picker
- Show the Custom Emote in the reaction

### Happens in the latest version

- [X] Yes, this feature is still missing.

**Comment by deepbluev7** [comment]
Well, there is no spec for that behaviour and we can't know the size, format, etc of the uri, which makes this quite annoying.
