### ISSUE TITLE
No audio or video playing with macOS

### ISSUE THREAD

**Issue by gymnae** [Nheko-Reborn/nheko#1439]
### Describe the bug

I'm using the homebrew build of nheko for ARM Macs.
It's working fine apart from that no audio or video media will play using the internal media player, I have to use the option to use an external player. 
Are codecs missing? The FAQ mentions that Windows users need to install a codec pack, but not sure if and what would be required for macOS users.

### To Reproduce

1. Use nheko on macOS ARM 
2. Receive message with audio or video content
3. Press play button and have it flash briefly, but not commence playing the media file

### What happened?

I can reproduce it with any message containing video or audio.
The same message plays flawlessly in the Linux build of nheko as is avaible for manjaro

### Expected behavior

Play the media with the integrated media player like on the Linux build

### Version

0.11.3-d27e42de

### Operating system

macOS

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Did you use profiles?

- [ ] Profiles used?

### Relevant log output

```shell
[2023-03-31 19:44:18.562] [qml] [warning] Warning: distance-field glyph is not available with index 65535 (:0, )
[2023-03-31 19:44:18.562] [qml] [warning] Warning: distance-field glyph is not available with index 65535 (:0, )
[2023-03-31 19:44:23.957] [ui] [info] Media player status 2 and error 0
[2023-03-31 19:44:23.959] [ui] [info] Media player status 8 and error 0
[2023-03-31 19:44:23.959] [ui] [info] Media player er
```

**Comment by deepbluev7** [comment]
This works for me now.

**Comment by deepbluev7** [comment]
(With the nightly)
