### ISSUE TITLE
High idle load with room list expanded

### ISSUE THREAD

**Issue by adasauce** [Nheko-Reborn/nheko#144]
### Describe the bug

Nheko has high idle load with room list expanded (at any size). nheko, kwin_x11, and Xorg procs all using 50%, 45%, 25% cpu respectively.

It doesn't have high load under these circumstances:
 - room list is hidden by window shrinking
 - room list is collapsed into avatar only mode
 - settings screen is brought in front

### Expected behavior

more respectful to my poor cpu

### System:

- Nheko version: master
- Installation method: local build
- Operating System: Arch Linux
- Desktop Environment: KDE / Plasma

### Logs

perf report: https://hastebin.com/ujecakoxow.css

**Comment by adasauce** [comment]
I should note that this doesn't happen on my desktop, only tablet.

This might have to do with display scaling, which I have enabled on the tablet.

**Comment by dessalines** [comment]
I'm getting ~10% load just with nheko running in the background, worse than riot.im right now.

**Comment by deepbluev7** [comment]
I think this may have had to do with our high dpi user avatar scaling. We did fix that issue, so I'm gonna close this. If you can still reproduce this with the current master or 0.7.2 (when it gets released), please reopen! Thanks :3
