### ISSUE TITLE
GUI option to reset "Font Family" & "Emoji Font Family" back to the default

### ISSUE THREAD

**Issue by jahway603** [Nheko-Reborn/nheko#1440]
### The Problem

Currently a user can change these settings manually within their nheko.conf as follows:

```
emoji_font_family=default
font_family=default
```

Unfortunately, not every user is going to know how to do this. I propose a feature request to have a button in the Settings options to reset these back to their defaults. Also, I'm not sure where the defaults used are documented.

### The Solution

I propose a feature request to have a button in the Settings options to reset these back to their defaults. Also, I'm not sure where the defaults used are documented.

### Alternatives

User can manually change these back to default within their nheko.conf as follows:

```
emoji_font_family=default
font_family=default
```

### Additional context

* Also not sure where the Defaults used are documented, as I asked in the support chat about the Default Emoji Font Family being used because I was missing certain emoji images.

### Happens in the latest version

- [X] Yes, this feature is still missing.

**Comment by MoralCode** [comment]
i find when i scroll down the settings page in nheko, sometimes my scrolling ends up changing the font, having a way to reset it would be awesome
