### ISSUE TITLE
mobile: automatic switching to Light / Dark theme based on the ambient light sensor

### ISSUE THREAD

**Issue by sc0w** [Nheko-Reborn/nheko#1449]
### The Problem

I always use dark theme in mobile with nheko, but in a sun day I need to change it to light theme.

### The Solution

automatic switching to Light / Dark theme based on the ambient light sensor in mobile

### Alternatives

for reference, in phosh we have this feature, see:

https://social.librem.one/@agx/108668794144125214

https://gitlab.gnome.org/World/Phosh/phosh/-/merge_requests/1107

### Happens in the latest version

- [X] Yes, this feature is still missing.

**Comment by deepbluev7** [comment]
That sounds like a bad idea to do on the Nheko side. We'll eventually adapt to theme light/dark changes automatically (on Qt6), in which case we would automatically switch if Phosh changes the theme, which I think covers this. That is partially covered in #1220, but maybe there is another issue as well.

So basically yes, but not in the manner you described and it should just work once we get to it :3
