### ISSUE TITLE
Annoying layout change between mouse and touchscreen (scrollbar)

### ISSUE THREAD

**Issue by baltitenger** [Nheko-Reborn/nheko#1453]
### Describe the bug

The type of the scrollbar in the message timeline changes depending on the last type of input received (mouse or touchscreen). This causes a layout change of the messages, making them slightly move left / right to make space for the new scrollbar width.

### To Reproduce

1. open any chat
2. touch the screen (-> messages jump right)
3. move the mouse (-> messages jump left)

### Version

0.11.3

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Desktop Environment

sway

### Did you use profiles?

- [ ] Profiles used?

**Comment by LorenDB** [comment]
Qt 6 seems to have fixed this.
