### ISSUE TITLE
Nheko could not connect to the secure storage to save encryption secrets to

### ISSUE THREAD

**Issue by notmentaloutlaw** [Nheko-Reborn/nheko#1459]
On my gentoo system I have recently updated world and after that for some reason nheko can no longer access gnome-keyring. It used to work fine but I am not sure what happened to the underlying package to cause it to no longer work. I know that the gnome-keyring daemon is working as I can access and open the keyring using seahorse. I am running Hyprland currently.

**Comment by deepbluev7** [comment]
The keyring useflag got renamed. It is "keyring" now, not "gnome-keyring" (on qtkeychain).

**Comment by notmentaloutlaw** [comment]
Thanks this solved the issue
