### ISSUE TITLE
Text selection does not follow theme

### ISSUE THREAD

**Issue by duarm** [Nheko-Reborn/nheko#1462]
### Describe the bug

text selection not following theme
![image](https://github.com/Nheko-Reborn/nheko/assets/26150581/42580956-97eb-46e4-b913-39e3d4a005d0)

dolphin sample (qt6)
![image](https://github.com/Nheko-Reborn/nheko/assets/26150581/a7192a81-2c11-4832-97b1-24e66f7b1c3a)

it should follow the "Highlight" color

### To Reproduce

1. Select text

### Version

0.11.3

### Operating system

Linux

**Comment by LorenDB** [comment]
Are you sure Dolphin is using Qt 6? Qt 5 and Qt 6 use separate themes, and nheko still uses Qt 5, so you can expect them to look different. However, there could be a bug in our code or a slight difference between Qt Widgets and QML themes.

**Comment by duarm** [comment]
dolphin uses qt5, sorry my mistake

**Comment by deepbluev7** [comment]
The text selection color in the messages does not follow the theme, but the one in the text input should. That's because Qt does not allow theming that field properly, Qt6 should fix that.

**Comment by deepbluev7** [comment]
Seems to still happen on Qt6, but maybe switching the TextArea element will fix it.

**Comment by duarm** [comment]
Just noticed mumble, which is qt5, managed somehow
![image](https://github.com/Nheko-Reborn/nheko/assets/26150581/c03a43a1-c9a3-4edb-a8eb-fddcdd72a0c9)

**Comment by duarm** [comment]
this was regressed on d6ab752
