### ISSUE TITLE
switching dark/light mode through system theme doesn't work

### ISSUE THREAD

**Issue by pennae** [Nheko-Reborn/nheko#1466]
### Describe the bug

using QGnomePlatform to unify application styling. at startup nheko honors the gtk theme set in dconf, but runtime changes are not applied. restarting nheko applies the change, but that should not be necessary. QGnomePlatform receives the changes and (presumably) propagates them upwards, but nothing reacts.

### To Reproduce

1. set theme to "system"
2. `dconf write /org/gnome/desktop/interface/gtk-theme "'Adwaita-dark'"` (or light, depending on what you've currently got)
3. restart nheko

### What happened?

change is not applied before the restart.

### Expected behavior

change is applied and the restart is not necessary. a full theme change wouldn't even be necessary, but nheko seems to honor none of the theme settings, including the color scheme setting that it can clearly change at runtime.

### Version

0.11.3

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Qt version

5.15.9

### Desktop Environment

i3 without desktop environment

### Did you use profiles?

- [X] Profiles used?

**Comment by deepbluev7** [comment]
Fixed now, this was actually a duplicate from another issue and it was fixed by switching to qt6 :)
