### ISSUE TITLE
Settings page doesn't resize right

### ISSUE THREAD

**Issue by LorenDB** [Nheko-Reborn/nheko#147]
The settings page doesn't resize correctly for a mobile resolution.

### To Reproduce
1. Go to 'Settings'
2. Horizontally resize the window as small as possible.
3. The controls go off the window and are not accessible.

### Expected behavior
The controls should be fully accessible at all times.

### Screenshots
![Nheko-error](https://user-images.githubusercontent.com/55629213/76686601-0e52ff00-65f3-11ea-9fa2-97a3885329bb.png)

### System:

- Nheko version: 0.6.4
- Installation method: I installed Nheko via Discover on KDE Plasma
- Operating System: Linux (Kubuntu)
- Desktop Environment: KDE Plasma

**Comment by deepbluev7** [comment]
We already fixed this for 0.7.0. You could try out the flatpak, or wait for the official release of 0.7.0 to verify that ;-)

**Comment by LorenDB** [comment]
When will the official release come out?

**Comment by deepbluev7** [comment]
Sadly probably still a few months off, since we are working on 2 bigger features still and some polish. The nightly is fairly stable though.
