### ISSUE TITLE
Room history visibility cannot be seen anywhere

### ISSUE THREAD

**Issue by Mikaela** [Nheko-Reborn/nheko#1470]
### Describe the bug

There is no way to see room history visiblity in Nheko.

### To Reproduce

N/A

### What happened?

I tried to find the room history visibility everywhere and finally asked in the Nheko room to hear that it's not implemented.

- https://matrix.to/#/%23nheko%3Anheko.im/%24mS4tqsW_9xcVgiJMXCQe0iC4gW7fw0-BeD_GQKWBKjo?via=neko.dev&via=matrix.org&via=envs.net

### Expected behavior

I expect to always know the room history visiblity and it to be especially clear when the room is publicly readable.

Considering https://github.com/matrix-org/matrix-public-archive/issues/47 I would also like to know the state of history being readable by room members and whether the room is being archived (https://github.com/matrix-org/matrix-spec-proposals/pull/4021?).

### Screenshots

N/A

### Version

nheko 0.11.3-643fc440

### Operating system

Linux

### Installation method

Flatpak nightly repo or download

### Qt version

N/A

### C++ compiler

N/A

### Desktop Environment

sway version 1.8.1

### Did you use profiles?

- [X] Profiles used?

### Relevant log output

```shell
N/A
```

### Backtrace

```shell
N/A
```

**Comment by Mikaela** [comment]
Element is also thinking about this, I wonder if anything Nheko could benefit comes up or if inspiration could be took from their future implementation.

- https://github.com/vector-im/element-meta/issues/1807

**Comment by deepbluev7** [comment]
(Note that Nheko does now show history visibility, but I am not happy with the interface. It was just a quick fix to get something out)

**Comment by deepbluev7** [comment]
Sup, that is better now, so I will close it. We can still improve the wording, but someone else can do that! :D
