### ISSUE TITLE
Optionally store credentials in password store instead of dbus secrets provider

### ISSUE THREAD

**Issue by halcyonseeker** [Nheko-Reborn/nheko#1472]
### The Problem

As I understand it, Nheko currently stores credentials using a dbus secrets provider, and won't run without one.  I was able to get gnome-keyring-daemon working so I could log into my account on Nheko, but that was pretty inconvenient.

### The Solution

I use [password-store](https://www.passwordstore.org/) to manage my passwords and have used some applications in the past (specifically protonmail-bridge) that offer an option to store credentials there.  I don't know enough about C++, QT, or the Nheko codebase to submit a pull request, but I'd really appreciate it if Nheko had an option to store credentials in a password-store.  I have a friend who runs OpenBSD who chose not to use Nheko because of this requirement, so it would definitely help with accessibility.

### Additional context

Anyway, I hope you'll consider implementing this and thanks for making Nheko, it's so much more pleasant to use than Element.

### Happens in the latest version

- [X] Yes, this feature is still missing.

**Comment by deepbluev7** [comment]
pass can be used as a secrets provider, some random projects I found for it:

- https://github.com/mdellweg/pass_secret_service
- https://github.com/nullobsi/pass-secrets

I have never used any of them, but Nheko just requires the freedesktop secrets dbus API, which imo is a good enough generic interface. You can use whatever you want to provide that API.

**Comment by halcyonseeker** [comment]
For me using the dbus secrets API requires running extra software just for Nheko, I'd rather not use it at all and have Nheko have an option to store secrets in the password store directly, like protonmail-bridge does.

If the user has it set up and chooses that option, on Nheko's side it's just a matter of handling the stdin and stdout of the shell commands `pass insert -m nheko/whatever_secret_name` and `pass nheko/whatever_secret_name`.

**Comment by deepbluev7** [comment]
Well, either Nheko includes extra code or you install extra code. To me the latter sounds more flexible and it is also compatible with other applications. We can of course just bundle that code into Nheko, but that sounds stupid. Most systems have a secrets provider installed by default as well, it is mostly "minimal" systems that don't.

**Comment by deepbluev7** [comment]
(And you can just use the flag to store everything in the config file unencrypted instead)

**Comment by deepbluev7** [comment]
Not doing this, since other solutions already exist and it would mean duplicating that code in Nheko instead.
