### ISSUE TITLE
Pressing Enter won't send

### ISSUE THREAD

**Issue by mandrewsan** [Nheko-Reborn/nheko#1474]
### Describe the bug

Pressing enter always does a line break, will not send message. I am on Fedora 37, KDE Plasma 5.27.4, on a Samsung Galaxy Book2 360, a touch screen laptop.

I have a desktop on the same OS and desktop environment, which does not have the same issue. I have reinstalled Nheko (through DNF) and removed all config files and cache, to no avail.

I have tried toggling the settings for pressing enter for new line/send, as well as the touchscreen mode setting, but same behavior.

### To Reproduce

Type message, press enter. Only a new line has been created.

### Version

0.11.3

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Qt version

5.15.9

### Desktop Environment

KDE Plasma 5.27.4

### Did you use profiles?

- [ ] Profiles used?

**Comment by caught-dead** [comment]
Just adding that I have the same issue under arch on a Lenovo X13 Yoga, running plasma 5.27.8.

**Comment by RoblKyogre** [comment]
found a slight workaround, if I start nheko with the on screen virtual keyboard disabled (can do that by clicking the input method icon in the system tray), it lets me send messages by pressing enter
however, if i enable the keyboard and press any text field to bring it up (does not matter where, can even be a different app), i can no longer send messages by pressing enter
also should note, am using `maliit-keyboard` as my virtual keyboard

**Comment by cyborgcatboy** [comment]
can confirm turning virtual keyboard off fixed the enter problem on plasma 6.0 !! is as simple as clikcing the keyboard button in the systray before u start nheko :3 (i ams also using `maliit-keyboard`)

**Comment by djotaku** [comment]
> can confirm turning virtual keyboard off fixed the enter problem on plasma 6.0 !! is as simple as clikcing the keyboard button in the systray before u start nheko :3 (i ams also using `maliit-keyboard`)

OMG!!! Thank you thank you thank you! I was wondering why it was fine on my desktop with plasma 5.0, but not on my laptop with 6.0. And this was driving me bonkers!!! Thank you so much.

BTW for debugging I am NOT using maliit-keyboard. I must have hit some key combo or maybe it's a default upon upgrading to Plasma 6. But I found the keyboard icon in the systray and turned off the virtual keyboard and all worked as it should.
