### ISSUE TITLE
Font in the timeline is different from the font in the settings or the font from my DE

### ISSUE THREAD

**Issue by duarm** [Nheko-Reborn/nheko#1479]
### Describe the bug

Both my system's font and Nheko font is set to Terminus
![image](https://github.com/Nheko-Reborn/nheko/assets/26150581/777db6b3-23fc-4705-a772-a1c716b51acc)

The timeline font is different, compare the "nheko is now qt6" with the "Write a message" font
![image](https://github.com/Nheko-Reborn/nheko/assets/26150581/e8f8ea45-0cb9-48f2-873b-676321c32a09)

I think the font is the same, but the one in the timeline is antialiased, My system's Terminus is set to "no antialiasing" in fonts.conf, it worked in qt5.

### To Reproduce

1. Set a Font Family on Nheko's settings
2. Set that particular font to not antialias in fonts.conf, or all fonts, mine is like this
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
    <match target="font">
        <edit name="antialias" mode="assign">
            <bool>false</bool>
        </edit>
        <edit name="hinting" mode="assign">
            <bool>true</bool>
        </edit>
        <edit name="hintstyle" mode="assign">
            <const>hintslight</const>
        </edit>
        <edit name="rgba" mode="assign">
            <const>none</const>
        </edit>
        <edit name="autohint" mode="assign">
            <bool>true</bool>
        </edit>
        <edit name="lcdfilter" mode="assign">
            <const>lcdnone</const>
        </edit>
        <edit name="dpi" mode="assign">
            <double>102</double>
        </edit>
    </match>
</fontconfig>
```
3. The timeline font is antialiased regardless, when everywhere else it is not

### Version

nheko 0.11.3-885168c0

### Operating system

Linux

### Installation method

Git

### Qt version

qt6-base 6.5.1-1

### Desktop Environment

qt6ct

### Did you use profiles?

- [ ] Profiles used?

**Comment by duarm** [comment]
https://github.com/Nheko-Reborn/nheko/commit/9796c40619542b2dbdf0c205e93f42b57b62f56c also fixed this!

![image](https://github.com/Nheko-Reborn/nheko/assets/26150581/335755f4-cd0a-448c-bfa0-1f122c17b3c2)

**Comment by duarm** [comment]
The devices window is not using the new TextArea from Qt6, it's suffering from the same problem as the original issue

**Comment by duarm** [comment]
this was regressed by d6ab752

**Comment by nteodosio** [comment]
Has this regressed? All my other applications have antialiasing disabled, but Nheko insists on antialising them everywhere.

I'm in Ubuntu 24.04 with Nheko 0.11.3.

`/etc/fonts/local.conf` is
```
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "urn:fontconfig:fonts.dtd">
<fontconfig> 
  <match target="font">
    <edit name="antialias" mode="assign">
      <bool>false</bool>
    </edit>
    <edit name="fontfeatures" mode="append">
      <string>liga off</string>
      <string>dlig off</string>
    </edit>
  </match>
</fontconfig>
```

**Comment by duarm** [comment]
I'm guessing you're using the release 0.11.3 version, the bug is present on 0.11.3 using QT6, it was fixed, regressed, and fixed again in the git version. You need to build from source in order to fix this, or wait for a new release.

**Comment by duarm** [comment]
Not sure then, the only thing I can suggest is trying to build the most recent version yourself, or use a ppa, either nheko or qt5 can be the cause depending on their version.
