### ISSUE TITLE
Can't login in KDE's server

### ISSUE THREAD

**Issue by alxlg** [Nheko-Reborn/nheko#148]
### Describe the bug
I can login with matrix.org server but not with KDE's one (@username:kde.org at kde.modular.im)

### To Reproduce
1. Get an account at kde.modular.im
2. Try to login in Nheko with @username:kde.org as username and kde.modular.im as homeserver
3. See that the login fails and you are back to login screen

### Expected behavior
Login like with matrix.org homeserver

### System:

- Nheko version: 0.6.2
- Installation method: Flatpak
- Operating System: KDE Neon based on Ubuntu 18.04 LTS
- Desktop Environment: KDE Plasma

### Logs
```
/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=nheko io.github.mujx.Nheko                                    
ssl3 ext invalid servername
ssl3 ext invalid servername
[2020-03-15 18:13:16.619] [ui] [info] starting nheko 0.6.2
[2020-03-15 18:13:54.470] [db] [info] initializing LMDB
[2020-03-15 18:13:54.485] [crypto] [info] creating new olm account
[2020-03-15 18:13:54.496] [crypto] [info] ed25519   : jojyM0M4fMfA2c75UmuhaIJIukSv0HKdu1V3VuttGjo
[2020-03-15 18:13:54.496] [crypto] [info] curve25519: VR8hsRdTiZ64UnJhad2YjuKiSwTTyOj8SH+S1SMOATg
[2020-03-15 18:13:54.496] [crypto] [info] generating one time keys
[2020-03-15 18:13:59.751] [net] [info] uploaded 50 signed_curve25519 one-time keys
[2020-03-15 18:13:59.751] [net] [info] trying initial sync
[2020-03-15 18:14:09.672] [net] [error] initial sync error: 1 
[2020-03-15 18:14:09.672] [ui] [info] dropping to the login page: Please try to login again: 
[2020-03-15 18:14:09.672] [db] [info] deleted cache files from disk
```

**Comment by deepbluev7** [comment]
Could you please try our official flatpak, as linked from the README first? I.e. this one: https://flathub.org/apps/details/io.github.NhekoReborn.Nheko ? 0.6.2 is very old and has numerous issues, like not supporting .well-known at all, etc.

**Comment by alxlg** [comment]
@deepbluev7 sorry that was supposed to be your Flatpak version, so what is this one I have here?
![immagine](https://user-images.githubusercontent.com/26327475/76707588-c0bcbc00-66f0-11ea-8dce-7cb32af49ce6.png)

**Comment by deepbluev7** [comment]
@mujx was the original developer of Nheko, but because of various reasons, he dropped the project and transferred(?) it to @redsky17, who created the Nheko-Reborn project. So you basically installed the version before the organizational changes. You can find the original project here: https://github.com/mujx/nheko . At least I hope I'm describing that correctly.

**Comment by redsky17** [comment]
> @mujx was the original developer of Nheko, but because of various reasons, he dropped the project and transferred(?) it to @redsky17, who created the Nheko-Reborn project. So you basically installed the version before the organizational changes. You can find the original project here: https://github.com/mujx/nheko . At least I hope I'm describing that correctly.

Yeah, that sounds basically accurate to me.  Hopefully a newer version of nheko will solve the issue you're seeing.  Specifically, prior to version 0.6.4, nheko doesn't support room versions 3 and newer, which causes issues with the application loading at all if any rooms of those versions are in your timeline.

**Comment by alxlg** [comment]
Thank you, I had no idea of this change, I switched to your version and now it works, I love it, thank you very much
