### ISSUE TITLE
Nheko RPM binary for OpenSuSE-15.5

### ISSUE THREAD

**Issue by fulup-bzh** [Nheko-Reborn/nheko#1490]
### The Problem

While Nheko was available for the OpenSuse-15.4 & Tumbleweed it is not for the the new 15.5

Nheko README list OBS as the official source for RPM, but it does produce any RPM for SuSE-15.5.  What is even more strange is that I do not see Nheko from fails logs (was it removed ?)
* https://download.opensuse.org/repositories/network:messaging:matrix
* https://build.opensuse.org/project/show/network:messaging:matrix

I would really nice to get Nheko rpm back from OBS.

### The Solution

Update OBS config

### Happens in the latest version

- [X] Yes, this feature is still missing.

**Comment by LorenDB** [comment]
According to https://build.opensuse.org/repositories/network:messaging:matrix/nheko, nheko should be being built for Leap 15.5. I'd suggest getting in touch with the openSUSE packagers.

**Comment by deepbluev7** [comment]
We don't really provide support for distro packages. We do list them, whenever someone adds them to the readme, but that is more for convenience. Also this is probably outdated by quite a bit now and should be fixed with the next release, I hope.
