### ISSUE TITLE
Add URL-Preview

### ISSUE THREAD

**Issue by 0verEngineer** [Nheko-Reborn/nheko#1493]
### The Problem

Element can load URL-Previews from Synapse if enabled on both sides, i cannot find an option for URL-Preview in Nheko, it would be very nice to have them.

### The Solution

Add URL-Previews like Element.

### Happens in the latest version

- [X] Yes, this feature is still missing.

**Comment by tux93** [comment]
Duplicate of #561 ?

**Comment by deepbluev7** [comment]
Yep, thanks!
