### ISSUE TITLE
Dynamically update font settings (change font without restart)

### ISSUE THREAD

**Issue by aaronraimist** [Nheko-Reborn/nheko#15]
### System:

- Nheko version: 0.6.2-ebe5b19
- Installation method: dmg
- Operating System: macOS 10.14.3

### Actual behavior

Font size and font family stay the same

### Steps to reproduce

Change font size or font family in settings

**Comment by redsky17** [comment]
The settings are only applied at startup, so you need to exit and reopen nheko for them to take affect.  This is not ideal, but when I had functionality in there to update it dynamically, it caused all sorts of weirdness (basically, the font family and font sizes would change, but none of the controls would refresh their padding and it causes text to get cut off weirdly).  I figured that I should leave it as is until I can figure out how to make all of the Qt controls refresh.

**Comment by aaronraimist** [comment]
Oh sweet, I'll update this issue to request dynamic updates in the future

**Comment by deepbluev7** [comment]
Oh, that is already fixed for a few months now.
