### ISSUE TITLE
Adapt color of icons in group side bar to theme

### ISSUE THREAD

**Issue by codic12** [Nheko-Reborn/nheko#150]
Watch this (set the theme to dark to reproduce)
![image](https://user-images.githubusercontent.com/48339289/76998843-f4772c00-6912-11ea-9f22-fa7575b8366e.png)
those icons are wrongly colored

**Comment by deepbluev7** [comment]
Which icons have the wrong colours? The more subtle coloring is intentional, and the icon with the dark speech bubbles is intentionally greyed out, since it is not functional yet.

**Comment by redsky17** [comment]
I agree with Nico.  This is intentional.  If you want them to look different, use the system theme and tweak it with your chosen qt theme tools

**Comment by gsbhasin123** [comment]
The black globe and star

**Comment by gsbhasin123** [comment]
The system theme has a similar result:
![image](https://user-images.githubusercontent.com/48339289/77021590-62881700-6944-11ea-8ff8-5cc0dfff63f2.png)

**Comment by deepbluev7** [comment]
Yeah, those are currently not themed, but I actually thought about doing that a few days ago already.

**Comment by gsbhasin123** [comment]
Awesome, thanks!

**Comment by jwinnie** [comment]
Hello,

What's the progress on this issue? Is there any way I can help?

**Comment by deepbluev7** [comment]
Someone actually implemented that, but I'm not sure, if they are gonna PR it anytime soon: https://github.com/Rennerdo30/nheko/commit/fe974aa9795799bd45d4f2f9cdad6bdbaad8a21f

**Comment by jwinnie** [comment]
@Rennerdo30

**Comment by deepbluev7** [comment]
Done
