### ISSUE TITLE
Vim like keybindings for the room search

### ISSUE THREAD

**Issue by Janik-Haag** [Nheko-Reborn/nheko#1504]
### The Problem

I like leaving my hands on the home row and am quite used to use j and k for down and up navigations and would love if this worked in the room search.

### The Solution

Make ctrl+j and ctrl+k do the same action as arrow down and arrow up in the room search.

### Happens in the latest version

- [X] Yes, this feature is still missing.

**Comment by LorenDB** [comment]
That might be tricky since we already use Ctrl+k to open the room search. Also, this is related to (or even a duplicate of) #584.

**Comment by Janik-Haag** [comment]
GitHub's search being shitty, I searched for vim and didn't find anything, sorry for the duplicate.
