### ISSUE TITLE
Allow using control k to see a list of rooms to switch between

### ISSUE THREAD

**Issue by gsbhasin123** [Nheko-Reborn/nheko#151]
Check out Discord's

**Comment by deepbluev7** [comment]
Nheko already has a room quick switcher accessed by control+K though? Could you please verify, if that doesn't work for you and if it doesn't. please specify your OS, install method and especially the Nheko version.

**Comment by gsbhasin123** [comment]
OS: ubuntu budgie 19.10
Install method: `sudo apt install nheko`
Nheko version: 0.6.4

However indeed it works, I wasn't aware :sweat_smile:
