### ISSUE TITLE
Emoji picker icons are small squares

### ISSUE THREAD

**Issue by gsbhasin123** [Nheko-Reborn/nheko#152]
System font; comic neue
I've tried changing the font in nheko's settings to 'noto color emoji'; this does not fix it.

**Comment by deepbluev7** [comment]
Which version are you using? The size was already increased for 0.7.0, so could you please specify your platform (OS, install method, qt version) and nheko version?

**Comment by deepbluev7** [comment]
This is how it looks in 0.7.0 (development version):
![grafik](https://user-images.githubusercontent.com/16312324/77002486-7dae5300-6953-11ea-9602-33c5a7d470a5.png)

**Comment by gsbhasin123** [comment]
OS; Ubuntu (Budgie) 19.10
Install method: `sudo apt install nheko`
QT Version: Not sure, whatever comes with my OS
Nheko version: 0.6.4

I can't figure out how to take a screenshot of it, sadly

**Comment by deepbluev7** [comment]
Yeah, this is hopefully fixed in the next release. I'll close this for now, but you could try a nightly build to see, if it is actually fixed. Otherwise you can reopen it after 0.7.0 is released.

**Comment by kortewegdevries** [comment]
@codic12

I've fixed this. Seems like it's a bug where multiple fonts can render emoji. Do this:
1. `sudo apt purge fonts-dejavu-core fonts-dejavu-extra `
2. Delete the `dejavu` folder dpkg warns about `/usr/share/fonts/truetype/dejavu`
3. `sudo apt install fonts-noto-color-emoji` if you don't have.
4. Run this script https://gitlab.com/es20490446e/emoji.conf/ `./install-uninstall.sh` Needs sudo !
5.  `fc-cache -frv`, should complete successfully.

Before: https://imgur.com/RrtruzG
After: https://imgur.com/H68QwrH

**Comment by codic12** [comment]
Thanks! I already switched to Arch and found this method a long time ago while doing something else, though (only I used Twemoji instead).
