### ISSUE TITLE
Can't accept room invite because description overflows the UI

### ISSUE THREAD

**Issue by uninsane** [Nheko-Reborn/nheko#1547]
### Describe the bug

when accepting a room invite to a room with very long description, the description seems to crowd out all other UI elements such that the "accept invite" button isn't clickable. see screenshot.

### To Reproduce

1. Create a room with very long description.
2. Invite a Nheko user to the room.
3. Click the pending invite.
4. Observe that it's impossible to accept the invite.

### Screenshots

![image](https://github.com/Nheko-Reborn/nheko/assets/106709944/a722b66e-26c4-41f9-ab51-ab93d0189de0)

### Version

0.11.3

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Desktop Environment

NixOS / sway

### Did you use profiles?

- [ ] Profiles used?

**Comment by curt-wise** [comment]
Same here:

![Screenshot_20230907_155201](https://github.com/Nheko-Reborn/nheko/assets/124194790/d54e2461-8abd-4ad6-8e6b-ce1c909296d1)

---
My sys info:

Operating System: Fedora Linux 38
KDE Plasma Version: 5.27.7
KDE Frameworks Version: 5.109.0
Qt Version: 5.15.10
Kernel Version: 6.4.13-200.fc38.x86_64 (64-bit)
Graphics Platform: Wayland

**Comment by deepbluev7** [comment]
We do limit the height for the description now, which hopefully fixes this?
