### ISSUE TITLE
UI: text lables are not readable when creating Community/Room

### ISSUE THREAD

**Issue by Luciogi** [Nheko-Reborn/nheko#1549]
### Describe the bug

![image](https://github.com/Nheko-Reborn/nheko/assets/84625092/e6b50c73-3b3d-43c9-943e-7120c691662c)

when clicking any three button, then windows which pops up does not look good in Dark theme

### To Reproduce

1. Enable dark theme
2. Click on '+' button
3. Click on 
![image](https://github.com/Nheko-Reborn/nheko/assets/84625092/8f6e0080-b9bf-45f8-be7c-db2500bfb042)

### What happened?

Dark theme is not implemented in these windows

### Expected behavior

Dark themed window

## Light Theme:
![image](https://github.com/Nheko-Reborn/nheko/assets/84625092/129436aa-c709-4956-b4fd-86b9eaa7be9d)

## Dark Theme
![image](https://github.com/Nheko-Reborn/nheko/assets/84625092/73647add-3fcc-4b77-9eda-46515946f7cf)

### Version

0.11.3

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Desktop Environment

KDE plasma

### Did you use profiles?

- [ ] Profiles used?

**Comment by LorenDB** [comment]
Hm, that doesn't happen for me. I guess it could be related to your system theme? Is Plasma using a light theme or dark theme overall?

**Comment by Luciogi** [comment]
@LorenDB  I use fluent dark theme
![image](https://github.com/Nheko-Reborn/nheko/assets/84625092/604ff171-c6ce-470a-8689-f268d9e2ea53)

**Comment by Luciogi** [comment]
Ok reapply theme fixes problem
Thanks for response!
