### ISSUE TITLE
Crash when running flatpak on KUbuntu 22.04

### ISSUE THREAD

**Issue by 0xpr03** [Nheko-Reborn/nheko#1550]
### Describe the bug

No matter which flatpak version I install (also on b865ca20 ) the application crashes.

### To Reproduce

1. Go to 'https://matrix-static.neko.dev/room/!TshDrgpBNBDmfDeEGN:neko.dev/'
2. Click on nheko-master-b865ca20-amd64.flatpak
3. flatpak install "nheko-master-b865ca20-amd64.flatpak"
4. Run it from the .desktop entry, or the same via a terminal to get crash output

Note that flatpak downloads  
- org.freedesktop.Platform.GL.nvidia-470-182-03 1.4
- org.freedesktop.Platform.GL.nvidia-470-199-02 1.4
- org.kde.KStyle.Adwaita 6.5
- org.kde.Platform.Locale 6.5
- org.kde.Platform 6.5

### What happened?

Doesn't start. No window.

Assertion crash in stl_vector.h

### Expected behavior

No crash in C++ STD

### Version

b865ca20

### Operating system

Linux

### Installation method

Flatpak nightly repo or download

### Desktop Environment

KDE Plasma 5.24.7 on X11

### Did you use profiles?

- [ ] Profiles used?

### Backtrace

```shell
> /usr/bin/flatpak run --branch=master --arch=x86_64 --command=im.nheko.Nheko --file-forwarding im.nheko.Nheko @@u %u @@
[2023-08-14 12:52:58.705] [ui] [info] Restoring window size 0x0

(gst-plugin-scanner:10): GStreamer-WARNING **: 12:52:58.735: Failed to load plugin '/app/lib/gstreamer-1.0/libgstqml6.so': /app/lib/gstreamer-1.0/libgstqml6.so: undefined symbol: gst_navigation_event_new_touch_cancel
[2023-08-14 12:52:59.537] [ui] [info] WebRTC: initialised GStreamer 1.20.6
[2023-08-14 12:52:59.571] [ui] [error] Missing GStreamer elements: qmlglsink 
/usr/include/c++/12.2.0/bits/stl_vector.h:1123: constexpr std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](size_type) [with _Tp = webrtc::ScreenShareType; _Alloc = std::allocator<webrtc::ScreenShareType>; reference = webrtc::ScreenShareType&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.
Error: signal 6:
im.nheko.Nheko(+0x61db80)[0x562bfa768b80]
/usr/lib/x86_64-linux-gnu/libc.so.6(+0x3f0c0)[0x7f4fb3d9a0c0]
/usr/lib/x86_64-linux-gnu/libc.so.6(+0x91184)[0x7f4fb3dec184]
/usr/lib/x86_64-linux-gnu/libc.so.6(raise+0x1e)[0x7f4fb3d9a00e]
/usr/lib/x86_64-linux-gnu/libc.so.6(abort+0xd7)[0x7f4fb3d837fc]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xe1f9d)[0x7f4fb414df9d]
im.nheko.Nheko(+0x401bdf)[0x562bfa54cbdf]
im.nheko.Nheko(+0x52a1e9)[0x562bfa6751e9]
im.nheko.Nheko(+0x57978e)[0x562bfa6c478e]
im.nheko.Nheko(main+0x1418)[0x562bfa307088]
/usr/lib/x86_64-linux-gnu/libc.so.6(+0x2954a)[0x7f4fb3d8454a]
/usr/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x8b)[0x7f4fb3d8460b]
im.nheko.Nheko(+0x1bec25)[0x562bfa309c25]
```

**Comment by deepbluev7** [comment]
This is fixed on master.
