### ISSUE TITLE
"System" theme should default to the freedesktop preference

### ISSUE THREAD

**Issue by orowith2os** [Nheko-Reborn/nheko#1551]
### Describe the bug

The UI has three options: Light, Dark, and System. 

When selecting the Light and Dark modes, both work as expected. However, when I click System, it goes to a different theme, despite my system being set to Dark. 

### To Reproduce

1. Set dark mode via the freedesktop preference
2. Select System for the theme option

### What happened?

The theme was different than the Dark theme in Nheko, despite the system being set to dark mode.

### Expected behavior

Nheko would use its themes, and set them according to the freedesktop preference. 

### Screenshots

![image](https://github.com/Nheko-Reborn/nheko/assets/93224879/aaa72db5-87ed-4185-b518-87ea3f559bb7)
![image](https://github.com/Nheko-Reborn/nheko/assets/93224879/1ac2d1f1-5dcb-4cbb-84da-77da26380bef)
![image](https://github.com/Nheko-Reborn/nheko/assets/93224879/b07196d0-b82d-4cee-b0b2-39f594d5603a)

### Version

0.11.3-d27e42d

### Operating system

Linux

### Installation method

Flathub

### Qt version

NA

### C++ compiler

NA

### Desktop Environment

GNOME

### Did you use profiles?

- [ ] Profiles used?

### Relevant log output

```shell
NA
```

### Backtrace

```shell
NA
```

**Comment by orowith2os** [comment]
There are also a multitude of issues, like not using the Camera portal and low contrast, but those are better saved for another time.

**Comment by LorenDB** [comment]
The system theme is intended to use whatever color scheme your system is set to. In this case it is the dark adwaita palette. The light and dark themes are merely custom palettes that you can set if you don't want to use whatever your system is configured to use.

You're welcome to open another issue about the camera portal and also bring up the low contrast issue somewhere. I'm not sure if we have an existing accessibility issue anywhere that would fit that topic.
