### ISSUE TITLE
native notification windows

### ISSUE THREAD

**Issue by Tcll** [Nheko-Reborn/nheko#1555]
### The Problem

as I don't have dbus on my system, I don't have a global notification daemon either...
I've had to mock up some shoddy implementation using Gnome's old notification-daemon as a custom appimage launched within a pre-configured nheko dbus session.
(I've integrated dbus into nheko's appimage, so to start it, I use `Exec=dbus-run-session --config-file=~/.config/dbus/session.conf launch-nheko %u` within the appimage launcher)
^ `launch-nheko` starts the configured (`~/.config/nheko/launch.cfg`) notification daemon and keyring before actually starting nheko (even works with my custom homepath script, so I can even have mutliple nheko instances with multiple notification daemons if I prefer)

But anyways, the problem is all that complexity for displaying a simple popup window I could otherwise configure within Nheko's settings.

In addition, Gnome's craptastic notification-daemon doesn't even respond to click events, so I can't even configure it to take me to the notified message like I had with LibreWolf... heh
(never mind the fact I can't even theme it... (*something I can do easily in my own GUI toolkit*) get with it Gnome, even gtk2 makes that look bad)

### The Solution

Add a native notification thread that spawns prioritized (always on top) overlay windows containing the notification text

The settings can configure the native notification windows which can be toggled regardless of whether you have dbus or not (you may prefer it despite having dbus), as well as the notification theme (QSS) and window position (even RetroShare can do that with it's notifications)

additionally you should be able to configure if you want to open notifications as separate room windows, since Nheko already has functionality for this
(not sure if this can be done with dbus notifications as well, but as stated previously, currently I don't even have event feedback to even be taken to the notified message as I had with both Cinny and Schildi with LibreWolf's native notification windows)

### Alternatives

described in the problem (Gnome's notification-daemon)

### Additional context

described in the solution

and like RetroShare, this'll even beat LibreWolf since I still can't theme and position it's notification windows, at least as far as I know anyways (haven't been able to find anything if it's possible).

### Happens in the latest version

- [X] Yes, this feature is still missing.

**Comment by LorenDB** [comment]
We've already had this discussion in #1390 and #1391, and we made it clear that we aren't interested in doing this.

**Comment by Tcll** [comment]
this request is not about removing dbus

it's about adding native notifications

**Comment by LorenDB** [comment]
If you read #1391, Nico explicitly stated multiple times that we have no intentions of adding a custom notification handler.

**Comment by Tcll** [comment]
... alright alright fine, I forgot I actually requested that in the old issue... sorry
(I've dealt with other devs who've made similar nods to what I thought, please excuse me there)

it's just disappointing given just how simple of a task that actually is... (now that I've basically built my own)
if I understood the source of Nheko, I'd do it myself despite all my other projects...

it's not like I'm requesting you guys make Nheko a media player (which it kinda already is, sad it's gstreamer though and not a path ffmpeg), or web browser, or something else convoluted...

but regardless, I get it, I won't ask again.
