### ISSUE TITLE
Notification delivery issue when conntected to multiple devices

### ISSUE THREAD

**Issue by Dragnucs** [Nheko-Reborn/nheko#1557]
### Describe the bug

When connected to multiple devices, notifications do not reach correct or active target when screen is locked on device running Nheko.

The problem does not arise when Nheko is out of focus.

### To Reproduce

1. Start a chat on Nheko on the computer
2. Leave chat window focused and lock the computer screen
3. Continue chatting on the go on a smartphone using Element
4. Element does not receive any notification

### What happened?

Notification is delivered to Nheko on the computer which screen's is locked while not received by the mobile device.

### Expected behavior

Notification should not be delivered to a client on a screen-locked device. Mobile client should still receive message notification?

### Version

0.11.3

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Qt version

4.8.7

### Desktop Environment

Gnome 44.3

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment]
I very much hope the qt version you entered is incorrect. Also I can't seem to reproduce this on KDE, could it be that Gnome does not unfocus an application when locking the screen?

**Comment by Dragnucs** [comment]
My applogies for the late reply. During this time I was able to test many other software and frameworks. Gnome simply does not remove focus from a windows when it locks the screen. So this issue is not related to Nheko.
