### ISSUE TITLE
Tooltips (Mouse hover over reaction icons etc) not readable

### ISSUE THREAD

**Issue by handmade-it** [Nheko-Reborn/nheko#1559]
### Describe the bug

The color of the tooltips is white on light yellow and not readable. The color is not affected by the selected nheko theme. 

See the attached screenshot, this shows the problem.

Is there any quick workaround?

Thanks in advance!

### To Reproduce

1. React to a message with an icon. 
2. Hover over the icon
3. Try to read the content of the tooltip

### Screenshots

![Screenshot_2023-09-12_11-19-46](https://github.com/Nheko-Reborn/nheko/assets/13585631/7612c48c-d17b-4bf6-98e3-602e0432d853)

### Version

0.9.1

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Desktop Environment

XFCE 4.16

### Did you use profiles?

- [ ] Profiles used?

**Comment by LorenDB** [comment]
This looks like a theme problem. Can you share the following:

1. Your system Qt theme
2. Your overall system color scheme (i.e. is it light or dark)
3. What the theme setting in nheko settings is set to

However, even without the above information, I'm going to say that given that you are on XFCE, it seems possible that the Qt theme is not set properly; if you haven't, you could look into setting up qt5ct to see if that fixes it.
