### ISSUE TITLE
Special unicode characters cause message not to render

### ISSUE THREAD

**Issue by Nothing4You** [Nheko-Reborn/nheko#1564]
### Describe the bug

Some special unicode characters, specifically tested with U+FFFC ￼ OBJECT REPLACEMENT CHARACTER, will cause the entire message to not be rendered, both in the text input field and also when such a message is in the chat.
nheko will still allocate the necessary space for the message, but it will not display any text.

### To Reproduce

1. Copy this text to the text input: `U+FFFC ￼ is troublesome`
2. Observe text input not showing any text
3. Send the message
4. Observe the message seemingly being blank

When performing this with a multi line message, you'll also see space for multiple lines being used in the layout with seemingly no content.

### What happened?

Text is invisible.

### Expected behavior

Text is visible, potentially showing some placeholders for incompatible characters.
I don't know if this is easy to implement, but I would prefer that the original content will still be in the clipboard buffer when copied instead of a modified version.

### Screenshots

Element:
<img width="218" alt="image" src="https://github.com/Nheko-Reborn/nheko/assets/3694534/0c69d514-5c7a-4a38-b439-adf4a6bd7d85">
nheko:
<img width="133" alt="image" src="https://github.com/Nheko-Reborn/nheko/assets/3694534/291c5fed-cd42-4803-9806-ebc14c2d9490">

### Version

0.11.3-03be9e47

### Operating system

macOS

### Installation method

macOS DMG file

### Did you use profiles?

- [ ] Profiles used?

**Comment by Nothing4You** [comment]
can't reproduce this anymore on 0.11.3-eaf9ae31, seems like it probably got fixed at some point

**Comment by papoteur-mga** [comment]
> can't reproduce this anymore on 0.11.3-eaf9ae31, seems like it probably got fixed at some point, possibly with a newer qt version

Hello,
Which Qt version where implied?
