### ISSUE TITLE
nheko crashes on first launch in arm64 (librem 5)

### ISSUE THREAD

**Issue by nileshpatra** [Nheko-Reborn/nheko#1574]
### Describe the bug

I initially noticed this on mobian bookworm (then I switched to 
chatty). Now I can reliable reproduce it on trixie as well.

### To Reproduce

To reproduce rm -rf .local/share/nheko .config/nheko .cache/nheko
and run nheko from terminal

### What happened?

First noticed when I reinstalled, flatpack also fails same way so looks 
like an upstream issue.

Second time, nheko starts but initial sync never completes. Both chatty 
and gomuks works with same matrix id.

### Expected behavior

Nheko should have started without any issues

### Version

0.11.3

### Operating system

Mobian (Debian on mobile)

### Installation method

From apt repo

### C++ compiler

g++

### Did you use profiles?

- [ ] Profiles used?

### Backtrace

```shell
This is the same as debian issue: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1042967
Backtrace from the same bug:

[2023-08-03 17:42:55.678] [ui] [info] Restoring window size 0x0
[2023-08-03 17:42:55.759] [ui] [info] WebRTC: initialised GStreamer 1.22.4
[2023-08-03 17:42:55.883] [ui] [info] jdenticon plugin not found.
[2023-08-03 17:42:57.976] [ui] [info] starting nheko 0.11.3
[2023-08-03 17:42:57.986] [ui] [info] Unity service available: false
Error: signal 11:
nheko(_Z17stacktraceHandleri+0x40)[0xaaaad55ee940]
linux-vdso.so.1(__kernel_rt_sigreturn+0x0)[0xffffa06be7ac]
nheko(+0x973940)[0xaaaad5433940]
nheko(+0x977090)[0xaaaad5437090]
nheko(+0x9783bc)[0xaaaad54383bc]
/lib/aarch64-linux-gnu/libgstreamer-1.0.so.0(+0x55270)[0xffff9da25270]
/lib/aarch64-linux-gnu/libglib-2.0.so.0(g_main_context_dispatch+0x148)[0xffff9d83a6c8]
/lib/aarch64-linux-gnu/libglib-2.0.so.0(+0x5aaa0)[0xffff9d83aaa0]
/lib/aarch64-linux-gnu/libglib-2.0.so.0(g_main_context_iteration+0x34)[0xffff9d83ab44]
/lib/aarch64-linux-gnu/libQt5Core.so.5(_ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE+0x54)[0xffff9deef6d8]
/lib/aarch64-linux-gnu/libQt5Core.so.5(_ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE+0x13c)[0xffff9de89d2c]
/lib/aarch64-linux-gnu/libQt5Core.so.5(_ZN16QCoreApplication4execEv+0x98)[0xffff9de933f8]
nheko(main+0xd14)[0xaaaad526b684]
/lib/aarch64-linux-gnu/libc.so.6(+0x26dc0)[0xffff9d2a6dc0]
/lib/aarch64-linux-gnu/libc.so.6(__libc_start_main+0x98)[0xffff9d2a6e98]
nheko(_start+0x30)[0xaaaad526c770]
Error: signal 6:
nheko(_Z17stacktraceHandleri+0x40)[0xaaaad55ee940]
linux-vdso.so.1(__kernel_rt_sigreturn+0x0)[0xffffa06be7ac]
/lib/aarch64-linux-gnu/libc.so.6(+0x7fd30)[0xffff9d2ffd30]
/lib/aarch64-linux-gnu/libc.so.6(gsignal+0x1c)[0xffff9d2b9e2c]
nheko(_Z17stacktraceHandleri+0xd8)[0xaaaad55ee9d8]
linux-vdso.so.1(__kernel_rt_sigreturn+0x0)[0xffffa06be7ac]
nheko(+0x973940)[0xaaaad5433940]
nheko(+0x977090)[0xaaaad5437090]
nheko(+0x9783bc)[0xaaaad54383bc]
/lib/aarch64-linux-gnu/libgstreamer-1.0.so.0(+0x55270)[0xffff9da25270]
/lib/aarch64-linux-gnu/libglib-2.0.so.0(g_main_context_dispatch+0x148)[0xffff9d83a6c8]
/lib/aarch64-linux-gnu/libglib-2.0.so.0(+0x5aaa0)[0xffff9d83aaa0]
/lib/aarch64-linux-gnu/libglib-2.0.so.0(g_main_context_iteration+0x34)[0xffff9d83ab44]
/lib/aarch64-linux-gnu/libQt5Core.so.5(_ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE+0x54)[0xffff9deef6d8]
/lib/aarch64-linux-gnu/libQt5Core.so.5(_ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE+0x13c)[0xffff9de89d2c]
/lib/aarch64-linux-gnu/libQt5Core.so.5(_ZN16QCoreApplication4execEv+0x98)[0xffff9de933f8]
nheko(main+0xd14)[0xaaaad526b684]
/lib/aarch64-linux-gnu/libc.so.6(+0x26dc0)[0xffff9d2a6dc0]
/lib/aarch64-linux-gnu/libc.so.6(__libc_start_main+0x98)[0xffff9d2a6e98]
nheko(_start+0x30)[0xaaaad526c770]
```

**Comment by deepbluev7** [comment]
I think this is related to the voip code and should be fixed in the nightlies, can you confirm that?

**Comment by nileshpatra** [comment]
@pravi can you confirm it on your mobile device, please?

**Comment by pravi** [comment]
> @pravi can you confirm it on your mobile device, please?

@nileshpatra I tried to build it on debian trixie (which I run on my Librem 5), but it needs qt 6.5 (trixie has only 6.4 and 6.6 is only available on experimental). If we can find a specific commit that fixes this issue, we can test this sooner, or else I will have to wait till qt 6.6 is available in trixie. I will also consider rebuilding it on experimental but bit reluctant to test it as it is my primary phone.

**Comment by pravi** [comment]
I tried building on experimental, but qt6-multimedia is not yet updated to 6.6

**Comment by tiol11** [comment]
Hi, instead of waiting for Qt>=6.5 coming to Debian, why don't you try and build the 0.11.3 adding the recent voip-related commits?

with a search, there is just 1 voip-related commit 1594933 ...

**Comment by tiol11** [comment]
Ok, was able to reproduce the issue on my OG PP using the 0.11.3-2 package from Debian sid.

And, I was able to build and test the same package by applying commit 1594933 on top of it: can confirm that fixes this issue. Thanks @deepbluev7 !

**Comment by tiol11** [comment]
The patch to this was applied in Debian [last December](https://tracker.debian.org/news/1489256/accepted-nheko-0113-21-source-into-unstable/) and related [Debian bug](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1042967) was not re-opened since: @nileshpatra @pravi can you please double-check and close this issue?

**Comment by nileshpatra** [comment]
I will re-open if it is reported again.
