### ISSUE TITLE
Rename "bundled" dependencies to "downloadable".

### ISSUE THREAD

**Issue by lockywolf** [Nheko-Reborn/nheko#1587]
### Describe the bug

The name "bundled" is confusing. "Bundled" means that the dependencies are included in the archive file. Here they are not, they are downloaded with "hunter", and therefore builds on airgapped machines fail.

Please, consider changing "bundled" to "downloadable".

### To Reproduce

1. cmake -DUSE_BUNDLED...
2. cmake --build . on an airgapped machine.
3. Observer fail.

### Version

0.11.3

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment]
They are called bundled not because we can automatically download them, but because they will need to be shipped with the final binary and won't be updated with your operating system as usual. I think "bundled" describes that better than downloadable?
