### ISSUE TITLE
Limit size of reply

### ISSUE THREAD

**Issue by vurpo** [Nheko-Reborn/nheko#159]
When a message is a reply, the replied-to message seems to be rendered in full above the message. If that message is long, or especially if it's an image, the reply ends up being huge on screen and often just repeats another message that's already simultaneously visible. (Riot also has the same problem.)

I suggest that the reply's vertical size should be limited. If it's a text message, limit it to a specific vertical height and just cut off the rest of the message with an ellipsis. If it's an image, then shrink it down to a small thumbnail. (Basically the same way Telegram renders replies in their apps.) Of course, then it would also be nice if it scrolled to the message when you click the reply.

**Comment by deepbluev7** [comment]
I implemented that at some point. It does still have some issues, where it not necessarily scrolls to exactly the right position though, because the timeline lazy loads and the cutoff may not be at a nice line boundary. It should be part of the way there though.
