### ISSUE TITLE
media files lack licensing (seems to originate from files restricted to non-commercial use)

### ISSUE THREAD

**Issue by jonassmedegaard** [Nheko-Reborn/nheko#1590]
### Describe the bug

File below `resources/media` lack licensing, and is only documented to be derived from matrix-react-sdk. That in turn is derived from https://github.com/vector-im/element-web/commit/782234de6d where the files still lack licensing but at least there they have author field in metadata: https://freesound.org/people/FoolBoyMedia/ who seems to publish works under an only-non-commercially-free license.

Please replace those media files with explicitly and fully freely licensed material.

### To Reproduce

.

### Version

any

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment]
We asked if we could redistribute those files as part of Nheko and got permission for that, so why does the license from the top level directory not apply there?

**Comment by jonassmedegaard** [comment]
> We asked if we could redistribute those files as part of Nheko and got permission for that

Who did you ask, and what exactly did you ask for? If you asked the developers of matrix-react-sdk (as the README file in that media directory seems to indicate), then seemingly they were themselves only granted a license and do not hold copyright, and therefore were not in a position to grant you a relicensing of those files.

If you asked if you "could redistribute those files" then that is within the rights granted by the license, but is missing the point here: It is permission to *modify* the files (not to redistribute them) that is only permitted for non-commercial purposes in the `CC-by-nc` type license commonly used by Fool Boy Media.

> why does the license from the top level directory not apply there

The existence of a license file in a project is a very weak indicator that some asset within that project is in fact licensed by that contained license. The existence of *different* indicators closer to an asset - e.g. a document hinting that a subdirectory is derived from a different source usually is considered stronger pointer than such weak licensing hints for the project as a whole.

Please, if you have received permission from an author to relicense some assets, then write that information down, preferrably by quoting verbatim the message you received from that author.

**Comment by jonassmedegaard** [comment]
Also, even if those audio files have genuinely by their author been licensed under some GPL license, then those licenses require that credit not be removed which has occured (probably before you got hold of the files) for these media files.

**Comment by deepbluev7** [comment]
> Who did you ask, and what exactly did you ask for?

I asked the CEO of Element if we could redistribute those files as part of Nheko as long as we point to where we got them. However at the time I intended to refer to the license of those files for them, I guess. I guess I do now see, what you mean with those files, have you asked Element about how they obtained a license for those files?

**Comment by jonassmedegaard** [comment]
No, I have not reported this issue further upstream.  Nor have I made contact with the author.

**Comment by Mikaela** [comment]
I think https://reuse.tool might be helpful in declaring licenses of those files
