### ISSUE TITLE
Completely disable smooth scrolling

### ISSUE THREAD

**Issue by squeaktoy** [Nheko-Reborn/nheko#1592]
### The Problem

I see other issues mentioning smooth scrolling but for some reason, it is stated Qt 6.6 fixes those issues. That sounds pretty crazy, as no other Qt 6 program on my computer has a "smooth scrolling" issue. In fact, no other program on my computer has smooth scrolling. All I want is to completely eradicate smooth scrolling from nheko on my system. Anyone know which code is responsible for this crap? I'd love to nuke it.

### The Solution

A good solution would be the ability to completely disable smooth scrolling.

### Alternatives

Nuke smooth scrolling code as a patch

### Happens in the latest version

- [X] Yes, this feature is still missing.

**Comment by deepbluev7** [comment]
So why are you opening an issue? It is not us who implements the smooth scrolling, it is Qt and as mentioned, it should be fixed in Qt6.6.

**Comment by deepbluev7** [comment]
Since there was no reply and this seems to be a misunderstanding, I will close this.
