### ISSUE TITLE
A way to disable swipe motions

### ISSUE THREAD

**Issue by duarm** [Nheko-Reborn/nheko#1595]
### The Problem

I frequently misinput swipe motions when trying to select text, I always navigate through rooms with Ctrl+k, so I quite literally never want a swipe motion, everytime it happens is due to a mistake.

### The Solution

An option to disable swipe motions. I might be able to do it when I have time, so guidances are welcome.

### Notes

I think every swipe is handled with by a DragHandler, just disabling the appropriate ones with an option seems pretty easy.

### Happens in the latest version

- [X] Yes, this feature is still missing.

**Comment by deepbluev7** [comment]
The swipe motion should only be active, if your window is small enough to switch to mobile mode. Is that the case?

**Comment by duarm** [comment]
> The swipe motion should only be active, if your window is small enough to switch to mobile mode. Is that the case?

Yes, I'm on a tile window manager, nheko will most likely be squished somewhere

**Comment by duarm** [comment]
Worth noting, even when fullscreen, nheko still uses the mobile layout and swipe motions, not sure why, but I much prefer this way

**Comment by deepbluev7** [comment]
Quite possibly you are using a bitmap font, which breaks our width calculations (because Qt returns weird values for those fonts). However thanks for the PR!
