### ISSUE TITLE
Malformed images are still displayed

### ISSUE THREAD

**Issue by duarm** [Nheko-Reborn/nheko#1596]
### Describe the bug

sometimes I upload an image which might be end up malformed for any reason, e.g. when pasting from clipboard, which is overwritten, or when deleting the image, before the upload is finished.

the image remains malformed in the timeline

### To Reproduce

1. Upload image from clipboard/drag & drop
2. overwrite clipboard before upload finished, or close the program in which you dragged in case of drag & drop
3. image is malformed

### Expected behavior

The image is removed from db, or ignored, or display in a minimal way like a "malformed image event"

### Screenshots

![image](https://github.com/Nheko-Reborn/nheko/assets/26150581/c31cf4e5-cec4-49d4-b0d8-d17ea92190de)

the raw message
![278127532-04488843-1826-4afb-867f-a4da06d1eda0](https://github.com/Nheko-Reborn/nheko/assets/26150581/35bd7fea-f3cd-46ab-a2e0-4896afcaf6e0)

### Version

nheko 0.11.3-51976cf3

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Qt version

6.6

### C++ compiler

13.2.1

**Comment by deepbluev7** [comment]
How would we know, that the image is malformed?

**Comment by duarm** [comment]
No idea if there's a consistent way, maybe an image with size 0 or with million resolution, like the message I linked?

**Comment by deepbluev7** [comment]
That could also just be an image, which we didn't understand correctly and refusing to send those sounds like a mistake?

**Comment by duarm** [comment]
Not easy to solve indeed, I'll close this since it's not that much of a problem
