### ISSUE TITLE
Create an AUR package

### ISSUE THREAD

**Issue by dessalines** [Nheko-Reborn/nheko#16]
Here's the old [package build.](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=nheko-git) I tried to do it myself, replacing the url's, but my build failed due to some qt5 error.

**Comment by redsky17** [comment]
It looks like the AUR package has been updated to point to this repo instead of mujx/nheko.

**Comment by MasterOfTheTiger** [comment]
@redsky17 Yes. The main one is, but the nheko-git package is not. Everything there still points to the mujix/nheko instead. https://aur.archlinux.org/packages/nheko-git/

**Comment by redsky17** [comment]
That package is maintained by mujx himself and is very out dated as it is.  I'm not concerned about it
