### ISSUE TITLE
Hidden event toggle does not work 

### ISSUE THREAD

**Issue by bbhtt** [Nheko-Reborn/nheko#1600]
### Describe the bug

1. Install Nightly flatpak
2. Settings > Global message visibility > Hidden events 
3. Toggle user events and power level changes off, click ok
4. Return to save dialogue
5. See that they are automatically toggled on back again

I see this in the terminal:

```
[2023-10-30 13:00:53.786] [mtx] [warning] Error parsing events: Empty event type, {
  "content": {
    "hidden_event_types": [
      "m.reaction",
      "m.call.candidates",
      "m.call.negotiate",
      "",
      "m.call.select_answer",
      "m.room.member",
      "m.room.power_levels"
    ]
  },
  "type": "im.nheko.hidden_events"
}
```

Removing the empty event : `""` makes the toggle persist again.

### To Reproduce

See above

### What happened?

Hidden event toggle does not work

### Expected behavior

The toggle should work

### Screenshots

N/A

### Version

0.11.3-2b1844d4

### Operating system

Linux

### Installation method

Flatpak nightly repo or download

### Qt version

Qt 6.6

### C++ compiler

N/A

### Desktop Environment

GNOME

### Did you use profiles?

No

### Relevant log output

N/A

### Backtrace

N/A

**Comment by deepbluev7** [comment]
You need to manually clear the timeline after toggling that setting otherwise it will only apply to new events. You can do that using the `/clear-timeline` command :)

**Comment by deepbluev7** [comment]
Ah, I guess the issue here is that the toggle blocks when an empty event type is inserted and that this is inserted by default when modifying stuff inside of Nheko?

**Comment by bbhtt** [comment]
Yes, thanks!
