### ISSUE TITLE
Supporting Nheko custom events in my Matrix client

### ISSUE THREAD

**Issue by avdb13** [Nheko-Reborn/nheko#1625]
Hi there, first of all thanks for your amazing work on this client! However, I noticed that a few things like annotations are formatted differently (see example below). I was wondering if these custom extensions were documented somewhere to make it easier to support Nheko since it would be painful to have to reverse-engineer everything.

```ts
{
    "im.nheko.relations.v1.relations": [
        {
            "event_id": "$4Qr_OGH7IlPvsLFsALzHHpP2KS68RAOPbYMDVurA6oc",
            "key": "mxc://tastytea.de/ORllHqkABcIHyorgoSIgpgbs",
            "rel_type": "m.annotation"
        }
    ],
    "m.relates_to": {
        "event_id": "$4Qr_OGH7IlPvsLFsALzHHpP2KS68RAOPbYMDVurA6oc",
        "key": "mxc://tastytea.de/ORllHqkABcIHyorgoSIgpgbs",
        "rel_type": "m.annotation"
    }
}
```

**Comment by NepNep21** [comment]
`m.relates_to` and `m.annotation` are part of [the spec](https://spec.matrix.org/v1.9/client-server-api/#mannotation-relationship-type), I am unsure about the namespaced event but I find it likely it's a pre-spec legacy thing that doesn't matter anymore (citation needed).

**Comment by NepNep21** [comment]
For context, standard relationships are still supported by mtxclient, so it seems unnecessary to implement that extension.

**Comment by deepbluev7** [comment]
The custom relation format is documented here: https://github.com/matrix-org/matrix-spec-proposals/pull/3051
