### ISSUE TITLE
Random crashes while inactive

### ISSUE THREAD

**Issue by LorenDB** [Nheko-Reborn/nheko#163]
The program randomly crashes sometimes while it is inactive. To my knowledge, this does not depend on internet connectivity.

### System:
- Nheko version: 0.6.4
- Installation method: Installed via Discover on KDE
- Operating System: Kubuntu 19.10
- Desktop Environment: KDE Plasma 5.16.5

Log: [nheko.log](https://github.com/Nheko-Reborn/nheko/files/4465291/nheko.log)  
Backtrace: [nheko-backtrace.dump.tar.gz](https://github.com/Nheko-Reborn/nheko/files/4465292/nheko-backtrace.dump.tar.gz)

**Comment by redsky17** [comment]
I do believe we have addressed this in the 0.7.0 beta / nightlies that we have out.  There was an issue in the mtxclient related to closing connections incorrectly, and also some double-free related issues.  Could you try one of the nightly builds and report back?

**Comment by LorenDB** [comment]
Sure thing.

**Comment by LorenDB** [comment]
Due to my limited internet connection I'm actually not going to download it from Flathub (~3/4 GB) but I believe this can be closed.

**Comment by deepbluev7** [comment]
Yay, thanks :D

**Comment by redsky17** [comment]
@LorenDB Maybe I'm misunderstanding,but our nightlies are available on our nightly release channel on matrix: #nheko-nightlies:neko.dev.  The largest ones are still under 90MB, if you want to try those instead of the flathub releases.

**Comment by LorenDB** [comment]
I didn't realize that. Thanks.

**Comment by deepbluev7** [comment]
You can also view the nightlies here: https://matrix-static.neko.dev/room/!TshDrgpBNBDmfDeEGN:neko.dev/
