### ISSUE TITLE
Fix notification spam on opening Nheko

### ISSUE THREAD

**Issue by BentiGorlich** [Nheko-Reborn/nheko#1641]
### The Problem

When I wake up and open Nheko I get a notification for every message I received since the last start. It's very annoying and not useful at all

### The Solution

Only output one notification per chat with missed messages

### Alternatives

Don't ouput notifications for messages sent while Nheko was not active

### Additional context

Using the windows and Linux versions of Nheko

### Happens in the latest version

- [X] Yes, this feature is still missing.

**Comment by deepbluev7** [comment]
This is already fixed, there is only one message if you get more than a few notifications at once. Just not in a release yet.
