### ISSUE TITLE
nheko-git from aur fails to build, linking error

### ISSUE THREAD

**Issue by daweiheiu** [Nheko-Reborn/nheko#1645]
### Describe the bug

linking error

### To Reproduce

1. Install nheko-git from aur
2. get a linking error

### What happened?
dosent build

### Expected behavior

builds with out errors

### Version

0.11.3.r577.ge49a65e6-1

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### C++ compiler

gcc 13.2.1 

### Did you use profiles?

- [ ] Profiles used?

### Relevant log output
-- Generating done (0.1s)
-- Build files have been written to: /home/joe/.cache/aureate/nheko-git/src/nheko-git/build
[  0%] Built target coeurl
[ 15%] Built target matrix_client
[ 15%] Built target nheko_autogen_timestamp_deps
[ 36%] Built target nheko_tooling
[ 42%] Built target nheko_lrelease
[ 42%] Built target nheko_qmlimportscan
[ 43%] Built target nheko_autogen
[ 43%] Running AUTOMOC file extraction for target nheko
[ 43%] Built target nheko_automoc_json_extraction
[ 43%] Running moc --collect-json for target nheko
[ 43%] Generating meta_types/qt6nheko_release_metatypes.json
[ 43%] Generating meta_types/qt6nheko_release_metatypes.json
[ 43%] Linking CXX executable nheko
/usr/bin/ld: warning: libfmt.so.10, needed by /usr/lib/libspdlog.so.1.12.0, may conflict with libfmt.so.9
/usr/bin/ld: CMakeFiles/nheko.dir/src/timeline/CommunitiesModel.cpp.o: in function `CommunitiesModel::updateSpaceStatus(QString, QString, bool, bool, bool) const':
CommunitiesModel.cpp:(.text+0x127e5): undefined reference to `spdlog::details::log_msg::log_msg(spdlog::source_loc, fmt::v9::basic_string_view<char>, spdlog::level::level_enum, fmt::v9::basic_string_view<char>)'
/usr/bin/ld: CMakeFiles/nheko.dir/src/timeline/CommunitiesModel.cpp.o: in function `std::_Function_handler<void (mtx::responses::EventId const&, std::optional<mtx::http::ClientError> const&), CommunitiesModel::up
:optional<mtx::http::ClientError> const&)':
CommunitiesModel.cpp:(.text+0x13231): undefined reference to `spdlog::details::log_msg::log_msg(spdlog::source_loc, fmt::v9::basic_string_view<char>, spdlog::level::level_enum, fmt::v9::basic_string_view<char>)'
/usr/bin/ld: CMakeFiles/nheko.dir/src/timeline/CommunitiesModel.cpp.o: in function `std::_Function_handler<void (mtx::responses::EventId const&, std::optional<mtx::http::ClientError> const&), CommunitiesModel::up
:optional<mtx::http::ClientError> const&)':
CommunitiesModel.cpp:(.text+0x136e1): undefined reference to `spdlog::details::log_msg::log_msg(spdlog::source_loc, fmt::v9::basic_string_view<char>, spdlog::level::level_enum, fmt::v9::basic_string_view<char>)'
/usr/bin/ld: CMakeFiles/nheko.dir/src/timeline/CommunitiesModel.cpp.o: in function `std::_Function_handler<void (mtx::responses::EventId const&, std::optional<mtx::http::ClientError> const&), CommunitiesModel::up
:optional<mtx::http::ClientError> const&)':
CommunitiesModel.cpp:(.text+0x13b91): undefined reference to `spdlog::details::log_msg::log_msg(spdlog::source_loc, fmt::v9::basic_string_view<char>, spdlog::level::level_enum, fmt::v9::basic_string_view<char>)'
/usr/bin/ld: CMakeFiles/nheko.dir/src/timeline/CommunitiesModel.cpp.o: in function `std::_Function_handler<void (mtx::responses::EventId const&, std::optional<mtx::http::ClientError> const&), CommunitiesModel::up
:optional<mtx::http::ClientError> const&)':
CommunitiesModel.cpp:(.text+0x14041): undefined reference to `spdlog::details::log_msg::log_msg(spdlog::source_loc, fmt::v9::basic_string_view<char>, spdlog::level::level_enum, fmt::v9::basic_string_view<char>)'
/usr/bin/ld: CMakeFiles/nheko.dir/src/timeline/DelegateChooser.cpp.o:DelegateChooser.cpp:(.text+0x366b): more undefined references to `spdlog::details::log_msg::log_msg(spdlog::source_loc, fmt::v9::basic_string_v
/usr/bin/ld: /usr/lib/libcurl.so: undefined reference to `libssh2_session_set_read_timeout'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/nheko.dir/build.make:5278: nheko] Error 1
make[1]: *** [CMakeFiles/Makefile2:162: CMakeFiles/nheko.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

**Comment by deepbluev7** [comment]
Looks like you need top rebuilld all your aur packages or the Arch package repos are bork atm. This is not a Nheko issue, but a distro issue, most common on Arch.
