### ISSUE TITLE
Better suggestion sorting in @mentions and Ctrl-K

### ISSUE THREAD

**Issue by cloudrac3r** [Nheko-Reborn/nheko#165]
@mentions are noticably worse than Ctrl-K, but both have room for improvement. Here's some suggestions on how to rank results:

- If I type nothing, suggest things based on how recently they've been relevant. For users, put them in order of recently spoken. For rooms, put them in order of recent access by me, or most recent message (just like the left bar, but with keyboard controls)
- If I type one character, please actually search for that character.
- If I type multiple characters, I probably started typing at the start of the person's name, not at a random position in it. Prioritise matches where my input matches the first part of the name.
- If it thinks I made a typo, it's okay to suggest things that are close, but not at the expense of things that exactly match. `@Nic` probably matches `Nico`, not `cadence` (yes, this is a real example). If I write a letter in a mention, I very, very likely intended to write that letter. Levenshtein distance should definitely not be the primary ranking algorithm. Consider not even providing a target in the list  if I write a letter that isn't in the target's name.
- Consider also factoring relevancy into the suggestion order after I start typing. If there's a person named `Nico` and a person named `nitropowered`, but nitropowered has never spoken in the room and I'm currently conversing with Nico, we definitely want to rank Nico higher up (though probably not at the expense of better text matches).
- I very likely don't want to @mention myself or seek to the room I'm already in. Rank them lower when few characters have been typed.

Here are some cool examples of the sorting algorithm being bad. Perhaps these could be used as automated test cases, or just during development:

In a room with 3 people: cadence (me), cloudrac3r, and fyshnchips, typing `@f` ranks fyshnchips in 3rd place and cadence in 1st.

In the nheko room, to mention Nico (who I am currently talking to), it's typed like so:
- `@N` - Nico is not in the list.
- `@Ni` - Nico is not in the list.
- `@Nic` - Nico is in the list, ranked 4 out of 5 people. 1 is cadence. 2 is 0xC0ncord. 3 is crunch.
- `@Nico` - Nico is in the list, ranked 2 out of 5 people. 1 is 0xC0ncord.

In the nheko room, to mention CrystalGamma (who I am not talking to), typing `@Cry` suggests first crunch, then CrystalGamma.

In the Ctrl-K room switcher, typing 1 character excludes results from the list that contain that character, hence searching for the exact opposite of what I'm looking for. Since a user is probably in relatively few rooms, it's important to be able to search with just one character.

In the Bibliogram room, typing `@TheFr` gives spot number 1 to mascherone108, and number 2 to TheFrenchGhosty.

**Comment by cloudrac3r** [comment]
Addition:

If two things match with the same priority, for example, typing "tin" matching both "watching" and "wholesomeposting", give the shorter name a higher priority.

**Comment by deepbluev7** [comment]
New mentions should be sorted much more reasonably. Ctrl-K will come at some point.

**Comment by deepbluev7** [comment]
Fixed by #493
