### ISSUE TITLE
Stickers without body don't get displayed

### ISSUE THREAD

**Issue by spantaleev** [Nheko-Reborn/nheko#166]
**Is your feature request related to a problem? Please describe.**
Not rendering [`m.sticker`](https://matrix.org/docs/spec/client_server/r0.6.0#m-sticker) messages means that one is missing out on the meaning that they add to the conversation.

Sometimes it's a "thumbs up" sticker that the other person is sending to let you know they agree with your last message. Other times it's something else they're trying to tell you.

Not rendering these stickers at all means you're missing out on important information or clues that it's your turn to chat.

**Describe the solution you'd like**

Ideally, `m.sticker` events would get rendered correctly, as images. They seem to contain the same payload as `m.room.message`/`m.image` events, so it shouldn't be too hard to reuse the same handling code.

As a fallback, the message's `body` can likely be used to indicate what the image is about.

At the very least, it'd be nice to render sticker events as a simple "Person X sent you a sticker".
This way, at least you know they've said something. You can then either ask them what it's like, tell them you just can't see stickers, or you can check their sticker in another client. Currently, nheko silently drops the message from the timeline. The conversation looks dead, even though it's not. The other person has sent something which likely requires that you continue your participation in the conversation, yet you're completely unaware it's your turn.

**Note**: this issue is more about **rendering stickers**, so that we won't be missing out on information conveyed to us. Actually **sending stickers** from nheko seems like something that's much less important.

**Comment by deepbluev7** [comment]
Nheko does render stickers. What system and version are you on and could you show, which stickers don't work?

![grafik](https://user-images.githubusercontent.com/16312324/79428443-af97f100-7fb5-11ea-91cb-451ba36ec112.png)

**Comment by spantaleev** [comment]
Ah, you're right! It's one specific sticker that didn't work.

The event looks like this:

```json
{
  "type": "m.sticker",
  "sender": "masked",
  "content": {
    "msgtype": "m.sticker",
    "url": "mxc://devture.com/OCPdbcEzBVCmomNwbOyvHuFY",
    "info": {
      "mimetype": "image/png",
      "size": 16901,
      "h": 240,
      "w": 240
    }
  },
  "origin_server_ts": 1586985031228,
  "unsigned": {
    "age": 38
  },
  "event_id": "masked",
  "room_id": "!masked:devture.com"
}
```

The corresponding image is [here](https://matrix.devture.com/_matrix/media/r0/download/devture.com/OCPdbcEzBVCmomNwbOyvHuFY).

------------

The stickers that I observe to work seem to have a `body` field and this one doesn't (for some reason). It's a sticker coming from the [Mautrix Facebook bridge](https://github.com/tulir/mautrix-facebook). It should be noted that **not all** Mautrix Facebook bridge stickers lack a `body` field.

Looking at the [m.sticker](https://matrix.org/docs/spec/client_server/r0.6.0#m-sticker) specs, `body` is listed as required, so if nheko is dropping this event because it's lacking a `body`, then it may be doing the right thing, spec-wise.

It's probably the Mautrix Facebook bridge that needs to be fixed to ensure it always provides some `body` for stickers events. I'll open a bug there, but making nheko tolerate such bad input is probably a good idea as well?

Maybe Synapse needs to reject such invalid events as well.. Right now it seems to be accepting and spreading them around. Riot is rendering them fine, but..

**Comment by deepbluev7** [comment]
Yeah, that sounds reasonable, I'll fix that this evening :3

**Comment by spantaleev** [comment]
Can confirm it's fixed! Thank you very much! :+1:

**Comment by deepbluev7** [comment]
No worries, making Nheko more robust is always a good thing :D
