### ISSUE TITLE
Improve/Implement Caching of Messages

### ISSUE THREAD

**Issue by dvn0** [Nheko-Reborn/nheko#168]
**Is your feature request related to a problem? Please describe.**
When nheko is opened it shows no previous messages and appears to reload all messages from the server[s]. If nheko is opened while offline, no messages are ever displayed.

**Describe the solution you'd like**
I would like nheko cache loaded messages, and display them immediately upon launch, after which it then proceeds to load new messages.

If you are offline, then you could still look through previously loaded messages.

**Comment by deepbluev7** [comment]
Yeah, that's something I want to work on next, after 0.7.0 is released :D

**Comment by deepbluev7** [comment]
Remind myself to clean up the pending_events db as mentioned in #188 too, when I do this!
