### ISSUE TITLE
nheko starts using http3/quic 

### ISSUE THREAD

**Issue by nishanthkarthik** [Nheko-Reborn/nheko#1682]
### Describe the bug

This is no longer a bug report with nheko but I'd like leave it searchable for others facing the same issue.

Some dependency (my bets are on libcurl 8.6.0-3) was updated on archlinux and nheko started using http3. I had to allow UDP over port 443 on my firewall to make nheko work.

### To Reproduce

1. Start nheko
2. Logs complain about failing network requests

### Version

0.11.3

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Qt version

5.15.12+kde+r150-1

### Did you use profiles?

- [ ] Profiles used?

**Comment by nishanthkarthik** [comment]
Closing because the fix is allowing UDP over 443.

**Comment by m5r** [comment]
You're right, I just downgraded `curl` from 8.6.0-3 to 8.5.0-1 and nheko is working fine again.
