### ISSUE TITLE
nheko does not render cinny strikethrough

### ISSUE THREAD

**Issue by pennae** [Nheko-Reborn/nheko#1693]
### Describe the bug

cinny renders strikethrough to html as `<del data-md="~~">`, which confuses the hell out of nheko because it textually replace `<del> → <s>` to render strikethrough. checked that the replacement code is still like this on current master, so we expect it to be broken there too

### To Reproduce

1. view a cinny-generated strikethrough

### What happened?

it's not struck through

### Expected behavior

it being struck through

### Version

0.11.3

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Did you use profiles?

- [X] Profiles used?

**Comment by Mikaela** [comment]
Which one performs the replacement, Cinny or Nheko? Either way it seems wrong, unless I am misunderstanding, under

- https://github.com/matrix-org/matrix-spec/pull/1732
- https://github.com/matrix-org/matrix-spec-proposals/pull/4077

**Comment by deepbluev7** [comment]
I strip the attribute out in the sanitization step now, thank you for the report. Sadly Qt does not support the del tag, so some replacement still needs to happen, however the spec suggest to strip out all attributes anyway unless they are allowed and we are doing that for at least del tags now. Thank you for the report! :)
