### ISSUE TITLE
Binding restoreMode

### ISSUE THREAD

**Issue by adriaandegroot** [Nheko-Reborn/nheko#170]
This applies to the FreeBSD package of nheko, against mtxclient 0.3.0 with Qt 5.14.2.

On startup, or while scrolling the timeline, this message is printed:

```
[2020-04-21 11:31:24.073] [qml] [warning] qrc:/qml/TimelineView.qml:175:5: QML Binding: Not restoring previous value because restoreMode has not been set.
This behavior is deprecated.
You have to import QtQml 2.14 after any QtQuick imports and set
the restoreMode of the binding to fix this warning.
In Qt < 6.0 the default is Binding.RestoreBinding.
In Qt >= 6.0 the default is Binding.RestoreBindingOrValue.
 (qrc:/qml/TimelineView.qml:175, )
```

It's "just" a warning and I can't tell if there's a user-visible impact, but it's certainly spamming my console.

**Comment by deepbluev7** [comment]
Yes, this is a warning, that doesn't apply to us. We actually blacklist one of them already, but 5.14.2 changed the warning, so our filter doesn't catch that anymore. We probably need to make the filter more generic. There is no real other way to fix that, without dropping support for Qt < 5.14, which is still used in a few distros iirc.
