### ISSUE TITLE
Threaded replies can cause a crash

### ISSUE THREAD

**Issue by geekosaur** [Nheko-Reborn/nheko#1703]
### Describe the bug

If I reply to a message in a thread, nheko sometimes closes. Usually this is when I hit Enter or the send button, but on occasion it happens when I start typing my reply. I'm using Flatpak so I don't have a crash log or core dump.

### To Reproduce

1. Right-click select "Reply" to a message in a thread.
2. Type your reply. (It may crash on the first keypress, but more commonly when you press Enter.)
3. Sometimes (not reliably) nheko will exit.

### Version

0.11.3-d27e42d

### Operating system

Linux

### Installation method

Flathub

### Desktop Environment

MATE with xmonad 0.18 as window manager

### Did you use profiles?

- [ ] Profiles used?

### Relevant log output

```shell
(empty, may need to capture it before restarting)
```

**Comment by geekosaur** [comment]
I'm running `flatpak run` in a terminal to try to catch messages; unfortunately, since the crash is intermittent, I won't have anything else to report until it reproduces.

**Comment by geekosaur** [comment]
Reproduced; `flatpak run` returned `exit 139` (segfault), sadly there is nothing on its stdout/stderr or in `~/.cache/nheko/nheko/nheko.log`.

**Comment by geekosaur** [comment]
Interestingly, I have another crash bug where `flatpak run` gives me a (admittedly not very useful) backtrace. This makes me wonder if it is Flatpak('s sandbox) that is crashing and taking Nheko with it.

**Comment by deepbluev7** [comment]
Can you reproduce this issue on the nightly builds? I think I fixed an issue like that already. You should be able to install the nightly flatpak by using the flatpakref file in this repo.

**Comment by geekosaur** [comment]
I am now running the nightly; I'll have to wait several hours before I can reproduce it, meaning I won't be able to test until tomorrow morning my time.

**Comment by deepbluev7** [comment]
Took me 2 days to reply, I can wait a few days :)

**Comment by geekosaur** [comment]
It looks like the nightly doesn't crash. This makes me curious as to why flatpak didn't show a backtrace, but I guess that's not my problem 😁
