### ISSUE TITLE
Open a chat in a separate window

### ISSUE THREAD

**Issue by HammyHavoc** [Nheko-Reborn/nheko#1714]
### The Problem

Only seeing one conversation at a time is limiting.

### The Solution

One of the killer features of oldskool IM was being able to open up multiple chats simultaneously in separate windows, resize them and position them as desired, and even have a monitor dedicated to them. It was great!

### Alternatives

NeoChat offers it, but NeoChat isn't Nheko.

### Happens in the latest version

- [X] Yes, this feature is still missing.

**Comment by LorenDB** [comment]
Nheko supports this. Just right-click a room in the sidebar and click "Open separately".
