### ISSUE TITLE
Cannot set system theme

### ISSUE THREAD

**Issue by Samonitari** [Nheko-Reborn/nheko#172]
### Describe the bug

If I select system theme, Nheko becomes unresponsive, and CPU usage goes up.
With this settings, Nheko fails to start next time 

### To Reproduce

Select Theme->System in Settings

### Expected behavior

Nheko repaints to follow system theme

### System:

Nheko version: 0.7.0+commit 22ecdfc
Installation method: rpm package
Operating System: Tumbleweed
Qt version: 5.14.1
C++ compiler: gcc9-c++ 9.3.1
Desktop Environment: KDE with kwin in Wayland

### Logs

Did not found current logs in given location

**Comment by deepbluev7** [comment]
Can you try starting it from the commandline and see if anything strange is up? I don't experience that on Sway and Plasma/X.Org. Can't run Plasma/Wayland sadly, since it is simply broken on my systems.

**Comment by Samonitari** [comment]
Thanks for the quick reply!

It seems like it will be a packaging, or a depency's package issue. Because for me it behaves the same on X.Org, Wayland and Full Wayland.

**Comment by deepbluev7** [comment]
Well, it could still be a bug, but without further info, I have a bit of a hard time debugging it :D

**Comment by Samonitari** [comment]
I've built it myself, then removed it, and the necessary devel packages after 0.7 appeared in the experimental repo.

Didn't tested nheko thoroughly with the self built one, so I'll try again.

I'll try to debug it, and/or contanct the maintainers, and report back after.

Ironically I haven't done any Qt debug on Linux, Qt Creator should do the job I presume...

**Comment by deepbluev7** [comment]
Yeah, Qt Creator should work.

**Comment by Samonitari** [comment]
Bit dumb question, but I cannot debug it, always fails with permission denied, even though anybody can run the build executable

Any tip?

**Comment by deepbluev7** [comment]
Since I don't know, what your exact issue is, how a bout you join #nheko-reborn:matrix.org and we debug it interactively?

**Comment by Samonitari** [comment]
Hotfix in [35601b6](https://github.com/Nheko-Reborn/nheko/commit/35601b6bef6165e254aa0becc38939f1122b0181) seems effective
