### ISSUE TITLE
@room warning shows even for rooms where you can't ping room

### ISSUE THREAD

**Issue by TheDrawingCoder-Gamer** [Nheko-Reborn/nheko#1722]
### Describe the bug

typing `@room` always shows the "You are about to notify the whole room" even when you don't have the permissions to ping room. 

### To Reproduce

1. Go to a room where you don't have ping permissions (for testing you may have to have two accounts to make a room)
2. Type `@room`

### What happened?

You see the warning on top of the text field.

### Expected behavior

Nothing appears because you can't ping the room

### Screenshots

![image](https://github.com/Nheko-Reborn/nheko/assets/26726264/10a5d9e9-2bdd-4d7a-9e7b-80acc6cf768c)

### Version

0.11.3-f465a5b5

### Operating system

Linux

### Installation method

Local build

### Qt version

6.7.0

### C++ compiler

gcc 13.2.1

### Desktop Environment

i3

### Did you use profiles?

- [X] Profiles used?

**Comment by deepbluev7** [comment]
Pretty sure I fixed that.
