### ISSUE TITLE
Confirm password when exporting keystore

### ISSUE THREAD

**Issue by ghost** [Nheko-Reborn/nheko#1729]
### The Problem

When exporting keys, the user may enter a password that is not what they thought they wrote.

### The Solution

Ideally the user is prompted to enter the password a second time, and the application should alert and not proceed if they do not match.

### Happens in the latest version

- [X] Yes, this feature is still missing.

**Comment by Integral-Tech** [comment]
Fixed in https://github.com/Nheko-Reborn/nheko/pull/1734, this issue can be closed.
