### ISSUE TITLE
When sending spoilers nheko should obfuscate the plain text

### ISSUE THREAD

**Issue by Cadair** [Nheko-Reborn/nheko#1730]
### Describe the bug

The spec states:

> When sending a spoiler, clients SHOULD provide the fallback in the body as shown above (including the reason). The fallback SHOULD NOT include the text containing spoilers since body might show up in text-only clients or in notifications. To prevent spoilers showing up in such situations, clients are strongly encouraged to first upload the text containing spoilers to the media repository, then reference the mxc:// URI in a markdown-style link, as shown above.

When you send a spoiler with nehko this is not done:

```
{
    "content": {
        "body": "||warning|see, you can still see it in notifications||",
        "format": "org.matrix.custom.html",
        "formatted_body": "<span data-mx-spoiler=\"warning\">see, you can still see it in notifications</span>",
        "msgtype": "m.text"
    },
```

### To Reproduce

1. Send a spoiler
2. View message source or look at room list (which renders the plain text)

### Version

0.11.3 but not really it's actually git

### Operating system

Linux

### Installation method

Local build

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment]
This is not possible to implement in encrypted rooms.
