### ISSUE TITLE
If a message has only few emojies as content, show those emojies large

### ISSUE THREAD

**Issue by farooqkz** [Nheko-Reborn/nheko#1733]
### The Problem

When a message is a single emoji, it is hard to see the emoji

### The Solution

When a message content is only a single emoji or just a few emojies, show them largely

### Additional context

The reason is UI/UX

### Happens in the latest version

- [X] Yes, this feature is still missing.

**Comment by LorenDB** [comment]
There is a setting called "Large Emoji in timeline" under the Timeline section in the settings page. Turn that on and you will see large emoji like so:
![image](https://github.com/Nheko-Reborn/nheko/assets/55629213/325d1197-96b7-438c-bd68-7b0e751db365)
