### ISSUE TITLE
Sending matrix.to link results in unexpected formatting.

### ISSUE THREAD

**Issue by Kladki** [Nheko-Reborn/nheko#1738]
### The Problem

Sometimes I want to share a room address by pasting a matrix.to link into the message composal box directly, especially if I am not in the room I are sharing. However, this results in unexpected formatting, having only "https://matrix.to/#/" converted into a hyperlink, and the rest of the url in plain text.

### The Solution

Detect and format matrix.to URLs correctly, likely by using some other URL parsing library or something else.

### Alternatives

Formatting the markdown myself, but this is inconvenient.

### Additional context

![image](https://github.com/Nheko-Reborn/nheko/assets/158313939/11858780-77e3-4fa4-bea0-a0605b80e8a7)

### Happens in the latest version

- [X] Yes, this feature is still missing.

**Comment by deepbluev7** [comment]
This should already be fixed for the next release, however be aware that the matrix spec says the identifier in the matrix.to url should be fully escaped and most URL RFCs allow for only one # in a link as well.
