### ISSUE TITLE
(Verification request) Flathub

### ISSUE THREAD

**Issue by hardBSDk** [Nheko-Reborn/nheko#1741]
Please verify your ownership on Flatuhb.

![image](https://github.com/Nheko-Reborn/nheko/assets/55782009/d0892b14-3658-40ab-9afc-f870e0c91b33)

**Comment by deepbluev7** [comment]
It is not possible to verify the old flathub package because the app id has no dash, while our github organization has a dash. We are migrating to a new app id to fix that, but until then there is no way to verify that package.
