### ISSUE TITLE
Crash after message removal

### ISSUE THREAD

**Issue by hardBSDk** [Nheko-Reborn/nheko#1745]
### Describe the bug

At some point of the runtime the message removal will crash the program.

### To Reproduce

1. Click on the "Remove message" button
2. Do some tries

### What happened?

The program crashed without a window pop-up.

### Expected behavior

Remove the message without a crash.

### Version

0.11.3-d27e42d

### Operating system

Linux

### Installation method

Flathub

### Desktop Environment

GNOME 42.9

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment]
I think this is just the usual issue with the gnome menus. Setting the environment variable `XDG_CURRENT_DESKTOP` to null should work around that.
