### ISSUE TITLE
Rooms are not immediately marked as read if already scrolled to the bottom

### ISSUE THREAD

**Issue by cloudrac3r** [Nheko-Reborn/nheko#175]
When I read all the messages in a room, I would like it to be marked as read. Currently, scrolling to the bottom of a room marks it as read, which is great. However, if there are not many new messages since I last opened the room, then when I open it it may already be scrolled to the bottom. And if the room is scrolled to the bottom as I open it, it is not marked as read until I scroll up one click, then back down to the bottom.

To be clear:

If there are many new messages when I open a room, I would like to be placed at the top of them, and the room be marked as read when I reach the bottom. (I believe this is the current behaviour, yay!)

If there are few new messages when I open the room and no scrolling is required, I would like the room to be marked as read immediately. (This is not the current behaviour.)

**Comment by deepbluev7** [comment]
I think the place at top is currently broken, but that is definitely the plan :D

**Comment by deepbluev7** [comment]
The mark as read is implemented, the other one is tracked in #560
