### ISSUE TITLE
no way to activate encryption using recovery passphrase

### ISSUE THREAD

**Issue by foresto** [Nheko-Reborn/nheko#1750]
### Describe the bug

The Activate Encryption dialog explains that it can be done by entering the account's recovery passphrase, and directs the user to select the corresponding option "below", but does not offer any such option.

### To Reproduce

1. Log in to a new session, or click the Unverified Login banner on an existing one.
2. Read the Activate Encryption dialog.
3. Look for the recovery passphrase option.

### What happened?

The recovery passphrase option doesn't exist.

### Expected behavior

The recovery passphrase option should exist.

### Screenshots

![activate encryption](https://github.com/Nheko-Reborn/nheko/assets/322134/1db4c7f9-3f42-410d-8bf5-b7e1539949ee)

### Version

0.12.0

### Operating system

Linux

### Installation method

Local build

### Qt version

org.kde.Sdk 6.6 flathub

### C++ compiler

whatever the flatpak manifest uses

### Desktop Environment

KDE Plasma 5.27.5 (debian stable)

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment]
The recovery phrase option is only shown, if that is actually supported for your account. You probably don't have SSSS enabled?

**Comment by deepbluev7** [comment]
The app does adjust the prompt, it removes the passphrase button if there is no passphrase to enter. The wording of the explanation could probably be improved as well as an option be added to reset your cross-signing. Currently you need Element for the latter, but the button not being present is not a bug.
