### ISSUE TITLE
Nheko 0.12.0: Status Notifier Icon no longer changes for new messages

### ISSUE THREAD

**Issue by Tamaranch** [Nheko-Reborn/nheko#1752]
### Describe the bug

With version 0.11.3, the systray icon changed when new messages were received (a red dot was added to the nheko icon). With version 0.12.0, the icon remains unchanged for new messages.

### To Reproduce

1. Adjust settings so that systray icon appears
2. Receive new messages
3. See the systray icon unchanged

### Version

0.12.0

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Desktop Environment

Xfce 4.19

### Did you use profiles?

- [ ] Profiles used?

**Comment by Tamaranch** [comment]
Hm actually downgrading nheko to 0.11.3 and even the whole environment to what it was at that time doesn't solve the problem, so there must be something else. I'll have to investigate this later, and report my findings.

**Comment by Tamaranch** [comment]
Ok so I confirm the regression. Downgrading nheko to 0.11.3 does solve the problem, even if the modified icon (with the red dot) doesn't appear when there are new messages at startup for some reason (I thought it did), but it does appear afterwards when other messages arrive. Whereas it doesn't appear at all with nheko 0.12.0.

**Comment by deepbluev7** [comment]
Should be fixed since a486d8d7fc567c191e7259b478b6f03b3800ac4a

**Comment by Tamaranch** [comment]
Yes I can confirm it's fixed (currently using nheko-git-0.12.0.r25.gbca7faf7 from the AUR on Arch).

**Comment by NintendoManiac64** [comment]
I don't suppose there will be a new release sooner rather than later to alleviate this issue? I've now missed the notification of new messages twice now because the notification dot is broken.
