### ISSUE TITLE
FR: Add number of unread messages to systray icon tooltip

### ISSUE THREAD

**Issue by Tamaranch** [Nheko-Reborn/nheko#1758]
### The Problem

Currently, the number of unread messages appears in a red circle on the systray icon, but it's not always easy to read, depending on the size of the icon.

### The Solution

It would be nice if the number of unread messages also appeared in the icon's tooltip. Thanks!

### Happens in the latest version

- [X] Yes, this feature is still missing.

**Comment by Integral-Tech** [comment]
@Tamaranch This issue can be closed.

**Comment by Tamaranch** [comment]
@Integral-Tech Cool, thanks for implementing this, but I think there's a little regression: the red circle with the number of messages (and the tooltip text modification) no longer appears at startup, if there are new messages or unread messages from the previous session. I previously used `nheko-git-0.12.0.r25.gbca7faf7` where it worked, then `nheko-git-0.12.0.r32.gdeba5586` where I think it worked too, now `nheko-git-0.12.0.r35.g50f9edfe` where it doesn't work anymore.

**Comment by Tamaranch** [comment]
> but I think there's a little regression:

It works again apparently, without having changed version, I don't really understand this thing. Well, I guess we can forget it :)
