### ISSUE TITLE
Possible race condition leads to weird formatting of join/part messages

### ISSUE THREAD

**Issue by geekosaur** [Nheko-Reborn/nheko#1766]
### Describe the bug

In a room with a puppeted heisenbridge, join and part messages are relayed from the linked IRC channel. Sometimes, when the user immediately rejoins, the join or part message gets formatted to the width of the corresponding part/join message, but because heisenbridge removed its display name, its (synthetic and fairly long) MXID is formatted instead. This doesn't happen consistently, which makes me think there's a race condition where it sizes the part message with the display name but that is gone by the time it displays it.

### To Reproduce

1. Join a room with a puppeted heisenbridge, such as #hackage:matrix.org
2. Wait for a user to part and rejoin IRC.

### What happened?

The message (not very consistently) is formatted to the width it would have been with the display name, but is output with the MXID.

### Expected behavior

The display name should have been cached when the width was computed, and used for the actual output.

### Screenshots

![nheko-race-condition](https://github.com/Nheko-Reborn/nheko/assets/2036384/ea0b256b-7f61-487a-9faa-2507aa8ef541)

### Version

0.12.0-24c687d

### Operating system

Linux

### Installation method

Flatpak nightly repo or download

### Desktop Environment

MATE with xmonad as window manager

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment]
That's not a bug. When a user leaves a room, we remove their display name. As a result all their messages will be rendered without a displayname and just their mxid. This should also happen without any race if you just close and reopen a room, that someone left.

**Comment by geekosaur** [comment]
That it does that is not the bug. The bug is the resulting formatting, which is inconsistent and appears to possibly be a race.

**Comment by geekosaur** [comment]
Here's how a normal part message looks. Note that it's formatted according to the width of the mxid, _not_ the display name as with the buggy one.
![Screenshot_2024-07-27_23-28-58](https://github.com/user-attachments/assets/96db3906-6094-4fee-9986-0ee40ee134b3)

**Comment by geekosaur** [comment]
Here's how a normal one looks. Note that it's formatted with the width of the mxid, _not_ the display name.
![Screenshot_2024-07-27_23-30-35](https://github.com/user-attachments/assets/64fd86fd-e7c5-4af9-9572-c758a0416faf)

**Comment by geekosaur** [comment]
If it's not clear, in the first screenshot it's the part message for `_surfbluecrab_` that's wrong, not the one following it which is what I would expect.
