### ISSUE TITLE
is there a way to hide this pink border around reply messages?

### ISSUE THREAD

**Issue by darkralts** [Nheko-Reborn/nheko#1775]
### The Problem

![image](https://github.com/user-attachments/assets/fbaffa6f-f74d-4bbf-b0f6-278fcef3b873)
as you can see theres this pink border, i remember it being introduced a long time ago but i only had problems with it showing up now, i would like to disable it.

### The Solution

how can i disable it?

### Happens in the latest version

- [X] Yes, this feature is still missing.

**Comment by deepbluev7** [comment]
That border is there for messages that notify you. You can only disable that by disabling the pings for replies, but Nheko has no option to do that, you need to modify your pushrules in a different client or manually.
