### ISSUE TITLE
No notification in tray icon since v0.12.0

### ISSUE THREAD

**Issue by olivia-fox** [Nheko-Reborn/nheko#1779]
### Describe the bug

Since the v0.12.0 update (which is great by the way!) the tray icon no longer shows a small visual indicator that a message has been received. The application icon in the task bar/manager still does as before, but the tray icon now appears static and doesn't change upon receiving a message.

### To Reproduce

With Nheko open and the tray icon enabled, receive a message. The OS-level notification will appear and the application icon will show a small (1) as expected, but the tray icon will not as it did in prior versions.

### Version

0.12.0-24c687d

### Operating system

Linux

### Installation method

Flathub

### Desktop Environment

KDE 6 on Fedora Kinoite

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment]
Fixed in https://github.com/Nheko-Reborn/nheko/commit/a486d8d7fc567c191e7259b478b6f03b3800ac4a

**Comment by tycho-kirchner** [comment]
Thanks for the fix. However, since the last nheko release is from Jun 12, 2024 nheko users not directly installing from github cannot benefit from it. Thus I would kindly like to encourage the nheko authors, to publish a new release. Thank you 🙂.
