### ISSUE TITLE
Qt version dependency

### ISSUE THREAD

**Issue by Smarre** [Nheko-Reborn/nheko#178]
Hi,

You probably should both mention in README and restrict in cmake file that Qt 5.10 is required (in master). This is because QtQuick.Controls 2.3 is only available in Qt 5.10. 

And maybe have a mention that Qt Quick Compiler, useful for speedup, is available from 5.11 release.

**Comment by Smarre** [comment]
Uhm no, this is not correct.

**Comment by deepbluev7** [comment]
Hm, I don't think we actually need Controls 2.3, I will verify that. Thank you for reporting!

**Comment by deepbluev7** [comment]
We require Qt 5.10 now, so that resolves this as well.
