### ISSUE TITLE
authentication in database

### ISSUE THREAD

**Issue by theotheroracle** [Nheko-Reborn/nheko#1788]
### The Problem

was looking into configuring nheko with home-manager, only to realise that it's not currently feasible, due to nheko storing the authentication information in the config, which prevents the config from being modified or stored elsewhere

### The Solution

the home-manager documentation mentions there are plans to move these fields into the database instead of the config, but i couldn't find an issue or PR for it, so i decided to make one so i could stay in the loop

### Happens in the latest version

- [X] Yes, this feature is still missing.

**Comment by deepbluev7** [comment]
Duplicate of https://github.com/Nheko-Reborn/nheko/issues/1591
