### ISSUE TITLE
Unable to import E2E Encryption Keys

### ISSUE THREAD

**Issue by securerootd** [Nheko-Reborn/nheko#179]
### Describe the bug
Unable to import E2E Encryption keys and unable to see encrypted chats

### To Reproduce
1. Go to Settings
2. Click on Import Keys
3. Select key backup file
4. Type in passphrase
5. Encounter Error

### Expected behavior
Keys should be imported and previous encrypted messages should decrypt

### Screenshots
![image](https://user-images.githubusercontent.com/1446332/80310609-2a89b480-87cb-11ea-9daf-d87f89df83a9.png)

### System:

- Nheko version: 0.6.4-2build2
- Installation method: apt (system repository)
- Operating System: (X)ubuntu 20.04 LTS
- Qt version: 
- C++ compiler: 
- Desktop Environment: XFCE 4.14

### Logs
[nheko.log](https://github.com/Nheko-Reborn/nheko/files/4535511/nheko.log)

**Comment by redsky17** [comment]
This has been addressed in the 0.7.0 release of nheko.  Prior to that release, nheko didn't follow the official spec for session import / export.

**Comment by deepbluev7** [comment]
A bit of a clarification, they changed the spec, after Nheko implemented it, to match what Riot does, which is why Nheko was incompatible before 0.7.0.

**Comment by darkralts** [comment]
im getting this on 0.8

**Comment by deepbluev7** [comment]
Which version of 0.8?

**Comment by deepbluev7** [comment]
Works fine here.
