### ISSUE TITLE
nheko seems to choke on replies

### ISSUE THREAD

**Issue by babolivier** [Nheko-Reborn/nheko#18]
### System:

- Nheko version: 0.6.3
- Installation method: AppImage
- Operating System: Arch Linux
- Desktop Environment: Gnome Shell (3.30.2)

### Actual behavior

Here's what nheko logs when stumbling upon a reply:

```
error while parsing xml "Expected ';', but got '='." "<html><blockquote><a href=\"https://matrix.to/#/!FyQrGcOoVamcLcvdob:matrix.org/$15487838774263HIAkp:amorgan.xyz?via=matrix.org&via=disroot.org&via=saces.de\">In reply to</a> * <a href=\"https://matrix.to/#/@andrewm:amorgan.xyz\">@andrewm:amorgan.xyz</a><br></br>bumps to 1.10</blockquote>should just bump to 1.11 and switch to modules :3</html>"
```

Not sure whether it chokes on every reply it encounters, but every occurrence of this error is about a reply. It doesn't prevent the reply itself to show up in nheko's UI.

### Expected behavior

No error in logs.

**Comment by redsky17** [comment]
I have noticed this as well.  I think the issue is with the Utils::linkifyMessage function.
