### ISSUE TITLE
High CPU usage on idle

### ISSUE THREAD

**Issue by rex4539** [Nheko-Reborn/nheko#180]
### Describe the bug
The app is using 30%-40% on idle.

### To Reproduce
Launch the app, let it run and inspect CPU usage.

### Expected behavior
CPU usage between 0.1%-1%.

### System:

- Nheko version:  0.7.1-17c657a | Darwin
- Installation method:  Local build
- Operating System: macOS 10.15.5 (19F62f)
- Qt version:  Qt 5.14.1 (x86_64-little_endian-lp64 shared (dynamic) release build; by Clang 11.0.0 (clang-1100.0.33.17) (Apple)) on "cocoa"
- C++ compiler:  Apple clang version 11.0.3 (clang-1103.0.32.59)

### Debugger backtrace
Running the app on Apple Instruments Time Profiler, it shows that it's spending most of the time in QtGui:
```
  32 QtGui 0x113c381c6
  31 QtGui 0x113c889f1
  30 QtGui QImage::convertToFormat_helper(QImage::Format, QFlags<Qt::ImageConversionFlag>) const
  29 QtGui 0x113c7617a
  28 QtGui 0x113c76034
  27 QtGui QPlatformBackingStore::composeAndFlush(QWindow*, QRegion const&, QPoint const&, QPlatformTextureList*, bool)
  26 QtWidgets 0x1137e318e
  25 QtWidgets 0x1137e47a0
  24 QtWidgets 0x1137e360e
  23 QtWidgets 0x1137e40ac
  22 QtWidgets QWidget::event(QEvent*)
  21 QtWidgets QApplicationPrivate::notify_helper(QObject*, QEvent*)
  20 QtWidgets QApplication::notify(QObject*, QEvent*)
  19 QtCore QCoreApplication::notifyInternal2(QObject*, QEvent*)
  18 QtCore QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*)
  17 libqcocoa.dylib 0x118758ac0
  16 libqcocoa.dylib 0x118759102
  15 CoreFoundation __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__
  14 CoreFoundation __CFRunLoopDoSource0
  13 CoreFoundation __CFRunLoopDoSources0
  12 CoreFoundation __CFRunLoopRun
  11 CoreFoundation CFRunLoopRunSpecific
  10 HIToolbox RunCurrentEventLoopInMode
   9 HIToolbox ReceiveNextEventCommon
   8 HIToolbox _BlockUntilNextEventMatchingListInModeWithFilter
   7 AppKit _DPSNextEvent
   6 AppKit -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:]
   5 AppKit -[NSApplication run]
   4 libqcocoa.dylib 0x118757f1a
   3 QtCore QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>)
   2 QtCore QCoreApplication::exec()
   1 nheko main /Users/rex/nheko/build/../src/main.cpp:207
   0 libdyld.dylib start
```

**Comment by deepbluev7** [comment]
Hm, interesting, thanks for reporting that. It seems like it is always converting an image. Does this happen only when certain rooms are open or does it always happen?

**Comment by rex4539** [comment]
It occurs in all rooms. Even in new rooms I just created that have no images posted whatsoever.

**Comment by rex4539** [comment]
Interesting to note that the high CPU usage occurs only when the app is active. If the app is hidden or minimized, then CPU usage drops to 0%-0.5%.

**Comment by deepbluev7** [comment]
Thanks for the additional info. I don't have a mac but maybe @redsky17 can investigate at some point? Otherwise I'll see what I can do at some point :3

**Comment by redsky17** [comment]
Hey, thanks for the report!  It's pretty funny you posted this, because I mentioned it to @deepbluev7 literally the day before you posted this.  After doing some investigation, I think I've boiled the issue down to an update that was made recently regarding how avatars are rendered on HiDPI displays.  I'm going to see if I can fix it (or if @deepbluev7 can before I get around to it =D).

**Comment by oz** [comment]
For the record, I think that I've got the same issue on Linux, on a HiDPI display (4k).

- I'm using the 0.7.1 release (AppImage),
- Showing the preferences screen gets the CPU back to "normal".

Hope this helps!

**Comment by deepbluev7** [comment]
Yeah, we figured out why it happens, we are currently looking into how to fix that reasonably :D
