### ISSUE TITLE
Feature: Authenticated Media

### ISSUE THREAD

**Issue by yellows111** [Nheko-Reborn/nheko#1803]
### The Problem

Since the 12th of September, 2024, or Matrix 1.12, matrix.org now requires authenticated media to be supported by clients and other homeservers. Same is expected to happen to any servers supporting Matrix 1.12.

Without it, the legacy attachments API returns 404 for *all* attachments uploaded since, and drops all uploads to the legacy attachments API.

### The Solution

Implement the Matrix 1.11+ authenticated upload and download attachments APIs.

### Additional context

Source: https://spec.matrix.org/v1.11/client-server-api/#content-repo-client-behaviour

### Happens in the latest version

- [X] Yes, this feature is still missing.

**Comment by deepbluev7** [comment]
This was already implemented in 0.12.0, please read the release notes...

**Comment by yellows111** [comment]
I use 0.12.0, and i'm still having problems uploading authenticated media.
