### ISSUE TITLE
Backslash escapes not working

### ISSUE THREAD

**Issue by glmdgrielson** [Nheko-Reborn/nheko#182]
### Describe the bug
If a message contains no Markdown other than backslash escapes, the backslashes go through instead of being removed.

### To Reproduce
Send a message of the form `\*test\*`.

### Expected behavior
According to Markdown, the result should be `*test*`, not `\*test\*`.

### System:

- Nheko version: 0.7.1-14ce480
- Installation method: AppImage
- Operating System: Linux
- Desktop Environment: LXDE

**Comment by LorenDB** [comment]
I'll work on this (if I can find where the offending code is located).

**Comment by deepbluev7** [comment]
A good start is probably in Utils.cpp the utils::markdownToHtml function. Thanks for looking into this! :3

**Comment by LorenDB** [comment]
No problem. 😉

**Comment by LorenDB** [comment]
The bug appears to be in the cmark library. I'll do some more research into the cmark code.

**Comment by LorenDB** [comment]
The current version of cmark renders `\*test\*` properly. Maybe the bundled cmark needs upgraded?

**Comment by redsky17** [comment]
@LorenDB that's probably true.  We're not always the best at keeping our dependencies updated.  Assuming you were able to build against a newer version and verify that it works, what version should we update to?

**Comment by LorenDB** [comment]
@redsky17 the latest release is 0.29, which is what you are using, but the latest Github code has the issue fixed. I'd recommend waiting for the next release and then making it the minimum version.

**Comment by redsky17** [comment]
Sounds good.  We'll keep an eye on it!  Thanks again

**Comment by LorenDB** [comment]
🙂 No problem

**Comment by deepbluev7** [comment]
cmark 0.30 is released and it seems to work fine now. If it doesn't, your distro might need to update the cmark package.

**Comment by LorenDB** [comment]
@deepbluev7 did you update the required version in CMakeLists.txt?

**Comment by deepbluev7** [comment]
No, because this is not an API break. People should just build against the newer version, if they want the fix.

**Comment by LorenDB** [comment]
Fine. I just thought maybe we would require it to make sure everybody has the fix. I guess it wouldn't hurt to update the version hunter downloads, at any rate.

**Comment by deepbluev7** [comment]
Does the bundled version not have the fix yet?

**Comment by LorenDB** [comment]
Oh look, it does!
