### ISSUE TITLE
qml6glsink Missing

### ISSUE THREAD

**Issue by Totallynotmwa** [Nheko-Reborn/nheko#1824]
### Describe the bug

When i try to stream it says missing I CANNOT FIGURE OUT HOW OT GET IT ON ARCH WHYY.

### To Reproduce

1. call someone
2. Click on 'screen'
3. click on 'Share'
4. The other guy accepts and boom qml6glsink missing error

### What happened?

Gives me a error about qml6glsink missing

### Expected behavior

it should call fine

### Version

0.12.0

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Desktop Environment

Kde plasma 6.1

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment]
Install all the optional dependencies: https://archlinux.org/packages/extra/x86_64/nheko/

Or at least the gst-plugin-qml6

**Comment by Totallynotmwa** [comment]
> Install all the optional dependencies: https://archlinux.org/packages/extra/x86_64/nheko/
> 
> Or at least the gst-plugin-qml6

Tysm
