### ISSUE TITLE
[Feature Request] App uses XWayland to run even though Im on wayland

### ISSUE THREAD

**Issue by Twig6943** [Nheko-Reborn/nheko#1832]
### Describe the bug

The app should use Wayland instead of XWayland considering that the app's engine is QT6
(I have the flatpak version from flathub installed)

### To Reproduce

title.

### What happened?

title.

### Expected behavior

title.

### Screenshots

title.

### Version

Latest

### Operating system

Linux

### Installation method

Flathub

### Qt version

Latest

### C++ compiler

N/A

### Desktop Environment

KDE Wayland

### Did you use profiles?

- [ ] Profiles used?

### Relevant log output

```shell
title.
```

### Backtrace

```shell
title.
```

**Comment by deepbluev7** [comment]
This is because flathub doesn't allow us to use both the x11 and wayland sockets at the same time anymore, so we had to remove the wayland socket. You can add it manually back by just giving Nheko access to the wayland socket using flatseal: https://github.com/flathub/flathub/pull/5328#discussion_r1635571186

**Comment by Twig6943** [comment]
> This is because flathub doesn't allow us to use both the x11 and wayland sockets at the same time anymore, so we had to remove the wayland socket. You can add it manually back by just giving Nheko access to the wayland socket using flatseal: [flathub/flathub#5328 (comment)](https://github.com/flathub/flathub/pull/5328#discussion_r1635571186)

Yep this does work
![image](https://github.com/user-attachments/assets/90452ca8-3f7b-4404-b4b9-6b21fe254741)
