### ISSUE TITLE
Manual line breaks are removed

### ISSUE THREAD

**Issue by PitcherSeven** [Nheko-Reborn/nheko#1839]
### Describe the bug

When manually inserting line breaks using `Shift+Enter` all *single* line breaks are removed, when URL is inserted or markup language is used to format text partially. This only happens, when lines end with single line break, not when inserting two or more line breaks at once.

### To Reproduce

1. Go to any conversation or room
2. Write text with line breaks, that contains URLs and/or markup language
3. Send message

### What happened?

As soon as markup language or URLs is involved, all *single* line breaks are removed. `\n\n` is sent as seen.

### Expected behavior

I as user expect to have messages sent as I wrote them. This means, that when I write a line containing a URL or markup language, I'd expect, that my manual line break is respected and receiver gets the message, as I wrote it.

### Screenshots

**Correct behavior without URL or markup langauage**
![2024-11-08_Correct](https://github.com/user-attachments/assets/31318096-ab16-4e56-8a15-a74dc78982c9)
![2024-11-08_Correct_Sent](https://github.com/user-attachments/assets/2b134f0f-b0ca-49a6-805b-e49d48981bb7)

**Wrong behavior using URL**
![2024-11-08_URL](https://github.com/user-attachments/assets/c338010d-a472-4740-b784-a44704e69abe)
![2024-11-08_URL_Sent](https://github.com/user-attachments/assets/731573ca-cd6d-4614-bcac-fabfb8bb93cd)

**Wrong behavior using markup language**
![2024-11-08_Markup](https://github.com/user-attachments/assets/abb5aab0-0edd-43fa-80cd-5697dd96c442)
![2024-11-08_Markup_Sent](https://github.com/user-attachments/assets/afaa7fb8-8d6e-43a1-8649-33dc9d72e963)

**Received in another Matrix client**
![2024-11-08_Received_Other_Client](https://github.com/user-attachments/assets/e1a1b8f1-a4de-4db9-a5c7-e3c010b08dbc)
(Please note: this is **not** about how others present URLs!)

**Correct behavior with `\n\n`**
![2024-11-08_URL_Two_LB](https://github.com/user-attachments/assets/28535156-e173-473d-920d-4f464d1f4c4c)
![2024-11-08_URL_Two_LB_Sent](https://github.com/user-attachments/assets/c7342c93-442e-40c2-a35b-9457cc29d782)

### Version

0.9.1

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Qt version

not essential

### C++ compiler

not essential

### Desktop Environment

Linux Mint 21.3 Cinnamon, X-Cinnamon 6.0.4, X11 window manager

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment]
This was fixed a few years ago, please use a recent release and if your distro doesn't provide that, use the flatpak :)

**Comment by PitcherSeven** [comment]
Sorry for that, works like charm now with flatpak from here.
The system repository is not yet updated. Sorry for complaining about 0.9 while we're already on 0.12
