### ISSUE TITLE
Increase font size of emojis when they are not "inlined"

### ISSUE THREAD

**Issue by Samonitari** [Nheko-Reborn/nheko#185]
**Is your feature request related to a problem? Please describe.**
Increase the "font" size of messages containing only emojis.

**Describe the solution you'd like**
Riot desktop app's behaviour would be nice. Not "inlined",  emojis are easier to distinguish, especially on high-dpi screens.

**Describe alternatives you've considered**
Op-in to increase in mixed content messages: check content line by line, and increase font size of emoji-only lines.

**Additional context**
Riot desktop app: blue rectangles show unmodified and modified size in a chat
![riot-emoji](https://user-images.githubusercontent.com/15932551/80571438-ec73d700-89fc-11ea-9116-8f2f9c23d8b5.png)

**Comment by deepbluev7** [comment]
So as I said, this is not a feature I would personally use, so this is pretty low on my priority list. I would however merge such a feature, if someone else implements it and if it can be toggled off in the settings :3

**Comment by deepbluev7** [comment]
This was implemented in #204, you just need to toggle it on in the settings.
