### ISSUE TITLE
read receipt, encryption lock, reply button, hamburger menu not aligned between messages

### ISSUE THREAD

**Issue by non-Jedi** [Nheko-Reborn/nheko#186]
### Describe the bug

This is a "polish" suggestion rather than a bug report. It would look much nicer if the various buttons to the right of a message lined up between messages. I'm assuming this is because the time is displayed in a variable-width font and all the buttons are simply right-aligned.

![scrot_hamburger_alignment](https://user-images.githubusercontent.com/17915621/80599646-3f4b8f80-89f9-11ea-9b04-5d79ccf3062a.png)

Aside: All in all, first time using nheko since "nheko-reborn", I'm pretty happy with it. Props to y'all for stepping up. :)

### System:

- Nheko version: 0.7.1
- Installation method: distribution package manager
- Operating System: Void Linux
- Qt version: 5.14.2

**Comment by deepbluev7** [comment]
Yes, this is bugging me too, but I have yet to find an easy solution for it. Also it only happens on some fonts, so your mileage may very. Interestingly your screenshot shows a 12 hour time format, which was actually requested in #162... What locale do you use, if you don't mind me asking? :D

**Comment by non-Jedi** [comment]
Nothing special:

```
❯ locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE=C
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

**Comment by deepbluev7** [comment]
Thanks :3

**Comment by deepbluev7** [comment]
I think I fixed this. If someone can still reproduce this, please reopen and mention the font used.

**Comment by deepbluev7** [comment]
cantarell or macOS works to repro
