### ISSUE TITLE
Host require authentication

### ISSUE THREAD

**Issue by med1001** [Nheko-Reborn/nheko#191]
### Describe the bug
I can not register.
### To Reproduce
sudo apt install nheko
open nheko 
go to register 
fill all information using matrix.org as Home Server
click on register 
and i get this message: Host requires authentication.
i am using Ubuntu 18.04.3 LTS
should i use another way to access matrix.org server?
thank you.
### Expected behavior
I expected to get access to the server because i think it is a public one.
### Screenshots
![nheko](https://user-images.githubusercontent.com/26111211/80911435-4a225f00-8d2e-11ea-9ddb-6a2fb45414cd.png)

**Comment by deepbluev7** [comment]
Which version did you install? It works for me using the same username on 0.7.1 (I didn't complete registration though). You may also just have hit matrix.org while they were restarting a service temporarily or so.

**Comment by med1001** [comment]
still get the same problem.
![Screenshot from 2020-05-03 23-29-51](https://user-images.githubusercontent.com/26111211/80927789-285dc200-8d98-11ea-9704-72451da354f6.png)
Ubuntu 18.04.3 LTS

**Comment by deepbluev7** [comment]
That is an ancient version and will not work. Please use at least 0.7.0. They changed the registration flow, so you can't register with older versions. They also have some bugs. If your distribution doesn't provide it, you can install a current version from FlatHub.

**Comment by med1001** [comment]
Okay. I close the issue.
