### ISSUE TITLE
Add a highlight background to the message that the mouse is currently over

### ISSUE THREAD

**Issue by disobeyedtoast** [Nheko-Reborn/nheko#193]
Add a highlight background to the message that the mouse is currently over, such as the feature that is currently in Riot and Discord. It would improve readability and allow users to more easily see which message they're on for replying/adding emotes/etc.
![Screenshot_20200506_101435](https://user-images.githubusercontent.com/56404924/81192748-19e6f480-8faa-11ea-91a7-1d680ebf96e9.png)

**Comment by deepbluev7** [comment]
As discussed, this needs to be configurable, since it can be quite annoying. On the other hand, this has been requested quite a few times.

**Comment by lkito** [comment]
I started working on this feature

**Comment by deepbluev7** [comment]
Fixed by #201 .
