### ISSUE TITLE
Failed to join room: %23nheko-reborn%3matrix.org was not a legal room ID or room alias

### ISSUE THREAD

**Issue by strct** [Nheko-Reborn/nheko#196]
### Describe the bug

I can't join any room with Nheko neither with the `/join #nheko-reborn:matrix.org` mechanism nor with the `Join a room`-Button and entering `#nheko-reborn:matrix.org`

Both fails with the error: `Failed to join room: %23nheko-reborn%3matrix.org was not a legal room ID or room alias`

related: #80 

### To Reproduce

1. Go to a room
2. Click on `Write a message...`
3. Send message `/join #nheko-reborn:matrix.org`
4. See error: `Failed to join room: %23nheko-reborn%3matrix.org was not a legal room ID or room alias`

### Expected behavior

Join the room as it is stated in https://matrix.to/#/#nheko-reborn:matrix.org

### System:

- Nheko version: 0.7.1-a5d5ea1
- Installation method: [Flatpak](https://flathub.org/apps/details/io.github.NhekoReborn.Nheko) 
- Operating System: Ubuntu
- Desktop Environment: i3

**Comment by deepbluev7** [comment]
This has been fixed already in d94ac86816f9f325cba11f71344a3ca99591130d but hasn't been released yet. A new release, that includes this, should come next week or so.
