### ISSUE TITLE
Support custom emotes

### ISSUE THREAD

**Issue by deepbluev7** [Nheko-Reborn/nheko#200]
Some clients support adding and sending custom emotes. Nheko does sometimes display them, but you may need to switch rooms once for it to load the emoji correctly.

Nheko should allow you to define your own emoji, send them and render them nicely.

The corresponding MSC is here: https://github.com/matrix-org/matrix-doc/pull/2545

**Comment by BBaoVanC** [comment]
Looks like in the time since this issue was created, the rendering part was fixed (I'm using fluffychat to send). Now it's just that you can send stickers using Nheko, but not emoji.

**Comment by deepbluev7** [comment]
Well, someone needs to twiddle them into the current input infrastructure and I so far have successfully avoided doing that ;-)

**Comment by BBaoVanC** [comment]
> Well, someone needs to twiddle them into the current input infrastructure and I so far have successfully avoided doing that ;-)

Ah, I didn't know about that

**Comment by tastytea** [comment]
> Looks like in the time since this issue was created, the rendering part was fixed

But animated emotes are not animated in Nheko, although the same image as sticker works. :crying_cat_face:

**Comment by deepbluev7** [comment]
> But animated emotes are not animated in Nheko, although the same image as sticker works. 

Animated images are hard enough to support, doing that in a text element will be a lot harder ;-)

**Comment by BBaoVanC** [comment]
> > But animated emotes are not animated in Nheko, although the same image as sticker works.
> 
> Animated images are hard enough to support, doing that in a text element will be a lot harder ;-)

They're animated for me, maybe Nheko is thumbnailing them (Synapse's built in media repo doesn't support thumbnailing animated gifs)

**Comment by deepbluev7** [comment]
I've added an ugly completer, that is accessible using ~ now. I want to unify the completers at some point and make it not insert raw html in the future, but I don't want to block access behind that :3
