### ISSUE TITLE
The application closes

### ISSUE THREAD

**Issue by Joselpdj** [Nheko-Reborn/nheko#209]
I have tried the version 0.7.1, and when I import the keys for view the encrypted messages, the app close and appears a archive "nheko-backtrace.dump" in the appimage folder.

Tested in Mageia Plasma 7.1

**Comment by redsky17** [comment]
Would you be comfortable with running the flatpak via gdb and generating a thread dump for us?

**Comment by deepbluev7** [comment]
Since no info was provided and I haven't managed to reproduce it, I will close this for now. Especially since I am reworking that code atm, so any crash will probably be either new or not reproducable anymore.
