### ISSUE TITLE
Emoji picker disappears before your mouse can get to it on Sway

### ISSUE THREAD

**Issue by Soundtoxin** [Nheko-Reborn/nheko#211]
### Describe the bug
When using Nheko on Sway, if I click the emoji picker icon, the emoji picker opens. If I move my mouse toward it, it disappears. I suspect it's maybe related to focus-follows-mouse. Not sure.

### To Reproduce
1. (on Sway) click the emoji symbol
2. move your mouse toward the picker

### Expected behavior
I expected it to stay there so that I could select an emoji.

### System:

- Nheko version: 0.6.4
- Installation method: Guix repo 
- Operating System: Guix System
- Desktop Environment: Sway

**Comment by deepbluev7** [comment]
Yep, we are aware of this issue and we even have half of the fix done already, but thanks for reporting it, makes it easier to track :3

**Comment by FantasyCookie17** [comment]
I actually get that bug in Plasma as well, sometimes, if I'm not fast enough, so it may indeed be an issue related to focus.

**Comment by deepbluev7** [comment]
Should be fixed now, since you need to click out of the emoji picker to close it.

**Comment by Soundtoxin** [comment]
![2020-12-25-015859_grim-edited](https://user-images.githubusercontent.com/3146494/103126949-8f94f300-4655-11eb-957f-2ca57a694de3.png)


Unfortunately, it does not appear to be fixed. It seems to put the emoji picker in the center of my screen. Moving toward it then closes it due to focus change.

Happens both in portrait and landscape, and when part of a split or taking up the whole workspace to itself.

**Comment by deepbluev7** [comment]
You still have the old version, the fix is in the next release or if you run the current nightlies/master. Sorry about that confusion!
