### ISSUE TITLE
Add a way to select emoji with only the keyboard

### ISSUE THREAD

**Issue by Soundtoxin** [Nheko-Reborn/nheko#212]
**Is your feature request related to a problem? Please describe.**
Cannot tab-complete emoji the way you can on Riot with something like `:think<tab>` to get the "thinking" emoji.

**Describe the solution you'd like**
I'd like the :words method of selecting emoji, but some way to open and select from the existing emoji picker with just the keyboard would be good as well. Maybe a mix of search filtering and ability to just move around with the arrows.

**Comment by deepbluev7** [comment]
Yep, this is planned already, but thank you for reporting it anyway. We'll probably add that, when we rework the suggestions.

**Comment by deepbluev7** [comment]
Implemented in #267
