### ISSUE TITLE
[question] resetting nheko session?

### ISSUE THREAD

**Issue by xdrie** [Nheko-Reborn/nheko#215]
From the riot app, Riot says nheko is trying to use a deleted session.

To try to address this, I want to reset nheko's session. How could I reset the session?

Also, what is the location of the nheko.conf file on windows? I am unable to find it.

**Comment by deepbluev7** [comment]
The config file should be in AppData. It should also store its session there. You can reset the session by logging out and logging in too. I don't see, why Riot would think, that it is using a deleted session though. Can you send a screenshot of where that happens? You may be confusing the warning message about deleted sessions in Riot, where a device logged out in an encrypted room.

**Comment by xdrie** [comment]
> only nheko messages are readable to me when i use nheko
there isn't even an option to verify nheko through riot
these messages, on riot, are shown as being messages from a deleted session, despite this session clearly being in use

logging out and logging back in does not appear to resolve it. we're not sure, but we believe this is because we tried deleting the session in Riot's settings (Settings > Security & Privacy), and new sessions are created with that same session ID?

![image](https://user-images.githubusercontent.com/54390138/83958466-00460080-a827-11ea-8128-d71247a0f62a.png)

**Comment by xdrie** [comment]
the Sessions tab: 
![image](https://user-images.githubusercontent.com/54390138/83958519-aa258d00-a827-11ea-8eca-6c27e1bd0375.png)

**Comment by deepbluev7** [comment]
When you log out, it should delete the database, but you can try deleting the config file and database manually and see, if that resolves it. But that looks weird, I'll need to try, if I can reproduce that.

**Comment by xdrie** [comment]
I switched from the previous version (where I was having these issues) to building the development version from Git, and it seems to resolve all my issues!
I think those were some bugs from the previous release and I guess the new patches haven't made it into the next release yet.

Thanks!
