### ISSUE TITLE
Avatar background doesn't update when theme changes

### ISSUE THREAD

**Issue by redsky17** [Nheko-Reborn/nheko#22]
Avatar background isn't refreshed when the theme changes (until a restart).  This causes the avatar to display the incorrect background color

**Comment by redsky17** [comment]
From @Linda on #nheko-reborn:matrix.org

But if I change from the system theme to dark theme, the avatar background color changes. Not vice versa.

And it does switch correctly again when switching from dark to white

From light to system theme, it keeps the light theme (not full white as in my system theme)
https://ocean.joedonofry.com/_matrix/media/v1/download/matrix.org/TYFJKtXouzvaoJSSEpiWPhQa
https://ocean.joedonofry.com/_matrix/media/v1/download/matrix.org/NtNWjiScnBjVppHKediAxnNc
https://ocean.joedonofry.com/_matrix/media/v1/thumbnail/matrix.org/fuFygQsVxsfNoIzSEqZEVXuH

**Comment by deepbluev7** [comment]
I think I fixed this.
