### ISSUE TITLE
Search known users when inviting

### ISSUE THREAD

**Issue by pravi** [Nheko-Reborn/nheko#221]
**Is your feature request related to a problem? Please describe.**
When we invite someone to a room, we have to enter the full user id

**Describe the solution you'd like**
But clients like riot and fluffy chat searches known users and auto completes full username when first few letters are typed

**Describe alternatives you've considered**
we have to type full username

**Additional context**
They also shows all known users in a list which you can scroll and select to invite users. Probably they consider members of all groups we joined as know users.

**Comment by LorenDB** [comment]
This was implemented in https://github.com/Nheko-Reborn/nheko/pull/1253
