### ISSUE TITLE
Show room addresses in settings of a room

### ISSUE THREAD

**Issue by pravi** [Nheko-Reborn/nheko#222]
**Is your feature request related to a problem? Please describe.**
We cannot easily find the room address of a room, for example when we want to share it with someone.

**Describe the solution you'd like**
I have to currently use another client like Riot to find the room address.

**Describe alternatives you've considered**
Using other clients as a fallback, but would love to have it in nheko

**Additional context**
we should be able to add more aliases too, and probably choose primary alias too, if we have admin access.

**Comment by LorenDB** [comment]
This was added at some point a while back. There is a button in the room settings to allow you to view and configure aliases.
