### ISSUE TITLE
unable to enter text windows

### ISSUE THREAD

**Issue by L0ric0** [Nheko-Reborn/nheko#223]
### Describe the bug
on the login screen i am unable t enter text into the field for the homeserver

### To Reproduce
1. open nheko
1. click on "anmelden"
1. try to enter homeserver

### Expected behavior
posibility to enter a homeserver

### System:

- Nheko version: 0.7.2
- Installation method: github realease installer exe
- Operating System: windows
- Qt version: don't know probably a bundeld one
- C++ compiler: didn't compile it myself

**Comment by deepbluev7** [comment]
Should be fixed, I hope. Otherwise please reopen.
