### ISSUE TITLE
Don't store encryption keys in cache

### ISSUE THREAD

**Issue by tastytea** [Nheko-Reborn/nheko#226]
Every time `$XDG_CACHE_HOME` is wiped, I have to generate a new key for my device.

According to the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html),

> $XDG_CACHE_HOME defines the base directory relative to which user specific non-essential data files should be stored.

I would argue that encryption keys are essential. Furthermore, it is my understanding that caches are only for data that can be re-generated.

Please store the keys in `$XDG_DATA_HOME` or `$XDG_CONFIG_HOME` instead.

**Comment by deepbluev7** [comment]
Fixed by #405
