### ISSUE TITLE
Label for private messages

### ISSUE THREAD

**Issue by Mte90** [Nheko-Reborn/nheko#230]
**Is your feature request related to a problem? Please describe.**
In Riot there is a section about private messages, so it is possible to divide rooms from private messages.

**Describe the solution you'd like**
Add an autogroup for those

**Describe alternatives you've considered**
The only solution is to create a new label and add them manually everytime I start a new conversation.

**Comment by deepbluev7** [comment]
I'm guessing you mean a tag for it on the left? I'm working on that. Or at least, I was, but I'm doing some crypto first now :D

**Comment by Mte90** [comment]
Yes I mean a tag on the left, sorry for the wrong term.

**Comment by deepbluev7** [comment]
It's fine. I don't think we have a proper term for it anyway, so...

**Comment by deepbluev7** [comment]
I actually added that a while ago already :D
