### ISSUE TITLE
Wrong font used for rendering

### ISSUE THREAD

**Issue by Mte90** [Nheko-Reborn/nheko#232]
### Describe the bug
As you can see this is not the right font
![immagine](https://user-images.githubusercontent.com/403283/86118932-e0c29080-bad1-11ea-9413-0faa158ac8de.png)

### System:

- Nheko version: 0.7.2
- Installation method: debian
- Operating System: debian sid
- Qt version: 5.14.2

This happens also with the official 0.7.2 version from debian sid

**Comment by Mte90** [comment]
Ok I checked the settings and nheko picked the first font available in the list not the default in the system as predefined.
I don't know if it is a bug or a feature.

**Comment by deepbluev7** [comment]
That's a bug, it should default to QFont(), which defaults to the system font.

**Comment by Mte90** [comment]
I don't know if the issues happened for #225 in my system.

**Comment by deepbluev7** [comment]
Well, if the initial font is wrong, that should be easy enough to reproduce by deleting the config file (or the font setting from it) and starting nheko. It may be related to the system font settings as well.
