### ISSUE TITLE
Messages won't mark as read if using Riot on phone at same time

### ISSUE THREAD

**Issue by vyrus714** [Nheko-Reborn/nheko#235]
I have nheko on my desktop and Riot on my phone. When I get new messages, if I view them on nheko, they will not be marked as read even if I manually select 'mark as read.' They will only stop being unread if I switch over to my phone and view them on Riot.

1. Set up a matrix.org account with both nheko and Riot
2. receive a message and view it on nheko
3. hit 'mark as read' on the message (does nothing)
4. open Riot and view the message (message is now marked as read)

Nheko version: 0.7.2-887ad25 | Linux
Installation method: AUR nheko-git (https://aur.archlinux.org/packages/nheko-git/)
Desktop Environment: KDE Plasma

**Comment by Mte90** [comment]
I see that same problem, in my case require a while of interactions like scrolling or keep the channel opened to get as read and is very annoying.

**Comment by Mte90** [comment]
I have the same issue with just using Nheko with no other client and it is very annoying.
