### ISSUE TITLE
Show font name in the font itself

### ISSUE THREAD

**Issue by utkarsh2102** [Nheko-Reborn/nheko#238]
It's very confusing which font to select since there's no preview available during selection.
I hit this bug when I selected some unreadable font by mistake and I couldn't read or select anything further.

Something like this would be really very awesome:
![image](https://user-images.githubusercontent.com/31288318/87455308-de5c4c80-c622-11ea-81d1-7b14d0d5406a.png)

(that is, showing the font name in the font itself :))

**Comment by deepbluev7** [comment]
Sounds like a good idea, but it may have some performance implications or make the code a lot more complicated, so this needs some investigation :3

**Comment by LorenDB** [comment]
I'll look into this one.

**Comment by LorenDB** [comment]
Completed. There should be a PR soon.
