### ISSUE TITLE
Pointer should indicate that room and community list items are clickable

### ISSUE THREAD

**Issue by jwinnie-the-great** [Nheko-Reborn/nheko#242]
## Problem

The cursor doesn't turn into a pointer when you hover over the room and community list.

## Solution

Make the cursor into a pointer when you hover over the room and community list.

**Comment by LorenDB** [comment]
I think the highlight on hover should be adequate indication.

**Comment by LorenDB** [comment]
We don't plan to implement this as there is no real standard for when a pointing hand cursor is used.
