### ISSUE TITLE
Mobile Enhancements

### ISSUE THREAD

**Issue by gjabell** [Nheko-Reborn/nheko#246]
I started using Nheko on a Pinephone and already it works fairly well as a mobile Matrix client! There are a few improvements that could make it more usable:
- The conversation list doesn't recognize drag-to-scroll events (not sure if there's a better name for them), so trying to scroll on this list will end up opening the conversation your finger last lands on. This makes it very difficult to open older conversations that are further down the list.
- The sidebar is a bit buggy; sometimes it will appear even on the mobile screen and replaces the back arrow, which makes it impossible to go back to the conversations list without closing and reopening the app. I think a resize event will trigger the sidebar being shown and subsequently hiding the back arrow.
    - Toggling the sidebar in the settings fixes this; maybe it should default to off on small screens?
- With the smaller screens on mobile devices, the inline buttons/labels for read receipts, encryption, emojis, reply, menu and timestamp take up a lot of space, which means messages are squished into a fairly small column and become hard to read. Toggling the "Show buttons in timeline" option "fixes" this but since you can't right click on a phone, there is no way to reply/react to a message since it also hides the triple-dot menu.
    - Since reply and react are already in the triple-dot menu, maybe their icons could be automatically removed on small screens?
    - It seems like the read receipt and encryption icon could also be moved underneath the timestamp to save even more horizontal space.

**Comment by deepbluev7** [comment]
In theory you should be able to open the context menu by long pressing on a message, but it could be, that this doesn't actually work in practice. The resize issues should be solved in the nearish future, when I port it to Qml, since then everything should be draggable. Anyway, thank you for your feedback, we'll see, what we can do.

**Comment by gjabell** [comment]
Yeah that'd probably be the most intuitive option. Doesn't look like it works at the moment, but maybe that will also be fixed by the Qml port. Thanks for all your work on Nheko!

**Comment by deepbluev7** [comment]
No, the timeline is already in qml, but I have no idea why it doesn't work, probably a bug :3

**Comment by KAMiKAZOW** [comment]
> The conversation list doesn't recognize drag-to-scroll events (not sure if there's a better name for them), so trying to scroll on this list will end up opening the conversation your finger last lands on.

It's the same on Windows tablets, btw.

**Comment by KAMiKAZOW** [comment]
Newest Appveyor artifact fixes srcolling of the conversation list but I can't scroll the chat messages that way at all. No idea if Windows-specific or a general problem.

**Comment by deepbluev7** [comment]
Have you tried toggling the mobile/touchscreen mode in the settings?

**Comment by KAMiKAZOW** [comment]
No, I wasn't aware that basic things like scrolling need an option to enable.

**Comment by KAMiKAZOW** [comment]
![image](https://user-images.githubusercontent.com/3259076/103167202-6e84fb80-4829-11eb-9d9e-955eadc22061.png)
I turned it on. No difference.

**Comment by deepbluev7** [comment]
The option actually just disables text selection in the timeline, which usually interferes with scrolling. I guess I'll need to look into this.

**Comment by deepbluev7** [comment]
Sidebar should work properly now and buttons got removed from the timeline. The rest has WIP PRs already and it is easier to track stuff there, so I am closing this, since it otherwise is confusing, what still needs to be done here. If you have any specific pain points, It would be great to reopen them as separate issues, so that they are easier to track and mark as done.
