### ISSUE TITLE
Wrong language under Windows

### ISSUE THREAD

**Issue by KAMiKAZOW** [Nheko-Reborn/nheko#253]
I've set my "Region" to Germany (for € currency, metric units, date format) but my Windows language is set to English (en-US).

Nheko should display in English but uses German instead. There's no in-app setting to change the language either.

![image](https://user-images.githubusercontent.com/3259076/89119037-55129a00-d4ab-11ea-81e8-459c96b084b9.png)

**Comment by deepbluev7** [comment]
I may have fixed that already in https://github.com/Nheko-Reborn/nheko/pull/251/commits/da2f80df60c7ca99efdf88c528fc357a052f4c3f (not merged yet). If that doesn't fix it, I'll need to investigate, but you should be able to override the language used using the LANG environment variable and adding that to the shortcut or starting nheko from the commandline using for example `LANG=en nheko`.
