### ISSUE TITLE
Empty tray icon when using AppImage

### ISSUE THREAD

**Issue by physkets** [Nheko-Reborn/nheko#254]
### Describe the bug

There is no icon displayed in the tray, even though some space is taken up. In the attached screenshot, look at the space between the media and clipboard tray icons.

### To Reproduce
I am using the AppImage from the release page.

### Screenshots
![Screenshot_20200802_225007](https://user-images.githubusercontent.com/18267400/89128340-8b204000-d4e4-11ea-8c6f-f6669519606d.png)

### System:

- Nheko version: **0.7.2-887ad25 | Linux**
- Installation method: **AppImage**
- Operating System: **Archlinux**
- Qt version: **5.15.0**
- Desktop Environment: **KDE Plasma**

**Comment by kortewegdevries** [comment]
Is currently an issue. Can you check if there are icons extracted in `~/local/share/icons` (hicolor) or `/.tmp_mountXXXX`? `nheko.png`

**Comment by physkets** [comment]
Neither of the directories `~/.local/share/icons` or `~/.tmp_mountXXXX` exist.

I'm currently using this `.desktop` file, with the icon image extracted and placed outside the `.AppImage` file.
```
[Desktop Entry]
Type=Application
Name=Nheko
Comment=Matrix client using C++/Qt
Icon=/home/user/Applications/Nheko/nheko.png
Exec=/home/user/Applications/Nheko/nheko-v0.7.2-x86_64.AppImage
Terminal=false
Categories=Network;InstantMessaging;Qt;
StartupWMClass=nheko
X-AppImage-Version=v0.7.2
```

**Comment by reivilibre** [comment]
I can reproduce this issue (also AppImage on KDE Plasma, personally on neon 20.04).

I can find nheko icons in `/tmp/.mount_nheko-n4REEB/usr/share/icons/hicolor/32x32/apps` (other sizes too) when nheko is running.

I can also find `~/.local/share/icons/hicolor/32x32/apps/appimagekit_d488dcc88b49e3861f605d6d5c470cd1_nheko.png`, but this is possibly due to having 'integrated the AppImage with the system', which seems to be a KDE thing as close as you can get to 'installing' the appimage.

**Comment by deepbluev7** [comment]
I talked with @kortewegdevries about this, I think and it seems like the Appimage needs a call to setWindowIcon or so to have the image properly set, so this should be easy to solve

**Comment by kortewegdevries** [comment]
> I talked with @kortewegdevries about this, I think and it seems like the Appimage needs a call to setWindowIcon or so to have the image properly set, so this should be easy to solve

Like I said on the room, the appimage icon appears either way (doing a new build without changes/adding setWindowIcon) for me, although I think adding `setWindowIcon` will be better since I checked that other clients use the same.

**Comment by LorenDB** [comment]
I think this can be closed: https://github.com/Nheko-Reborn/nheko/blob/master/src/main.cpp#L187
