### ISSUE TITLE
Double Nheko broken session

### ISSUE THREAD

**Issue by LibreHacker** [Nheko-Reborn/nheko#257]
### Describe the bug
Need check for running Nheko client once before run functions

### To Reproduce
1. Open first Nheko client
2. Login in account
3. Open second Nheko client
5. Close all clients
6. Open first Nheko client again

**Comment by deepbluev7** [comment]
Huh, I wonder how I managed to break that...

**Comment by deepbluev7** [comment]
Nheko clients should block each other again on master. If that is not the case, please reopen and provide a description of your system!
