### ISSUE TITLE
allow messages to be sent/saved or at least typed while offline

### ISSUE THREAD

**Issue by Soundtoxin** [Nheko-Reborn/nheko#258]
**Is your feature request related to a problem? Please describe.**
I'm using a pretty bad matrix server, it seems. I keep losing connection. I want to pre-type a message to send when I'm connected again.

**Describe the solution you'd like**
If I could type the message, press enter, and then have it show my message with a loading symbol in the timeline until it's sent, that would be good.

**Describe alternatives you've considered**
If you just left the chat box open, I could at least type my message, paste a link, or whatever else, and then just check back later and press enter. This way I don't forget what I wanted to send when I saw things were stuck offline.

**Comment by deepbluev7** [comment]
This works now although sending is janky. We need to fix that by adding a resend button and similar stuff, but the general issue is fixed.
