### ISSUE TITLE
Memory Corruption

### ISSUE THREAD

**Issue by redsky17** [Nheko-Reborn/nheko#26]
Nheko or mtxclient suffers for memory corruption issues that manifest as display artifacts in text messages.  May also cause crashes.

**Comment by rnhmjoj** [comment]
More info is available at https://github.com/mujx/nheko/issues/460.
From personal experience: the corruption usually happens when nheko has been running for a long time and on a device with low memory.

**Comment by colemickens** [comment]
My device is neither low-memory, nor under memory pressure. 
![nheko](https://user-images.githubusercontent.com/327028/57966287-a6655680-7904-11e9-8a16-7b4625fd530f.png)

Confirming with other clients, this appears isolated to Nheko.

**Comment by deepbluev7** [comment]
I think we fixed that in mtxclient now. Please reopen, if you can reproduce this with the current 0.7.0 or newer!
