### ISSUE TITLE
display file name on hover

### ISSUE THREAD

**Issue by Soundtoxin** [Nheko-Reborn/nheko#266]
**Is your feature request related to a problem? Please describe.**
When hovering over an image I sent, I can't see the file name. I wanted to send two files in a row with similar names, and was going to use the name of the first to find my place again.

**Describe the solution you'd like**
display the filename in the corner of the image when hovered over, maybe also when viewed fullsize

**Additional context**
Dino (XMPP) has this feature implemented pretty well. (my mouse cursor is over the image at the time of this screenshot)

![screenshot of Dino image](https://files.catbox.moe/38w0kg.png)

**Comment by kamathmanu** [comment]
Hey! I'd like to work on this feature.

@deepbluev7 May I know how to find which part of the codebase to work on? I'm looking at the files under `src/ui`. Am new to contributing to open-source so a bit lost.

**Comment by deepbluev7** [comment]
The message timeline is implemented in Qml, so the corresponding code is in resources/qml/delegates/ImageMessage.qml. I think there are already properties for the filename as well as body of the image message, so you can use those to add a label on hover or so. Feel free to ping me in the #nheko room, if you have any questions!

**Comment by kamathmanu** [comment]
PR #301 enables this functionality.
