### ISSUE TITLE
Can't register on matrix.org

### ISSUE THREAD

**Issue by XakepSDK** [Nheko-Reborn/nheko#268]
### Describe the bug
I tried to register on matrix.org, but in the end, it always sends me to web page with this error:
```json
{
    "errcode": "M_UNKNOWN",
    "error": "Unknown auth stage type"
}
```

### To Reproduce
1. Open nheko
2. Click register
3. Fill username, password, repeat password
4. Write matrix.org as home server, i tried `matrix.org` and `https://matrix.org`
5. Click register
6. Pass captcha request
7. Pass privacy agreement request
8. Get another request that leads to web page with given error

### Expected behavior
Registration works

### System:

- Nheko version: nheko 0.7.2-b7b9cee
- Installation method: AUR `nheko-git`
- Operating System: Arch Linux
- Qt version: 5.15.0
- C++ compiler: gcc-Version 10.2.0 (GCC)
- Desktop Environment: KDE

### Logs
https://gist.github.com/XakepSDK/4f43c6e27c99be31cbddf0ea35c40907

**Comment by deepbluev7** [comment]
Closing in favor of #670
