### ISSUE TITLE
Arch Linux update AUR

### ISSUE THREAD

**Issue by LibreHacker** [Nheko-Reborn/nheko#282]
Try build Nheko with https://aur.archlinux.org/packages/nheko-git/
and VOIP not working.

Please fix it, if you can.

**Comment by LibreHacker** [comment]
@redsky17

**Comment by redsky17** [comment]
Thanks for letting me know.  I'll take a look at it.  Also, you can comment directly on the AUR page and I'll get an email about it

**Comment by redsky17** [comment]
I added the gstreamer dependency to the PKGBUILD and the .SRCINFO files.  Please let me know if it works for you (I was able to build and launch).

**Comment by LibreHacker** [comment]
Sadly, but seem its not fix problem...

**Comment by redsky17** [comment]
I added missing gstreamer plugins that trilene told me about.  Try again please.

**Comment by LibreHacker** [comment]
No, its not working again.

**Comment by deepbluev7** [comment]
What exactly is the issue you are having? Is the call button missing or do calls just not work?

**Comment by LibreHacker** [comment]
Call button missing and nothing see like calling. I can't test calls...

In chat see
`placed a voice call.
ended a voice call.`

**Comment by deepbluev7** [comment]
Yep, that's a dependency issue, thanks for confirming that.

**Comment by LibreHacker** [comment]
```
-- Checking for modules 'gstreamer-sdp-1.0>=1.14;gstreamer-webrtc-1.0>=1.14'
--   Package 'gstreamer-sdp-1.0', required by 'virtual:world', not found
--   Package 'gstreamer-webrtc-1.0', required by 'virtual:world', not found
```

**Comment by trilene** [comment]
gstreamer-sdp-1.0 is provided by 'gst-plugins-base'
gstreamer-webrtc-1.0 is provided by 'gst-plugins-bad'
These are needed at build time along with 'gstreamer'
'gst-plugins-good' is also needed but only at runtime

**Comment by LibreHacker** [comment]
> gstreamer-sdp-1.0 is provided by 'gst-plugins-base'
> gstreamer-webrtc-1.0 is provided by 'gst-plugins-bad'
> These are needed at build time along with 'gstreamer'
> 'gst-plugins-good' is also needed but only at runtime

All packages installed, but AUR build give "not found"

**Comment by trilene** [comment]
What does `pkg-config` output?

`$ pkg-config --cflags --libs gstreamer-sdp-1.0 gstreamer-webrtc-1.0`
`-I/usr/include/gstreamer-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/libmount -I/usr/include/blkid -pthread -lgstsdp-1.0 -lgstwebrtc-1.0 -lgstbase-1.0 -lgstreamer-1.0 -lgobject-2.0 -lglib-2.0`

**Comment by LibreHacker** [comment]
`-I/usr/include/gstreamer-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/libmount -I/usr/include/blkid -pthread -lgstsdp-1.0 -lgstrtp-1.0 -lgstwebrtc-1.0 -lgstbase-1.0 -lgstreamer-1.0 -lgobject-2.0 -lglib-2.0`

**Comment by redsky17** [comment]
It seems there was some issue with the cmake configure step in the build() section of the PKGBUILD that was causing pkg-config lookup for gstreamer-sdp-1.0 and gstreamer-webrtc-1.0 to fail.  I updated the configure step and now it seems to be working correctly (I placed a voice call w/ @nico a few minutes ago using the AUR build).

Considering I changed the configure step, please make sure you clean build when you update, and try again!

**Comment by LibreHacker** [comment]
> It seems there was some issue with the cmake configure step in the build() section of the PKGBUILD that was causing pkg-config lookup for gstreamer-sdp-1.0 and gstreamer-webrtc-1.0 to fail. I updated the configure step and now it seems to be working correctly (I placed a voice call w/ @nico a few minutes ago using the AUR build).
> 
> Considering I changed the configure step, please make sure you clean build when you update, and try again!

```
CMake Warning at build/_deps/matrixclient-src/CMakeLists.txt:102 (find_package):
  By not providing "FindOlm.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Olm", but
  CMake did not find one.

  Could not find a package configuration file provided by "Olm" (requested
  version 3) with any of the following names:

    OlmConfig.cmake
    olm-config.cmake

  Add the installation prefix of "Olm" to CMAKE_PREFIX_PATH or set "Olm_DIR"
  to a directory containing one of the above files.  If "Olm" provides a
  separate development package or SDK, be sure it has been installed.
```

```
-- The following REQUIRED packages have not been found:

 * Olm (required version >= 3), An implementation of the Double Ratchet cryptographic ratchet, <https://git.matrix.org/git/olm/about/>

CMake Error at /usr/share/cmake-3.18/Modules/FeatureSummary.cmake:457 (message):
  feature_summary() Error: REQUIRED package(s) are missing, aborting CMake
  run.
Call Stack (most recent call first):
  build/_deps/matrixclient-src/CMakeLists.txt:245 (feature_summary)
```

**Comment by LibreHacker** [comment]
Add to depends:
`libolm spdlog tweeny (AUR)`

**Comment by LibreHacker** [comment]
Look like tweeny and lmdbxx need only for build.

But new problem: messages not send. Message can receive from Element and older version Nheko.

Element calling to Nheko working. Nheko to Element and Nheko don't.

Its given on accept calling from Nheko.
```
[ui] [warning] WebRTC: no TURN server provided
[ui] [error] WebRTC: GstWebRTCICEConnectionState -> Failed
```

**Comment by LibreHacker** [comment]
Try clear cache Nheko, first message after be send, but call and others messages not...

**Comment by LibreHacker** [comment]
I'm change lmdbxx (AUR) for https://github.com/hoytech/lmdbxx

**Comment by redsky17** [comment]
I added the dependencies you mentioned to the pkgbuild / .srcinfo files.  Please check again.  As far as issues relating to gstreamer support are concerned, those should get separate issues (and also, double check your configuration of your TURN server and whatnot).

**Comment by redsky17** [comment]
@LibreHacker is this working for you now?
