### ISSUE TITLE
Tons of virtual memory allocated

### ISSUE THREAD

**Issue by Kratacoa** [Nheko-Reborn/nheko#287]
### Describe the bug
VIRT (virtual memory) parameter in `htop` is off the charts, with an average of 30+ G allocated to `nheko`.

### To Reproduce
Open `nheko` on Void Linux.  
[Link](https://github.com/void-linux/void-packages/blob/2bb4f7d872a154b738272d6729d40685b3190834/srcpkgs/nheko/template) to Void's template.

### Screenshots
https://files.catbox.moe/nu38nj.png

### System:

- Nheko version: 0.7.2
- Installation method: musl repository of Void Linux
- Operating System: Void Linux

### Logs
http://ix.io/2xYG  

P.S. I also had issues with it taking 100% of CPU on different threads, and crashing, but currently don't have the time to investigate

**Comment by deepbluev7** [comment]
That's intentional, lmdb does that, so it can map the database into memory. This memory is never used conpletely and the OS will just page it out, since those pages are usually not dirty. Only resident/dirty memory is actually RAM, that can't be used by other applications. So this is not a bug.
