### ISSUE TITLE
Use up arrow for redacting messages instead of your messages history

### ISSUE THREAD

**Issue by Kratacoa** [Nheko-Reborn/nheko#288]
As per title; this is a more common usage of the button in chat clients.

**Comment by LorenDB** [comment]
@deepbluev7 @redsky17 Y'all are the head honchos here. If you think that this is a good idea, let me know and I'll work on it.

**Comment by deepbluev7** [comment]
@LorenDB I would prefer to use arrow keys for editing, not reacting probably.

**Comment by LorenDB** [comment]
OK, case closed.

**Comment by deepbluev7** [comment]
We decided to use that for editing instead, message history got moved to ctrl-p/n

**Comment by Kratacoa** [comment]
Thanks for updating me and your work!
