### ISSUE TITLE
proxy setup

### ISSUE THREAD

**Issue by miocho** [Nheko-Reborn/nheko#29]
please enable configuring a SOCKS proxy so nheko's connections can be proxied through Tor using a local Tor daemon.

**Comment by Houkime** [comment]
One extra requirement is that this setting should be available right from start (register/login screen) or via config file/CLI.

**Comment by Houkime** [comment]
Unfortunately right now nheko can't be successfully torified even with torsocks which is a shame (seems like torsocks can't resolve addresses used in nheko for some reason)

**Comment by Houkime** [comment]
I've managed to have a settings button at the start (although sacrificed malfunctioning Olm in show handler) at my fork here
https://github.com/Houkime/nheko/tree/settings-at-start
But proxying stuff is not there to set. Need to do a research how to do it ok and also if there is a client that alredy does it for matrix. (Riot doesn't)

**Comment by selankon** [comment]
Hi,

Riot is torificable using the Electron feature `--proxy-server`:

```
./riot-web --proxy-server=socks5://127.0.0.1:9150
```

Font: https://github.com/vector-im/riot-web/issues/8390#issuecomment-471104103

**Comment by Glandos** [comment]
I also tried proxychains4 or environment variable (`https_proxy`) without success. This blocks the usage of Nheko within my corporate environment.
