### ISSUE TITLE
Can't use Matrix ID input

### ISSUE THREAD

**Issue by hissssst** [Nheko-Reborn/nheko#292]
### Describe the bug
Can't enter my Matrix ID, input does not work

### To Reproduce
1) Open Nheko while being **not** logged in
2) Open Login
3) Try to enter Matrix ID

### Expected behavior
I can enter my Matrix ID

### Screenshots
I have screen recording

### System:

- Nheko version: `0.7.2-33db0fa`
- Installation method: `AUR`
- Operating System: `Linux`
- Qt version: `5.15`
- Desktop Environment: `Wayland, sway`

### Logs
```
[2020-09-28 11:12:51.235] [qml] [warning] QVariant::load: unable to load type 1025. (:0, )
ssl3 ext invalid servername
ssl3 ext invalid servername
[2020-09-28 11:12:51.449] [ui] [debug] Status changed to 1
[2020-09-28 11:12:51.545] [ui] [info] jdenticon plugin not found.
[2020-09-28 11:12:51.549] [ui] [info] starting nheko 0.7.2-33db0fa
```

**Comment by deepbluev7** [comment]
This is probably just the UI guidance being bad. Have you tried starting your input with an @?

**Comment by hissssst** [comment]
@deepbluev7 Yeah, that helps, but should it be that way?

**Comment by deepbluev7** [comment]
Not really, the validator should give better hints and not just block input. But I need to fix that still...

**Comment by hissssst** [comment]
@deepbluev7 You can give me the file:line of code where to look and I'll try to implement a PR

**Comment by deepbluev7** [comment]
In line 98 of the LoginPage Nheko sets a validator: https://github.com/Nheko-Reborn/nheko/blob/master/src/LoginPage.cpp#L98

That one blocks all input. Instead it should have a listener, when a key is pressed and interactively validate the input and give proper error messages.
