### ISSUE TITLE
One time key error message can cause the nheko login screen to become very wide

### ISSUE THREAD

**Issue by AndrewJDR** [Nheko-Reborn/nheko#30]
TDLR: I think there should be a forced text wrapping width for error messages on the login screen.

Long version:
If a startup error shown in nheko's login screen happens to be quite long, it will cause the width of window to expand far beyond the width of the monitor. In my case, nheko was showing a message concerning being unable to upload one time keys. The message looked like this but all on one line. I have redacted portions of it with `R` and `r`, but have tried to maintain same text length:
```
Failed to setup encryption keys. Server response: One time key signed_curve25519:AAAAAQ already exists. Old key: {"key":"RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR","signatures":{"RRRRRRRRRRRRRRRRRRRRR":{"ed25519:rrrrrrrrrr":"rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr"}}}; new key: {'key': 'rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr', 'signatures': {'rrrrrrrrrrrrrrrrrrrrr': {'ed25519:rrrrrrrrrr': 'rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr'}}} 400
```

In terms of how I was able to reproduce this message in the first place, I believe it may have happened because, with a previous version of nheko, I attempted but failed to login in (due to the sync loop issue https://github.com/Nheko-Reborn/nheko/issues/19). I more recently tried a new version to see if that problem is fixed, and this is when i encountered this issue.

Perhaps, with the older version of nheko that had the sync issue, it got part way through the login process such that certain aspects of the key management were finished, but some other parts of it were unfinished, resulting in this error the next time I started nheko.

**Comment by deepbluev7** [comment]
The error label should wrap now.
