### ISSUE TITLE
How can I import E2E keys from Element?

### ISSUE THREAD

**Issue by ZarusMods** [Nheko-Reborn/nheko#304]
Hello, I would like to import my E2E keys from Element but the problem is that nheko don't accept it.
So is there some way to import them?

**Comment by deepbluev7** [comment]
You can import the keys in the settings (at the very bottom). This should work, if you have a recent version of Nheko (i.e. 0.7.2). Old versions won't work, since Element changed their format.

**Comment by ZarusMods** [comment]
> f you have a recent version of Nheko (i.e. 0.7.2

Yes, I already have newest version from github. But it still decline it giving HMAC error

**Comment by deepbluev7** [comment]
Hm, I can't reproduce that. Are you sure you entered the correct password?

**Comment by deepbluev7** [comment]
Closing because no info and I have tested it multiple times recently.
