### ISSUE TITLE
Font rendering of the chat blurry on Windows

### ISSUE THREAD

**Issue by AgentOak** [Nheko-Reborn/nheko#309]
### Describe the bug
Font rendering of text messages in the chat field is very blurry. 

### To Reproduce
1. Open nheko
2. Join/Open any room
3. Observe text

Settings used in the screenshots are:
Scale factor: 1
Font size: 10
Font Family: DejaVu Sans

Font size and family does not matter however, I've also tried 10.5/11/12, Liberation Sans and Noto Sans, all of them are blurry.

### Expected behavior
The text should be as sharp as in the rest of the UI.

### Screenshots
![nheko-blurry-text](https://user-images.githubusercontent.com/1313295/97369645-9699c200-18ad-11eb-841a-357882daa029.PNG)
![nheko-sharp-text](https://user-images.githubusercontent.com/1313295/97369646-97caef00-18ad-11eb-9a3f-804565694ee7.PNG)
(open them in a new tab so they're unscaled)
As you can see the font in the chat window is very blurry, including the time, but other fonts in the UI, like "Write a message..." and the rooms sidebar looks fine.
The chat text also seems too big in general; 10pt fonts look much smaller in other applications. In nheko the font sizes are huge by comparison.

### System:

- Nheko version: 0.7.2-887ad25
- Installation method: nheko-v0.7.2-installer.exe
- Operating System: Windows 10 2004 x64

**Comment by LorenDB** [comment]
Is this still an issue with the latest Nheko version?

**Comment by deepbluev7** [comment]
Closing, since we got no feedback on that anymore and we had multiple changes, that should fix that.
