### ISSUE TITLE
Symbol lookup error

### ISSUE THREAD

**Issue by HeikoTietze** [Nheko-Reborn/nheko#315]
[2020-11-02 07:22:57.503] [ui] [info] WebRTC: initialised GStreamer 1.18.1
ssl3 ext invalid servername
ssl3 ext invalid servername
nheko: symbol lookup error: nheko: undefined symbol: _ZN3fmt2v76detail10vformat_toIcEENS0_20basic_format_contextISt20back_insert_iteratorINS1_6bufferIT_EEES6_E8iteratorERS7_NS0_17basic_string_viewIS6_EENS0_17basic_format_argsINS3_IS4_INS5_INS0_13type_identityIS6_E4typeEEEESH_EEEE

nheko 0.7.2-9169a26e on ArchLinux

**Comment by deepbluev7** [comment]
That sounds like you linked dynamically against libfmt and that library got updated. Rebuild nheko and maybe mtxclient.

**Comment by deepbluev7** [comment]
Closing this, as this seems stale and not an actual issue (just a missing rebuild). Please reopen, if this is still an issue.

**Comment by fulup-bzh** [comment]
For your information, all version build for OpenSuSE=-15.4 on the OBS have this issue. https://software.opensuse.org/download/package?package=nheko&project=home%3ADead_Mozay%3Amatrix
