### ISSUE TITLE
FR: Filter OUT some of chat categories/groups/communities.

### ISSUE THREAD

**Issue by JuniorJPDJ** [Nheko-Reborn/nheko#321]
I'd like to be able to select all-but-this-one or multiselect categories.
For example I'd like to be able to filter out low-priority chats when persisting all other from the list.

**Comment by deepbluev7** [comment]
You can right click a tag/space and hide that from all others. I think that should be enough?

**Comment by JuniorJPDJ** [comment]
Yup, this is cool, thanks :D
