### ISSUE TITLE
Consider renaming "Redact" to "Delete"

### ISSUE THREAD

**Issue by deepbluev7** [Nheko-Reborn/nheko#329]
Redact seems to not be as easy to understand and it is very close to react. Needs some discussion though.

**Comment by slondr** [comment]
Isn't `redact` the name the protocol uses?

**Comment by deepbluev7** [comment]
Yes, but the protocol also calls replies "Rich replies", communities "groups" and edits "replaces". The naming of sessions as devices is also a bit confusing. We are not bound to use the spec names for the user visible parts. If there is a name, that is easier to understand, we should probably use that, as long as it doesn't add any confusion.

**Comment by redsky17** [comment]
We could always choose the wording that Element uses: "Remove".  Since delete isn't exactly accurate, I'd like to find an alternative!

**Comment by deepbluev7** [comment]
Yeah, remove sounds great actually!

**Comment by LorenDB** [comment]
I would go for "Remove" as well, especially since messages aren't actually deleted, the content is what gets removed.

**Comment by Kirillpt** [comment]
Where I can fix it? (In what file)
