### ISSUE TITLE
Implement Proper Replies

### ISSUE THREAD

**Issue by redsky17** [Nheko-Reborn/nheko#33]
There's currently no way in nheko to reply to a specific message (like in Riot, for instance).  Users should have the ability (perhaps via right-clicking on a message) to quote or reply to that specific message

**Comment by vtronko** [comment]
IMO icon-only reply button on the right to the message fits here better. Right-click actions are not obvious here, as messages are not *THAT* much separated visually as in e.g. Telegram.
Icon-only button would be more user-friendly from my perspective.
Just an opinion here

**Comment by aaronraimist** [comment]
Do you want to wait until threading comes along and changes how replies work? My understanding was the current reply system was eventually going to change.

**Comment by redsky17** [comment]
> Do you want to wait until threading comes along and changes how replies work? My understanding was the current reply system was eventually going to change.

Do you know how substantially they are going to change?  Is the entire m.relates_to/m.in_reply_to going away?  Also, do you know the timeline for threading?  It seemed like something that was a long ways off from the discussions I've seen about it.

**Comment by aaronraimist** [comment]
You're right that it is probably going to be a while and I guess today's replies won't go away for backwards compatibility. `#matrix-sepc:matrix.org` would probably know more.

**Comment by deepbluev7** [comment]
Apart from some issues, I'd say this works now. Since we already have bug reports for the individual issues, I'll mark this as done.
