### ISSUE TITLE
Problem with compilation, libmatrix_client.so.0.3.1: Error 40

### ISSUE THREAD

**Issue by powerjungle** [Nheko-Reborn/nheko#333]
After I've compiled and installed "mtxclient" and compiled nheko v0.7.2, when running the binary in "build", I just get this:
./nheko: error while loading shared libraries: libmatrix_client.so.0.3.1: cannot open shared object file: Error 40

I've even made symlinks from /usr/local/lib to /usr/lib just in case, but same result.

I'm running 5.8.18-1-MANJARO.

**Comment by deepbluev7** [comment]
That is because your library path is not setup correctly, either build with `-DBUILD_SHARED_LIBS=OFF` or install both (or use the AUR build).

**Comment by deepbluev7** [comment]
Closing this, since this doesn't seem like our issue and no more feedback was provided. If this is still an issue, ping me.
