### ISSUE TITLE
FR: Toggle for showing only chats with unread messages/events

### ISSUE THREAD

**Issue by JuniorJPDJ** [Nheko-Reborn/nheko#336]
I'd like to see togglable filter which would show only chats/rooms with unread messages/events.
It would make getting updated with chats much faster.

**Comment by deepbluev7** [comment]
It already shows those at the top, doesn't that solve that already?

**Comment by JuniorJPDJ** [comment]
It doesn't.
Chat seems to be sorted by activity.
When I read some recent chat(1) while skipping other chat(2), the (2) is still behind (1).

**Comment by deepbluev7** [comment]
What version are you on? At least the current development version (and I think the latest stable release) put mentions first, then unmuted rooms with unread messages, then all other rooms.

**Comment by JuniorJPDJ** [comment]
Latest stable from arch repository - 0.7.2-33db0fa
I still think there should be at least setting for it.

**Comment by JuniorJPDJ** [comment]
![image](https://user-images.githubusercontent.com/7334549/100309584-890a5180-2fab-11eb-9ea9-0059e427cc8e.png)
It's still the same behaviour for me on 0.7.2-90cae987

**Comment by deepbluev7** [comment]
Ah, you disabled notifications for those rooms, so they are not sorted to the top. Or at least there is no unread count, just the marker.

**Comment by LorenDB** [comment]
I think this should be closable by now.
