### ISSUE TITLE
File upload - size limited

### ISSUE THREAD

**Issue by Peter2121** [Nheko-Reborn/nheko#35]
- Nheko version: 0.6.3 Darwin
- Installation method: DMG from Github and local build (same error)
- Operating System: Mac OS X 10.13.6
- Qt version: I don't know
- C++ compiler: I don't know

I use my own installation of Synapse (domain bimp.fr).
Using Nheko I cannot upload files larger than 1MB approximately (_"Failed to upload image. Please try again"_).
There is no problem to upload files even larger than this using Riot (the same server, the same room, the same account).
Nothing in logs (how can I increase the debug level?)
I think that it is a problem of timeout too short, but I cannot find a place where i can increase it.
I can build Nheko from sources using provided CMake files and instructions from GitHub, so I can do more tests, but I cannot debug (no working IDE for Qt/C++).

**Comment by redsky17** [comment]
Do you have any other error messages you can provide, maybe from the console or log?  I just tested uploading a 9MB file with nheko and it works as expected (my synapse has a 10MB filesize limit).

**Comment by Peter2121** [comment]
If I start Nheko from terminal, I have the following error on the console:
`[net] [warning] failed to upload image:   (413)`

**Comment by Peter2121** [comment]
The problem is fixed adding `client_max_body_size 20M;` to `http` section of `nginx.conf` file (reverse proxy for Synapse).
I still don't understand how Riot could send large files to the same server.
Sorry for noise.
