### ISSUE TITLE
Send bar is not vertically aligned properly. [Super minor]

### ISSUE THREAD

**Issue by Kommynct** [Nheko-Reborn/nheko#351]
### Describe the bug
The elements in the send bar are not perfectly vertically aligned

### To Reproduce
Use the system theme, go to any messages.

I suspect it has something to do with my font choice. -- noto sans regular 10.5

### Expected behavior
These elements should all be aligned.

### Screenshots
![image](https://user-images.githubusercontent.com/13646790/101272411-e6e02b80-3759-11eb-8ef4-007c4eeb613e.png)

Red line is my sway border. Message text is low. for no apparent reason.

For comparison, this is what telegram looks like
![image](https://user-images.githubusercontent.com/13646790/101272543-3115dc80-375b-11eb-9fbc-bd7dc607b533.png)

### System:

- Nheko version: 0.7.2-5aa22180
- Installation method: AUR
- Operating System: Arch
- Desktop Environment: Sway

Anyway, I am certain this is the most important bug report you have so I expect this to be fixed VERY urgently /s

**Comment by deepbluev7** [comment]
Could probably be fixed by changing the height of the text input or setting some option on the text area.

**Comment by Kommynct** [comment]
Oddly, having switched back to nheko in the aur rather than nheko-git, the issue is completely resolved
![image](https://user-images.githubusercontent.com/13646790/101294052-e8a20180-37e2-11eb-8baf-0c3d39251bfe.png)

I've also noticed the back button at the top left is half as large, perhaps it was something related to hidpi that causes the behavior.

**Comment by deepbluev7** [comment]
No, it is because the input bar was completely rewritten in a different technology, so some fallout was somewhat expected. This particular issue is probably because the buttons now align to the bottom, when a message gets higher than a few lines.

**Comment by LorenDB** [comment]
I am experiencing a similar visual misalignment (made especially obvious by my hacks to get around the wacky `background:` issue).
