### ISSUE TITLE
Room alias creation can cause internal server errors

### ISSUE THREAD

**Issue by deepbluev7** [Nheko-Reborn/nheko#354]
### Describe the bug

Currently you can enter an alias at room creation time. If you enter a full alias, i.e. #a:neko.dev, this will cause an internal server error. We should make sure to catch such issues before they happen and provide appropriate hints.

### To Reproduce
1. Create a new room
2. Enter a full alias instead of just the local part.

You will get an internal server error at room creation time.

### Expected behavior
Understandable error message.

### System:

- Nheko version: 0.7.2 (and current master)

**Comment by Apurv404** [comment]
Fixes #1033
