### ISSUE TITLE
[severe] undefined symbol: _ZTIN3fmt2v612format_errorE

### ISSUE THREAD

**Issue by utkarsh2102** [Nheko-Reborn/nheko#362]
Hi,

Whilst trying to open `nheko`, it fails to open with the following message:

```
$ nheko                                   
nheko: symbol lookup error: nheko: undefined symbol: _ZTIN3fmt2v612format_errorE
```

Is that known? Any idea what caused this regression or failure? Any workaround this?

**Comment by deepbluev7** [comment]
What install method did you use? Is it the AUR on arch by chance and you forgot to rebuild nheko, after libfmt was updated?

**Comment by deepbluev7** [comment]
Probably a duplicate of #315

**Comment by utkarsh2102** [comment]
> What install method did you use?

Installed via apt repository from Debian. Version 0.7.2.

**Comment by utkarsh2102** [comment]
> Is it the AUR on arch by chance and you forgot to rebuild nheko, after libfmt was updated?

Whilst it was Debian, but this hint did the trick! I did a rebuild with the latest libfmt version in the Debian archive and then nheko worked fine as usual. I'll soon upload the rebuild to the apt archive so nobody would face the same.

Thanks for all your work! And seasons greetings! ❤️
