### ISSUE TITLE
cmake: GStreamer presence/absence should be presented in the configuration feature summary

### ISSUE THREAD

**Issue by lbeltrame** [Nheko-Reborn/nheko#366]
### Describe the bug
It's easy to miss the optional GStreamer dependency because it does not use `find_package` and so it is not present in the final summary. 

As there is no proper FindGStreamer.cmake around (the ones I've found are pretty old), one could implement the suggestion from 

https://stackoverflow.com/questions/38554732/how-to-make-featuresummary-include-packages-found-by-pkg-check-modules

### To Reproduce
Run cmake

### Expected behavior
Present or missing GStreamer is present in the final feature summary

**Comment by deepbluev7** [comment]
I guess that would make sense. I think we can just use the `add_feature_info` and tell the user, that they won't have VOIP support,

**Comment by deepbluev7** [comment]
Does that work for you?

**Comment by lbeltrame** [comment]
Yes, works, thanks.
