### ISSUE TITLE
Can't choose font size smaller than 10

### ISSUE THREAD

**Issue by pztrn** [Nheko-Reborn/nheko#367]
There are no possibility to choose font size smaller than 10.

### To Reproduce
1. Go to Settings
2. Try to choose smaller font because current is very large
3. Fail to do so.

### Expected behavior
I am able to choose font size smaller than 10.

### Screenshots
![изображение](https://user-images.githubusercontent.com/869402/104095939-7168fd00-52bb-11eb-8247-b2fee7af0818.png)

### System:

- Nheko version: just-from-git
- Installation method: AUR
- Operating System: Arch Linux
- Qt version: 5.15.2
- C++ compiler: 10.2.0
- Desktop Environment: latest KDE

**Comment by deepbluev7** [comment]
Well, that is easy enough to fix, we can just change the displayed values in the combobox here: https://github.com/Nheko-Reborn/nheko/blob/master/src/UserSettingsPage.cpp#L674

Alternatively we could make it a spinbox, that allows arbitrary values.

Which value would you like to use?

**Comment by pztrn** [comment]
I need at least 9, but spinbox should be more useful IMO.

**Comment by deepbluev7** [comment]
Okay, I'll see what I can do.

**Comment by LorenDB** [comment]
As a reference, Libreoffice Writer has 6 as the smallest font value.

Most people aren't going to need terribly tiny or huge values for this, though. One possible approach would be to define a list of common values, put them in an editable QComboBox, and use a QValidator to weed out invalid entries (such as -1982).

**Comment by deepbluev7** [comment]
@LorenDB In this case a https://doc.qt.io/qt-5/qspinbox.html would be more appropriate.

**Comment by LorenDB** [comment]
I understand and somewhat agree, but in this case I think that using a spin box would not be what many users would expect. Maybe this isn't anything to worry about, but that's my thoughts on the matter.

**Comment by deepbluev7** [comment]
Why not? If it moves in .5 increments or so, that sounds fairly reasonable to select a font size between 6 and 24 or so.

**Comment by LorenDB** [comment]
Yes, but I guess my thing is that most people aren't expecting a spin box. Maybe that doesn't matter, though :shrug:

**Comment by deepbluev7** [comment]
I changed the lower limit to 6 now, so I consider this fixed.
