### ISSUE TITLE
Crash with SIGABRT when bringing up the UI

### ISSUE THREAD

**Issue by lbeltrame** [Nheko-Reborn/nheko#368]
### Describe the bug
Opening up the main interface (while everything works if it's minimized in the system tray) crashes with a SIGABRT. 
I don't know if it's a driver bug or a Qt bug, or a Nheko bug yet. See backtrace to see what I mean.

### To Reproduce
Launch Nheko minimized, then open the UI.

### Expected behavior
UI shows up and it is operational.

### System:

- Nheko version: Master, from cc9de7f3b0d0459a773a82a79a6c38bbf4ea6ea7
- Installation method:  Source build
- Operating System: openSUSE Tumbleweed
- Qt version: Qt 5.15.1
- C++ compiler: gcc 10.2.1
- Desktop Environment:  Plasma (from git master)

(given the backtrace):

Mesa 20.3.2

### Logs
Latest lines before the crash (no meaningful information in debug mode):

```
[2021-01-10 00:34:36.445] [ui] [info] timelineWidth: -280
[2021-01-10 00:34:36.445] [ui] [info] timelineWidth: 18446744073709551336, min 700
[2021-01-10 00:34:36.615] [ui] [info] timelineWidth: 833
[2021-01-10 00:34:36.615] [ui] [info] timelineWidth: 833, min 700
```

### Debugger backtrace

https://pastebin.com/7Kg9Bzp9

**Comment by lbeltrame** [comment]
Driver or Qt bug. If running with LIBGL_ALWAYS_SOFTWARE=1 it does not crash.

**Comment by lbeltrame** [comment]
FTR, I opened an upstream issue about this: https://gitlab.freedesktop.org/mesa/mesa/-/issues/4134

**Comment by deepbluev7** [comment]
Just to be on the safe side, could you remove the local qml cache at ~/.cache/nheko/nheko/qmlcache? That sometimes causes issues.

**Comment by lbeltrame** [comment]
I tried, but when the QML cache has issues it crashes all applications using it (including Plasma). So far *only* nheko has this issue in this system, but I have no idea what's triggering it. So far I suspect Mesa, but it may be a bug in Qt even. I only know it doesn't happen with Mesa 20.2 but it does with 20.3.
