### ISSUE TITLE
Create std::vector larger than max_size()

### ISSUE THREAD

**Issue by Jihadist** [Nheko-Reborn/nheko#371]
### Describe the bug
Crash

### To Reproduce
1. Go to 'Settings'
2. Click on 'Import'
4. See error if i choose malformed file

> terminate called after throwing an instance of 'std::length_error'
>   what():  cannot create std::vector larger than max_size()
> Aborted (core dumped)

### Expected behavior
Import 

### System:

- Nheko version: fcedfac59785a0a57990d1bd9d82b2f2aa258d1a
- Installation method: AUR
- Operating System: arch
- Qt version: 5.15.2
- C++ compiler: it compiled with aur script
- Desktop Environment: KDE

### Debugger backtrace

Please don't close this if u cannot reproduce, i'll try to do it with gbd later.

**Comment by deepbluev7** [comment]
A backtrace would be nice, looks like something corrupts memory or uses after free somewhere.

**Comment by deepbluev7** [comment]
Oh, this happens only with malformed files? That should be easy enough to reproduce!

**Comment by Jihadist** [comment]
Try to use small password and malformed file, i catch this error multiple times with password 1

**Comment by deepbluev7** [comment]
Okay, thanks!
