### ISSUE TITLE
request: keyboard shortcuts

### ISSUE THREAD

**Issue by Spacewalker2** [Nheko-Reborn/nheko#38]
[Riot](https://github.com/vector-im/riot-web/blob/master/docs/shortcuts.md) like keyboard shortcuts would be nice. Maybe some more for other use cases. Thanks.

**Comment by redsky17** [comment]
Can you provide some examples of must-have keyboard shortcuts?  I don't
really know most of them.  that being said, nheko does support a few
keyboard shortcuts (such as Ctrl+K to search joined rooms).

Thanks

**Comment by Spacewalker2** [comment]
- ↑/↓ - navigate within room list like riot
- PgDn/Ctrl-f/Space - scroll timeline down (one page/window)
- PgUp/Ctrl-b - scroll timeline up (one page/window)
- Enter/Return/Ctrl-n - scroll timeline down (one line)
- Ctrl-y - scroll timeline up (one line)
- Ctrl-↑- history up (input line)
- Ctrl-↓- history down (input line)
- Ctrl-w - delete current word (input line)
- Ctrl-u - delete entire input line
- Ctrl-←/Alt-b - jump one word left (input line)
- Ctrl-→/Alt-f -  jump one word right (input line)
- Ctrl+Home/End - jump to timeline start/end like riot
- Ctrl-n - jump to first unread message (current room)
- Ctrl-r - mark as read (current room)
- Ctrl-q - quote last message (current room)

I'm sure there is space for improvement in this list. Maybe anybody else can provide ideas too.

**Comment by BurnyBoi** [comment]
Navigation between rooms would likely need to be something like **alt +** (up and down), no?

There are a couple others I can think of that could be neat:

- ctrl+alt+(up and down)  - Navigate between community filters)

- Shortcuts to select low priority and favorite filters (not sure what these would be mapped to)

Another idea that comes to mind would be to have these keybinds as default, but implement a system to allow the user to remap the keybinds.

**Comment by redsky17** [comment]
Esc should close the image modal after the user selects an image

**Comment by deepbluev7** [comment]
You can now switch to the next/previous room in the room list via Ctrl+Up/Down. You can also scroll half the screen up/down in the timeline via PgUp/PgDown.

**Comment by deepbluev7** [comment]
Reminder to myself to add tab as an option to refocus the message input.

**Comment by PC25** [comment]
@redsky17 @deepbluev7 I'd like to work on some of the mentioned shortcuts. Are there some of the particularly required shortcuts that I should focus on?

**Comment by deepbluev7** [comment]
I think refocusing the input panel would be nice to have. Closing the image dialog via escape seems also very useful and maybe Ctrl+o to send attachments. Some of the others seem already to be implemented in some shape or form or not that important imo.

**Comment by cloudrac3r** [comment]
Esc should scroll to the bottom of the timeline (and mark as read, of course). I use this all the time in Discord.

**Comment by deepbluev7** [comment]
I think currently the plan is to have Esc close the chat. We could make the "End" key scroll to the bottom though.

**Comment by cloudrac3r** [comment]
Oh no, my muscle memory! D:

We already have Alt-F4 to close the window from the keyboard, or whatever your WM's bindings are.

**Comment by deepbluev7** [comment]
Well, the idea was not to close the window, but close the chat, so that no messages get accidentally read, when you focus the window, etc. See issue #55 .

**Comment by ptman** [comment]
So nheko supports Ctrl+k? Can we have a list of currently supported keyboard shortcuts?

**Comment by ptman** [comment]
riot keyboard shortcuts can be viewed with Ctrl+/ , I think

**Comment by MayeulC** [comment]
> riot keyboard shortcuts can be viewed with Ctrl+/ , I think

It doesn't work for me, at least the web version. Why not F1, that's pretty standard for help :)

**Comment by deepbluev7** [comment]
Or we just use the Qt default shortcut for help ;p

**Comment by ptman** [comment]
@deepbluev7 I'm not arguing for using the same, just that one could check the shortcuts in riot and maybe make a similar listing

**Comment by deepbluev7** [comment]
Yeah, something like that was already on my mind for a bit, I'll probably do that at some point.

**Comment by pstn** [comment]
About quoting: I'm not sure that `C-q` is the best idea for quoting. It is bound to "close window" in many window managers. I propose `Shift-↑/↓` to scroll select the quoted message. One press of `Shift-↑` while nothing is quoted should quote the last message. I think `Shift-↓` should be unbound as long as nothing is quoted but I'm not sure about that one.

**Comment by cloudrac3r** [comment]
I agree with the above, but rich reply instead of quote text.

**Comment by deepbluev7** [comment]
The problem with Shift is that it conflicts with text selection. I'm going for alt for now, but we can easily change that, if it causes other conflicts.

**Comment by deepbluev7** [comment]
Reply target selection done: https://github.com/Nheko-Reborn/nheko/commit/e48dfd15fe9ae1ca0dd27fd3fb69e5acaf564833

**Comment by bjesus** [comment]
When the window is narrow and layout is showing either the rooms list or the chat, is there anyway to navigate back to rooms list from the chat? Since `Ctrl+Up/Down` takes you between the rooms, it feels like this perhaps should be `Ctrl-Left`?

**Comment by deepbluev7** [comment]
Yeah, I think that is needed, but I'm not sure about Ctrl+Left, since that is used to select a full word. Probably something more like Ctrl+Backspace.

**Comment by cloudrac3r** [comment]
That won't work, Ctrl-Backspace is backspace word. `Alt-Left` has potential.

I'm unsubscribing from this thread as I don't think bikeshedding specific key combinations deserves to be in my inbox.

**Comment by LorenDB** [comment]
> * Ctrl-u - delete entire input line

Taken care of a few days ago.

**Comment by Kommynct** [comment]
I recognize how niche my usecase is, but I am on the dvorak layout, and as a result, would like to be able to rebind these keys.

Is making them rebindable an option?

**Comment by deepbluev7** [comment]
That would be fairly annoying, which key combinations are an issue for you?

**Comment by Kommynct** [comment]
If rebinding isn't an option I wouldn't really worry about it, but anything with b, w, r, and n is problematic as they're on the right half of the keyboard, if we care about one handed use, anyway.

**Comment by deepbluev7** [comment]
I think the only key combination, that doesn't just use arrows + modifiers or page up/down is ctrl+k. Every other shortcut should be almost the same across different layouts, but one handed use was never a concern when choosing them, so that probably sucks. :D

**Comment by Kommynct** [comment]
ctrl+k happens to be super easy on dvorak. So, non-issue I guess.

**Comment by guedressel** [comment]
Would be nice to have settings screen close by pressing [Esc]

**Comment by jgarte** [comment]
Is there currently any shortcut to search a room's history for text?

**Comment by deepbluev7** [comment]
Nope

**Comment by jgarte** [comment]
I think joining a room and creating a room should have a keyboard shortcut. As well as going to the settings menu. That would be nice :)

**Comment by jgarte** [comment]
> Nope

Is there currently a way to search a room for text without a keyboard shortcut? I am having trouble finding a way to do this.

**Comment by jgarte** [comment]
ctrl + k is awesome! I'd be content with just a `ctrl + s` or whatever to search history of a particular room. Those two and nothing else :)

**Comment by deepbluev7** [comment]
> > Nope
> 
> @deepbluev7 Is there currently a way to search a room for text without a keyboard shortcut? I am having trouble finding a way to do this.

Nope. :D

**Comment by MayeulC** [comment]
I second this, it's a lot better to ask such questions in #nheko. Text search is another issue (#8 to be precise).

I just want to add that I was interested in overhauling shortcut support a bit, making shortcuts configurable and discoverable (from the configuration screen, at least). Not sure if I'll end up having time for this, but my design ideas are pretty clear.

**Comment by deepbluev7** [comment]
I'm gonna close this, because Nheko does have a lot of shortcuts now and they are somewhat documented. For specific shortcut related issues, it is probably better to open separate issues at this point.

**Comment by darkralts** [comment]
is there anywhere to see all the keybinds?

**Comment by ptman** [comment]
https://github.com/Nheko-Reborn/nheko/blob/master/man/nheko.1.adoc#keyboard-shortcuts

**Comment by darkralts** [comment]
thank you pt!
