### ISSUE TITLE
Paste from clipboard does not work in Login screen

### ISSUE THREAD

**Issue by Rogier-E** [Nheko-Reborn/nheko#386]
### Describe the bug
Paste (from clipboard) seems disabled in the initial Login screen

### To Reproduce
1. Download the latest client, open it and click on 'Login'
2. Make sure there is something (like a username or password) in the clipboard
3. Press ⌘V (on macOS, not sure if the same bug occurs on other platforms), problem: it won't paste.
4. Or right-click on any of the input fields: Paste in the context menu is disabled (grayed out)

### Expected behavior
Paste should work normally. Not only for convenience, also for security (when using a password manager).

### Screenshots
![Screenshot](https://i.imgur.com/3vmgV3U.png)

### System:
- Nheko version: 0.7.2
- Installation method: `brew install --cask nheko`
- Operating System: macOS 10.15.6 Catalina
- Qt version: n/a
- C++ compiler: n/a
- Desktop Environment: n/a

**Comment by Rogier-E** [comment]
Update - I noticed this only occurs for the 'Matrix ID' field if the clipboard contents does not contain a valid Matrix ID.

For password and device name, paste does work, however the item is still grayed out in the context menu.

**Comment by LorenDB** [comment]
I tested this on Linux and both `Ctrl-V` and selecting "Paste" from the context menu work in all fields.

Interestingly enough, on my context menus "Paste" is the only _active_ item (instead of the only inactive item on your system).

**Comment by LorenDB** [comment]
I should mention that nheko 0.8.0 was just released today. When the homebrew cask for nheko gets updated, your issue very possibly will be fixed.

**Comment by deepbluev7** [comment]
With our validation changes, this should be fixed now.
