### ISSUE TITLE
Upgrade from 0.7.2 to 0.8.0 break current user

### ISSUE THREAD

**Issue by nico202** [Nheko-Reborn/nheko#390]
### Describe the bug
When running nheko 0.8.0 after 0.7.2, nheko fails to start with:
```QVariant::load: unknown user type with name UserSettings::Presence. (:0, )```

### To Reproduce
1. Run nheko 0.7.2
2. Login
3. Close nheko 0.7.2
4. Run nheko 0.8.0
4. Does not start, throwing error

```
[2021-01-20 13:29:38.429] [qml] [warning] QVariant::load: unknown user type with name UserSettings::Presence. (:0, )
[2021-01-20 13:29:38.673] [ui] [info] WebRTC: initialised GStreamer 1.18.1
[2021-01-20 13:29:38.673] [ui] [error] WebRTC: failed to start device monitor
Aborted
```

If running nheko 0.8.0 with HOME set to /tmp, nheko starts fine (but the user must log in again)

**Comment by deepbluev7** [comment]
The above error message should not cause Nheko to fail to start, so something else has to be going on. Can you create a backtrace for me?

**Comment by deepbluev7** [comment]
I tested the upgrade from 0.7.2 to 0.8.0 multiple times on multiple systems now and can't reproduce it. Maybe it has something to do with the WebRTC error?

**Comment by nico202** [comment]
Indeed it's segfaulting, but sometimes it does start.  I'm attaching gdb log

[gdb.txt](https://github.com/Nheko-Reborn/nheko/files/5842761/gdb.txt)

**Comment by trilene** [comment]
Is the crash on Arch? There was some GStreamer-related weirdness only seen with Arch's packaged 1.18.1 binaries, albeit you had to start a voice call to see it.

**Comment by deepbluev7** [comment]
@trilene Looks like guix to me.

**Comment by deepbluev7** [comment]
Can you try, if that still happens with 1.18.2 or 1.18.3?

**Comment by nico202** [comment]
I get the same behaviour both without gstreamer and with gstreamer 1.18.3, here's the bt without gstreamer
[gdb.txt](https://github.com/Nheko-Reborn/nheko/files/5843089/gdb.txt)

**Comment by deepbluev7** [comment]
Hm, I don't understand the bt at all, it seems to crash somewhere when creating Qml stuff. You could maybe try toggling the COMPILE_QML option on during compile time and see, if that improves things. Otherwise I'm a bit stumped.

**Comment by deepbluev7** [comment]
Another thing you can try is the QML_DISABLE_DISK_CACHE=1 environment variable.

**Comment by nico202** [comment]
COMPILE_QML seems to be working (started 20 times in a row without segfault, both with and without gstreamer).
Whad do this imply (I'm having an hard time finding documentation for it)

Thanks!

**Comment by deepbluev7** [comment]
It means that the qml disk cache is corrupted/mismatches. I think that issue is fixed with Qt 5.15, but can also be fixed by removing the `~/.cache/nheko/nheko/qmlcache/` folder.

**Comment by deepbluev7** [comment]
We should probably document that somewhere.

**Comment by nico202** [comment]
Stupid me, it's [here](https://github.com/Nheko-Reborn/nheko/blob/a9faecea47a87a813450d110fcfd35fea8d91efa/CMakeLists.txt#L7).
Well, re-compiling it seems the best solution, since when qt changes, the package is always rebuilt.

Closing this, hopefully I'll be able to submit the package upgrade to guix before tomorrow.

Thanks again!

**Comment by deepbluev7** [comment]
Thank you for packaging!

**Comment by deepbluev7** [comment]
Also, the recompilation requirement only applies on Qt < 5.15
