### ISSUE TITLE
Unbundle SingleApplication and blurhash

### ISSUE THREAD

**Issue by deepbluev7** [Nheko-Reborn/nheko#391]
Distros are weird, so they prefer every single file from a different Repo to be looked up as a dependency, if possible. We should do that, if we can.

**Additional context**
https://github.com/Nheko-Reborn/blurhash/issues/1

**Comment by xvitaly** [comment]
[cpp-httplib](https://github.com/yhirose/cpp-httplib) should be unbundled too.

**Comment by LorenDB** [comment]
cpp-httplib was unbundled with #1371

**Comment by LorenDB** [comment]
As SingleApplication is not really able to be bundled, I'm closing this.
