### ISSUE TITLE
Read receipts dialog is not touch-scrollable

### ISSUE THREAD

**Issue by LorenDB** [Nheko-Reborn/nheko#397]
### Describe the bug
The read receipts dialog cannot be scrolled by touch. This is likely due to the fact the this dialog is not written in QML.

### To Reproduce
1. Open a read receipts dialog for a message with a lot of read receipts (enough that the read receipts window doesn't display them all).
2. Try scrolling with a touch screen.

### Expected behavior
The dialog should scroll.

### System:

- Nheko version: 0.8.0-a6717007 (likely any version will suffice)
- Installation method: local build
- Operating System: Linux
- Qt version: 5.12.8
- C++ compiler: not sure, either clang or gcc
- Desktop Environment: Plasma 5.18.5

**Comment by deepbluev7** [comment]
You can also fix that by using a QScroller. Alternatively just porting the dialog to Qml may be a good idea anyway.
