### ISSUE TITLE
Pasting images from clipboard does not work on Windows (and presumably macOS)

### ISSUE THREAD

**Issue by redsky17** [Nheko-Reborn/nheko#399]
### Describe the bug
Take a screenshot (ie, win+shift+s or cmd+shift+4) and try to paste into nheko.  File Upload dialog shows up with no image preview (or sometimes, the preview *does* appear).  If you upload the image, it's a zero-length file.  This is because the MIME data Qt sees does not contain image data.  I think it might be due to the fact that Qt picks BS MIME types for Windows and macOS.  See here for more information on Qt mime types: https://doc.qt.io/qt-5/qmimedata.html#platform-specific-mime-types

### System:

- Nheko version: 
- Installation method: 
- Operating System:
- Qt version: 
- C++ compiler: 
- Desktop Environment:

**Comment by LoganDark** [comment]
Crashes on macOS

**Comment by redsky17** [comment]
> Instantly crashes on macOS - that is, the application just closes when you press Cmd+V

I fixed the crashing issue a while back without actually fixing the pasting issue itself.  Please make sure you're on an up-to-date build.  If it still crashes on a newer build, please let me know.

**Comment by LoganDark** [comment]
> > Instantly crashes on macOS - that is, the application just closes when you press Cmd+V
> 
> I fixed the crashing issue a while back without actually fixing the pasting issue itself. Please make sure you're on an up-to-date build. If it still crashes on a newer build, please let me know.

I installed it via Homebrew Cask a couple days ago. Is that build outdated?

**Comment by redsky17** [comment]
It looks like the cask was updated 5 days ago: https://github.com/Homebrew/homebrew-cask/pull/98456

You can verify which version you're running by looking in the bottom left corner of the settings page

**Comment by LoganDark** [comment]
It says: `0.7.2-887ad25 | Darwin`, so... https://github.com/Nheko-Reborn/nheko/commit/887ad25

Guess it's time for a `brew update`.

**Comment by LoganDark** [comment]
Right, guess I was stupid to think that a super out-of-date version of Homebrew would have new releases. I have confirmed that pasting does nothing, which is an improvement over instantly crashing.

I shall now await a fix for this issue normally. :P

**Comment by absorber** [comment]
Here (on Ubuntu 18.04 and amd64 flatpak nightlies of nheko), I have observed the following:

When you paste an image, the preview should contain that image, if not, try exiting out of the preview and pasting again until it does. When the preview contains the image, it can be successfully sent in the message.

**Comment by Thulinma** [comment]
I do believe this one was fixed by #736 😁
Untested on MacOS, but all types of image pasting I tested now work on Windows, at least.
