### ISSUE TITLE
Windows client crashes if user named with non latin symbols

### ISSUE THREAD

**Issue by redsky17** [Nheko-Reborn/nheko#4]
_From @nihirash on October 8, 2018 19:45_

### System:

- Nheko version: nheko-v0.6.2
- Installation method: official installer 
- System: Win 10

### Actual behavior

Crashes on start 

### Expected behavior

Runs correctly

### Steps to reproduce

Just use username with non latin symbols. For example "Обычный пользователь"

### Logs

Doesn't created. Crashed on trying to create file. 

_Copied from original issue: mujx/nheko#459_

**Comment by redsky17** [comment]
_From @mujx on October 9, 2018 0:20_

I can't reproduce. Does this also happen in v0.6.1?

**Comment by redsky17** [comment]
_From @nihirash on October 9, 2018 15:5_

I'll try to record video  how I get this bug today.

**Comment by redsky17** [comment]
_From @nihirash on October 10, 2018 18:29_

0.6.2 start - can't create log file
https://giphy.com/gifs/X6aDHBcSYyiFdSN4cL

**Comment by redsky17** [comment]
_From @nihirash on October 10, 2018 18:33_

Version 0.6.1 have same issue

**Comment by redsky17** [comment]
_From @mujx on October 10, 2018 18:56_

@nihirash Could you paste the output of the console?

**Comment by redsky17** [comment]
_From @nihirash on October 10, 2018 20:16_

```
Log initialization failed: Failed opening file C:/Users/╨б╨░╤И╨░ ╨╕ ╨в╨░╨╜╤П/AppData/Local/nheko/nheko/cache/nheko.log for writing: No such file or directory
```

**Comment by nihirash** [comment]
Thank you for moving issue here!

**Comment by deepbluev7** [comment]
Can this still be reproduced?

**Comment by nihirash** [comment]
I haven't access to Windows machine with Cyrillic user name. 
I can try check it a bit later.

**Comment by deepbluev7** [comment]
If you can reproduce it with the latest nightly, I'll see if I can fix it next week. Thank you!

**Comment by deepbluev7** [comment]
Please reopen this, if you can actually still reproduce it!
