### ISSUE TITLE
Highlight at-room notifications in the room timeline

### ISSUE THREAD

**Issue by Cadair** [Nheko-Reborn/nheko#400]
Unlike mentions of your nick, it's quite hard to scan back in the room timeline and see at-room notifications.

**Comment by deepbluev7** [comment]
Remind @redsky17 , that he wanted to work on notifications stuff ;p

**Comment by antoyo** [comment]
Unrelated to this issue, but @Cadair can you explain me how it's easy to find a mention of your nick?
I only see my nick as a link, so it's quite easy to miss.
Do you mean it will show a number next to the room name which represents the number of times you were highlighted?
Or is there a shortcut to jump to the last mention of your nick?
Thanks for the help.

**Comment by LorenDB** [comment]
Hmmm, what about putting a red dot or red `!` next to the timestamp?
