### ISSUE TITLE
no keys found for decryption however session key was imported

### ISSUE THREAD

**Issue by teletrail** [Nheko-Reborn/nheko#404]
hi, import  session keys does not unenxrypt chats, how to do this? using nheko compiled from git.
![Screenshot_20210123_150253](https://user-images.githubusercontent.com/27707208/105565527-1be92180-5d8c-11eb-88d0-39b09f317750.png)

thanks.

**Comment by deepbluev7** [comment]
Does that go away after a restart?

**Comment by teletrail** [comment]
oh sorry, yes, had to restart app twice. thanks for suggestion!

**Comment by deepbluev7** [comment]
Hm, you should only need to restart it once and I should finally fix that... But glad it worked for you!
