### ISSUE TITLE
F11/full screen settings not scrollable

### ISSUE THREAD

**Issue by mahdi1234** [Nheko-Reborn/nheko#407]
nheko 0.8.0, gentoo linux, LXQt

Normal window mode

- launch settings dialog

Both mouse wheel and up/down arrow keys can scroll the dialog.

- In main window hit F11 to get full screen mode
- go Settings dialog

Neither mouse wheel nor up/down works, impossible to scroll.

**Comment by deepbluev7** [comment]
I can not reproduce that on KDE, maybe it is DE related?

**Comment by mahdi1234** [comment]
Maybe, can you suggest some test to check whether it's DE related?

Note if I hit F11 after opened Settings, it works fine. To be able repro I need F11 mode before opening Settings dialog.

**Comment by deepbluev7** [comment]
I can only suggest to try a different DE or plain X, to check if it is DE related, but that may be some effort. I've tried both ways now, but it works either way.

**Comment by LorenDB** [comment]
@mahdi1234 Did you make sure that the settings page was focused (i.e. click in a blank spot on the settings page and see if the problem still persists)? I can't reproduce it either.

**Comment by mahdi1234** [comment]
@LorenDB Yes, tried clicking in, keyboard etc still the same behavior with 0.8.1, but since no one is able to repro I guess it's related to my DE/WM setup.

**Comment by deepbluev7** [comment]
We rewrote the whole settings page now, so this is either fixed or I have no idea how to fix it :D

**Comment by mahdi1234** [comment]
Cheers can scroll witn 0.9.2 (gentoo) now :) :+1:

**Comment by deepbluev7** [comment]
Thank you for verifying <3
