### ISSUE TITLE
Emoji widget lacks visual feedback for user

### ISSUE THREAD

**Issue by vtronko** [Nheko-Reborn/nheko#41]
It would be nice to see background for hovered emoji, as well as provide some feedback when it is actually inserted into text (e.g. blink animation in background).
Currently emoji widget looks dull enough.

**Comment by deepbluev7** [comment]
I think i partially addressed that in 78ed78c, but I don't have a good idea of how to provide feedback on insertion. Should that blink the emoji in the message field, a ripple animation in the emoji picker or just blink the text field?

**Comment by deepbluev7** [comment]
Since none complained about my changes, that provide more feedback now, I will close this now ;-)
