### ISSUE TITLE
FR: option to hide user events in room chat

### ISSUE THREAD

**Issue by mahdi1234** [Nheko-Reborn/nheko#411]
This is how room with many user events look like, not much of actual messages.

![nheko_events](https://user-images.githubusercontent.com/1097047/105643109-e7f22700-5e85-11eb-8da3-65e1e421d3f2.png)

Schildichat implemented filtering those and it looks way better imo (I don't have desktop version, taken from my phone)

![schildi_events](https://user-images.githubusercontent.com/1097047/105643128-06582280-5e86-11eb-8062-540ecdc694cc.jpg)

Would be great to be able hide all those.

**Comment by legoktm** [comment]
This would be really handy in rooms that are bridged to IRC channels where people tend to join/leave channels much more frequently. I like how Element handles it, it collapses them by default but lets you expand them.

![element1](https://user-images.githubusercontent.com/81392/122705112-ed238a00-d209-11eb-82ad-cf4c3dcc2d28.jpg)

![element2](https://user-images.githubusercontent.com/81392/122705145-fc0a3c80-d209-11eb-9418-87076a2b4228.jpg)

**Comment by mahdi1234** [comment]
> but it would be trivial to add a button for that in the usersettings in the future, if someone wants to.

Then please add it or do you prefer new issue for it @deepbluev7 ?

**Comment by deepbluev7** [comment]
I prefer someone implements it :3 

I'll consider adding a button once this is somewhat tested, because it might break things.
