### ISSUE TITLE
Double click a message to reply to it.

### ISSUE THREAD

**Issue by Bubu** [Nheko-Reborn/nheko#414]
Telegram-desktop has had this for ages and I keep trying to do that in Nheko. (Which I guess is a sign of Nheko being simialr enough to Telegram-desktop by now to trigger my muscle memory :D)

**Comment by Bubu** [comment]
(I don't know if this fits Nehkos UX ideas but I do find it quite a handy feature.)

**Comment by deepbluev7** [comment]
This may need to wait until we can require Qt 5.15 (or at least 5.12), since otherwise handling overlapping input events is a pain.
