### ISSUE TITLE
Connection to server through VPN is very slow to nonexistent

### ISSUE THREAD

**Issue by Samonitari** [Nheko-Reborn/nheko#415]
### Describe the bug

Home office work forces me to run Cisco Anyconnect VPN client at home.
If I connect to a VPN server with it, it takes Nheko up to minutes to sync.
The busy animation stays for minutes, the messages are sent with the same delay.

I don't know how to get more info, as I cannot see anything out of ordinary in debug output, only it progresses much slower.
Spectral works just as limited-but-fast as without the VPN running, so I am inclined like to say that the source of error is indeed Nheko.

### To Reproduce
1. Use VPN
2. Start Nheko

### Expected behavior
I'd expect the same great experience with VPN on the PC as without VPN.

### System:

- Nheko version: 0.8.0 
- Installation method: rpm from https://download.opensuse.org/repositories/network:/messaging:/matrix/openSUSE_Factory/
- Operating System: openSUSE Tumbleweed
- Desktop Environment: KDE

### Logs
```
[2021-01-25 14:37:46.137] [ui] [debug] Send: szervasz
[2021-01-25 14:37:46.140] [crypto] [debug] next message_index 13
[2021-01-25 14:37:46.141] [db] [debug] saving '{"event_id":"mM9wDgGs9dtcD5NxdGoXSQEhzw2zgx9Fy"}'
[2021-01-25 14:37:46.142] [ui] [debug] begin insert from 0 to 0
[2021-01-25 14:37:48.067] [net] [info] TURN server(s) retrieved from homeserver:
[2021-01-25 14:37:48.068] [net] [info] username: 1611585468:@samonitari:meszaros-szegi.cloud
[2021-01-25 14:37:48.068] [net] [info] ttl: 3600 seconds
...
[2021-01-25 14:39:57.358] [ui] [debug] sent mM9wDgGs9dtcD5NxdGoXSQEhzw2zgx9Fy
```

**Comment by deepbluev7** [comment]
That's curious, maybe it's an issue with Boost? Need to investigate that at some point.

**Comment by EchedeyLR** [comment]
I have a similar issue without VPN just sensing messages in my normal connection.

**Comment by EchedeyLR** [comment]
@deepbluev7 would it be possible to push new micro-versions of nheko every time an important bug like this is fixed?

**Comment by deepbluev7** [comment]
This isn't a micro bugfix. We changed the complete networking backend, so we may have introduced a lot of new bugs. We rewrote a LOT of stuff in the backend. If you want to try it, using the flatpak nightlies is fairly safe, but there will be bugs to sort out before a release. We sadly don't have the bandwidth to release often, because of all the testing that goes into a release. We'd rather work on bug fixes than doing all the release management.

**Comment by EchedeyLR** [comment]
On 31 July 2021 10:19:21 WEST, "DeepBlueV7.X" ***@***.***> wrote:
>This isn't a micro bugfix. We changed the complete networking backend, so we may have introduced a lot of new bugs. We rewrote a LOT of stuff in the backend. If you want to try it, using the flatpak nightlies is fairly safe, but there will be bugs to sort out before a release. We sadly don't have the bandwidth to release often, because of all the testing that goes into a release. We'd rather work on bug fixes than doing all the release management.
>

Thank you for the explanation.

I understand now.
-- 
Saludos,
Echedey, López Romero
