### ISSUE TITLE
Inserting a mention deletes a space before the inserted text

### ISSUE THREAD

**Issue by Cadair** [Nheko-Reborn/nheko#421]
### Describe the bug

The autocomplete removes a space

### To Reproduce

1. Type "Hello <tab>"
2. autocomplete something
3. observe "Hello[nick]..." in the input field

### Expected behavior

No space is deleted

### System:

- Nheko version: 0.8.0-6313ecb7

**Comment by deepbluev7** [comment]
Hm, I can reproduce that only with mentions triggered via <tab> not triggered by @?

**Comment by Cadair** [comment]
oh yes you are correct, only by mashing tab without the @
