### ISSUE TITLE
Inserting a mention sends a markdown formatted URL in plain text body

### ISSUE THREAD

**Issue by Cadair** [Nheko-Reborn/nheko#422]
### Describe the bug

A mention in plain text should just be the nick, not a markdown formatted pill.

See https://matrix.org/docs/spec/client_server/r0.6.1#user-room-and-group-mentions and https://github.com/vector-im/element-android/issues/1506 for a collection of reasons why this is a bad idea.

**Comment by deepbluev7** [comment]
I agree, it is not really good to leak that into rooms. On the other hand it is kinda nice, that you can distinguish between mxids that way even in plain text messages. I think we should just strip it out though.

**Comment by LorenDB** [comment]
Also, it could be a good idea to check if the user is using the `/plain` or `/md` overrides and format accordingly.

**Comment by deepbluev7** [comment]
Well, it currently only checks the setting, but it wasn't updated, when those commands were added.
