### ISSUE TITLE
Unwanted occuring of emoji completer popup in message area

### ISSUE THREAD

**Issue by kotelnik** [Nheko-Reborn/nheko#425]
### Describe the bug
When writing a message and typing colon `:` a popup menu shows up with bunch of flag/keycap items. I don't want that, is there a way to disable this behaviour? :)

This started with nheko version 0.8.0.

It has also the unwanted consequence that when mouse pointer happen to be in the popup menu area and I type `:)` and then enter to send the message -> it will replace my text smile with one of the flag from menu (instead of sending the message).

### To Reproduce
1. Start writing a message to someone
2. Type colon `:`
3. Observe - popup menu occurs

### Expected behavior
There is a way to disable this popup menu.

### Screenshots
![Screenshot_20210127_180502_flagPopup](https://user-images.githubusercontent.com/1174734/106029184-be730e80-60c4-11eb-819b-51e12622f473.png)

### System:

- Nheko version: 0.8.0
- Profile used: (don't know what it is, probably default)
- Installation method: Gentoo packages - guru repository
- Operating System: Gentoo Linux
- Qt version: 5.15.2
- C++ compiler: gcc 10.2.0
- Desktop Environment: Plasma (Wayland)

**Comment by kotelnik** [comment]
Other then that I'd like to say thanks for this great program! Awesome work, love it, really, thanks!

**Comment by deepbluev7** [comment]
That is actually an emoji completer allowing you to enter unicode emoji. It currently is a bit too agressive, since it opens even when no emoji is matched. You can test it by typing :heart for example and it should allow you to enter a heart emoji (like here on github too)

**Comment by kotelnik** [comment]
Understood, thanks!

Although I appreciate the possibility to enter unicode emojis, I still personally stick with old-school text smiles like `:)`. Therefore I'd like if nheko team would consider an off switch in settings or at least stop showing menu when not matched / after a space is typed.

I can make a pull request if you like :)

**Comment by deepbluev7** [comment]
Yeah, we want to fix that somehow. Most likely we just make it autoclose on space.

**Comment by deepbluev7** [comment]
d1280af2e4c704147a36da510faa0a994d3159c7 makes the completer autoclose, when you press space and there is no completion match.

**Comment by deepbluev7** [comment]
Now the completer also doesn't select stuff, if you don't use your mouse. I'll consider this fixed because of that. You still can't disable the popup, but it should not prevent normal text emojis anymore.

**Comment by kotelnik** [comment]
That was fast! Thanks!

The mouse fix works. But the space still does not close the popup. Try typing `:) ` or even `: `.

**Comment by deepbluev7** [comment]
That's because there are matches in that case. It won't close in that case, since some emoji currently need a space to access them, like `:black cat:`. If there are no matches, it closes on space.
