### ISSUE TITLE
Allow access to user profile from members list

### ISSUE THREAD

**Issue by Cadair** [Nheko-Reborn/nheko#427]
**Is your feature request related to a problem? Please describe.**

There seems to be no way to get from the members list for a room to a user profile to perform actions like kick.

**Describe the solution you'd like**

Clicking on a member in the list should open the profile panel like clicking an avatar in the timeline does.

**Comment by deepbluev7** [comment]
May also rewrite the memberlist in qml at that point.

**Comment by LorenDB** [comment]
I've been considering rewriting the memberlist in qml anyway--might as well let me take care of this.

**Comment by deepbluev7** [comment]
Done
