### ISSUE TITLE
Add some indication that you are offline if the HS can't be reached

### ISSUE THREAD

**Issue by Cadair** [Nheko-Reborn/nheko#428]
**Is your feature request related to a problem? Please describe.**

My wifi dropped and I noticed there was no indication I was offline, so not getting new messages and any I sent wouldn't work. The sending wait symbol isn't that obvious that a message is stuck, turning it red or some other larger indicator that a send has *failed* rather than the request is still pending would also be nice.

**Comment by Cadair** [comment]
Interestingly it seems the whole room got wedged after coming back online and now none of the messages in that room will send, new or pending.

**Comment by LorenDB** [comment]
At one point (probably before @deepbluev7 QML'ed the InputBar), Nheko would not let you create or send messages. This seems to have been lost in the QMLing.

> Interestingly it seems the whole room got wedged after coming back online and now none of the messages in that room will send, new or pending.

I can verify that Nheko doesn't do very well at sending messages that were pending while offline.

**Comment by Cadair** [comment]
They did eventually send in one big lump, giving the person on the other end something to think about :rofl:
