### ISSUE TITLE
Add an autocompleter for slash commands

### ISSUE THREAD

**Issue by Cadair** [Nheko-Reborn/nheko#429]
**Is your feature request related to a problem? Please describe.**

I don't know what all the available slash commands are, it would be great to have an autocompleter in the same way as for emoji or members. Bonus points for a description of the command like Element does in theirs.

**Comment by deepbluev7** [comment]
Yeah, that is planned, but in the mean time, they are documented here: https://github.com/Nheko-Reborn/nheko/wiki/Commands
