### ISSUE TITLE
Dark theme highlight colour has low contrast in room search popup

### ISSUE THREAD

**Issue by Cadair** [Nheko-Reborn/nheko#430]
### To Reproduce
1. Enable dark theme
1. Open search bar
1. Observe that it is hard to see which room is selected.

### Expected behavior

The highlights in the other parts of the app are more noticeable, maybe due to the transparency in the search popup?

### Screenshots

![image](https://user-images.githubusercontent.com/1391051/106150848-a9a18400-6173-11eb-9c09-66f2e3efebaa.png)

**Comment by capellavacancies** [comment]
gonna add this, dark theme on win10
![Senza nome](https://user-images.githubusercontent.com/58681964/106958891-41860b80-673a-11eb-8c39-0b5412a83451.png)

**Comment by deepbluev7** [comment]
Should be fixed by #493
