### ISSUE TITLE
Add a quick reactions / most recently used reactions section to the emoji picker

### ISSUE THREAD

**Issue by Cadair** [Nheko-Reborn/nheko#435]
It would be nice to have a section of the emoji picker which is you top N most recently used emoji. This would make it faster to react to messages with your favourite emoji.

**Comment by LorenDB** [comment]
Indeed. This is actually something that I was thinking about suggesting.

**Comment by LorenDB** [comment]
I should link #604 here.

**Comment by deepbluev7** [comment]
They are not at the top of the right click menu, but in the hover menu. The right click menu is very full atm and adding them there felt wrong.
