### ISSUE TITLE
nheko doesn't start as sudo user

### ISSUE THREAD

**Issue by z0rti** [Nheko-Reborn/nheko#436]
using v0.8.1 on ubuntu 20.04

[logged in as user1]

user1@ubuntu $ ./nheko-v0.8.1-x86_64.AppImage
[... works ...]

user1@ubuntu $ sudo -i -u user2

user2@ubuntu $ ./nheko-v0.8.1-x86_64.AppImage
[nothing]

the nheko v0.6.4 installed with 'apt install nheko' does work as both users.

**Comment by deepbluev7** [comment]
Are your environment variables set up correctly in the latter case? Could also be that the other user is simply not allowed access to the Xserver or so. This is not really something we are trying to support, what do you want to achieve?

**Comment by z0rti** [comment]
As i said nheko from the Ubuntu repo does work as user2 (but it's old)
I just want to run it as other user, to connect with a different matrix user id.

**Comment by deepbluev7** [comment]
You can just pass --profile=secondUser as a commandline argument now. The other one probably doesn't start, as Nheko is running already and sudo doesn't do a clean login.

**Comment by z0rti** [comment]
OK that worked, thank! Nice feature :-)
(after adding a second user with '--profile=user2' starting without '--profile' doesn't load the first profile workaround: leave it empty '--profile=' )

but still: why doesn't it work with sudo, nheko isn't running at all according to htop and ps.
everything else works with sudo, like firefox, even games and video player.

**Comment by deepbluev7** [comment]
Nheko implements some shared memory stuff and such to prevent launching it twice by accident and allow it to open matrix links. It could be that that is interfering, since sudo is not a clean login and keeps some environment stuff and such.

**Comment by z0rti** [comment]
Got it!
I found out that after exiting nheko for user1 there is still /tmp/appimage-*-ld-linux-x86-64.so.2 with user1 and 770 permissions
when i remove that first, nheko works as user2 with sudo as expected.
So it's a little clean up bug i guess?

**Comment by deepbluev7** [comment]
That sounds more like an AppImage issue, not something specific to Nheko?

**Comment by LorenDB** [comment]
> OK that worked, thank! Nice feature :-)
> (after adding a second user with '--profile=user2' starting without '--profile' doesn't load the first profile workaround: leave it empty '--profile=' )
> 
> but still: why doesn't it work with sudo, nheko isn't running at all according to htop and ps.
> everything else works with sudo, like firefox, even games and video player.
> 
> 

To load the default profile, just use `--profile=default`

**Comment by deepbluev7** [comment]
Closing.This is not something we need to solve, it is just a limitation/quirk of appimages as a whole.
