### ISSUE TITLE
some combined emojis render as separate emojis

### ISSUE THREAD

**Issue by Bubu** [Nheko-Reborn/nheko#439]
### Describe the bug
👩‍❤️‍👨 renders as 👩‍❤️👨 in nheko and as one emoji in element. This should be supported by the emoji font I use (twemoji in the latest revision)

Another example:

![image](https://user-images.githubusercontent.com/105185/106519180-35504300-64db-11eb-9c15-bc9d8b9c0184.png)

**Comment by deepbluev7** [comment]
I think this is https://bugreports.qt.io/browse/QTBUG-97401

I actually made this worse just now by switching to the fully qualified versions of the emojis in the picker...
