### ISSUE TITLE
Suggestion: don't share message inputs between chat pages

### ISSUE THREAD

**Issue by vtronko** [Nheko-Reborn/nheko#44]
Wouldn't it be better to clean up text in text input after switch to other channel? Makes no logic to implicitly share textbox contents between different rooms.
This, or even saving state per room, would be better, wouldn't it?
Thinking about this in context of replies implementation, AFAIK you can't reply with referenced message into another channel, so this should be prevented in UI. Doing so at least for plain messages would be a good start.

**Comment by deepbluev7** [comment]
This is done now.
