### ISSUE TITLE
Sync Error When Logging Into Dendrite Server

### ISSUE THREAD

**Issue by Rayqan** [Nheko-Reborn/nheko#447]
### System:
Nheko: 8.1 Compiled From AUR Package
OS: Arch

On attempting to login to my account on my dendrite server I get the error: `[net] [info] trying initial sync
[net] [error] initial sync error: -1775303440 M_UNRECOGNIZED`. Which just loops until nheko is killed. It seems that nheko works perfectly fine when using other synapse servers so I would guess that it is some sort of interoperability issue between nheko and dendrite.

**Comment by deepbluev7** [comment]
Right, seems like our recent changes require the events key inside the presence key of the sync response by accident and dendrite send a presence key without events. Fixed in https://github.com/Nheko-Reborn/mtxclient/commit/f788961494069606ddd5321bb55150ada32a8d12 .

**Comment by sseneca** [comment]
I just ran into this issue, would it be possible to have a bug fix release of `mtxclient`? Because as it stands Nheko doesn't work for me

**Comment by deepbluev7** [comment]
There will be a release, once we figure out the deployment issues on Windows currently, but I only have limited time to work on that atm. Until then the current nightlies should work.
