### ISSUE TITLE
Cant Register Accounts On Dendrite (Device Key Error)

### ISSUE THREAD

**Issue by Rayqan** [Nheko-Reborn/nheko#448]
### System:

Nheko: Compiled From Latest Commit As Of Now
OS: Arch

There seems to be an issue with differing device keys when attempting to use nheko to register on dendrite. The specific error is: `[crypto] [critical] failed to upload one time keys:  400`. I previously brought it up on the dendrite repo [here](https://github.com/matrix-org/dendrite/issues/1744) and it was determined to a nheko issue.

Btw thanks for the quick fix on the other issue, it works great.

**Comment by deepbluev7** [comment]
FTR, I did register using Nheko on dendrite.matrix.org a few weeks ago. Don't have much time to look into this in the near future though.

**Comment by Rayqan** [comment]
Just tested at dendrite.matrix.org and looks like its the same error.

**Comment by Rayqan** [comment]
But interestingly enough it does look like the account is still created as I am able to login manually to the newly created account after I'm kicked back to the main login menu.

**Comment by deepbluev7** [comment]
Yeah, it is probably some issue in the handover from registration to login.

**Comment by deepbluev7** [comment]
Fixed in #494 :3
