### ISSUE TITLE
Using the /react in a reply does not close the reply

### ISSUE THREAD

**Issue by Cadair** [Nheko-Reborn/nheko#449]
### Describe the bug

After sending a text reaction with /react in a reply context the reply is not closed, meaning without action your next message replies to the message.

### To Reproduce
1. Click to reply to a message
2. Type /react something
3. Send the message
4. Observe how the message editor is still replying to the message.

**Comment by deepbluev7** [comment]
This is intentional. You often want to do multiple reactions in a row. Having to got back to the appropriate message is annoying.

**Comment by Cadair** [comment]
Yeah I can see that, this just caught me out though as I am used to sending a reply and the context closing. If you want to close this as "feature not a bug" that's fine by me lol

**Comment by deepbluev7** [comment]
Yeah, it is not necessarily consistent, but that's because different behaviours are ideal in those different contexts imo. So yeah, gonna close this. Thanks for letting me document the thought process behind it! :3
