### ISSUE TITLE
Can't see room's full topic

### ISSUE THREAD

**Issue by wantija** [Nheko-Reborn/nheko#453]
### Describe the bug
Cannot see full topic of room you are in from the top bar, or in room settings.

### To Reproduce
1. Go to a room you have joined
2. Click on the three dots in the top right
3. Click on 'Setting'
4. Cannot see room's topic, clients such as Element allow this

### Expected behavior
Check room's settings and see the topic

### Screenshots
![nheko_no_topic](https://user-images.githubusercontent.com/13387832/106937403-b54cf780-66eb-11eb-972f-9ec57c3545d2.png)
![element_room_topic](https://user-images.githubusercontent.com/13387832/106937419-b9791500-66eb-11eb-91ba-e4616c60e37c.png)

### System:

- Nheko version: 0.8.1-50e2b561 | Linux
- Installation method: nheko-git from AUR
- Operating System: Arch Linux
- Desktop Environment: KDE Plasma 5.20

**Comment by Jedi18** [comment]
@deepbluev7 This has been implemented in PR #474 , so you can close it :D

**Comment by deepbluev7** [comment]
Yeah, I noticed that yesterday evening too :3
