### ISSUE TITLE
Voice Chat Does Not Detect Mic (WebRTC Error)

### ISSUE THREAD

**Issue by p0da** [Nheko-Reborn/nheko#454]
Nheko: Latest
OS: Arch

When Launching nheko it the first messages that are logged are:
`WebRTC: initialised GStreamer 1.18.3
 WebRTC: failed to start device monitor`

And whenever a voice call is attempted the UI popup "No Microphones Found" appears. I have also ensured that gst-plugins-base, gst-plugins-good, and gst-plugins-bad are installed and updated.

**Comment by trilene** [comment]
I've only seen this when pulseaudio isn't running. You can test against GStreamer directly by calling gst-device-monitor-1.0 at the command line. Nheko effectively makes the same call.

**Comment by Rayqan** [comment]
Yep its a pulseaudio issue as Im runnning an alsa only audio setup. Looks like nheko works fine with apulse. Would you happen to know of a way to get gstreamer to play to the alsasink by default?

**Comment by trilene** [comment]
I don't sorry. I used to use apulse - I caved to pulseaudio when firefox mandated it. Now we have pipewire, which must be music to your ears (though not via pulseaudio, obviously).

**Comment by rnhmjoj** [comment]
It's a gstreamer bug: I opened an issue but haven't receive a reply, yet.
https://gitlab.freedesktop.org/gstreamer/gstreamer/-/issues/667

A workaround is to disable the pulse support in gst-plugins-good. Unfortunately, I don't think there is any way to disable the plugin at runtime.

**Comment by rnhmjoj** [comment]
Fixed in gstreamer 1.19.3.
