### ISSUE TITLE
Buttons on home screen are huge

### ISSUE THREAD

**Issue by vachan-maker** [Nheko-Reborn/nheko#456]
# Issue
The buttons on  the main screen or home screen are huge when compared to the rest of the elements. There are other buttons as well which are large.
## Screenshot
![Capture](https://user-images.githubusercontent.com/65799568/107028964-45ff0280-67d4-11eb-9e33-f88387ed6243.PNG)

**Comment by deepbluev7** [comment]
That's intentional, since those buttons are the only thing there. One could debate the design, but this is not a bug :D
