### ISSUE TITLE
Paste images and send it as attachments

### ISSUE THREAD

**Issue by vachan-maker** [Nheko-Reborn/nheko#457]
**Is your feature request related to a problem? Please describe.**
Currently, I cannot paste images or gifs and send it as an attachment. Element has this feature and it is very convenient.

**Describe the solution you'd like**
Copy an image
Paste the image and send

**Describe alternatives you've considered**
Using the paper clip or attachment button

**Additional context**
Element desktop app has this feature,

**Comment by deepbluev7** [comment]
You can totally paste images, I do it all the time. What system do you use and which version?

**Comment by vachan-maker** [comment]
> 
> 
> You can totally paste images, I do it all the time. What system do you use and which version?

I am so stupid, you are right. It does work. Don't know why it didn't work earlier.
Thanks very much. :-)
Closing this issue
