### ISSUE TITLE
[Wishlist] Tagging users

### ISSUE THREAD

**Issue by YamiYukiSenpai** [Nheko-Reborn/nheko#46]
Riot currently does it, but if I try with Nheko, it simply just copies their username.

**Comment by ptman** [comment]
You mean "mentioning"?

**Comment by deepbluev7** [comment]
@ptman  Yeah, that's what's meant by this feature request.

**Comment by ptman** [comment]
This seems to be partially implemented? #14 is related

**Comment by deepbluev7** [comment]
This is done, although it does not look super nice yet and may be confusing to some users. Should improve a lot, when we use newer Qt though.
