### ISSUE TITLE
Animated gifs in the timeline are not animated

### ISSUE THREAD

**Issue by Cadair** [Nheko-Reborn/nheko#461]
### Describe the bug

See a gif in the timeline and see how it is a static unmoving muggle picture.

**Comment by LorenDB** [comment]
We're waiting on Qt to fix a bug that will let us do that.

**Comment by deepbluev7** [comment]
Alternatively, we could add workarounds, that bug will probably take years to fix.

**Comment by deepbluev7** [comment]
I think we should just work around the Qt issue for now, where we use an AnimatedImage after image was loaded, with a temporary filesystem path or so.
