### ISSUE TITLE
libolm.so.2: cannot open shared object file

### ISSUE THREAD

**Issue by qazip** [Nheko-Reborn/nheko#47]
### System:

- Nheko version: Latest in AUR
- Installation method: AUR
- Operating System: Arch

When trying to open nheko, I get the following error:

`/usr/bin/nheko: error while loading shared libraries: libolm.so.2: cannot open shared object file: No such file or directory`

Libolm got updated recently:
```
Name            : libolm
Version         : 3.0.0-1
```

**Comment by ptman** [comment]
IIRC you can symlink libolm.so.2 to libolm.so.3, since it's ABI compatible

**Comment by redsky17** [comment]
Yes, for now, the best approach is to do what Paul suggested.

**Comment by qazip** [comment]
Alright. `sudo ln -s /usr/lib/libolm.so.3 /usr/lib/libolm.so.2` fixed it.
