### ISSUE TITLE
Nheko doesn't show an error message when there is no internet

### ISSUE THREAD

**Issue by vachan-maker** [Nheko-Reborn/nheko#472]
When there is no internet, Nheko doesn't show any error message. It would be great if Nheko could display one when the connection drops.

Also, some messages don't send after internet has been restored.
Example:
If I send a message when the connection goes down, the message still doesn't deliver even when the internet comes back.

Thanks

**Comment by LorenDB** [comment]
> When there is no internet, Nheko doesn't show any error message. It would be great if Nheko could display one when the connection drops.
This used to be a thing, but it disappeared somehow when @deepbluev7 ported the message input to QML.

**Comment by LorenDB** [comment]
Well, something is happening on this finally... I got bored :D
![clipboard](https://user-images.githubusercontent.com/55629213/150901369-5d45b1c9-8451-43f6-8dc8-bc8c1f3fbe9b.png)

**Comment by vachan-maker** [comment]
@LorenDB That is cool. Maybe you can tone down the red color a little bit? Its too bright

**Comment by LorenDB** [comment]
Sure, I can work on that. I was just using some predefined theme colors for that, so there is definitely room for improvement.
