### ISSUE TITLE
Add a forward message button

### ISSUE THREAD

**Issue by Cadair** [Nheko-Reborn/nheko#473]
**Is your feature request related to a problem? Please describe.**

It is useful to be able to forward the contents of a message in one room to another room. I find this particularly useful for images, where you don't have to download and re-upload the image if it is sent into the new room with the same mxc url.

**Describe the solution you'd like**

Add a forward message button with roughly the same features as Element Web.

**Comment by deepbluev7** [comment]
If anyone implements this, remember that this needs to forward encryption keys for images too, maybe reupload them, if one room is encrypted, while the other isn't, send stuff encrypted with the right megolm session and maybe a few more caveats.
