### ISSUE TITLE
Alt-Up to select message to reply to should ignore redacted events

### ISSUE THREAD

**Issue by Cadair** [Nheko-Reborn/nheko#478]
### To Reproduce
1. Redact a message
2. Press Alt-Up
3. Observe how it suggests you reply to the redaction

### Expected behavior
The redacted message is ignored, as you probably don't want to reply to it, and if you do you can always click the reply button.

**Comment by deepbluev7** [comment]
So after some discussion, I'm going to close this as "Working as intended".

I don't really like having the inconsistency of needing the mouse to ask about why an event was redacted and I also think you should be able to reply to any event, including redacted and state events. If someone has a really good reason, why you would not want that, we can discuss that again. :3
