### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by vachan-maker** [Nheko-Reborn/nheko#481]
# Feature
Some sort of system which notifies the user when an update is available within the program.
One way of doing it (Saw some other applications doing this)
- Once the application has started, it will send a request to Github/Gitlab. It will check the current version with the version on Github Releases/Gitlab Releases via tags or something. If a new version is available, Nheko will automatically download the installer file and close itself - so that the update can install properly.
Don't know if what I wrote is 100% correct.

**Comment by vachan-maker** [comment]
Or some check for updates button which when clicked will take the user to the releases page.

**Comment by deepbluev7** [comment]
For which platform is that? Windows or macOS?

**Comment by vachan-maker** [comment]
> 
> 
> For which platform is that? Windows or macOS?

Windows

**Comment by deepbluev7** [comment]
I see, we should probably just provide msix instead.

**Comment by LorenDB** [comment]
A while back, the topic of updates came up in the nheko room. At that time, I suggested using either [QSimpleUpdater](https://github.com/alex-spataru/QSimpleUpdater) or [QtAutoUpdater](https://github.com/Skycoder42/QtAutoUpdater). If I recall correctly, @redsky17 was working on update stuff at the time.

**Comment by deepbluev7** [comment]
The msix now supports automatic updates when installed using the appinstaller file (currently only available for the nightlies, but the next release should also provide it for stable).
