### ISSUE TITLE
Can't Use Matrix.org Credentials

### ISSUE THREAD

**Issue by ibrokemypie** [Nheko-Reborn/nheko#487]
### Describe the bug
When trying to login with a matrix.org account, the password box is replaced with the SSO login button, which does not have an option to sign in with an existing matrix.org account

### To Reproduce
1. Open nehko
2. Click log in
3. Type @ibrokemypie:matrix.org in the Matrix ID field

### Expected behavior
Allow login with matrix.org credentials

### Screenshots
![image](https://user-images.githubusercontent.com/7827846/108618721-7c937900-7474-11eb-8eab-3f1b71e2274e.png)

### System:

- Nheko version:  0.8.1
- Profile used: 
- Installation method:  aur/nheko
- Operating System: arch linux
- Qt version: 5.15.2-5
- C++ compiler: gcc (GCC) 10.2.0
- Desktop Environment: i3/none

**Comment by deepbluev7** [comment]
That's because Matrix.org changed their setup and now offers SSO as well as password login. Nheko used to prefer SSO, if it is available. This is fixed in the current development version (i.e. when you use nheko-git from the AUR), but we didn't release a stable release with that yet. Alternatively you can enter your password first, then your userid and click the loginbutton with the mouse, I think, but that is just a workaround I heard people mention.

**Comment by ForNeVeR** [comment]
The workaround works (had to click that button quick!), but the situation is pretty confusing.

**Comment by teotikalki** [comment]
Matrix.org offering SSO as well as password login is NO reason for anything else to REMOVE the password login. I use matrix to avoid centralization and data silos and I avoid using all of the SSO providers for the same reason.
I used Riot for years before it became Element... just heard about Nheko and downloaded it today to try (AppImage on Debian) thinking 'native client in C sounds better than Electron/etc' but the inability to actually log in makes this dead in the water. :(

**Comment by deepbluev7** [comment]
@teotikalki We did not remove the login option, that the option gets hidden is a bug and we already fixed it, we just haven't managed to get a stable release with that fix out.

**Comment by ForNeVeR** [comment]
While bugs understandably happen even to the best of us, this (inability to log in for a big chunk of users) looks pretty critical. Could we have a bug fix released?

**Comment by deepbluev7** [comment]
We certainly are trying to, but we have some other critical issues to fix in the mean time, like the Windows build being completely broken right now, and have a lot of other stuff going on right now, which is why we sadly didn't have the time to do it yet.

**Comment by ForNeVeR** [comment]
Understood. Fingers crossed for you, guys.

**Comment by yisraeldov** [comment]
> The workaround works (had to click that button quick!), but the situation is pretty confusing.

The work around doesn't work for me.

**Comment by deepbluev7** [comment]
Well, the release that fixes this issue is currently in the second release candidate. We'll probably release it on Friday.

**Comment by yisraeldov** [comment]
> > The workaround works (had to click that button quick!), but the situation is pretty confusing.
> 
> The work around doesn't work for me.


Actually it did work after a few tries, don't know why it didn't at first.

**Comment by deepbluev7** [comment]
0.8.2 is out now :3

**Comment by Minoru** [comment]
This issue can be unpinned now, I guess ;)

**Comment by deepbluev7** [comment]
It could, but I'm leaving it pinned in case someone is using an old version. People often forget to look at closed issues and then open a new issue, even if it is already fixed. I will unpin this in a few months probably.
