### ISSUE TITLE
Choppy scrolling in timeline

### ISSUE THREAD

**Issue by big-caballito** [Nheko-Reborn/nheko#495]
### Describe the bug
When scrolling on the timeline, the timeline appears choppy like so [youtube](https://yewtu.be/watch?v=ItjNPGuhPhg) (fyi yewtu.be is invidious)

### To Reproduce
1. Open nheko
2. Click on 'a room'
3. Scroll down to see choppy scrolling

### Expected behavior
scrolling is as smooth as buttered silk

### Screenshots
[youtube](https://yewtu.be/watch?v=ItjNPGuhPhg)

### System:

- Nheko version: 0.8.1
- Profile used: default
- Installation method: AUR
- Operating System: Manjaro ARM
- Qt version: Qt 5.15.2
- C++ compiler: GNU g++
- Desktop Environment: i3

**Comment by deepbluev7** [comment]
It should be quite a bit smoother now with the latest changes, I hope.

**Comment by deepbluev7** [comment]
Your video looks like software rendering though, which is a GPU driver issue not a Nheko issue.
