### ISSUE TITLE
General UI Improvements

### ISSUE THREAD

**Issue by redsky17** [Nheko-Reborn/nheko#5]
These should get broken out into their own issues at some point.  Just keeping a running log of the things I encounter.

#### Notifications aren't cleared when room is read
Expected behavior is that notifications will be removed by the notification manager when the messages in question are actually read.  Currently, they stick around.  Even worse, they stick around after nheko has been closed.
#### Notifications missing user avatar and other display issues
Notifications currently have a large empty section where the user avatar should be.  Additionally, the formatting of the text itself does not do a good job of differentiating between the author and message contents themselves.

#### Link Text Not Controlled by QSS styles
Currently, link text is hard-coded in the Utils.cpp class.  This prevents it from being tweaked in the stylesheets and also means that adding a new style sheet will result in unexpected behavior (should additional themes ever be implemented).  This should be moved to the stylesheet and code updated to read from the stylesheet.

#### General Style Issues
Spacing is off in places, font isn't taken fully advantage of to differentiate different sections of the UI.  Some things feel cramped.  Other things aren't quite centered.  This covers basic tweaking of various things.

**Comment by deepbluev7** [comment]
Do you still consider those things an issue? Could you clean out things, that don't apply anymore? I.e. the first 2 seem to be fixed and the last one is a bit too general, I think?

**Comment by Francesco149** [comment]
I've also noticed that having `QT_QPA_PLATFORMTHEME` set affects the chat theme and that font settings don't affect chat fonts at all ![](https://i.imgur.com/ftI14iw.png)

**Comment by deepbluev7** [comment]
Most of those are fixed, so I'll close this.
