### ISSUE TITLE
At registration screen, silent failure if a URL is used for Home Server value

### ISSUE THREAD

**Issue by maxidorius** [Nheko-Reborn/nheko#50]
If a URL is used for "Home Server" on the register page, nothing happens in the GUI upon clicking "Register".

The console shows the following:
```
[net] [warning] failed to register: status_code (-1472400592)
```
If the hostname without `https://` or `http://` is used instead, it works. It would be good if the textfield label was clearer on the expect value, or handle URL protocol scheme gracefully.

**Comment by deepbluev7** [comment]
I tried this just now with https://matrix.org and the flow seems to continue fine. I think we should support .well-known discovery and improve the hints on the textfield a bit.
