### ISSUE TITLE
Selecting all and Pasting text doesn't replace the old text

### ISSUE THREAD

**Issue by vachan-maker** [Nheko-Reborn/nheko#501]
### Describe the bug
When I use Ctrl + A to select taste and paste another text, the old text doesn't get replaced

### To Reproduce
1. Enter some random text and copy some text
2. Select all text in the messaging field
3. Paste the text 

### Expected behavior
Pressing Ctrl + A and pasting the text should replace the old text

### Screenshots
**Actual Behavior**

https://user-images.githubusercontent.com/65799568/109588208-63eb2900-7b2e-11eb-8361-51b45af28dba.mp4

### System:

- Nheko version: 0.8.1-1a2517e8 | Windows
- Profile used: 
- Installation method: .exe file from Github Releases page
- Operating System: Windows 10

**Comment by deepbluev7** [comment]
Fixed that a few hours ago.
