### ISSUE TITLE
When editing a message, start the cursor at the end of the message

### ISSUE THREAD

**Issue by Cadair** [Nheko-Reborn/nheko#502]
**Is your feature request related to a problem? Please describe.**
The logical place to me to start editing a message is at the end where you last edited it.

**Describe the solution you'd like**
When starting editing a message put the cursor at the end.

**Comment by Cadair** [comment]
This doesn't seem to apply when doing alt-up then ctrl-e, the cursor ends up at the end there, so I think this is just a quirk of the new up key shortcut. @deepbluev7

**Comment by deepbluev7** [comment]
Yeah, the problem is that I'm not quite sure how the cursor movement should work there, press up twice to edit a previous message maybe? So first up moves to front and second up moves to edit a message above?

**Comment by Cadair** [comment]
That's what element does, and I find it pretty natural, so :+1:
