### ISSUE TITLE
Build: CMake errors out if USE_BUNDLED_LMDBXX is set but all the other bundling options are off

### ISSUE THREAD

**Issue by lbeltrame** [Nheko-Reborn/nheko#511]
### Describe the bug

The reason lies in https://github.com/Nheko-Reborn/nheko/blob/47e97d490c928f4e330e27253672ac254d82d678/CMakeLists.txt#L420

It misses the line `include(FetchContent)` from other `USE_BUNDLED_XXX` options.

**Comment by deepbluev7** [comment]
Thank you for the detailed report, should be fixed now :3
