### ISSUE TITLE
Chat view: right click menu does not appear on pointer location

### ISSUE THREAD

**Issue by lbeltrame** [Nheko-Reborn/nheko#512]
### Describe the bug

After the inline buttons were merged in master, the position of the menu is always where the buttons are, instead of where the mouse is.

You can see this from the screenshot (notice the mouse pointer and the position of the menu)

### To Reproduce

Right click anywhere on a message.

### Expected behavior

Menu appears where the mouse pointer is.

### Screenshots

![Screenshot_20210307_100743](https://user-images.githubusercontent.com/25192/110234832-fa538c00-7f2c-11eb-8128-61e07a054b92.png)

### System:

- Nheko version: 0.8.1-c03f716e
- Installation method: Source
- Operating System: openSUSE Tumbleweed
- Qt version: 5.15.2
- C++ compiler: GCC 10
- Desktop Environment: KDE Plasma (master)

**Comment by deepbluev7** [comment]
I see, this only happens after you opened the menu once via the hover menu...
