### ISSUE TITLE
Nheko crashes on Windows

### ISSUE THREAD

**Issue by vachan-maker** [Nheko-Reborn/nheko#513]
### Describe the bug
Nheko crashes when adding an empty value is set as a tag

### To Reproduce
1. Right click a room
2. Click on New Tag
3. Click OK (do not enter anything)
4. Wait for a minute, click around.
5. BOOM🔥 Nheko crashes. ( I did notice my CPU fans spinning at high speed when this event happens)

### Expected behavior
No crash
### System:

- Nheko version: 0.8.1-1a2517e8 | Windows
- Profile used: Nil
- Installation method: .exe file from GitHub Releases
- Operating System: Windows 10

**Comment by Jedi18** [comment]
Dosen't crash for me. I don't think the empty new tag was the reason for the crash. Were you able to replicate the crash more than once?

**Comment by vachan-maker** [comment]
> 
> 
> Dosen't crash for me. I don't think the empty new tag was the reason for the crash. Were you able to replicate the crash more than once?

Yes
