### ISSUE TITLE
Show a list of nicks which have seen the event when mouse overing the RR marker

### ISSUE THREAD

**Issue by Cadair** [Nheko-Reborn/nheko#514]
I really miss the little chat heads from element in Nheko, I like being able to see at a glance who has read my messages. Failing this, it would be nice to see the names on mouse over at least rather than having to load a new window on click.

**Comment by Jedi18** [comment]
I agree, I really like the chat heads in element. @deepbluev7 Are you ok with adding chat heads? If so I'd like try checking if it's possible to implement it

**Comment by deepbluev7** [comment]
I don't like how much they jump around (it's very distracting). I would be fine with having a permanently visible list of who read everything at the bottom or so though.

**Comment by deepbluev7** [comment]
duplicate of #243
