### ISSUE TITLE
Pressing return on image upload dialog should send the event

### ISSUE THREAD

**Issue by Cadair** [Nheko-Reborn/nheko#515]
Upload an image, i.e. by pasting it into Nheko, then press return to confirm the preview popup, observe how the image is not sent.

I think the cursor is in the filename box by default, perhaps just adding a return handler in that text box would do the trick?

**Comment by salahmak** [comment]
i second that, assuming I've been using discord for a long time, it is pretty hard to switch from keyboard and drag the mouse to the send button.
