### ISSUE TITLE
Webcam not available

### ISSUE THREAD

**Issue by Yajo** [Nheko-Reborn/nheko#517]
### Describe the bug
I can't choose a webcam from settings. I can't make video calls.

### To Reproduce
1. Go to settings
2. The camera dropdown is empty.

### Expected behavior
It should let me do video calls.

### Screenshots
![screenshot-2021-03-10-09-15-25](https://user-images.githubusercontent.com/973709/110605572-29fad200-8181-11eb-978c-9c51e90d0041.png)

### System:

- Nheko version: 0.8.1-1a2517e | Linux
- Profile used: 
- Installation method: Flathub 
- Operating System: Fedora Silverblue 33
- Qt version: 
- C++ compiler: 
- Desktop Environment: GNOME

**Comment by deepbluev7** [comment]
What webcam do you have? Is it supported by gstreamer, i.e. does gst-device-monitor-1.0 list it as a video source? Is it maybe inaccessible in flatpaks?

**Comment by Yajo** [comment]
> What webcam do you have?

The one integrated in the laptop. Reported as `Acer, Inc HD Webcam` from `lsusb`



> Is it supported by gstreamer, i.e. does gst-device-monitor-1.0 list it as a video source?

I don't have that command installed, but it works everywhere else FWIW. Some apps where it works fine:

- https://flathub.org/apps/details/org.gnome.Cheese
- https://flathub.org/apps/details/im.riot.Riot
- https://flathub.org/apps/details/org.jitsi.jitsi-meet



> Is it maybe inaccessible in flatpaks if you are not using pipewire?

I'm using pipewire AFAIK.

I noticed these permissions from flatseal. Maybe `device=all` is missing? (Jitsi has it)

![Captura de pantalla de 2021-03-14 07-19-18](https://user-images.githubusercontent.com/973709/111060611-1e1b5280-8496-11eb-8c24-bfec62329163.png)

**Comment by deepbluev7** [comment]
Yeah, device=all could be an issue. If you toggle that manually, does it start working? Also all the other applications you listed use a different library, so if you could install gstreamer-monitor and try it, that would be very helpful!

**Comment by Yajo** [comment]
I weren't yet able to install gstreamer-monitor, but I was able to enable `device=all` for the flatpak and that fixed the issue:

![imagen](https://user-images.githubusercontent.com/973709/111163185-d0394400-8594-11eb-96b6-11d955452bdc.png)

Do you have permissions to transfer this issue to the flathub repo?

**Comment by deepbluev7** [comment]
I don't. but I can fix it for the next release.

**Comment by deepbluev7** [comment]
Fixed in the nightlies, if we don't forget to copy that file into the final yaml, it should be in the next release ;-)

**Comment by 1xPdd** [comment]
Hi. I'm having the exact same issue with the AppImage and the webcam (actually, also with the microphone). Both work in Jami, Linphone, Jitsi, BigBlueButton, Cheese, etc. Is there an equivalent of the `device=all` for AppImages?

System:
    Nheko version: 0.8.1-1a2517e
    Profile used:
    Installation method: AppImage
    Operating System: Debian Bullseye
    Qt version:
    C++ compiler:
    Desktop Environment: Openbox

**Comment by deepbluev7** [comment]
Not that I know of. I recommend to use the backport for debian instead or the flatpak. The AppImage probably does not have the right gstreamer modules for your system and gstreamer in an appimage has a lot of issues anyway..
