### ISSUE TITLE
Support Pinned Messages

### ISSUE THREAD

**Issue by Cadair** [Nheko-Reborn/nheko#519]
**Is your feature request related to a problem? Please describe.**
The spec supports pinned events: https://matrix.org/docs/spec/client_server/r0.5.0#m-room-pinned-events even if Element doesn't. Who doesn't want a pinned message?

**Comment by deepbluev7** [comment]
Some notes on this:

- mtxclient supports this already, so we would just need to check the state event in the database: https://nheko-reborn.pages.nheko.im/mtxclient/structmtx_1_1events_1_1state_1_1_pinned_events.html
- We probably should limit how many pinned messages are shown and how big, as well as make it possible to hide them. Like show only 2 or 3 pinned messages?
