### ISSUE TITLE
Nheko converts clipboard images to tiff format which doesn't work properly

### ISSUE THREAD

**Issue by salahmak** [Nheko-Reborn/nheko#521]
### Describe the bug
When I paste an image from clipman (xfce4's clipboard manager) it changes its format from png to tiff, which doesn't work properly, it freezes nheko and doesn't appear as an image in the chat (same goes for other clients like element). meanwhile when I use xclip, or manually drag and drop the image in nheko, it doesn't get converted to tiff and works completely fine, so I don't know why this happens.
Note that xfce4-screenshooter and clipman both save images in .png format, so I'm pretty sure the file i'm pasting is right.

### To Reproduce
1. Take a screenshot with xfce screenshooter and save it to the clipboard ( `xfce4-screenshooter -rc` )
2. paste the screenshot on nheko
3. you will see that the picture gets converted to .tiff

### Expected behavior
Images not being converted to tiff

### Screenshots
![image](https://user-images.githubusercontent.com/49586511/111070277-4d02ea00-84d1-11eb-9cd8-170943c8c991.png)

### System:

- Nheko version: 0.8.1-c47ae998 | Linux
- Profile used: default
- Installation method: downloaded and built from the AUR (nheko-git)
- Operating System: Arch linux (5.11.4-arch1-1)
- Desktop Environment: xfce 4.16

### Logs
[nheko.log](https://github.com/Nheko-Reborn/nheko/files/6136746/nheko.log)

**Comment by deepbluev7** [comment]
The problem is that your clipboard manager says it has an image available in multiple formats. Nheko just picks the first, which ends up being tiff. You can check what formats your clipboardmanager provides with xclip, for example `xclip -o -target TARGETS`.

**Comment by salahmak** [comment]
Thanks for replying.
hmmm, so since I'm using clipman (xfce's clipboard manager) what would be the workaround to make the png format on top?

**Comment by salahmak** [comment]
i have checked clipman settings and it should be only saving jpg, png, gif format
![image](https://user-images.githubusercontent.com/49586511/111072376-a15e9780-84da-11eb-91e4-130eb82cc6b3.png)

**Comment by deepbluev7** [comment]
Sorry, I don't know much about the xfce clipboard ._.

**Comment by salahmak** [comment]
I'll just start using xclip then, thanks for the help, also I'm looking into contributing to the project when I have some spare time.

**Comment by deepbluev7** [comment]
Sure, maybe you can figure out a good workaround for that, if you want to contribute something. The relevant code for that is https://github.com/Nheko-Reborn/nheko/blob/master/src/timeline/InputBar.cpp#L68 and https://github.com/Nheko-Reborn/nheko/blob/master/src/timeline/InputBar.cpp#L530 . Maybe instead of picking the first, we pick the first, if it is not tiff, otherwise pick the second, if it is available, otherwise fall back to the first?
