### ISSUE TITLE
Emojis are not drawn when standard font selected

### ISSUE THREAD

**Issue by XakepSDK** [Nheko-Reborn/nheko#528]
### Describe the bug
Emojis are not drawn, just plain box symbol
Emoji font is empty in settings, when i set it to standard and restart nheko, it resets to empty
When i set it to noto color emoji and restart nheko, then emojis are drawn properly and emoji font in settings is noto color emoji

### To Reproduce
1. Install nheko-git
2. Log in
3. Observe no emojis

### Expected behavior
Emojis are drawn properly

### Screenshots
![grafik](https://user-images.githubusercontent.com/4938483/111653104-899b5200-87ff-11eb-8f4e-f07cc1905c7e.png)

### System:
- Nheko version: 0.8.1-f6de6657 | Linux
- Profile used: 
- Installation method: nheko-git from aur
- Operating System: Arch Linux
- Qt version: 5.15.2
- C++ compiler: gcc 10.2.0
- Desktop Environment: KDE

**Comment by deepbluev7** [comment]
Your font does not have those emoji, so how do you expect them to get drawn correctly?

**Comment by XakepSDK** [comment]
I don't know how it should work, all other apps are working as expected and picking correct emoji font

**Comment by deepbluev7** [comment]
Does that also work in Qt apps? Because from this bug I'm pretty sure that it should not work: https://bugreports.qt.io/browse/QTBUG-85744

**Comment by XakepSDK** [comment]
Can confirm, Qt bug

**Comment by Salamandar** [comment]
@XakepSDK That's still unresolved in Qt. Is there any workaround ?

**Comment by deepbluev7** [comment]
Yeah, set a emoji font in the settings. Like noto-color-emoji.

**Comment by Salamandar** [comment]
Yea,h but it does not work.

**Comment by deepbluev7** [comment]
It should and does so on according to most users. If it doesn't, please report a bug, that explains the issue in depth and which platform you are on, etc.
