### ISSUE TITLE
Useless horizontal scrollbar in chat page

### ISSUE THREAD

**Issue by anjanik012** [Nheko-Reborn/nheko#530]
### Description
A scroll bar appears above input field . That scrollbar is useless and shouldn't be there.

### To Reproduce
It was just present for me from the first run

### Expected behavior
No horizontal scrollbar should be present in the chat page

### Screenshots
![clipboard](https://user-images.githubusercontent.com/24349858/111777036-bcfddf80-88d8-11eb-97f0-97cfc1ef69bb.png)

### System:

- Nheko version: 0.8.1-b31e74d9 | Linux
- Installation method:  Built from source (master branch)
- Operating System: Arch Linux
- Qt version:  5.15.2
- C++ compiler:  gcc 10.2.0
- Desktop Environment:  KDE Plasma 5.21.3

**Comment by deepbluev7** [comment]
I may have fixed that, can someone verify that?

**Comment by anjanik012** [comment]
Yes it is fixed
