### ISSUE TITLE
feature request: keyboard shortcut to switch to next unread room

### ISSUE THREAD

**Issue by symphorien** [Nheko-Reborn/nheko#533]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I want to read new events just arriving in another room and I have to either use the mouse or use ctrl+arrows repeatedly to reach it.

**Describe the solution you'd like**
like in weechat: Alt+a switches to a room with unread events, or does nothing if there are none.
(or any other keyboard shortcurt, really)

**Describe alternatives you've considered**
none

**Additional context**
weechat has this functionality, and I think mirage also has it.

**Comment by deepbluev7** [comment]
Would that be any room with unread events or any room with a notification counter?

**Comment by symphorien** [comment]
In weechat, rooms with notifications are switched to in priority, and only then rooms with regular unread messages.

**Comment by shubhav99** [comment]
Hi Sir
I want to contribute to this issue
this is my first issue ever
so please guide me through

**Comment by deepbluev7** [comment]
Well, you would need to create a new Shortcut, probably in the TimelineView.qml, that then invokes a slot on the TimelineManager, that changes which timeline is currently shown. I'm not sure, where the notification count is stored though, which may make this difficult (since the count is stored somewhere else).

**Comment by shubhav99** [comment]
Please guide me through scratch .....
This is my first contribution ever.

**Comment by deepbluev7** [comment]
It will be much easier to do that in the #nheko:nheko.im room, than spamming everyone subscribed to this issue.

**Comment by symphorien** [comment]
did something come out out of this?

**Comment by deepbluev7** [comment]
No
