### ISSUE TITLE
Inaccurate website info?

### ISSUE THREAD

**Issue by KrazyKirby99999** [Nheko-Reborn/nheko#537]
The page at https://nheko-reborn.github.io/ shows "* **Only** available for Linux and macOS.", while this repo shows "Releases for Linux (AppImage), macOS (disk image) **& Windows** (x64 installer) can be found in the GitHub releases."

It seems that the website needs to be updated.

**Comment by deepbluev7** [comment]
It actually says repository installations are only available for macOS and Linux, but the design makes that confusing.
