### ISSUE TITLE
Setting a different WM_CLASS value for popups to specify custom wm rules (floating, tiling..)

### ISSUE THREAD

**Issue by salahmak** [Nheko-Reborn/nheko#538]
**Is your feature request related to a problem? Please describe.**
It is kinda annoying that everytime i open a popup such as room settings or user profile, it opens in tiling mode when using a window manager, and due to small space allocated to it, some of it doesn't show and I can't even scroll it.

**Describe the solution you'd like**
Giving the popups a different WM_CLASS value such as : "nheko:Popup", so that users can specify wm rules for it to choose between tiling and floating mode for it.

**Additional context**
![image](https://user-images.githubusercontent.com/49586511/112718543-0d39fa80-8ef4-11eb-868d-e535c49375cd.png)

**Comment by Cadair** [comment]
I am sad that I only have but one :+1: to give.

**Comment by deepbluev7** [comment]
WM_CLASS has 2 values, do you mean to set the second one?

**Comment by deepbluev7** [comment]
What about setting:

```
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_DIALOG, _NET_WM_WINDOW_TYPE_NORMAL
```

?

**Comment by salahmak** [comment]
@deepbluev7 sure. if it would work and give the dialogs a different class string.

**Comment by deepbluev7** [comment]
It will not give it a different class string, but it sets a different window type, so you can use window_type=dialog instead of class=something.

**Comment by salahmak** [comment]
oh, so do window managers automatically make dialogs float ?

**Comment by deepbluev7** [comment]
No idea :D

Anyway, closing this, because the flag is now set.

**Comment by salahmak** [comment]
oh, hope that works, thanks for the looking into this.

**Comment by salahmak** [comment]
I'll send feedback when I build nheko again when I have free time

**Comment by deepbluev7** [comment]
You can at least write window rules for it, if you are unhappy :3
