### ISSUE TITLE
Publish nheko on flathub

### ISSUE THREAD

**Issue by qazip** [Nheko-Reborn/nheko#54]
It would be awesome if nheko was published on flathub. It is the only proper matrix client that supports E2EE, everyone should be able to easily use it.

**Comment by frzifus** [comment]
i guess this isnt up to date? https://github.com/Nheko-Reborn/nheko#flatpak

**Comment by redsky17** [comment]
Related to #57 

If someone can help me get nheko back on flathub, that'd be excellent.

**Comment by mujx** [comment]
@redsky17 Just open a PR on [flathub](https://github.com/flathub/flathub). The maintainers there will guide you through the process. 

Or open an issue [here](https://github.com/flathub/io.github.mujx.Nheko) and let them know you are the new maintainer.

**Comment by redsky17** [comment]
I opened a new PR:  https://github.com/flathub/flathub/pull/998
