### ISSUE TITLE
Inline images are not displayed

### ISSUE THREAD

**Issue by Cadair** [Nheko-Reborn/nheko#541]
### Describe the bug
A image with an inline `<img>` tag is not displayed in the timeline.

**Comment by deepbluev7** [comment]
That usually should not be the case. In most cases `<img>` tags work, but you need to switch rooms once to have them display correctly, after the image got downloaded.

**Comment by Cadair** [comment]
That didn't seem to work for me either :thinking:

**Comment by deepbluev7** [comment]
I've used them in the TWIM posts and obviously I could see those and similar, so this seems to be either event or system specific?

**Comment by Cadair** [comment]
What things should I give you about the event, because I have never seen this work.

**Comment by deepbluev7** [comment]
I have no idea, I'll probably fix the other bug in Qt first :D

**Comment by Cadair** [comment]
My issue is fixed by #624 it's just then the Qt bug that this is worth keeping open for.

**Comment by deepbluev7** [comment]
https://bugreports.qt.io/browse/QTBUG-93281
