### ISSUE TITLE
Display name change wording is confusing

### ISSUE THREAD

**Issue by Cadair** [Nheko-Reborn/nheko#542]
### Describe the bug

When I read "user has changed their display name." it's not immediately clear to me if they have changed their display name to or from what has been displayed.

I would prefer a "<old display name> has changed their display name to <new display name>".

**Comment by LorenDB** [comment]
I believe that the username displayed on all events is the current display name (and same for the avatar) .

**Comment by Jedi18** [comment]
Yeah I remember this confused me intially too. @deepbluev7 This should be a very simple fix, should this be kept around as a good first issue for a new contributor or should I go ahead and fix it?

**Comment by deepbluev7** [comment]
If you want to fix it, go ahead. There are enough easy issues and we should try to reduce such papercuts.
