### ISSUE TITLE
Discussion: The idea of "Discordification"

### ISSUE THREAD

**Issue by BrandonKMLee** [Nheko-Reborn/nheko#544]
A simple callback to https://github.com/mujx/nheko/issues/462 and https://github.com/vector-im/element-web/issues/7487 regarding the Pros and Cons of Discord over Matrix. Community UX management is still somewhat of a concern.

**Comment by deepbluev7** [comment]
Imo this is still to generic. Please open separate issues for specific improvements. If you have multiple of them, feel free to link them in one meta issue or so, but just this issue is nothing actionable, so I can never know, if this is "done". So I'll be closing this,
