### ISSUE TITLE
Open Matrix/Element links in Nheko

### ISSUE THREAD

**Issue by vachan-maker** [Nheko-Reborn/nheko#545]
When clicking on a matrix link in the browser, we usually go to https://matrix.to/#/#nheko-reborn:matrix.org
On clicking the blue continue button, Element app will launch or the browser will ask us to select a default application.
It would be great if I can open element://vector/webapp/#/room/#nheko-reborn:matrix.org in Nheko itself.

**Comment by LorenDB** [comment]
I think that some sort of Matrix link will open in Nheko. @deepbluev7, want to elaborate?

**Comment by deepbluev7** [comment]
Nheko will never support element links, but it supports matrix: links as in this proposal: https://github.com/matrix-org/matrix-doc/pull/2312 . I guess we should PR a change to matrix.to, so that it allows opening Nheko.

**Comment by deepbluev7** [comment]
Probably depends on this issue: https://github.com/matrix-org/matrix.to/issues/192

**Comment by deepbluev7** [comment]
Should be fixed by https://github.com/matrix-org/matrix.to/pull/200 if it gets merged :3

**Comment by deepbluev7** [comment]
This is merged upstream now, just needs to be deployed by the matrix.to people.
