### ISSUE TITLE
Images sent from Nheko do not show up in Mirage

### ISSUE THREAD

**Issue by MRAAGH** [Nheko-Reborn/nheko#549]
### Describe the bug
Mirage client does not show images sent using Nheko (https://github.com/mirukana/mirage/issues/197)

### To reproduce

1. Send any image in an encrypted room using the Nheko client
2. Look at the same room in the Mirage client
3. Notice that the image does not display
4. Look at the downloaded file and notice it is not a valid image file

### Screenshots

Image being sent in Nheko:
![](https://f.mazie.rocks/Screenshot_2021-04-13_21-13-19.png)
Image fails to display in Mirage:
![](https://f.mazie.rocks/Screenshot_2021-04-13_21-13-28.png)

### System:

- Nheko version: 0.8.1-18e96d5c | Linux
- Profile used: default
- Installation method: AUR package `nheko-git`
- Operating System: Arch Linux 64-bit
- Qt version: 5.15.2
- C++ compiler: g++ 10.2.0
- Desktop Environment: Awesome wm v4.3

**Comment by deepbluev7** [comment]
If I send the file and download it again in any client I have (which is not mirage), the checksums are exactly the same. Are you sure this is not just a mirage bug? Does this only happen in specific types of rooms, like encrypted rooms?

**Comment by deepbluev7** [comment]
One thing I can imagine, is that in encrypted rooms Nheko only sends the mimetype in the info object, not in the file object. See https://github.com/matrix-org/matrix-doc/pull/2582

**Comment by MRAAGH** [comment]
Turns out images display fine in unencrypted rooms. This only happens in encrypted rooms. 
That about the mimetypes is a possible cause @mirukana

**Comment by deepbluev7** [comment]
Yeah, Nheko does not send the mimetype, because the spec only has that in the example and not in the actual event spec. And we want it to be removed instead, because it is redundant.

**Comment by deepbluev7** [comment]
Closing, as imo Nheko is spec compliant enough here.
