### ISSUE TITLE
i386 Flatpak build is out of date

### ISSUE THREAD

**Issue by aidaho** [Nheko-Reborn/nheko#551]
### Describe the bug
Published i386 flatpack build is out of date compared to amd64 one (0.6.4 vs 0.8.1)

### To Reproduce

Running this on i386 system:
```
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
flatpak search nheko
```
Produces this output:
```
Name          Description                                    Application ID                      Version         Branch         Remotes
nheko         Desktop client for the Matrix protocol         io.github.NhekoReborn.Nheko         0.6.4           stable         flathub
```

### Expected behavior
i386 build should be in sync with amd64 one

### System:

- Nheko version: *not applicable*
- Installation method: Flatpak
- Operating System: Debian GNU/Linux 10
- Desktop Environment: TDE

**Comment by aidaho** [comment]
There is a bug in Debian Backports version (0.7.2) I wanted to report, (endless loop during initial sync
```
[2021-04-15 17:39:26.023] [net] [info] initial sync completed
[2021-04-15 17:39:26.693] [db] [info] mark room !NtXwyVyXZsoKoTSznq:grin.hu as encrypted
[2021-04-15 17:39:26.763] [db] [error] failed to save state after initial sync: mdb_put: MDB_MAP_FULL: Environment mapsize limit reached
```
), so I wanted to check first with the latest published build before doing so.

Unfortunately the official flatpak build is even older than the one in Debian Backports.

**Comment by deepbluev7** [comment]
I'm not sure, why no flatpaks are built for 32bit, but the database issues is probably because we have set the maximum database size to 32 GB, which won't work on x86. We would need to set that lower on 32bit platforms by modifying this line: https://github.com/Nheko-Reborn/nheko/blob/master/src/Cache.cpp#L48

**Comment by xvitaly** [comment]
32-bit support was dropped: https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/970

**Comment by deepbluev7** [comment]
Thanks for the info, we won't be trying to fix that then! If someone needs 32bit flatpaks, they will need to solve that.
