### ISSUE TITLE
Nheko can't log in to Conduit server

### ISSUE THREAD

**Issue by timokoesters** [Nheko-Reborn/nheko#558]
### Describe the bug
Nheko uses an old version of the /login endpoint

### To Reproduce
1. Create an account on conduit.rs using element
2. Try to log in to that account using nheko

Nheko shows M_BAD_JSON and my server logs show "missing field `identifier`"

### System:

- Nheko version: v0.8.2-rc2

**Comment by deepbluev7** [comment]
For reference, that endpoint is just deprecated, but still part of the spec. While we should migrate to the newer one, it should be alright to still use the old method to provide a username at the moment and afaik it even worked with conduit for a while, but they removed support for it a year ago or so.
