### ISSUE TITLE
Position awared context menu

### ISSUE THREAD

**Issue by FollieHiyuki** [Nheko-Reborn/nheko#559]
**Is your feature request related to a problem? Please describe.**
Right now all context menus are opened to the right of the mouse. I use a tiling WM so they sometimes go out of screen.

![screenshot](https://user-images.githubusercontent.com/67634026/115965284-f1883b00-a517-11eb-9ccf-2a015ae03acc.png)

**Describe the solution you'd like**
The context menu is opened within the Nheko's display region.

**Describe alternatives you've considered**

**Additional context**
WM: sway
Nheko version 0.8.2

**Comment by deepbluev7** [comment]
I think this is not our fault, but https://bugreports.qt.io/browse/QTBUG-95637

**Comment by FollieHiyuki** [comment]
I see. Thanks for the link. Closing now.

**Comment by deepbluev7** [comment]
New bug: https://bugreports.qt.io/browse/QTBUG-87303
