### ISSUE TITLE
missing translation strings

### ISSUE THREAD

**Issue by miocho** [Nheko-Reborn/nheko#56]
the following strings seem to be missing in the translation files in resources/langs/:
in the room creation dialog, the labels of the drop-down menus for "Room Visibility" and "Room Preset" as well as the "Cancel" and "Create room" buttons are missing.

btw:
the capitalization of "Create room" - shouldn't that read "Create Room", in line with the rest of the strings there?
and shouldn't there be colons after "Topic", "Direct Chat", "Room Preset", etc.?

**Comment by redsky17** [comment]
Thanks for the issue.  I'll mark this as a bug.  Eventually, I'd like to get nheko on lokalise or something so I can better manage the translations.

**Comment by redsky17** [comment]
Just to update... working on getting nheko set up on lokalise so that it's automatically tied to the github repo.  That way, any translation updates on lokalise will automatically show up here as pull requests.  After that... I'll need people to volunteer to actually submit translations.

**Comment by deepbluev7** [comment]
I think we updated the translations now. I can't find anything that is missing, if your language is incomplete, you could help translating here: https://weblate.nheko.im/engage/nheko/?utm_source=widget

If you actually notice a string, that can't be translated currently, please open an issue with the exact string location (the original string in this issue all seem to be translated, so I will close this).
