### ISSUE TITLE
Line to indicate up to which point messages were read/seen

### ISSUE THREAD

**Issue by antoyo** [Nheko-Reborn/nheko#560]
**Is your feature request related to a problem? Please describe.**
The problem is that there's no way to quickly see what is the first message that I haven't read/seen yet.

**Describe the solution you'd like**
Something like in weechat/Slack: a line between the last message that I've seen and the first new message.
The line should disappear (or even better, go down to the last message visible) after switching to another channel.

**Describe alternatives you've considered**
Any other visual indication would work.

**Comment by LorenDB** [comment]
Along with this, it would be nice to have a "jump to first unread" button, as well as a "scroll to bottom" button (see #426).
