### ISSUE TITLE
flatpak EOL info

### ISSUE THREAD

**Issue by apachelogger** [Nheko-Reborn/nheko#57]
### System:

- Nheko version: 0.6.2
- Installation method: flatpak
- Operating System: ubuntu
- Desktop Environment: plasma

### Actual behavior

`$ flatpak install flathub io.github.mujx.Nheko` produces the following info right at the end:

```
Info: io.github.mujx.Nheko is end-of-life, with reason: This application is no longer maintained.
Changes complete.
```

The app does still run fine.
Although admittedly I also don't really know what causes an EOL info like that.

### Expected behavior

Not have it say the app is EOL. Or not advertise flatpak as a viable installation option. Or make sure the flatpak gets updated on release (I am guessing that would possibly be why it says its EOL?).

### Steps to reproduce

`flatpak install flathub io.github.mujx.Nheko`

### Logs

```
$ flatpak install flathub io.github.mujx.Nheko

Looking for matches…

io.github.mujx.Nheko permissions:
    ipc       network       pulseaudio            wayland
    x11       dri           file access [1]       dbus access [2]

    [1] home, xdg-config/kdeglobals:ro, xdg-run/dconf, ~/.config/dconf:ro
    [2] com.canonical.AppMenu.Registrar, com.canonical.AppMenu.Registrar.*,
        org.freedesktop.Notifications, org.kde.StatusNotifierWatcher


        ID                                         Arch   Branch Op Remote  Download
 1. [✓] org.freedesktop.Platform.GL.nvidia-390-116 x86_64 1.4    u  flathub 47,1 MB / 47,6 MB
 2. [✓] org.freedesktop.Platform.GL.nvidia-390-77  x86_64 1.4    u  flathub 47,3 MB / 47,8 MB
 3. [✓] io.github.mujx.Nheko                       x86_64 stable i  flathub  3,0 MB / 3,0 MB

Info: io.github.mujx.Nheko is end-of-life, with reason: This application is no longer maintained.
Changes complete.
```

**Comment by MasterOfTheTiger** [comment]
> Not have it say the app is EOL. Or not advertise flatpak as a viable installation option. Or make sure the flatpak gets updated on release (I am guessing that would possibly be why it says its EOL?).

Well, that package is not maintained by the Nheko-Reborn team, thus they can't have it updated unless mujx does something about that. They probably should not advertise it on the README file though.

**Comment by redsky17** [comment]
I should probably remove it from the README.  I would like to get nheko back on flathub, but I don't know what all is required to make that happen.

**Comment by redsky17** [comment]
PR to flathub opened: https://github.com/flathub/flathub/pull/998
