### ISSUE TITLE
Clicking on a reply doesn't scroll the original message into view

### ISSUE THREAD

**Issue by Bubu** [Nheko-Reborn/nheko#572]
### Describe the bug
When I click on a reply nheko scrollup to *near* where the original message is, but I still have to scroll up about 4 more messages until the replied to message is scrolled into view.

### To Reproduce
1. Participate in a chat where people reply to each other
2. Click on a reply
3. Be confused because you end up at a seemingly random point in the timeline.

### Expected behavior
Replied to message is in view when clicking on the reply

### System:
See #571

**Comment by deepbluev7** [comment]
Yeah, this can't be fixed atm. Blocked on a few qtbugs regarding large content in a flickable.

**Comment by Thulinma** [comment]
I do believe this particular bug was fixed in #728 😁
