### ISSUE TITLE
(self) Nick change event in a room shows as "You joined this room" in the room list

### ISSUE THREAD

**Issue by Cadair** [Nheko-Reborn/nheko#573]
### Describe the bug
Change your nick in a room (i.e. send a `m.room.member` event), and then see how the room list shows "You joined this room".

**Comment by LorenDB** [comment]
In my experience, the text displayed can vary. For example, the nick change might display correctly at first but show as a join after restarting Nheko.

**Comment by deepbluev7** [comment]
That's because the cache does not try to look at the prev event to calculate the right join status. So it works, if the room emits the right event.

**Comment by deepbluev7** [comment]
Should be fixed with the new room list
