### ISSUE TITLE
Nheko crashes randomly on macOS 10.14

### ISSUE THREAD

**Issue by srdiegoc** [Nheko-Reborn/nheko#576]
### Describe the bug
Every 10 minutes or so, the app crashes without explanation, or freezes and becomes unusable. I don't know exactly why, as I don't do much on it.

### To Reproduce
1. Just leave the app open for 10 minutes or so on macOS 10.14

### Expected behavior
I expected the program to stay open or not freeze

### System:

- Nheko version: 0.8.2-3dc1c3d7 | Darwin
- Profile used: default
- Installation method: Downloaded the app with Brew
- Operating System: macOS 10.14
- Qt version: 
- C++ compiler: 
- Desktop Environment: MacOS

**Comment by deepbluev7** [comment]
Could be related to #575

**Comment by srdiegoc** [comment]
Could be, although it doesn't always happen on resume from ram. If I minimise it or just leave it in the background for a while and try to go back to it, it simply crashes. A similar thing happens with Quaternion, but these are the only two apps in my laptop that do this. Could it be with some Matrix-related library?

**Comment by deepbluev7** [comment]
Quaternion and Nheko both use Qt, but completely different matrix libraries. So if the crash is caused by the same thing, then it is a Qt issue. Potentially related to your GPU or so.
