### ISSUE TITLE
Pasting text copied from nheko is slow

### ISSUE THREAD

**Issue by Bubu** [Nheko-Reborn/nheko#577]
### Describe the bug
When copying a message in nheko and pasting it into firefox address bar or gedit it lags by about a second until the copied text appears

### Expected behavior
Pasting works instantly

### System:

- Nheko version: 0.8.2-0bf611be | Linux
- Profile used: yes
- Installation method: nheko-git from aur
- Operating System: Arch
- Qt version: 
- C++ compiler: 
- Desktop Environment: Gnome 40

**Comment by deepbluev7** [comment]
Does this apply to everything, just selections, the copy action or copy link address?

**Comment by Bubu** [comment]
It applies to everything copied from a rooms timeline it seems. Copying a room address from the room page works instantly, copying nhekos version string does as well.

Copying even a single char from a message lags. It lags by the same amount for middle mouse button paste.

**Comment by LorenDB** [comment]
Maybe you could test against copying from another Qt app to see if it is a Qt bug.

**Comment by Bubu** [comment]
What would I be looking for? As mentioned parts of nheko are fine, only the stuff copied from the room timeline gets this delay.

Any suggestions for apps that use a similar widget/do similar things?

**Comment by LorenDB** [comment]
I'd suggest trying a QML based app next, such as Neochat.

**Comment by Bubu** [comment]
Uhm... problem is gone now.

Maybe some package upgrade fixed it on my side. Or maybe the logout/login did it, who know. I'll reopen when it happens again.
