### ISSUE TITLE
Quotes in the quick switcher get HTML-escaped.

### ISSUE THREAD

**Issue by absorber** [Nheko-Reborn/nheko#578]
### Describe the bug

After joining a room with quote characters in the room name, the room name is incorrectly displayed in the switcher.

Actual room name is: `The Spaces feedback "space"` (Internal ID: `!LPqOcoJQuGkweiTedq:riot.ovh`)
In the quick switcher however the name is: `The Spaces feedback &quot;space&quot;`

I had a vision in my dream in which a multidimensional being told me that in order to fix this, the textFormat probably had to be explicitly set to rich text.
So I thought I'd relay the message :)

### To Reproduce
1. Join a room with quotes (in my example `!LPqOcoJQuGkweiTedq:riot.ovh`)
2. Press Ctrl+k to activate the switcher.
3. Enter part of the room name for it to show up (In my case "spaces" was more than sufficient)

### Expected behavior
I would see a name without the HTML escapes.

### Screenshots
![nhekobla](https://user-images.githubusercontent.com/2358532/118154931-2dbc0680-b407-11eb-8da4-fc9b87714011.png)

### System:

- Nheko version: `nheko-master-44c52368-amd64.flatpak`
- Profile used: Default
- Installation method: FP
- Operating System: Linux 64bit
- Desktop Environment: i3wm

**Comment by LorenDB** [comment]
> a multidimensional being
Entirely off topic, but...
If you are truly a human (as I think you are), then you are a multidimensional being!
