### ISSUE TITLE
Keyboard workflow improvement: Add hints to the context menu items.

### ISSUE THREAD

**Issue by absorber** [Nheko-Reborn/nheko#579]
**Is your feature request related to a problem? Please describe.**
It annoys me that I have to use the mouse more than I need to when selecting items in the context menu.

**Describe the solution you'd like**
Similar to the right-click menu of Firefox and Chrom(e)ium, it would be pretty cool to see hints for items, see screenshot:

![Screenshot_20210513_182609__examplehint](https://user-images.githubusercontent.com/2358532/118155689-0580d780-b408-11eb-9997-fb69fa66a154.png)

**Describe alternatives you've considered**
Crying in my bed.

**Comment by deepbluev7** [comment]
You implemented that and forgot to close your own issue! :D
