### ISSUE TITLE
Opening a profile picture opens it behind profile page

### ISSUE THREAD

**Issue by Bubu** [Nheko-Reborn/nheko#580]
### Describe the bug
When clicking on a profile picture from a profile page it opens a fullscreen image *behind* the profile page (which means the image is ot visible at all, just the gray scrim). Oh and clicking the image again opens another image that gets overlayed over the gray background again (but still begind the profile picture.)

Also also: opening the profile picture takes ~1-2 seconds which is why I clicked multiple times to behin with.

### To Reproduce
1. Open Profile
2. Click on profile picture
3. Wait for it to open
4. See picture opening behind profile

### System:

- Nheko version: 0.8.2-0bf611be | Linux
- Profile used: yes
- Installation method: AUR nheko git
- Operating System: Arch
- Qt version: 
- C++ compiler: 
- Desktop Environment: Gnome 40

**Comment by LorenDB** [comment]
The first part doesn't affect me, but the second 2 do.

**Comment by deepbluev7** [comment]
I believe this is fixed?
