### ISSUE TITLE
Install with Chocolatey

### ISSUE THREAD

**Issue by BrandonKMLee** [Nheko-Reborn/nheko#582]
**Is your feature request related to a problem? Please describe.**
See: https://github.com/chocolatey-community/chocolatey-package-requests/issues/981
Chocolatey is basically "apt for windows"

**Additional context**
Note that the option is open

**Comment by dgalbraith** [comment]
A Chocolatey package ([nheko-reborn](https://community.chocolatey.org/packages/nheko-reborn/0.8.2)) has been constructed and pushed to the community repository.
