### ISSUE TITLE
Disable crash dumps in release builds or put them in some XDG directory

### ISSUE THREAD

**Issue by sinanmohd** [Nheko-Reborn/nheko#585]
**Is your feature request related to a problem? Please describe.**
Nheko randomly creates visible files directly on home dir.  eg : /home/user/nheko-backtrace.dump

**Describe the solution you'd like**
move to appropriate places like /tmp, ~/.config, ~/cache, etc...

**Describe alternatives you've considered**
make it hidden

**Additional context**

**Comment by redsky17** [comment]
The coredump files are written to whatever directory you run nheko from.  I suppose if you run from a launcher shortcut, it probably defaults to $HOME or so.  We can certainly look into writing those to one of the Qt locations, or perhaps we should just disable that entirely for non-debug builds.
