### ISSUE TITLE
Ability to explore/join public rooms

### ISSUE THREAD

**Issue by haasn** [Nheko-Reborn/nheko#587]
**Is your feature request related to a problem? Please describe.**
I can't find an analog of the Element "explore rooms" functionality. This is very useful.

**Describe the solution you'd like**
Rather than being required to type an exact room ID, the "join room" button should bring up a room search dialog (see how Element does it).

**Additional context**
![nheko](https://user-images.githubusercontent.com/1149047/119219669-f0323a00-bae6-11eb-94aa-b77f0bad3504.png)

**Comment by deepbluev7** [comment]
Duplicate of #328 and WIP #496 .
