### ISSUE TITLE
Input field not focused after opening and closing settings

### ISSUE THREAD

**Issue by haasn** [Nheko-Reborn/nheko#589]
### Describe the bug
The input field gets unfocused when opening the settings and closing them again.

### To Reproduce
1. Click on a room, and make sure the input field is focused.
2. Click on the 'settings' button at the top left.
3. Click on the 'back arrow' to close the settings.

### Expected behavior
The input field remains focused.

### System:

- Nheko version: 0.8.2
- Installation method: distro
- Operating System: openSuSE Tumbleweed

**Comment by deepbluev7** [comment]
Seems to be fixed
