### ISSUE TITLE
Crash when accepting room invite (via browser)

### ISSUE THREAD

**Issue by haasn** [Nheko-Reborn/nheko#590]
### Describe the bug
SIGSEGV

### To Reproduce
1. Launch nheko
2. Click on e.g. https://matrix.to/#/#bifrost:half-shot.uk
3. Choose "Nheko Reborn" in the list and let the browser associate `matrix:` URLs with it
4. Hit "Continue", then click "yes" when Nheko asks you if you want to join the room.

### System:
- Nheko version: 0.8.2
- Installation method: Distro
- Operating System: openSuSE Tumbleweed

### Debugger backtrace
[gdb session](https://0x1.st/HY.txt)

### Additional information
I can reproduce this crash consistently. That said, if I try it while nheko is on the same workspace, it appears to work. (I also don't get the "yes/no" confirmation prompt in this case, so maybe that's the cause)

**Comment by haasn** [comment]
Additional information: The "on a different workspace" requirement is not mandatory. It crashes even while Nheko is in the foreground. It seems to be tied to whether or not it shows the "Yes/No" prompt.

**Comment by Bubu** [comment]
I also just ran into this. It also crashes when declining the room invite. :upside_down_face:
