### ISSUE TITLE
Allow Multiple Accounts to Login

### ISSUE THREAD

**Issue by cfitz25** [Nheko-Reborn/nheko#592]
Is it possible to allow for multiple accounts to login at once?
I feel that would be quite useful for some people.

**Comment by deepbluev7** [comment]
You currently need to use different profiles, by starting Nheko from the command line with `--profile <profilename>`. This will however open multiple windows.

**Comment by pymq** [comment]
Seems like a duplicate of #489.

**Comment by deepbluev7** [comment]
Closing in favour of #489
