### ISSUE TITLE
Add a copy to clipboard action for full screen images

### ISSUE THREAD

**Issue by Bubu** [Nheko-Reborn/nheko#599]
**Describe the solution you'd like**
Element (and I believe telegram?) offer a right click - copy function on images. This is useful for pasting images into another chat client/account or even into an image editor for marking something quickly. 

**Describe alternatives you've considered**
Well, save the image and go from there. But dealing with files in 2021 is soooo cumbersome :).

**Comment by deepbluev7** [comment]
Just enabling the copy action in the context menu would probably also be a good first step :3
