### ISSUE TITLE
Spinner contrast is too low with dark theme (KDE)

### ISSUE THREAD

**Issue by MayeulC** [Nheko-Reborn/nheko#601]
### Describe the bug
Sync spinner is dark-on-dark. This is on KDE plasma, so it might be related to kirigami-themed spinners.

### To Reproduce
1. Use KDE plasma?
2. Go to nheko settings, select dark theme
3. Open a room while nheko is syncing

### Expected behavior
The spinner should probably be white. I use a light plasma theme systemm-wide, though.

### Screenshots

This is the spinner. Can you see it?
![image](https://user-images.githubusercontent.com/3952726/120888007-5befc900-c5f6-11eb-8fb8-27271c2f33ee.png)

### System:

- Nheko version: 0.8.2-33ad65dc | Linux
- Installation method: flatpak
- Operating System: Arch Linux
- Desktop Environment: KDE Plasma

**Comment by deepbluev7** [comment]
That's because you can't assign a color to the KDE spinner. It works fine with the fusion theme. It's a KDE bug imo.

**Comment by deepbluev7** [comment]
Closed by c318adbf
