### ISSUE TITLE
Add a search option to find rooms more easily & quickly

### ISSUE THREAD

**Issue by utkarsh2102** [Nheko-Reborn/nheko#602]
**Is your feature request related to a problem? Please describe.**
It's very painful to keep scrolling to find the right room. In a world, where everything is just a search away, I wonder if we could add a "search" bar at the top or somewhere so that we can find the required room very easily & quickly.

**Describe the solution you'd like**
A search bar to navigate to the rooms.

**Comment by deepbluev7** [comment]
Have you tried pressing Ctrl-K?

**Comment by drakmail** [comment]
Ctrl-K is good enough, but require some polish...

Long room names is not cropped, for example:

<img width="435" alt="image" src="https://user-images.githubusercontent.com/869453/126220957-6d07a62a-f75b-4691-8a21-fea7df672174.png">

**Comment by deepbluev7** [comment]
I think the cropping is already fixed. At least I can't reproduce it with the current development version.

**Comment by utkarsh2102** [comment]
Hey, I can confirm Ctrl+K is working for me, thank you!
