### ISSUE TITLE
nheko --help not working if an instance of nheko is already open

### ISSUE THREAD

**Issue by Bubu** [Nheko-Reborn/nheko#606]
### Describe the bug
I tried opening an second profile of nheko. To do this, you have to use `nheko --profile <name>`. The problem is that there's no way to discover this without closing the existing nheko instance beforehand.

`nheko --help` doesn't work, neither does `nheko --profile` produce any output. (if should be telling you that your are missing a profile name)

**Comment by deepbluev7** [comment]
Same cause as #104

**Comment by deepbluev7** [comment]
fixed in #736
