### ISSUE TITLE
Handle matrix.to room(event) links

### ISSUE THREAD

**Issue by deepbluev7-old** [Nheko-Reborn/nheko#61]
In TextLabel::handleLinkActivation we currently special case matrix.to URLs, so we can open the user profile. This should be extended to handle room links, so clicking on `In reply to` would navigate to that message instead of opening in a browser.

[Specification of matrix.to links.](https://matrix.org/docs/spec/appendices.html#matrix-to-navigation)

Room links can be either a link to a room or a link to a specific event (which comes after the / after the room id).

So we would first have to check, if we already joined the room. If not, we should probably allow joining the room if joining is possible without an invitation. If we have already joined (or we can peek?), we should show the room.

Additionally, if the link contains an event and we can see that event in the room, we should scroll the view to that specific event and maybe highlight it. 

The hard part of this is probably handling unjoined rooms and scrolling to the correct position. I think scrolling is the important part, as it makes seeing the context of a reply much easier.

**Comment by deepbluev7** [comment]
This should work now apart from links to rooms, that you haven't joined yet. So I will close this now, we can handle the join foreign rooms, when we actually implement more sophisticated room linking.
