### ISSUE TITLE
Option to adjust blur intensity

### ISSUE THREAD

**Issue by vachan-maker** [Nheko-Reborn/nheko#613]
An option to increase the blur intensity would be nice. The blur doesn't really obfuscate images properly. Its still possible for a person to identify the image even when blur is enabled.

**Comment by vachan-maker** [comment]
![image](https://user-images.githubusercontent.com/65799568/122514690-f48c3d00-d029-11eb-8d52-ae3fe1742c03.png)

**Comment by LorenDB** [comment]
This is a random thought that might work: would it be possible to switch the image to its blurhash while the privacy screen is enabled?

**Comment by LorenDB** [comment]
Maybe we could even do our own local blurhashing...

**Comment by redsky17** [comment]
Thanks for the issue report.  This is something Nico and I have discussed, but haven’t actually come with an appropriate solution for just yet.  I agree that it needs to be addressed though.

**Comment by LorenDB** [comment]
So I did the blurhashing thing:
![image](https://user-images.githubusercontent.com/55629213/218613855-71eb0772-4734-4676-9ec4-1d6d842d4f41.png)
![image](https://user-images.githubusercontent.com/55629213/218613926-348f7d5c-dd01-40d5-a2b4-787e36908831.png)
How's this?

**Comment by LorenDB** [comment]
(Please note that currently my PR simply hides images if there is no blurhash available)
