### ISSUE TITLE
Exported session keys are not importable from some clients

### ISSUE THREAD

**Issue by Huy-Ngo** [Nheko-Reborn/nheko#615]
### Describe the bug

I tried to import session keys to Gomuks. Importing from Element is OK, but not from Nheko. It shows an error message:

`Failed to import sessions: invalid Matrix key export: missing suffix`.

This seems to be because the output file has all data in a single line, while it is wrapped within 128 character limit if exported from Element. In fact, I've tried to do that manually, and the keys can be imported

### To Reproduce
1. Go to 'Session Keys' in Settings
2. Click on 'Export'
3. Import the keys into Gomuks
5. Wrap the line with 128 character limit
6. Try to import again, which succeeds.

### Expected behavior
The exported keys file is imported in Gomuks.

### System:

- Nheko version: 0.8.2
- Installation method: distro repository
- Operating System: openSUSE Tumbleweed
- Desktop Environment: None

**Comment by deepbluev7** [comment]
That sounds like a bug in gomuks, I don't think the spec requires linewrapping?

**Comment by Huy-Ngo** [comment]
I suppose so.
