### ISSUE TITLE
Links are not clickable in message view

### ISSUE THREAD

**Issue by yuyichao** [Nheko-Reborn/nheko#617]
### Describe the bug
When the message (also the channel topic) contains links, it is highlighted as links in the message view but it's not clickable. For channel topic, clicking on it brings the room settings popup and the links in that window is clickable.

### To Reproduce
1. Send a message with link
2. Put a link in the channel topic
3. Links are not clickable.

### Expected behavior
The behavior for the channel topic is workable since at least it's clickable in the popup even though it'll still be nice to allow clicking the link there and only fallback to bringing up the popup when there's nothing clickable in the topic. This should be OK even if the whole topic is a link since there's the channel icon to bring up the popup. The message view one is really unusable.

### System:

- Nheko version: 57a9a1d0
- Profile used: 
- Installation method: build from source, search "nheko-git" from https://repo.archlinuxcn.org/x86_64/ to find the exact binary I used
- Operating System: ArchLinux
- Qt version: 5.15.2
- C++ compiler: g++ 11
- Desktop Environment: KDE

**Comment by deepbluev7** [comment]
They are all clickable here, so do you have some special settings enabled like the mobile mode?

**Comment by yuyichao** [comment]
Turning off touchscreen mode does fix the issue.
So I guess maybe change the issue to automatically differentiating touch and mouse and also allow link clicking/selection in touch mode (say with long press?). Does qt5 support xinput2 ?

**Comment by deepbluev7** [comment]
Hm, clicking links should work in touchscreen mode, but automatically differentiating would be difficult, so we didn't go that route. Anyway, I pushed a fix for this to my spaces branch, so the fix should land in master at some point.
