### ISSUE TITLE
Allow text selection in message window

### ISSUE THREAD

**Issue by yuyichao** [Nheko-Reborn/nheko#619]
**Is your feature request related to a problem? Please describe.**
AFAICT, currently, it's only possible to copy the whole message and not part of it. It's quite inconvenient in many cases IMO. (and https://github.com/Nheko-Reborn/nheko/issues/618 makes this much worse....) This also makes https://github.com/Nheko-Reborn/nheko/issues/617 worse since I couldn't even select only the link and copy it to the browser...

**Describe the solution you'd like**
As the title says, allow selecting the text in the message window and enable standard copying hotkey

**Describe alternatives you've considered**
Copying to a different window and edit there. Works especially poorly for https://github.com/Nheko-Reborn/nheko/issues/617 (hard to edit in the small browser address bar)

**Additional context**
AFAICT element allows it so I don't feel like there's a security concern here. If anything, allowing that as an option is also fine for me...

**Comment by deepbluev7** [comment]
This is not true. You can copy parts of the message. This is just disabled if you select the mobile mode option, since that interferes with scrolling otherwise.

**Comment by deepbluev7** [comment]
(Also you can right click a link to copy it)

**Comment by yuyichao** [comment]
You are right https://github.com/Nheko-Reborn/nheko/issues/617#issuecomment-866325693 . So the actual enhancement is to improve the touchscreen mode/make it automatic based on the type of input.

**Comment by yuyichao** [comment]
In another word, both this and https://github.com/Nheko-Reborn/nheko/issues/617 are about improving the touchscreen mode. Feel free to close one/merge them as you see fit.

**Comment by deepbluev7** [comment]
Can you create a new issue with the specific improvements for touchscreen mode you would like to see? I.e. if you want to switch touchscreen mode automatically depending on the connected devices or so? Since the title and comment history of this will probably be confusing. It is not possible currently to make text elements only respond to input of specific devices, as far as I am aware, but you can do that for tap handlers and such.

**Comment by yuyichao** [comment]
Sorry for the delay. My expected 1 week travel was turned into a 2 and a half months one = = ......

I'll test the latest version and see if I think any of the behaviors can be improved though I'm currently hitting https://github.com/Nheko-Reborn/mtxclient/issues/63
