### ISSUE TITLE
Allow encrypted messages to be shown in notification

### ISSUE THREAD

**Issue by yuyichao** [Nheko-Reborn/nheko#620]
**Is your feature request related to a problem? Please describe.**
On receiving an encrypted message, the desktop notification will simply show that an encrypted message is received without showing the actual message. This is especially ironic since the notification seems to allow replying without actually being able to see the message.

**Describe the solution you'd like**
Have an option to allow showing encrypted message in notification just like the option for showing the message in the room list.

**Comment by mxmehl** [comment]
Is there a technical reason why the message is not shown in the notification?

I can see a reason why this should be optional (e.g. to avoid that a sensible message leaks during a screencast or so) but as a user I would expect the actual text to be visible there.

**Comment by deepbluev7** [comment]
Well, we can't decrypt all messages immediately and we haven't thought about what to do in that case so we just show none at all.

**Comment by maltee1** [comment]
couldn't you show a notification that an encrypted message was received and update the notification once it has been decrypted?

**Comment by deepbluev7** [comment]
> couldn't you show a notification that an encrypted message was received and update the notification once it has been decrypted?

Yes, if someone implements it. You need to plumb quite a few things through for that.

**Comment by deepbluev7** [comment]
Fixed, it will just show "received an encrypted message" if it couldn't be decrypted for now.
