### ISSUE TITLE
Show more details for a room invite

### ISSUE THREAD

**Issue by Cadair** [Nheko-Reborn/nheko#622]
When getting a room invite only a panel in the room list is shown, which shows you the name and picture for the room. There is no additional information shown which might give you more context on an unfamiliar invite, such as the inviters mxid or room topic etc.

**Comment by LorenDB** [comment]
@deepbluev7 @redsky17 

What if we would remove the invite buttons from the room list item and put them in the timeline view instead? That could be used as a larger display for information about the room, and theoretically could be used to preview a public room's contents as well.

**Comment by deepbluev7** [comment]
Yeah, that would make sense. I'm currently working on peeking rooms too, so that you can join them in spaces.

**Comment by Cadair** [comment]
The view in the timeline is really nice, but still gives me little to no information about what the invite is for or who it is from. i.e. is this a DM with this person or a room invite from this person, if it's a room, what's the topic etc.

**Comment by deepbluev7** [comment]
We probably could show the topic there, if we store it in the db already. I think most of that stuff is there, someone just needs to add it in the Model or in the UI.

**Comment by Mikaela** [comment]
I think abuse reports for spam invites may also require invite event ID.
