### ISSUE TITLE
Show more (or all) of a room description in the room summary screen

### ISSUE THREAD

**Issue by Cadair** [Nheko-Reborn/nheko#623]
Even when the room panel is large:

![image](https://user-images.githubusercontent.com/1391051/123413872-2ca3fa80-d5ab-11eb-915f-18dcc6b05782.png)

only two or three lines of the description are shown.

Also there is no visible scroll bar until you mouse over.

It would be better if the whole description was shown in this panel imo, unless the window is too small. (i.e. the default panel size should be larger)

**Comment by LorenDB** [comment]
Probably set `Layout.fillHeight: true` on the description ScrollView (or whatever it is)

**Comment by deepbluev7** [comment]
We tried that before and it broke the layout. But maybe it works now.

**Comment by deepbluev7** [comment]
This is fixed
