### ISSUE TITLE
Move invites to left bar before tags and spaces

### ISSUE THREAD

**Issue by Kirillpt** [Nheko-Reborn/nheko#625]
What you think about moving all invites to the left bar. Mark it like tag, and hide from all rooms and maybe hide this tag when user hasn't got any of them (or empty tags hides by default?)

**Comment by LorenDB** [comment]
I'd personally prefer leaving them where they are and adding an informational view in the timeline, but that's definitely an interesting idea!

**Comment by deepbluev7** [comment]
I think adding a filter for invites could work (same as for DMs), but moving it out from the room list would be weird.
