### ISSUE TITLE
[spaces] Exclude spaces from room search

### ISSUE THREAD

**Issue by Cadair** [Nheko-Reborn/nheko#629]
These are not the rooms I am looking for ;)

Or at least do something so I can tell what's what.

**Comment by deepbluev7** [comment]
We should distinguish them at least, yes, but I am not quite sure yet, if I want to remove them from the quick switcher. We should rather switch to the space in that case!

**Comment by Cadair** [comment]
By switch to the space do you just mean in the room panel or also select it in the spaces panel?

**Comment by deepbluev7** [comment]
Also select it in the spaces panel.
