### ISSUE TITLE
Make available in Homebrew?

### ISSUE THREAD

**Issue by apjanke** [Nheko-Reborn/nheko#63]
It would be convenient if Nheko Reborn were available on macOS through Homebrew as well as MacPorts. Right now only the old Nheko client is available as a Homebrew cask.

If you want to do this, to qualify for inclusion in Homebrew core, your GitHub repo needs to be the root of its own fork tree, instead of a fork of `mujx/nheko`. Since the upstream `mujx/nheko` project is defunct, and changes to this repo are never going to make it back there, that seems like the "Right Thing" to do, anyway. To do this, you need to contact GitHub support and ask them to make your repo a "canonical" repo that is no longer a fork of `mujx/nheko`.

In the meantime, to show how this would work, I've created a [`nheko-reborn` cask in my `apjanke/personal` custom tap](https://github.com/apjanke/homebrew-personal/blob/master/Casks/nheko-reborn.rb). To use it:

```
brew tap apjanke/personal
brew cask install nheko-reborn
```

### System:

- Installation method: Homebrew
- Operating System: macOS

**Comment by redsky17** [comment]
I totally agree that it'd be great to have nheko on homebrew.  Other folks have suggested reaching out to GitHub to make this the official nheko repo rather than a fork.  I'll reach out to them and see what happens.

**Comment by apjanke** [comment]
Great! Let me know if you get a positive response from them, and then I'll make a PR to Homebrew to add a formula for Nheko-Reborn.

**Comment by redsky17** [comment]
GitHub has moved this repository to the root of its own network, so it no longer appears as a fork of @mujx/nheko

**Comment by aaronraimist** [comment]
It is available in Homebrew now 
https://github.com/Nheko-Reborn/nheko#macos-1014-and-above
https://github.com/Homebrew/homebrew-cask/blob/master/Casks/nheko.rb

**Comment by deepbluev7** [comment]
Since this is on homebrew now, I'm gonna close this. Thank you aaron for telling us and to the packager for packaging! I'm sure @redsky17 appreciates that :3
