### ISSUE TITLE
Show actual reply in sidebar preview, not msg being replied to

### ISSUE THREAD

**Issue by SlidingHorn** [Nheko-Reborn/nheko#630]
![Screenshot_2021-07-08_09-22-15](https://user-images.githubusercontent.com/6623121/124929230-5529ec80-dfce-11eb-8fee-12e30061b4c5.png)
**Is your feature request related to a problem? Please describe.**
When the most recent post in a room is a quote-reply, the sidebar preview shows the contents of the post being replied to rather than the response itself.

**Describe the solution you'd like**
The preview should probably display the *new(est)* message rather than pulling the quoted one.

**Describe alternatives you've considered**
I don't really think there is a better alternative. This seems to be common sense (to me, at least)

**Comment by deepbluev7** [comment]
Well, it actually shows the full message including the quoted reply, but we should remove the quoted part, yes.

**Comment by SlidingHorn** [comment]
> Well, it actually shows the full message including the quoted reply, but we should remove the quoted part, yes.

Ah, I guess due to the limited space in which it's shown (at least if it's not fullscreen) only the quote fits
