### ISSUE TITLE
Day separators rendered in middle of the day

### ISSUE THREAD

**Issue by nh2** [Nheko-Reborn/nheko#632]
### Describe the bug

Sometimes the day separators are rendered in the middle of the day, even though a new day isn't starting there:

![image](https://user-images.githubusercontent.com/399535/125013758-b0122100-e06c-11eb-8c1e-997d6cf530ed.png)

### To Reproduce

Not surper sure yet; I just installed nheko 0.8.2 for the first time, opened a previously unloaded room (in which I had history on element.io), scrolled up a bit, and this occurred. Switching to another room, and back to my room, fixed the issue.

So maybe it's a race condition with message loading?

### System:

- Nheko version: 0.8.2
- Profile used: default
- Installation method: `nix-shell -p nheko --run nheko`
- Operating System: NixOS 21.05
- Desktop Environment: i3

**Comment by deepbluev7** [comment]
This happens when the separator gets rendered before the previous messages are rendered. We should emit a dataChanged for the last message not fetched too, once we loaded older messages from the server, so that this doesn't happen.
