### ISSUE TITLE
Nheko removes whitespace, Mac

### ISSUE THREAD

**Issue by iambumblehead** [Nheko-Reborn/nheko#633]
### Describe the bug

On Mac there are bugs related to typing/inputting whitespace. It also appears to remove whitespace from messages displayed by users in the room.

Typed: `hello, world. now`
Result: `hello,world.now` <-- nheko removes the whitespace typed by the user

Typed: `hello,  world.  now`
Result: `hello, world. now` <-- the workaround is to type two whitespace characters

### Expected behavior

Nheko should not remove whitespace

### Screenshots

<img width="649" alt="Screen Shot 2021-07-09 at 10 44 37 AM" src="https://user-images.githubusercontent.com/2058705/125117209-bcb16c00-e0a2-11eb-80ff-1aa5c52bbb96.png">

### System:

- Nheko version: 0.8.2-3dc1c3d7 Darwin
- Profile used: N/A
- Installation method: dmg from github release page
- Operating System: Mac

**Comment by deepbluev7** [comment]
Might be related to https://bugreports.qt.io/projects/QTBUG/issues/QTBUG-95100 ? Are you on Big Sur by chance?

**Comment by iambumblehead** [comment]
@deepbluev7  yes Big Sur here `macOS Big Sur, Version 11.4 (20F71)`

**Comment by redsky17** [comment]
For the record, I can reproduce this on Big Sur on my 2019 MBP.  It seems to happen after periods, as well, but not question marks.  I'm assuming there's some Qt bug here, but I'll look into it more.

**Comment by redsky17** [comment]
<img width="501" alt="Screen Shot 2021-07-12 at 1 41 36 PM" src="https://user-images.githubusercontent.com/962117/125332330-f25e8b00-e316-11eb-97ba-11c5aa6fea64.png">

**Comment by redsky17** [comment]
It also appears to only be a render-related client-side issue (check the Raw Text by right-clicking the sent message and you should see spaces where you expect them to be).

**Comment by deepbluev7** [comment]
This should be fixed, once we update Qt: https://bugreports.qt.io/browse/QTBUG-88495

**Comment by deepbluev7** [comment]
5.15.3 with the fix is released now, waiting for brew to release it too.

**Comment by LorenDB** [comment]
Brew is now all the way to Qt 5.15.8, so I think this can be closed :D

**Comment by iambumblehead** [comment]
nheko is awesome I'm still using it on my mac -- thank you for keeping it going
