### ISSUE TITLE
When accepting an invite from the new preview screen you have to click off the room and back in once the join completes

### ISSUE THREAD

**Issue by Cadair** [Nheko-Reborn/nheko#639]
To reproduce:

* Get invite
* Click onto full screen invite panel
* Click Accept
* Wait for join to complete and room to display in sidebar
* observe how you have to click that room to see the timeline.

**Comment by deepbluev7** [comment]
fixed by 47899ee7ed76bba468465bd4c5706e9a7dac360c which I forgot to push a few days ago
