### ISSUE TITLE
Support screen capture on Wayland

### ISSUE THREAD

**Issue by deepbluev7** [Nheko-Reborn/nheko#643]
Should be possible using pipewire: https://gitlab.freedesktop.org/pipewire/pipewire/-/blob/master/src/gst/gstpipewiresrc.c#L31

API to enumerate windows: https://github.com/flatpak/xdg-desktop-portal/blob/master/data/org.freedesktop.impl.portal.ScreenCast.xml

**Comment by progandy** [comment]
This seems to be a GPL3 project implementing recording with gstpipewiresrc and the screencast portal in c++, maybe some of the code can be reused: https://github.com/lirios/screencast

**Comment by deepbluev7** [comment]
Ah, this got merged.
