### ISSUE TITLE
Opening a non-downloaded image does nothing until the image is loaded

### ISSUE THREAD

**Issue by Cadair** [Nheko-Reborn/nheko#644]
### Describe the bug
The full screen image viewer does not load until the image is downloaded. This can lead to a situation where the user clicks the image thumbnail in the timeline and nothing happens for multiple seconds. (Especially if the image is large or the connection is slow).

### To Reproduce

Steps to reproduce the behaviour:
1. Get a new message with a new image.
2. Click on the thumbnail
3. Observe how nothing happens for a while

### Expected behaviour

The image preview should open and show a loading screen while the image is being downloaded.

**Comment by deepbluev7** [comment]
Doesn't show a spinner, but the viewer should open immediately now and just show nothing until the image is loaded.
