### ISSUE TITLE
Nheko is slow to show the main window on startup

### ISSUE THREAD

**Issue by Cadair** [Nheko-Reborn/nheko#645]
When running nheko it takes a while before the main window is displayed. It would be nice if a placeholder window was shown as soon as possible in the loading process and then populated with the content once it was loaded.

I am not asking for a splash or a window which gets replaced with the main window, I would like the main window to load with nothing but a spinner in the middle and then the UI pop in when loaded.

A slow startup is a bad first impression for a desktop app which is "native" and "fast", but also it's really annoying to have to wait for the window to load so my tiling window manager puts it in the right place ;)

**Comment by deepbluev7** [comment]
That's because we load all the rooms from the database an all the last messages on first start. We could probably just delay that. I don't really notice any slow loading, since it takes about 1s for me to have Nheko with 450 rooms completely loaded and ready to use (Element takes 30s).

**Comment by Cadair** [comment]
Element desktops electron window appears immediately tho and I have to wait a second to see the window with nheko ;)

**Comment by deepbluev7** [comment]
This is fixed, imo. We show the window pretty fast now, but it shows a spinner for a while.
