### ISSUE TITLE
QML all the things

### ISSUE THREAD

**Issue by LorenDB** [Nheko-Reborn/nheko#647]
History: this started life as PR #595, but I'm going to split up all the work among multiple PRs, so I'm creating a meta issue to track all this stuff.

## :tada: QML all the things! :tada: 

This issue's purpose in life is to track all QMLing efforts for all things that remain to be QMLed as of today, July 17, 2021.  This list includes:

- [ ] Dialogs
  - [x] Member list (#595)
  - [x] Invite (#595)
  - [x] New room
  - [x] Join room (#741)
  - [x] Leave room (#742)
  - [x] Logout (#743)
  - [x] Read receipts (#655)
  - [x] Raw message (#662)
  - [x] File upload
  - [x] Recaptcha
  - [ ] Fallback auth
  - [x] EditModal in the room settings
- [x] General
  - [x] Welcome page (#893) 
  - [x] Login page (#893)
  - [x] Registration page  (#893)
  - [x] Settings page (#883)
  - [x] Fullscreen image viewing overlay

Please let me know if I missed anything or if you are planning to QML any of these things yourself. I'm doing this work so that my Android port can run nicely, but I'll welcome any help.

**Comment by deepbluev7** [comment]
While we are at it, we probably should rework the create and join room dialogs. Too many useless options.

**Comment by LorenDB** [comment]
I have both of those in there (join room and new room)!

**Comment by deepbluev7** [comment]
Yeah, I was just thinking we should change the design, while we are already porting them. :3

(Also a dialog for knocks would be nice)

**Comment by LorenDB** [comment]
> (Also a dialog for knocks would be nice)

That's not existing functionality, so I won't put it in this list.

**Comment by deepbluev7** [comment]
Yeah, the list is fine. Again, just mentioning this for anyone picking that up, that this would be easy to do, when someone is already touching that code. :3

**Comment by Kirillpt** [comment]
Image viewer (Image Overlay) still c++ code :)
nheko/src/dialogs/ImageOverlay.cpp (.h)

**Comment by deepbluev7** [comment]
I think that is meant with "Fullscreen image viewing overlay"

**Comment by maltee1** [comment]
Is there a good reason notifications are not on the list?

**Comment by deepbluev7** [comment]
Notifications are not drawn by us, they are just a dbus call.

**Comment by maltee1** [comment]
What I meant is this: https://doc.qt.io/QtApplicationManager/qml-qtapplicationmanager-notification.html

**Comment by deepbluev7** [comment]
Huh, I didn't know about those. Although we do now already have a lot of custom tweaks to notifications, that are not supported by that.

**Comment by LorenDB** [comment]
Uh, there are still 2 or 3 things that are not QMLed.
