### ISSUE TITLE
Missing libcmark.so.0.30.0:

### ISSUE THREAD

**Issue by qazip** [Nheko-Reborn/nheko#649]
`/usr/bin/nheko: error while loading shared libraries: libcmark.so.0.30.0: cannot open shared object file: No such file or directory`

OS: Arch
Nheko: Latest git version (nheko-git from AUR)

**Comment by deepbluev7** [comment]
Please recompile. Your packagemanager does not preserve needed libs or automatically rebuild dependent packages, so you need to do that manually, if your packagemanager removes shared libraries.

**Comment by qazip** [comment]
Oh ya. I did know this. stupid me. 

Recompiled and worked. Thank you.
