### ISSUE TITLE
Change rooms with keyboard shortcuts

### ISSUE THREAD

**Issue by SlidingHorn** [Nheko-Reborn/nheko#652]
**Is your feature request related to a problem? Please describe.**
I spend a lot of time using applications that are keyboard driven, including addons for Firefox for vim keys. It would be nice to have to reach for the mouse less when using nheko

**Describe the solution you'd like**
Would it be possible to implement switching the selected room similarly to how browsers switch tabs? e.g. `Ctrl + PgUp` and `Ctrl + PgDown`

**Describe alternatives you've considered**
It would be even cooler if this could be custom keymapped, but that's probably asking a bit much

**Comment by deepbluev7** [comment]
Ctrl-Up/Down switches rooms: https://github.com/Nheko-Reborn/nheko/wiki/Shortcuts
