### ISSUE TITLE
Cannot register; no error is shown

### ISSUE THREAD

**Issue by tsoernes** [Nheko-Reborn/nheko#66]
### System:

- Nheko version: nheko-0.6.3-1.fc29.x86_64
- Installation method: fedora repos
- Operating System: fedora 29

### Actual behavior
Terminal outputs `[2019-05-13 12:36:56.822] [net] [warning] failed to register: status_code (0)`
when clicking register button, but nothing happens in the GUI

### Logs
Logs are empty

**Comment by deepbluev7** [comment]
I think I fixed it in the latest nightly. If you can still reproduce it, please reopen and add which server you can't register with (matrix.org is still broken, but that is an issue on their side).

**Comment by twitchyliquid64** [comment]
What version did you fix it in? I am able to replicate using dendrite on `master` & nheko in Debian (`0.6.3`).

**Comment by deepbluev7** [comment]
It was fixed somewhere in the 0.7 series. 0.6.3 is ancient and I'm surprised it is even still useable! :D

**Comment by twitchyliquid64** [comment]
Yipes! `0.6.3` is the version that Debian is carrying.
