### ISSUE TITLE
Option to disable caching and logging

### ISSUE THREAD

**Issue by ChemicalXandco** [Nheko-Reborn/nheko#665]
Cache and log can wear SSDs unnecessarily and take up storage space. I propose that there should be options to disable these functions.

**Comment by deepbluev7** [comment]
Disabling the cache won't happen. Nheko would use multiple GB of RAM in that case and you won't be able to restart Nheko without getting logged out. The cache is the full database of login, e2ee keys, messages, etc. You can't easily disable that.

**Comment by deepbluev7** [comment]
I'm going to close this. The log file shouldn't cause that many writes, if you are not using a debug mode and we can't disable the database. We depend on it too much.

**Comment by foresto** [comment]
The latest code allows you to set log levels and type, through environment variables or command line options. See the man page for details. This will be available in the next release.
