### ISSUE TITLE
Hi dpi scaling window size issue (wayland sway)

### ISSUE THREAD

**Issue by toger5** [Nheko-Reborn/nheko#67]
### System:

- Nheko version: Cannot press because of scaling issue ;)
- Installation method: (package manager) dnf
- Operating System: Linux, Fedora 30
- Qt version: 
- C++ compiler: 
- Desktop Environment: Sway

### Actual behavior
The window size is not the same than the buffer size. On wayland you specify the window scale, and the window size. The actual buffer than needs to be the window size multiplied by the scaling factor. (Probably just a Qt setup issue though)
This also affects the possible input area. Which makes it unusable and i cannot revert the scaling Settings. (Because I don't know where the conf file is located.)
![2019-05-13-130331_grim](https://user-images.githubusercontent.com/16718859/57616853-8db11580-757f-11e9-8b4d-cfe07293879b.png)

### Expected behavior
It should scale correctly.

**Comment by redsky17** [comment]
Have you tried setting QT_SCALE_FACTOR and restarting nheko?  Alternatively, the nheko configuration file lives at ~/.config/nheko.  You can try changing the scale factor in there as well.

**Comment by deepbluev7** [comment]
This works for me on nheko and the 0.7.0 dev branch on sway. Maybe that was an issue with an old sway version or I fixed it in the mean time. If you can still reproduce it, please specify how you are setting the scale factor and please test the nighly version first, before reopening.

**Comment by toger5** [comment]
I still have this issue on gnome-shell. It could be because of dpi settings. Flatpak Nheko on Fedora gnome shell with dpi 1.5 or similar and font scaling 1.4.

**Comment by deepbluev7** [comment]
@toger5  Can you open a new bug report for this maybe?
