### ISSUE TITLE
"ESC" to close images

### ISSUE THREAD

**Issue by SlidingHorn** [Nheko-Reborn/nheko#672]
### The Problem

When images are viewed, there doesn't seem to be any way to close them except to reach over with the mouse and click the close icon in the top right corner. For people who like to stay keyboard-centric, it can be a bit of a pain.

### The Solution

Set the "Escape" key as another option to close the image.

### Happens in the latest version

- [X] Yes, this feature is still missing.

**Comment by Kirillpt** [comment]
Feature added, may be closed :)

**Comment by SlidingHorn** [comment]
Beautiful - Thanks
