### ISSUE TITLE
Newlines in room list don't render properly

### ISSUE THREAD

**Issue by LorenDB** [Nheko-Reborn/nheko#682]
### Describe the bug

When a room's last message contains a newline near the beginning of the message, so that it displays in the room list, the newline becomes a sort of null character and simply doesn't display, leaving the rest of the message run together.

### To Reproduce

1. Go to a test room
2. Send a message with the content
  ```
  Hello
  world!
  ```
3. Observe room list entry.

### Expected behavior

Maybe rendered as space instead of doing nothing?

### Version

master

### Operating system

Linux

### Installation method

Local build

### Qt version

5.15.2

### C++ compiler

clang, I think

### Desktop Environment

Plasma 5

### Did you use profiles?

- [X] Profiles used?

**Comment by maltee1** [comment]
Works for me

**Comment by LorenDB** [comment]
Same, closing.
