### ISSUE TITLE
Ignore some rooms for "sort by unread"

### ISSUE THREAD

**Issue by joao-paulo-parity** [Nheko-Reborn/nheko#687]
### The Problem

I have "Sort rooms by unread" activated but I don't care about some rooms (I am not allowed to leave them, either, for other reasons).

Therefore, I would like to have a way of ignoring some rooms from the "sort by unreads" criteria.

### The Solution

In the room's settings we could have an option "Ignore this room when sorting by unread" so that they are always assigned the lowest importance when the option "Sort rooms by unread" is activated, i.e. they would be on the bottom of the list.

### Happens in the latest version

- [X] Yes, this feature is still missing.

**Comment by deepbluev7** [comment]
You can tag those rooms and hide all rooms with that tag. You will only see them, once you click on that tag then.

**Comment by joao-paulo-parity** [comment]
> You can tag those rooms and hide all rooms with that tag. You will only see them, once you click on that tag then.

This is super useful! Thank you
