### ISSUE TITLE
'>' is not displayed properly for list items in Ctrl-K jump to room

### ISSUE THREAD

**Issue by joao-paulo-parity** [Nheko-Reborn/nheko#689]
### The Problem

When I'm searching with Ctrl-K (jump to room shortcut), the listed item is not displayed properly if the name has `>`. As an example, the room in the following screenshot is named `erin 🏕️-> 30th`, but it shows the HTML-escaped version of `>`.

![image](https://user-images.githubusercontent.com/77391175/130349683-cc5f113a-ef6f-46a4-82fa-44b45e266e98.png)

### The Solution

Show relevant characters without html-escaping them.

### Happens in the latest version

- [X] Yes, this feature is still missing.

**Comment by deepbluev7** [comment]
I think this is already fixed. Also this should have been a bug report. Which version did you experience this with?

**Comment by joao-paulo-parity** [comment]
> Also this should have been a bug report

Sorry! You're right, I got carried away with choosing this option because I also opened two other issues similar to this.

>  Which version did you experience this with?

0.8.2 which is the latest tag (https://github.com/Nheko-Reborn/nheko/tags).

```
> flatpak info io.github.NhekoReborn.Nheko

nheko - Desktop client for the Matrix protocol

          ID: io.github.NhekoReborn.Nheko
         Ref: app/io.github.NhekoReborn.Nheko/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 0.8.2
     License: GPL-3.0-or-later and CC-BY
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 46.4 MB
     Runtime: org.kde.Platform/x86_64/5.15
         Sdk: org.kde.Sdk/x86_64/5.15

      Commit: 1107d8f31a5392d783ab617249efe3a43d02e0e97fe913a026cfccfd5c6dd505
      Parent: fd6bc4192b34b4e2b4132f0150e3dd77e585ffeaa786dcda56b8cbd22d44cb3e
     Subject: Fix data to be date in appdata.xml (13cb9090)
        Date: 2021-04-29 09:57:55 +0000
```

**Comment by deepbluev7** [comment]
Okay, yeah, we fixed that already in the development version, so you will get a fix with the next release.
