### ISSUE TITLE
Add option to change date format

### ISSUE THREAD

**Issue by aaronraimist** [Nheko-Reborn/nheko#69]
Currently the dates in the room list are DD/MM(/YY). As an American this is hard to read. I'd like to be able to pick either YYYY-MM-DD or MM/DD/YY.

**Comment by deepbluev7** [comment]
I'd probably prefer it, if we would pick the system locale by the default. The hard part with that is, that  Qt doesn't have a locale specific way to format just day and month, only year or day, so we would have to find a different solution or change the way we show dates of the last 365 days.

**Comment by deepbluev7** [comment]
So, Nheko should now use the date format, that your OS uses for your current locale. Could you check, if that is enough to fix this issue for you?
