### ISSUE TITLE
Lite version that doesn't bundle GTK?

### ISSUE THREAD

**Issue by Darthagnon** [Nheko-Reborn/nheko#692]
### The Problem

[GTK for Windows](https://github.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer/releases) exists as an external dependency. Other open source projects ([czkawka](https://github.com/qarmin/czkawka), [szyszka](https://github.com/qarmin/szyszka)) attempt to use it, and thus shrink their installer size by a lot, as well as avoiding duplication of resources. Currently, nheko uses built-in GTK resources, and its installer is of a moderately large size.

### The Solution

Would a "lite" nheko Windows installer be possible, that uses system-wide GTK resources rather than bundling its own?

### Happens in the latest version

- [X] Yes, this feature is still missing.

**Comment by deepbluev7** [comment]
Nheko is using Qt, so how do you know it bundles GTK?
