### ISSUE TITLE
Release an update for mac!

### ISSUE THREAD

**Issue by iambumblehead** [Nheko-Reborn/nheko#694]
### The Problem

Fans following Nheko's rapid and awesome development want to experience its qml'd goodness but the last release was a few months ago on Apr 23

### The Solution

Release a new version of Nheko at the releases page right away https://github.com/Nheko-Reborn/nheko/releases

### Happens in the latest version

- [X] Yes, this feature is still missing.

**Comment by deepbluev7** [comment]
We won't be releasing that soon. We have a goal for the next release and for that we still need to implement 2 or 3 little bits. If you are impatient, try using the nightly linked in the README. We could use some testing on macOS and that should make a release come sooner. :3

**Comment by iambumblehead** [comment]
@deepbluev7 I'm trying the nightly today and its awesome. The sidebar rooms/channels list and the animated nheko logo on startup are both awesome. It looks great :) and thank you
