### ISSUE TITLE
Unable to "Copy link location" inside of quoted text in replies

### ISSUE THREAD

**Issue by resolritter** [Nheko-Reborn/nheko#695]
### Describe the bug

When the quoted message inside of a reply message has a link, if you right-click that link, there will be no "Copy link location" option.

### To Reproduce

1. Send a message with a link
2. Reply to it
3. In the replied message's content, right click the link and you'll notice the menu does not have the "Copy link location" option.

### Screenshots

![image](https://user-images.githubusercontent.com/17429390/130776874-5a181168-0295-488e-ae4f-1e12e5304961.png)

### Version

0.8.2-b5af1d81

### Operating system

Linux

### Installation method

Local build

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment]
Duplicate of #529

**Comment by deepbluev7** [comment]
But might make sense to implement this, but not the behaviour in #529.

**Comment by resolritter** [comment]
As far as I'm concerned this was fixed by https://github.com/Nheko-Reborn/nheko/pull/696, so closing
