### ISSUE TITLE
Custom emojis only displayed sometimes

### ISSUE THREAD

**Issue by tastytea** [Nheko-Reborn/nheko#701]
### Describe the bug

`<img data-mx-emoticon>` inside `org.matrix.custom.html` are only displayed sometimes. I don't have this problem with “normal” images. I used FluffyChat on Android to send the emoji.

Raw message:

``` json
{
    "content": {
        "body": ":raccoon_tea: ",
        "format": "org.matrix.custom.html",
        "formatted_body": "<img data-mx-emoticon=\"\" src=\"mxc://pixie.town/OYRIwyj8LRjhcvoAuiXBfkct\" alt=\":raccoon_tea:\" title=\":raccoon_tea:\" height=\"32\" vertical-align=\"middle\" />",
        "msgtype": "m.text"
    },
…
}
```

### To Reproduce

1. Write message with custom emoji

### What happened?

When someone writes a message with a custom emoji, the image is initially not displayed. If I change to another room and then back, the image is there. Another method to make them appear is with text selection.

When I change to 5-10 other rooms and come back, the image is not displayed again.

### Screenshots

Initially: ![No emoji](https://user-images.githubusercontent.com/3681516/131214487-6afd6669-cca7-4d66-ac65-19b065eb0782.png)
After changing the room: ![Yes emoji](https://user-images.githubusercontent.com/3681516/131214494-66da93b1-3eec-46f4-95c7-dcacd593cd6a.png)

### Version

0.8.2

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Qt version

5.15.2

### C++ compiler

gcc-10.3.0

### Desktop Environment

i3

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment]
This is fixed for the next release, but it will be a few weeks before that is actually out ;-)
