### ISSUE TITLE
add an option to directly seperate group chats and direct chats.

### ISSUE THREAD

**Issue by vachan-maker** [Nheko-Reborn/nheko#702]
### The Problem

I am always frustrated when nheko combines the group chats and 1 to 1 chats.😀

### The Solution

An option in the settings to filter group chats and direct chats

### Alternatives

Using tags

### Additional context

Neochat and element has this option

### Happens in the latest version

- [x] Yes, this feature is still missing.

**Comment by deepbluev7** [comment]
Duplicate of #296 #317

Please search the issue tracker before opening an issue .-.
