### ISSUE TITLE
Unable to access secret storage inside Flatpak

### ISSUE THREAD

**Issue by alistair23** [Nheko-Reborn/nheko#708]
### Describe the bug

Running Nheko nightly from flatpak on a PinePhone with Phost pmOS, Nheko is unable to connect to the secure storage.

I have gnome-keyring installed and other apps correctly use it, yet Nheko reports that it can't access the secure storage.

### To Reproduce

1. Install Nheko nightly on pmOS Phosh
2. Launch Nheko

### What happened?

I see a error pop up saying that: "Nheko could not connect to the secure storage..."

### Version

Nightly

### Operating system

Linux

### Installation method

Flatpak nightly repo or download

### Desktop Environment

Phosh

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment]
Do you know what dbus interface gnome-secrets uses? I thought it was --talk-name=org.freedesktop.secrets, and we do whitelist that?

**Comment by alistair23** [comment]
That looks right: https://gitlab.gnome.org/GNOME/geary/-/blob/mainline/org.gnome.Geary.json#L20

This is the error I see in the console:

```
[db] [error] Restoring secret 'm.cross_signing.master' failed (7): Unknown error
```

**Comment by alistair23** [comment]
I checked and I see the same error without the Flatpak when running on pmOS

**Comment by deepbluev7** [comment]
Is your secrets storage maybe not unlocked? Or is there any additional logging you could provide?

**Comment by alistair23** [comment]
The secrets are unlocked as other applications work. Any hints on where I could get better logs from?

**Comment by deepbluev7** [comment]
No, frankly, I don't know what's the issue here :D

**Comment by deepbluev7** [comment]
Can you try the latest flatpak? We were missing the libsecret library in it, which might have caused the issues.

**Comment by alistair23** [comment]
Trying the latest Flatpak, I don't see that error. Instead I just get stuck at the loading circle and never progress from there

**Comment by alistair23** [comment]
Looks like I'm hitting this issue: https://github.com/Nheko-Reborn/nheko/issues/816

**Comment by alistair23** [comment]
Fixed with the latest nightly flatpak
