### ISSUE TITLE
Latest master (54723b06) fails to start

### ISSUE THREAD

**Issue by unclechu** [Nheko-Reborn/nheko#715]
### Describe the bug

![2021-09-07 16-42-53](https://user-images.githubusercontent.com/799353/132355853-9097c005-b67b-43d8-8e75-61938e85475b.png)

d97e408c works normally, without this error.

### To Reproduce

1. Checkout to 54723b06
2. Build nheko
3. Run `nheko -p default`

### Expected behavior

Nheko runs normally

### Version

master: 54723b06

### Operating system

Linux

### Installation method

Local build

### Did you use profiles?

- [X] Profiles used?

**Comment by deepbluev7** [comment]
Related to #705 and #708

Did you setup some secret service like kwallet, gnome-secrets, keepassXC or similar?

**Comment by unclechu** [comment]
@deepbluev7 I have gnome-keyring.

**Comment by deepbluev7** [comment]
Okay, yeah, it seems like the same issue as in #708 then. Which version of qtkeychain do you have?

**Comment by unclechu** [comment]
@deepbluev7 

``` console
$ nix repl <<< '(import <nixpkgs> {}).qtkeychain.version'
Welcome to Nix version 2.3.15. Type :? for help.

"0.9.1"
```

**Comment by deepbluev7** [comment]
That is super old, can you try updating it to 0.12?

**Comment by unclechu** [comment]
@deepbluev7 it works with 0.12 (taken from nixos-unstable channel, instead of stable nixos-21.05).

**Comment by deepbluev7** [comment]
Okay, then I guess this is resolved?

**Comment by deepbluev7** [comment]
(Older Nheko versions actually did not work, they just didn't tell you they were broken)

**Comment by unclechu** [comment]
> Okay, then I guess this is resolved?

I think we can say so.

> (Older Nheko versions actually did not work, they just didn't tell you they were broken)

Yeah, makes sense. Since when I was trying to download the signing key nothing was happening. And now it actually works.

**Comment by unclechu** [comment]
@deepbluev7 maybe it would be nice to mention in the error message that “qtkeychain dependency is expected to be 0.12 version or higher”.

**Comment by deepbluev7** [comment]
I'll add it to the README instead._
