### ISSUE TITLE
Unable to delete edited messages.

### ISSUE THREAD

**Issue by DAMO238** [Nheko-Reborn/nheko#718]
### Describe the bug

If a message is edited and deleted (by any client), on nheko, the message remains visible. If the message is 'deleted' from nheko, then other non-nheko clients do see the deletion, despite it appearing to have done nothing in nheko.

### To Reproduce

1. Enter a room and send a message using any client.
2. Edit the message using any client.
3. Remove the message using any client.
4. View the deleted message in nheko.

### What happened?

I was trying to get strikethrough to work and was editing messages to try different methods (this was `<del>strikethrough</del>`). Afterwards, I decided to delete the message and retype it to avoid a massive edit history from my phone, running element. When I was using nheko later, I realised the message wasn't actually deleted and tried to delete it. After which, I did some tests to find that edited messages would always be visible in nheko, even if they are deleted.

### Expected behavior

The deleted, edited messages, should not be visible in nheko.

### Version

0.8.2.r533.g80fa3e80-1

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc), Local build

### Qt version

5.15.2+kde+r222-1

### C++ compiler

gcc 11.1.0-1

### Desktop Environment

i3 /w picom

### Did you use profiles?

- [ ] Profiles used?

### Relevant log output

```shell
Log file does not have any messages with the timestamp coinciding with when I did the tests.
```

**Comment by deepbluev7** [comment]
Yeah, I should really fix that, sadly the spec at that point only requires deleting the original event when deleting an edit...

**Comment by deepbluev7** [comment]
Fixed
