### ISSUE TITLE
Synchronise Nheko tags and Element Matrix spaces?

### ISSUE THREAD

**Issue by Darthagnon** [Nheko-Reborn/nheko#719]
### The Problem

Matrix recently introduced "Spaces", which work better than... whatever it was they had before. They also work more or less the same way as Nheko's tags.

### The Solution

Would it be possible to synchronise Nheko tags and Matrix Spaces?

### Happens in the latest version

- [X] Yes, this feature is still missing.

**Comment by deepbluev7** [comment]
Synchronize probably not, but the master branch can show spaces the same way as it does tags.

**Comment by Darthagnon** [comment]
Testing the latest nightly, and it does indeed display Spaces the same way as tags. Will it eventually be possible to create spaces in nheko, deprecating tags?

**Comment by deepbluev7** [comment]
Tags probably won't get deprecated, but creating spaces will come, yes.

**Comment by deepbluev7** [comment]
Can I close this then?
