### ISSUE TITLE
Use system image viewer

### ISSUE THREAD

**Issue by eddsalkield** [Nheko-Reborn/nheko#725]
### The Problem

Currently, Nheko has its own built-in image viewer, but I'd quite like to have to option for it to detect my preferred system-wide image viewer and launch that instead.

### The Solution

Using [XDG MIME types](https://specifications.freedesktop.org/mime-apps-spec/mime-apps-spec-latest.html) on Linux, perhaps with alternatives for other platforms, could allow Nheko to detect the preferred application for viewing the images.

### Happens in the latest version

- [X] Yes, this feature is still missing.

**Comment by deepbluev7** [comment]
You can right click the image and open it in an external program. It is one extra click, but otherwise does exactly what you want.

**Comment by eddsalkield** [comment]
Thanks for your tip!  On touchscreen devices, however, it might be nice to have this behaviour as the default.

**Comment by deepbluev7** [comment]
I don't see why it would be. Those image viewers need to store files unencrypted on disk, so in general they should be the second option. You can long press to access them on touch too.

**Comment by duarm** [comment]
anyway to overwrite this behavior? I would like to click in the image and open an external program by default.

**Comment by deepbluev7** [comment]
No, not unless someone implements that
