### ISSUE TITLE
Crash on creating new olm account

### ISSUE THREAD

**Issue by c7hm4r** [Nheko-Reborn/nheko#73]
### System:

- Nheko version: 0.6.4
- Installation method: local build
- Operating System: Fedora 30
- Qt version: 5.12.1
- C++ compiler: gcc
- Desktop Environment: Gnome under X11

### Actual behavior

On first start, after I passed the login credentials for matrix, nheko crashed. It does now immediately crash on start.

```
christoph@localhost:~/repos/nheko
$ build/nheko 
ssl3 ext invalid servername
ssl3 ext invalid servername
[2019-06-03 00:20:42.149] [ui] [info] jdenticon plugin not found.
[2019-06-03 00:20:42.170] [ui] [info] starting nheko 0.6.4-1b34b53
[2019-06-03 00:21:16.445] [db] [info] initializing LMDB
[2019-06-03 00:21:16.475] [crypto] [info] creating new olm account
Aborted (memory dump written)
[134]christoph@localhost:~/repos/nheko
$ build/nheko 
ssl3 ext invalid servername
ssl3 ext invalid servername
[2019-06-03 00:21:42.459] [crypto] [info] creating new olm account
Aborted (memory dump written)
```

### Expected behavior

It should not crash

### Steps to reproduce

1. Build nheko according to the README
2. `build/nheko`
3. Log in using the full matrix username `@user:matrix.org`
-> crash

### Logs

Log is empty.

### Debugger backtrace

https://gist.github.com/c7hm4r/66fc1f72e3a6e822016a38daa8ca87a4

**Comment by c7hm4r** [comment]
Possibly I messed something up with my `libolm` installation. I previously had a self-built `libolm.so` under `/usr/local/lib64/` while an older `libolm.so` was already installed from OS package sources under `/lib64/`.

Solution: I uninstalled the OS package, copied the self-built `libolm.so*` to `/lib64/` and rebuilt Nheko. Now it works.

**Comment by redsky17** [comment]
Thanks for the due diligence with investigating the root cause!
