### ISSUE TITLE
Unseen removed messages are not acknowledged as read upon visiting the room

### ISSUE THREAD

**Issue by resolritter** [Nheko-Reborn/nheko#731]
### Describe the bug

Someone sent multiple of messages in a room I was in and later deleted all of them. I did not get to see the messages before they removed them and only knew the messages were sent due to notifications.

When I later opened the room in Nheko, the unread count was not cleared when I visited it. The unread count matched the number of deleted messages so that is how I noticed the correlation.

I restarted Nheko and then something weird happened: the unread could vanished for a while, but then it came back some time after (say, 30 minutes or something like that...). Then I switched to Element web and noticed the unread count was also appearing there, but it vanished when I visited the room; I was not able to do the same using Nheko.

Based on all this evidence, it seems like Nheko does not acknowledge unseen removed messages as being read when you visit a room, but Element does.

### To Reproduce

1. Have someone sent a message in a room you are in
2. Ask them to delete the message
3. Visit the room and you'll notice the unread count will still be active

### Version

0.8.2-3f8bb19b

### Operating system

Linux

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment]
I believe I fixed this for 0.9.0.
