### ISSUE TITLE
"Nheko could not connect to the secure storage to save encryption secrets."

### ISSUE THREAD

**Issue by qazip** [Nheko-Reborn/nheko#733]
### Describe the bug

When opening nheko, I am getting a pop-up window which starts with:

"Nheko could not connect to the secure storage to save encryption secrets.". Then mentions KWallet and whatnot. In terminal I get:

`[2021-09-24 08:12:36.586] [db] [error] Restoring secret 'm.cross_signing.master' failed (7): Could not connect: Permission denied`

I have `extra/qtkeychain-qt5 0.12.0-1 [installed]` and `extra/keychain 2.8.5-2 [installed]` and `extra/gnome-keyring 1:40.0-1 (gnome) [installed]` installed. What else do I need?

I am using `aur/nheko-git 0.8.2.r386.g35b36e24-1 (+24 0.77) (Installed: 0.8.2.r596.gd499fffb-1)` from AUR.

### To Reproduce

Open Nheko.

### What happened?

Error.

### Expected behavior

No error.

### Version

aur/nheko-git 0.8.2.r386.g35b36e24-1 (+24 0.77) (Installed: 0.8.2.r596.gd499fffb-1)

### Operating system

Arch

### Desktop Environment

(wm) i3

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment]
Did you install and configure something like gnome keyring, kwallet or keepassXC?

**Comment by qazip** [comment]
gnome-keyring is installed and running. and it works in other software so I guess it is configured?

**Comment by qazip** [comment]
Nevermind. If I run it without firejail it works as intended.

**Comment by deepbluev7** [comment]
I guess you need to fix your firejail config then to allow access to that dbus interface.
