### ISSUE TITLE
Nightly appimage (nheko-master-07fbd13a-x86_64) is missing libQt5Svg.so.5

### ISSUE THREAD

**Issue by bbhtt** [Nheko-Reborn/nheko#735]
### Describe the bug

Nightly appimage (nheko-master-07fbd13a-x86_64) missing libQt5Svg.so.5.

### To Reproduce

Download https://matrix.neko.dev/_matrix/media/r0/download/neko.dev/XmSyqBWQdeRjVgrufPItyHTy and try to run ??(`$ chmod +x nheko-master-07fbd13a-x86_64.AppImage`, `$ ./nheko-master-07fbd13a-x86_64.AppImage`)

Error:
```
squashfs-root/usr/bin/nheko: error while loading shared libraries: libQt5Svg.so.5: cannot open shared object file: No such file or directory
```

### Version

master-07fbd13a

### Operating system

Linux

### Installation method

AppImage

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment]
Yeah, we need to either fix that by messing with the AppImage build again or we are just going to remove it. It is far too difficult to build a working appimage, the flatpaks are much more reliable.

**Comment by deepbluev7** [comment]
I decided to drop the AppImage we provide for now. It is just too annoying to maintain. If someone wants to see this come back, please step up and open a PR. It was removed in b27b7c9482ef62e1828f9bd4f804ba4a8bf2b074, which you can use as a starting point. I know, this is not the resolution you probably wanted to see, but maintaining the AppImage is a lot of effort and there are a lot of AppImage specific bugs, which we never solved. We need someone, who actually uses the AppImage, to maintain it.
