### ISSUE TITLE
Feature request: Embedded video playback

### ISSUE THREAD

**Issue by alex-tee** [Nheko-Reborn/nheko#74]
Ability to view videos inside nheko like in riot. When you upload videos it shows some blank space atm.

**Comment by MasterOfTheTiger** [comment]
This seems to be possible with this: https://doc.qt.io/qt-5/videooverview.html

The code seems to be at [src/timeline/TimelineItem.cpp](https://github.com/Nheko-Reborn/nheko/blob/0.7.0-dev/src/timeline/TimelineItem.cpp) if anyone wants to work on this after there being more discussion about this.

**Comment by deepbluev7** [comment]
You should be able to play videos in nheko now directly in the timeline. Please reopen this, when it doesn't work for you.
