### ISSUE TITLE
Room settings misaligned if room ID is long-ish

### ISSUE THREAD

**Issue by tastytea** [Nheko-Reborn/nheko#746]
### Describe the bug

If the internal room ID is a bit longer than most, the buttons and other controls are shoved to the right, outside of the room settings window.

### To Reproduce

1. Join !TioxbMCjhsofiKWqSW:matrix.sp-codes.de a.k.a. #GNULinuxTalk:matrix.sp-codes.de
2. Open room settings

### Screenshots

![Screenshot](https://user-images.githubusercontent.com/3681516/135718653-cd54bab4-9060-42af-9a43-5472c0c671e9.png)

### Version

9da10b1 (master branch from 2021-10-01)

### Operating system

Linux

### Installation method

Local build

### Qt version

5.15.2

### C++ compiler

gcc-10.3.0

### Did you use profiles?

- [ ] Profiles used?

**Comment by tastytea** [comment]
This was fixed a while ago. The internal ID is now displayed in a much smaller font. Should be all right for rooms on servers with domain names with up to 40 characters or so. 

I don't know what happens when a room is on a server with a domain name that is longer than that, but who would do such a thing? 😊

**Comment by deepbluev7** [comment]
lol, yes, before the roomid actually used a 20% larger font than anything else...
