### ISSUE TITLE
Support the creation/edition of Spaces

### ISSUE THREAD

**Issue by qazip** [Nheko-Reborn/nheko#747]
### The Problem

One cannot create nor edit Spaces in Nheko.

### The Solution

So, it would be nice if one could:

- Create new Spaces;
- Join Spaces (?);
- Edit Spaces;

### Happens in the latest version

- [X] Yes, this feature is still missing.

**Comment by LorenDB** [comment]
Joining spaces is supported. Editing them is limited to what you can do to regular rooms. (Note that the editing stuff is not yet released, so you'll have to run a nightly to get it for now.)

**Comment by LorenDB** [comment]
It turns out that we also support creating spaces. Please note that nheko refers to spaces as "communities" within the app.
