### ISSUE TITLE
Scrolling in touchscreen mode on a mobile is very buggy

### ISSUE THREAD

**Issue by SamuelNorbury** [Nheko-Reborn/nheko#749]
### Describe the bug

Scrolling up through existing messages is very buggy and randomly jumps back to the bottom of the messages list (without new messages being sent or any external events).

### To Reproduce

1. Go to a chat with many messages on a mobile linux device using touchscreen mode.
2. Try to scroll up through the messages.

### What happened?

chat jumps up and down, _mostly_ going in the right direction but it takes multiple tries

### Expected behavior

smooth scrolling in the right direction.

### Version

0.8.2-05c1d1b8ac

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Did you use profiles?

- [ ] Profiles used?

**Comment by LorenDB** [comment]
This a known issue that also happens on desktop. It will be fixed when we switch to Qt 6.2 instead of 5.15.

**Comment by deepbluev7** [comment]
See also https://bugreports.qt.io/browse/QTBUG-90734

**Comment by sc0w** [comment]
the same here, the scroll is a nightmare xD

instead, we can scroll using the keys <kbd>PgUp</kbd> and <kbd>PgDn</kbd> with squeekboard (mobian phosh pinephone)

**Comment by maltee1** [comment]
Is this fixed? It's not perfect yet, but it mostly works. At least it's no longer "very" buggy.
