### ISSUE TITLE
Allow User to Specify LMDB Password

### ISSUE THREAD

**Issue by redsky17** [Nheko-Reborn/nheko#75]
Let users choose their own LMDB password (optionally).  Ideally, the file would be re-encrypted on system suspend, screen lock, etc, so that it would need to be re-entered next time.

**Comment by deepbluev7** [comment]
The solution currently would probably use the keychain. Encrypted messages would be stored encrypted with the decryption secret being stored in the keychain. The user can then control access to that using his DE settings.

**Comment by deepbluev7** [comment]
Fixed in c80e253a2432d39c5548052fabeeb7408eda1f23

A secret 64 char string is generated and stored in the platform specific wallet. The user has control over how secure their wallet, gnome-keyring, keychain, whatever is.
