### ISSUE TITLE
Connection to server is silently lost when device changes network interfaces.

### ISSUE THREAD

**Issue by notinecrafter** [Nheko-Reborn/nheko#753]
### Describe the bug

When the machine changes network connections, nheko appears to lose the connection to the matrix server.
This means messages will forever remain in the sending state and no new messages are received.
The user is not immediately notified of this.

### To Reproduce

1. Open Nheko
2. Change your laptop from wired to wireless (or do some similar action, as described below)
3. Attempt to send a message
4. Confirm that the message remains in the sending state indefinitely

### What happened?

Machines can change network interfaces in a number of scenarios; for example, a laptop could switch from wired to wireless (removing the wired interface), a wireless interface could be disconnected, or the device can go to sleep - temporarily severing the network interface.

In these scenarios, Nheko loses its connection to the server.
This means messages will remain in the sending state indefinitely, and that no new messages can be received.
The problem can be fixed by restarting Nheko, which will cause it to resend the pending messages and display any new ones.

The user is never notified of this connection drop, so this issue can be rather annoying, as it can cause one miss messages without being aware of it.

### Expected behavior

Nheko should attempt to open a new connection once the interface stops existing, or at the very least notify the user the connection has been lost.

### Version

0.8.2-3dc1c3d7

### Operating system

Linux, macOS

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Desktop Environment

KDE Plasma on Linux, Aqua on MacOS

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment]
How long did you wait for Nheko to switch connection? It should notice it after 60s at least.

**Comment by notinecrafter** [comment]
I've waited for several hours, with still no resolve; sometimes I switch to wi-fi, and only notice the problem once I realise I haven't had any messages in a while, or when I send a message and it keeps sending indefinitely.

**Comment by deepbluev7** [comment]
Partially related to #428

**Comment by deepbluev7** [comment]
Have you verified, that this still happens with 0.9.0? In theory it should be fixed there.
