### ISSUE TITLE
Don't show loading spinner above a room creation event in the timeline

### ISSUE THREAD

**Issue by Cadair** [Nheko-Reborn/nheko#754]
### Describe the bug

When you load a new room, the backpaging spinner is shown above the creation event. There is obviously nothing for it to be loading there.

### To Reproduce

1. join new room
2. observer spinner

### Version

0.8.2-c514acb7

### Operating system

Linux

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment]
That's a regression from this: https://github.com/Nheko-Reborn/nheko/blob/master/src/timeline/TimelineModel.cpp#L701

Just didn't have the time to fix it.
