### ISSUE TITLE
MacOS nightlies no longer published?

### ISSUE THREAD

**Issue by lbeltrame** [Nheko-Reborn/nheko#756]
### Describe the bug

As the title says. Checking the "Nheko Nightllies" room only shows artifacts for Linux (flatpaks) and Windows.
However the CI builds for MacOS are green.

### Expected behavior

MacOS nightlies should be there.

**Comment by redsky17** [comment]
Ah, it seems to be an issue with the macOS runner.  @deepbluev7 updated his certificate recently, and it seems like either macOS Mojave or the specific version of python we're using hasn't been updated to include the new root certificate used to sign the LE cert.  Thanks for bringing this to my attention.  I'll look into it.

**Comment by deepbluev7** [comment]
Fixed by forcing the lets encrypt setup to use the "ISRG Root X1" using --preferred-chain.
