### ISSUE TITLE
Support markdown input for strikethroughs

### ISSUE THREAD

**Issue by VarLad** [Nheko-Reborn/nheko#758]
### The Problem

nHeko Reborn supports md, but not strike throughs

### The Solution

When typed 
```
Hi, I am ~~not~~ an alien
```
It should render as
Hi, I am ~~not~~ an alien

### Additional context

![Screenshot from 2021-10-11 17-11-52](https://user-images.githubusercontent.com/51269425/136784386-07ef8c62-db10-4e22-8410-ff282d48da6f.png)

Current state of the problem

### Happens in the latest version

- [X] Yes, this feature is still missing.

**Comment by VarLad** [comment]
Thanks
Thats a nice workaround
Although, lets keep the issue open until it gets implemented so others can find the issue and the workaround as well

**Comment by LorenDB** [comment]
Really, this problem will only be fixed if we switch to a different MD parser; CommonMark isn't going to just add extra features to their reference implementation, which is what we use.

**Comment by deepbluev7** [comment]
I mean, there is a cmark variant that supports the github extensions, which includes strikethrough (cmark-gfm) or we could just write an extension for cmark ourselves, that we use in addition to the current parser.

**Comment by deepbluev7** [comment]
Fixed in ec3ba352c0a46b3776b224cb3101619698fa8e26, some limitations apply.

**Comment by hiiamboris** [comment]
@deepbluev7 for some reason it's not getting rendered in my 0.11.3:
![](https://i.gyazo.com/98d25d7e3244535cf3755e45c376cb43.png)
