### ISSUE TITLE
Very old messages show up as newest

### ISSUE THREAD

**Issue by tastytea** [Nheko-Reborn/nheko#761]
### Describe the bug

There were some connection problems (don't know if it was one of the matrix servers or my connection), now the message history is messed up. Don't know if that's connected.

### To Reproduce

Don't know how to reproduce.

### What happened?

The last message in `#gentoo:matrix.org` was from 2021-10-14 14:28. Below that are messages from 2021-08-22 and 2021-08-21 (in that order). This persists across restarts.

### Expected behavior

Messages in chronological order.

### Screenshots

![screenshot_2021-10-14T16:47:45](https://user-images.githubusercontent.com/3681516/137342701-808049ce-3504-42e2-80c8-3e9d97cb1655.png)

### Version

Commit c43c2bd4b9481f761e9f1b16453f0e7f5b1beabe from 2021-10-03

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Qt version

5.15.2

### C++ compiler

gcc-10.3.0

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment]
This is not a Nheko issue, those messages were just delivered out of order by your homeserver (since /clear-timeline fixed it). There will be improvements to handling this in the future, but that is separate from this bug.
