### ISSUE TITLE
Windows Installer Unexpected exit code 1 (Windows 7)

### ISSUE THREAD

**Issue by Avispa** [Nheko-Reborn/nheko#762]
### Describe the bug

Installer Error:
`Error during installation process (io.github.nhekoreborn.nheko): Execution failed (Unexpected exit code: 1): "C:\Windows\System32\reg.exe ADD HKEY_CLASSES_ROOT\matrix /f /t REG_SZ /d URL:Matrix Protokol"`

**_Update_**: and more similar errors after clicking "ignore" only differs in the registry key:
* ... \matrix\shell\open\command /f
*  ... \matrix\shell\open\command /f /t REG_SZ /d "E:\Program.......\nheko.exe" "%1""
* .... and more ... -- clicked through them by accident but only difference is the stuff passed to `reg.exe` so probably the error lays somewhere in `reg.exe` anyway (or missing permissions more likely since I also checked the syntax roughly). 

**_Addition 2_**: File `C:\Windows\System32\reg.exe` exists. Also had Brief look into the syntax of "my" `reg.exe` and it looks okayish without diving into details.

### To Reproduce

1. Installer for Windows for _nheko_ 0.8.2
2. Choose partition *other* than C:\

### Expected behavior

Registers protocol without error.

### Version

0.8.2

### Operating system

Windows 7

### Installation method

Windows download

### Did you use profiles?

- [ ] Profiles used?

**Comment by Rainb0wCodes** [comment]
I have the same error and I'm on Windows 11

**Comment by Rainb0wCodes** [comment]
@Avispa you need to run the installer as Administrator

**Comment by deepbluev7** [comment]
The windows installer got removed and replaced with msix for the next release :)
