### ISSUE TITLE
Nheko Crashes on Mobian At Login When Password is Typed

### ISSUE THREAD

**Issue by Simmonz** [Nheko-Reborn/nheko#765]
### Describe the bug

When trying to login to Nheko on my Pinephone which uses Mobian when I get to typing my password into the login field the app crashes.

### To Reproduce

1. Install Nheko on Mobian
2. Run Nheko
3. Attempt to Login to Matrix

### What happened?

The app crashes when attempting to login

### Expected behavior

To login successfully.

### Screenshots

[log.txt](https://github.com/Nheko-Reborn/nheko/files/7355327/log.txt)

### Version

0.7.2

### Operating system

Other

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Desktop Environment

Phosh/Gnome 3.38.5

### Did you use profiles?

- [ ] Profiles used?

### Relevant log output

```shell
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
ssl3 ext invalid servername
ssl3 ext invalid servername
[2021-10-13 13:57:34.904] [ui] [info] jdenticon plugin not found.
[2021-10-13 13:57:34.933] [ui] [info] starting nheko 0.7.2
```

**Comment by deepbluev7** [comment]
Use a version newer than 0.7.2 or get the packagers to use the right compilation flags. This is fixed already ;.)
