### ISSUE TITLE
Some messages are still encrypted after verification

### ISSUE THREAD

**Issue by VarLad** [Nheko-Reborn/nheko#770]
### Describe the bug

Some messages are still encrypted after verification

### To Reproduce

1. Logout and login in a new session
2. View encrypted messages

### What happened?

They're encrypted and can't be viewed

### Expected behavior

They were supposed to be visible

### Screenshots

![Screenshot from 2021-10-20 20-30-26](https://user-images.githubusercontent.com/51269425/138118805-5f64b24c-0c79-41c3-a2db-fd7e94e51de3.png)

### Version

0.8.2-33ad65dc | Linux

### Operating system

Linux

### Installation method

Flathub

### Desktop Environment

GNOME41

### Did you use profiles?

- [ ] Profiles used?

**Comment by VarLad** [comment]
@deepbluev7 Is there a Flatpak available of the pre-released version 0.9.0 to try it out?

**Comment by VarLad** [comment]
This only happens with cross-verification for some reason

But if I import the exported keys from Element, it works fine
Any idea @deepbluev7 ? Also happens in v0.9.0

**Comment by deepbluev7** [comment]
Nheko should rerequest the keys, if you restart it once after verification. Does it not do that? Is online key backup enabled?

**Comment by JulianGro** [comment]
Similar problem here.
I needed to run Element (for hosting the keys I assume) and restart nheko multiple times for all messages to get decrypted.
