### ISSUE TITLE
The window is too big for my screen

### ISSUE THREAD

**Issue by mlell** [Nheko-Reborn/nheko#771]
### Describe the bug

The Nheko window does not adapt to my screen (too big) and behaves erroneously when resizing (which is hard because the top and bottom of the window is not visible)

### To Reproduce

I have a Lenovo Yoga C740 with a 14'' screen. I have a HiDPI screen.

1. 1920x1080 Pixel screen
2. Windows 10, global scaling 150&
3. Install and open Nheko for the first time.

### What happened?

The window is too big for my screen. Title bar is not visible and the buttons to log in not as well.

If I try to resize it, it vanishes to somewhere outside the screen (I see it moving fast, then it's gone).

### Expected behavior

Nheko window fits on the screen, I can see the whole window and it does not move off-screen quickly when I try to resize it.

### Screenshots

![grafik](https://user-images.githubusercontent.com/16210594/138132581-0df17295-d465-4efe-9a14-3298f80899c7.png)

### Version

0.8.2

### Operating system

Windows

### Installation method

Windows download

### Did you use profiles?

- [ ] Profiles used?

**Comment by LorenDB** [comment]
For now you could try using snap keys to get the window down to size, I guess

**Comment by exaCORE42** [comment]
I have also had this issue on the latest commit.  Nheko always starts around 100 pixels taller than my screen is (my total screen height is 768 pixels, but (according to the config file), Nheko starts around 863 pixels tall.  This is relatively minor because simply un-maximizing and re-maximizing the window fixes the issue, but it can get annoying.

**Comment by LorenDB** [comment]
This is a somewhat known bug and honestly, I should try fixing it before 0.9.0

**Comment by opusforlife2** [comment]
I have a 1366 x 768 screen, and Nheko 0.9.0 always starts with a large window size, such that its right and bottom sections are cut off by the screen. Thankfully, the top left corner is well inside the screen, so it is trivial to reduce the size and/or maximise it.

But Nheko should remember the last window size and position, as well as maximised/non-maximised state anyway. Should I open a new issue for this?

**Comment by deepbluev7** [comment]
> Should I open a new issue for this?

No, it is the same issue. We didn't have time to fix it for 0.9.0, because it would break other stuff unless we change a lot of things.

**Comment by deepbluev7** [comment]
Seems like I fixed this.
