### ISSUE TITLE
Alpine Linux - Libcmark 0.30.2 installed, installer still looking for 0.30.1

### ISSUE THREAD

**Issue by Joshndroid** [Nheko-Reborn/nheko#772]
### Describe the bug

ERROR: unable to select packages:
  so:libcmark.so.0.30.1 (no such package):
    required by: nheko-0.8.2-r6[so:libcmark.so.0.30.1]

It appears that it is still looking for an older package whereas the new package is 0.30.2

### To Reproduce

Follow installation method as outlined in the github.

receive error as outlined above

install libcmark, cmark, et al from the package manager and try again to which the issue remains.

### What happened?

Attempting to install on alpine linux as its a great program.

After running apk add nheko got an error regarding libcmark

installed libcmark, cmark, cmark-dev, cmark-static all of which were 0.30.2 - https://pkgs.alpinelinux.org/package/edge/community/armv7/libcmark

attempt to instakk nheko again to which error persists.

checked /usr/lib and see that libcmark.so.0.30.2 is installed a necessary... it appears its looking for an outdated one?

### Expected behavior

Install nheko as per included installation docs

### Version

latest

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Desktop Environment

xfce4

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment]
Closing, because I really think the distro package just wasn't rebuilt. (And there was no reply)
