### ISSUE TITLE
the settings channel dialog is not fit to screen in phone (pinephone)

### ISSUE THREAD

**Issue by sc0w** [Nheko-Reborn/nheko#779]
### Describe the bug

the settings channel dialog is not fit to screen in phone

### To Reproduce

1. Go to the settings dialog in a channel.

### What happened?

2. the appearance is wrong.

### Expected behavior

it must be fit to the screen

### Screenshots

![2021-10-31_11-45](https://user-images.githubusercontent.com/7734191/139578991-30c7c413-55fc-4af0-a53a-08f3270f3806.png)

### Version

0.8.2

### Operating system

Linux

### Installation method

debian package installed from debian sid

### Desktop Environment

mobian bookworm, pinephone

**Comment by deepbluev7** [comment]
Have you tried it in 0.9.0?

**Comment by sc0w** [comment]
yes, I confirm the issue in nheko 0.9.0 (deb package installed from debian sid)

**Comment by deepbluev7** [comment]
Thank you for verifying! <3
