### ISSUE TITLE
/confetti messages are not sent or received.

### ISSUE THREAD

**Issue by DAMO238** [Nheko-Reborn/nheko#780]
### Describe the bug

For the rest of this report, assume all messages start with '/confetti'. Messages that are sent from Nheko are not visible on any device, including the sender's. If a non-nheko device sends the message, the message appears in Nheko as 'Unretrieved event'. Selecting 'view raw message' yields no results.

### To Reproduce

1. Send a message starting with '/confetti' from Nheko
2. Attempt to view said message on any device
3. Send a message starting with '/confetti' from a non-Nheko device
4. Attempt to view said message on a Nheko device

### What happened?

The message sent from nheko was not visible anywhere and the one sent from elsewhere was seen as Unretrieved event.

### Expected behavior

The message sent from Nheko should be visible to everyone and the one sent from elsewhere should be visible from Nheko even if no confetti is shown.

### Screenshots

![image](https://user-images.githubusercontent.com/32229196/139590118-ebce9160-cdd7-4f1b-83b1-22331d690df4.png)

### Version

0.8.2-7a9c69cb

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Qt version

5.15.2+kde+r254-1

### C++ compiler

gcc 11.1.0-1

### Desktop Environment

i3 /w picom

### Did you use profiles?

- [ ] Profiles used?

### Relevant log output

```shell
No logs created at time of relevant events.
```

**Comment by deepbluev7** [comment]
Confetti messages are not part of the spec, but an Element extension. As such they won't work in other clients properly. We could show a better fallback though probably in such cases.

**Comment by DAMO238** [comment]
Yes, sorry for the confusion. This is exactly what I mean. If we simply show a literal /confetti rather than hiding the message, at least any attached message is visible.

**Comment by LorenDB** [comment]
Confetti is supported now
