### ISSUE TITLE
Able to click through bar at the bottom of the room list

### ISSUE THREAD

**Issue by exaCORE42** [Nheko-Reborn/nheko#783]
### Describe the bug

This is a very small bug where you are able to click through the bar at the bottom of the room list (which houses the settings button, the room directory button and the start new chat button).  See image below for reference.

### To Reproduce

1. Go to the bar below the room list
2. Click to the right or left of one of the buttons present on the white bar.
3. See that you can select a room

### What happened?

I can click through the bar mentioned previously and select/view rooms which are 'under' the bar

### Expected behavior

You should not be able to click through the bar.

### Screenshots

![image](https://user-images.githubusercontent.com/85199808/140099911-826baee1-cbd9-4f20-9a42-306dc9a1ecaf.png)

As you can see, my mouse is on the bar, not the room, but I can select the room.

### Version

0.8.2-a9dde2ef

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Qt version

5.15.2+kde+r254

### C++ compiler

gcc 11.1.0

### Desktop Environment

KDE

### Did you use profiles?

- [ ] Profiles used?

**Comment by maltee1** [comment]
I can't reproduce this (anymore)

**Comment by deepbluev7** [comment]
Ah, right, I fixed that by using a Pane
