### ISSUE TITLE
'Bubble' animation after clicking room directory or new chat button not centered correctly

### ISSUE THREAD

**Issue by exaCORE42** [Nheko-Reborn/nheko#785]
### Describe the bug

This is a small issue where the bubble animation after clicking room directory button or new chat button centered on mouse pointer not the button (see attached GIF).

### To Reproduce

1. Go to the new chat button or room directory button
2. Click slightly off-center of the button

### What happened?

The 'bubble' animation is not centered on the button I just clicked, rather it is centered on the mouse pointer.

### Expected behavior

The bubble animation should be centered on the button I just clicked.  It would look better that way (in my opinion).

### Screenshots

![untitled](https://user-images.githubusercontent.com/85199808/140195843-ce5ef095-dee7-48a1-bae1-1676a8746546.GIF)

As you can see the bubble is centered on the mouse pointer.

### Version

0.8.2-a9dde2ef

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Qt version

5.15.2+kde+r254

### C++ compiler

gcc 11.1.0

### Desktop Environment

KDE

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment]
That is intentional, it shows where you clicked, not where the button is!
