### ISSUE TITLE
Stickers on IOS send and display for non IOS users but not the sender

### ISSUE THREAD

**Issue by K1D77A** [Nheko-Reborn/nheko#786]
### Describe the bug

Multiple users of my stickerservice who have Apple IOS devices are able to send stickers successfully into a room, however they cannot see the stickers they send and they cannot see stickers that are sent by others.
What a user of mine sees:
![image](https://user-images.githubusercontent.com/10334164/140380495-444d0bc5-3a5e-4c10-9142-29a9d0d4f573.png)
On element web I am able to see what they have sent:
![image](https://user-images.githubusercontent.com/10334164/140380604-7f179266-b4db-4721-a4ba-1e475d4db778.png)

They cannot see stickers sent by others either!
## The events
This is the event sent into Matrix from the IOS Device
```js
{
  "room_id": "!cllJYBlqcviJqfBTak:scyldings.com",
  "type": "m.sticker",
  "content": {
    "url": "mxc://scyldings.com/xCXUvAFVUacNReJrBTmqXKkC",
    "info": {
      "size": 24819,
      "w": 128,
      "mimetype": "image/png",
      "h": 128,
      "thumbnail_info": {
        "size": 7577,
        "w": 64,
        "mimetype": "image/png",
        "thumbnail_url": "mxc://scyldings.com/JlTohjJVbQfNcdGgZvfHFdbw",
        "h": 64
      }
    },
    "body": "PepeHands"
  }
}
```
This is the JS that is generated for the event @ my stickerservice 
```js
(function () {
    var data = { name : 'PepeHands',
                 description : 'PepeHands',
                 file : 'PepeHands.png',
                 content : { url : 'mxc://scyldings.com/xCXUvAFVUacNReJrBTmqXKkC',
                             body : 'PepeHands',
                             info : { w : 128,
                                      h : 128,
                                      mimetype : 'image/png',
                                      size : 24819,
                                      thumbnail_info : { h : 64,
                                                         w : 64,
                                                         mimetype : 'image/png',
                                                         thumbnail_url : 'mxc://scyldings.com/JlTohjJVbQfNcdGgZvfHFdbw',
                                                         size : 7577
                                                       }
                                    }
                           },
                 description : 'PepeHands'
               };
    return threeThousandThreeHundredFortySixth = { api : 'fromWidget',
             action : 'm.sticker',
             widgetId : 'stickerpicker',
             requestId : 'sticker-ready-3845032729',
             data : data,
             widgetData : data
           };
})();
```
## Known versions
Iphone SE - Element 1.6.5
Iphone 8 - Element 1.6.5 

### To Reproduce

.

### Version

1.6.5

### Operating system

Other

### Did you use profiles?

- [ ] Profiles used?

**Comment by redsky17** [comment]
Hey friend, I think you might have the wrong repository here!  The repo for element iOS is here: https://github.com/vector-im/element-ios

If you meant that you can't view element stickers on nheko, that's because element has their own implementation that is different than the one used by nheko and other clients (such as fluffychat).

**Comment by deepbluev7** [comment]
And if you mean, that element can't see stickers sent from Nheko, that is because iOS needs a thumbnail, even though the spec says none is needed (and it makes no sense on stickers): https://github.com/vector-im/element-ios/issues/2353

**Comment by K1D77A** [comment]
Frick

**Comment by K1D77A** [comment]
Yeh sorry wrong app.
