### ISSUE TITLE
in image viewer, allow to zoom with two fingers in touchscreens

### ISSUE THREAD

**Issue by sc0w** [Nheko-Reborn/nheko#787]
### The Problem

unable to zoom in image viewer

### The Solution

allow to zoom the images with two fingers, in touchscreens

### Happens in the latest version

- [X] Yes, this feature is still missing.

**Comment by LorenDB** [comment]
This could probably be done at the same time the image dialog is QMLed

**Comment by deepbluev7** [comment]
Done
