### ISSUE TITLE
Nheko crashes at startup with KeePassXC running as a secure storage

### ISSUE THREAD

**Issue by maxigaz** [Nheko-Reborn/nheko#789]
### Describe the bug

After installing `nheko-git` from the AUR on Manjaro Linux, I'm presented with a popup message saying that Nheko could not connect to the secure storage for saving encryption secrets. It also mentions KeePassXC, which I happen to have installed (v2.6.6), so I enabled Secret Service integration in its options. Now, Nheko's empty window briefly appears, and then crashes.

### To Reproduce

1. Enable Secret Service integration in the settings of KeePassXC.
2. Rename or remove `~/.config/nheko/nheko.conf`
3. Run `nheko --debug`

### What happened?

Nheko briefly showed an empty window and then crashed.

(It also created `nheko-crash.dump`; see its contents attached here: [nheko-crash.dump.txt](https://github.com/Nheko-Reborn/nheko/files/7488560/nheko-crash.dump.txt))

### Expected behavior

Nheko keeps running.

### Version

0.8.2-ac9601e4

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Qt version

5.15.2

### C++ compiler

gcc 11.1.0

### Desktop Environment

i3

### Did you use profiles?

- [ ] Profiles used?

### Relevant log output

```shell
[2021-11-05 20:10:03.757] [ui] [info] Restoring window size 0x0
[2021-11-05 20:10:03.813] [ui] [info] WebRTC: initialised GStreamer 1.18.5
[2021-11-05 20:10:04.013] [ui] [info] jdenticon plugin not found.
[2021-11-05 20:10:04.277] [ui] [debug] Profile requested
[2021-11-05 20:10:04.334] [ui] [debug] Status changed to 1
[2021-11-05 20:10:04.340] [ui] [debug] WebRTC: audio device added: Family 17h (Models 00h-0fh) HD Audio Controller Analóg sztereó
[2021-11-05 20:10:04.347] [ui] [debug] Profile requested
[2021-11-05 20:10:04.357] [ui] [debug] Profile requested
[2021-11-05 20:10:04.402] [qml] [debug] static bool LibSecretKeyring::findPassword(const QString&, const QString&, QKeychain::JobPrivate*) (:0, )
[2021-11-05 20:10:04.420] [qml] [debug] static bool LibSecretKeyring::findPassword(const QString&, const QString&, QKeychain::JobPrivate*) (:0, )
[2021-11-05 20:10:04.421] [qml] [debug] static bool LibSecretKeyring::findPassword(const QString&, const QString&, QKeychain::JobPrivate*) (:0, )
[2021-11-05 20:10:04.423] [qml] [debug] static bool LibSecretKeyring::findPassword(const QString&, const QString&, QKeychain::JobPrivate*) (:0, )
[2021-11-05 20:10:04.621] [ui] [info] starting nheko 0.8.2-ac9601e4
[2021-11-05 20:10:04.651] [db] [debug] setting up cache
[2021-11-05 20:10:04.652] [crypto] [info] creating new olm account
[2021-11-05 20:10:04.652] [qml] [debug] static bool LibSecretKeyring::findPassword(const QString&, const QString&, QKeychain::JobPrivate*) (:0, )
[2021-11-05 20:10:04.671] [crypto] [info] Online key backup disabled.
[2021-11-05 20:10:04.671] [crypto] [info] ed25519   : bFoNwROO/nKZpHeN5bpR9NQlR0YKDryqfn4ZDmE5XFc
[2021-11-05 20:10:04.671] [crypto] [info] curve25519: pIdbaa+4CxrqG0FZOYuxGMKSU1tuot/XSx5kZU818nw
[2021-11-05 20:10:04.671] [crypto] [info] generating one time keys
[2021-11-05 20:10:04.671] [net] [warning] failed to retrieve own profile info
[2021-11-05 20:10:04.682] [db] [info] Invalidating self verification status
[2021-11-05 20:10:04.682] [crypto] [critical] failed to upload one time keys:  32605
[2021-11-05 20:10:04.682] [db] [error] Failed to retrieve user keys for : mdb_get: MDB_BAD_VALSIZE: Unsupported size of key/DB name/data, or wrong DUPFIXED size
[2021-11-05 20:10:04.682] [db] [debug] Marking user keys out of date:
```

**Comment by deepbluev7** [comment]
It seems like not being able to connect to secret storage might have corrupted your database. If you move your config file and database, does it start properly and allow you to login?

**Comment by maxigaz** [comment]
> If you move your config file and database, does it start properly and allow you to login?

I've tried renaming `~/.config/keepassxc/keepassxc.ini` and opening a freshly created database. Nheko still crashes.

**Comment by maxigaz** [comment]
I'm wondering if KeePassXC is actually correctly set up as a secret storage. (This is the first time I'm using it for this purpose.)

After a quick online search, I've come across [this blog post](https://c3pb.de/blog/keepassxc-secrets-service.html). I followed what's written there:

1. I went to the Settings and checked the checkbox, "Enable KeepassXC Freedesktop.org Secret Service integration".
2. I created a new group and designated it for the Secret Service (from Database menu → Database settings…)
3. I enabled search for the group (right click → Edit Group… → dropdown next to the label "Search:")

Nheko still crashes as before.

**Comment by deepbluev7** [comment]
Well, that is not great. I will try to reproduce this, hopefully in the near future. Alternatively you could maybe create a backtrace? But it sounds like actually your nheko login is corrupt, not the keepassXC database. What I meant before was to move ~/.config/nheko and ~/.local/share/nheko.

**Comment by maxigaz** [comment]
> What I meant before was to move ~/.config/nheko and ~/.local/share/nheko.

Oh, I see. Actually, I've already tried renaming both, and I have the same results.

> Alternatively you could maybe create a backtrace?

That requires compiling Nheko again with a flag and running it via `gdb`, right? Can both of these steps be done by editing the [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=nheko-git)? (I'm especially wondering about the second step.) If not, I'll try building and running it manually later.

**Comment by deepbluev7** [comment]
Yes, you just need to replace Release with Debug in the PKGBUILD in 38 and 39. Thank you!

**Comment by maxigaz** [comment]
I've just reinstalled it (after editing the PKGBUILD) and it crashed only once (this time my KeePassXC database was locked, so it prompted me to enter its passphrase). I haven't been able to make it crash since then.

In case it does crash again, how do I find/generate a backtrace? I've looked at the terminal output as well as in places like `~/.cache/nheko` and `/tmp`, and what I could find was just normal log output and a dump file, which I could see even before reinstalling.

**Comment by deepbluev7** [comment]
You can create a backtrace by creating a debug build and then running `gdb nheko`, type `r` to run Nheko and `bt` after the crash, to create a backtrace.

**Comment by maxigaz** [comment]
I see, thank you! (I realised that I also needed to install the package `gdb` from the extra repository.)

I'm closing this for now, and I'll reopen and upload a backtrace in case the problem returns. Thank you for all the help!

**Comment by maxigaz** [comment]
I've just checked to see what happens if I rename `~/.config/nheko/nheko.conf` and `~/.local/share/nheko`, and sure enough, it crashes. But then, all subsequent runs are fine.

So, here's the backtrace:

```
#0  0x00007ffff515ad22 in raise () at /usr/lib/libc.so.6
#1  0x00007ffff5144862 in abort () at /usr/lib/libc.so.6
#2  0x00007ffff5505802 in __gnu_cxx::__verbose_terminate_handler() () at /build/gcc/src/gcc/libstdc++-v3/libsupc++/vterminate.cc:95
#3  0x00007ffff5511c8a in __cxxabiv1::__terminate(void (*)()) (handler=<optimized out>) at /build/gcc/src/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:48
#4  0x00007ffff5511cf7 in std::terminate() () at /build/gcc/src/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:58
#5  0x00007ffff5511f8e in __cxxabiv1::__cxa_throw(void*, std::type_info*, void (*)(void*)) (obj=<optimized out>, tinfo=0x555555f8be30 <typeinfo for lmdb::error>, dest=0x555555905780 <lmdb::error::~error()>)
    at /build/gcc/src/gcc/libstdc++-v3/libsupc++/eh_throw.cc:95
#6  0x00005555557e5cc7 in  ()
#7  0x0000555555a2a837 in Cache::markUserKeysOutOfDate(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) ()
#8  0x00005555559e0751 in  ()
#9  0x00007ffff5cbcad7 in  () at /usr/lib/libQt5Core.so.5
#10 0x00007ffff5caefef in QObject::event(QEvent*) () at /usr/lib/libQt5Core.so.5
#11 0x00007ffff6910ff6 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#12 0x00007ffff5c811ba in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt5Core.so.5
#13 0x00007ffff5cd9dbd in QTimerInfoList::activateTimers() () at /usr/lib/libQt5Core.so.5
#14 0x00007ffff5cda742 in  () at /usr/lib/libQt5Core.so.5
#15 0x00007ffff570f4dc in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#16 0x00007ffff5763749 in  () at /usr/lib/libglib-2.0.so.0
#17 0x00007ffff570cbc1 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#18 0x00007ffff5cdaada in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#19 0x00007ffff5c7fa6b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#20 0x00007ffff5c88258 in QCoreApplication::exec() () at /usr/lib/libQt5Core.so.5
#21 0x000055555585506b in main ()
```

**Comment by deepbluev7** [comment]
Can you check it with the latest commit? I had a condition the wrong way, which could fix this as well.

**Comment by maxigaz** [comment]
No crashes this time. Thank you!

**Comment by deepbluev7** [comment]
Thank you for the quick feedback and all the debugging!
