### ISSUE TITLE
Log Out button doesnt work

### ISSUE THREAD

**Issue by exaCORE42** [Nheko-Reborn/nheko#795]
### Describe the bug

When I click the log out button, There is no 'confirm' option to log out

### To Reproduce

1. Sign into Nheko
2. Hit the power button at the top (log out)
3. See that there is no option to hit 'OK' to the prompt

### What happened?

The log out dialog has no 'OK' or confirm option

### Expected behavior

That there would be an 'OK' or confirm option that one could use to log out using this dialog instead of going to 'manage devices and then logging out your current device from there.

### Screenshots

![image](https://user-images.githubusercontent.com/85199808/140844589-284f7278-c84b-4493-9278-04a1ed08c156.png)

### Version

0.8.2-b27b7c94

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Qt version

qt5-base 5.15.2+kde+r254

### C++ compiler

gcc 11.1.0

### Desktop Environment

KDE

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment]
My button has both options, can you try building the latest version and deleting ~/.cache/nheko/qmlcache?

**Comment by exaCORE42** [comment]
I did both, but it didn't help

**Comment by exaCORE42** [comment]
fixed.
