### ISSUE TITLE
Allow to choose between different Sticker packs when choosing a sticker

### ISSUE THREAD

**Issue by exaCORE42** [Nheko-Reborn/nheko#800]
### The Problem

This is not a huge issue, but if you have a lot of stickers, then it might be cumbersome to scroll through all of the stickers to find the one you want to send.

### The Solution

Ability to choose what sticker pack you want to choose a sticker from when you open the choose sticker menu.  It would really help with organization if you have a lot of stickers.

### Alternatives

A 'favorite' system could work (and would be welcome in addition to the solution described above) but I think that ultimately, it wouldn't solve the core problem described above which is organization of a large amount of stickers.

### Happens in the latest version

- [X] Yes, this feature is still missing.

**Comment by deepbluev7** [comment]
We could try to fiddle in a category selector like in the emoji picker. Would require packs to have a reasonable avatar though.

**Comment by deepbluev7** [comment]
Ah, I did fix that (finally)
