### ISSUE TITLE
Same font size for text entry bar as log.

### ISSUE THREAD

**Issue by DuskWulf** [Nheko-Reborn/nheko#801]
### The Problem

Currently, the text entry box uses an incredibly tiny font. This is kind of an accessibility issue. I have poor sight, so I can't actually see the text I'm entering. It's a shame, as nheko is my favourite Matrix client of those I've tested so far but it'd be nice if I could see what I was typing.

### The Solution

One way to fix this is to have the font settings used for the log apply to the text entry. I imagine that wouldn't be too hard to implement that way? It'd mean that for those with poor sight, the text entry field would become usable if twas the same as the log.

Thanks for reading.

### Happens in the latest version

- [X] Yes, this feature is still missing.

**Comment by deepbluev7** [comment]
The text entry does use the same font. Please report a bug, which states what version you see this issue on as well as info about your system.

**Comment by DuskWulf** [comment]
I meant font _size_, rather than font _family_. I'm an idiot and didn't think to specify that. The font size looks to be around, I want to say... 8? Whereas the font size in the log is whatever I want it to be.

**Comment by deepbluev7** [comment]
Well, I can't reproduce that in the current version. But you didn't tell me, what version you use and on what system, so I can't say if it is fixed or try to reproduce it.
