### ISSUE TITLE
When Nheko can't fetch secrets from KeePassXC, display option to retry

### ISSUE THREAD

**Issue by maxigaz** [Nheko-Reborn/nheko#802]
### The Problem

Secret Storage service is enabled in KeePassXC so that Nheko can store its secrets in it. Let's suppose that I have logged in with my Matrix account at least once and exit both Nheko and KeePassXC.

Later, if I run KeePassXC, unlock its database, and *then* launch Nheko, I'm automatically logged into my pervious Matrix session, so I don't have to authenticate the device again.

On the other hand, if KeePassXC is running but its database is *locked* when I launch Nheko, the following happens:

1. KeePassXC prompts me to unlock the database.
2. KeePassXC asks me if I want to move Nheko's entries into the recycle bin/trash one by one.
3. Nheko has me create another session that has to be authenticated for E2E.

### The Solution

When the KeePassXC database is locked, Nheko could display a message like "Secret storage for the pervious session is unreachable" with two options:

- "Try again," which allows me to unlock the database and then clicking on this will restore the previous login session.
- "Create new session," which does what the current behaviour is.

### Alternatives

I know KWallet and Gnome Keyring can be used with Nheko, too, but I haven't tried them yet. (I'm using i3wm, so I would prefer using standalone applications that don't rely on full-fledged desktop environments.)

### Additional context

I'm using Nheko 0.8.2-d11fcb0f and KeePassXC 2.6.6 under Manjaro Linux.

### Happens in the latest version

- [X] Yes, this feature is still missing.

**Comment by deepbluev7** [comment]
Does Nheko not show an error, that it couldn't connect to the secret storage? Does it log any obvious error, that we could handle, or does KeePass just say "not found"?

**Comment by maxigaz** [comment]
Nheko shows the following message on the login screen:

> Failed to restore OLM account. Please login again.

Here's the generated log when I run `nheko --debug`: [nheko-e.log](https://github.com/Nheko-Reborn/nheko/files/7526080/nheko-e.log)

**Comment by deepbluev7** [comment]
This seems to be fixed in https://github.com/keepassxreboot/keepassxc/pull/6943, which should be in KeePassXC 2.7, which isn't released yet. You could try the development version of it?

**Comment by maxigaz** [comment]
I've just tried it in a VM running Arch Linux. (I installed it from Chaotic AUR as `keepassxc-git`.)

I can confirm that it doesn't have the issue anymore. Now Nheko waits until I unlock the database and authorize Nheko inside KeePassXC. (I've also noticed that this last prompt window for authorization pops up every time, even if "Always" is checked, although this is probably a separate issue.)

Thank you for your help!

**Comment by cquike** [comment]
Hi,
I also have this problem. I guess the KeePassXC issue mitigates the problem, but nheko _still_ has a problem. I think it is a problem in nheko that if the libsecret service cannot be contacted, nheko looses any account configuration and cannot be restored.

**Comment by deepbluev7** [comment]
No, Nheko only loses the account info, if the secret service CAN be contacted, but returns empty data instead of an error.
