### ISSUE TITLE
Very difficult to see 'removed' marker for removed messages

### ISSUE THREAD

**Issue by exaCORE42** [Nheko-Reborn/nheko#803]
### The Problem

I use the 'system' theme in Nheko (which in my case is more like the 'light' theme than the dark theme) and it is very difficult to see the 'removed' marker for removed marker which also leads to confusion about what was sent.

![image](https://user-images.githubusercontent.com/85199808/141348895-63847e01-bc8a-4baa-bdcf-db71785be405.png)

### The Solution

Maybe make the text in a dark color (such as black) or make the bubble around the text a dark color if the person is using a lighter theme.

### Happens in the latest version

- [X] Yes, this feature is still missing.

**Comment by deepbluev7** [comment]
fixed
