### ISSUE TITLE
nheko audio player doesn't work (mobian pinephone)

### ISSUE THREAD

**Issue by sc0w** [Nheko-Reborn/nheko#805]
### Describe the bug

play audio inside nheko audio player doesn't work

### To Reproduce

1. Recieve audio
2. I see "Voice message.ogg"
3. arrow down icon
4. play icon
5. I see the pause icon and I hear nothing

### What happened?

I hear nothing

### Expected behavior

Hear the audio

NOTE: "open in external program" I can hear the audio, but not inside nheko audio player

### Versions

`0.8.2`, `0.9.1`, `0.9.3`

### Operating system

Linux

### Desktop Environment

mobian bookworm pinephone

### Did you use profiles?

- [ ] Profiles used?

**Comment by redsky17** [comment]
Hey there, we have made quite a few changes to the audio and video player in the master branch.  Would you be willing to install the nightly flatpak (see the link in the README) to see if the issue still persists or not?

**Comment by sc0w** [comment]
I have tested again, this time with nheko 0.9.0 (deb package from debian sid), and the same behavior, the player doesn't work

**Comment by deepbluev7** [comment]
Are you possibly missing the gstreamer dependencies for that codec?

**Comment by sc0w** [comment]
I have these packages related to gstreamer:

```
mobian@mobian:~$ dpkg --get-selections|grep gstreamer
gir1.2-gstreamer-1.0:arm64			install
gstreamer1.0-clutter-3.0:arm64			install
gstreamer1.0-gl:arm64				install
gstreamer1.0-gtk3:arm64				install
gstreamer1.0-libav:arm64			install
gstreamer1.0-nice:arm64				install
gstreamer1.0-packagekit				install
gstreamer1.0-plugins-bad:arm64			install
gstreamer1.0-plugins-base:arm64			install
gstreamer1.0-plugins-good:arm64			install
gstreamer1.0-plugins-ugly:arm64			install
gstreamer1.0-pulseaudio:arm64			install
gstreamer1.0-qt5:arm64				install
gstreamer1.0-vaapi:arm64			install
gstreamer1.0-x:arm64				install
libgstreamer-gl1.0-0:arm64			install
libgstreamer-plugins-bad1.0-0:arm64		install
libgstreamer-plugins-base1.0-0:arm64		install
libgstreamer1.0-0:arm64				install
mobian@mobian:~$ 
```

**Comment by deepbluev7** [comment]
What mimetype is that video and what codec does it use?

**Comment by sc0w** [comment]
is a .ogg file, I can open it with external program (smplayer)

```
$ file Voice\ message.ogg 
Voice message.ogg: Ogg data, Opus audio, version 0.1, mono, 48000 Hz (Input Sample Rate)

```

**Comment by deepbluev7** [comment]
Hm, that should work with gstreamer-plugins-base... Sorry, no idea, what is the issue.

**Comment by deepbluev7** [comment]
You don't have Nheko muted in pulseaudio, do you?

**Comment by sc0w** [comment]
I don't know how to verify it, I see pulseaudio with max volume in alsamixer

anyway, if I do play nothing happens, I mean, the seconds are 0 always, I see `"0.00 / -1:0-1"`

**Comment by deepbluev7** [comment]
Okay, that does not sound like it is muted :D

**Comment by maltee1** [comment]
works for me on Pinephone Pro / Plasma Mobile.
Playing videos on the other hand makes nheko crash. I should file a bug.

**Comment by sc0w** [comment]
not here, on pinephone, mobian phosh, with 0.9.1 the same behavior, it isn't fixed

**Comment by maltee1** [comment]
have you tried the latest nightly rather than the release?
The easiest way to get it is probably flatpak.

**Comment by sc0w** [comment]
With 0.9.3 the same behavior, audio player doesn't work

**Comment by deepbluev7** [comment]
Your log files had some weird log messages about the media player service not being available.

```
[2022-05-18 16:16:59.362] [qml] [warning] defaultServiceProvider::requestService(): no service found for - "org.qt-project.qt.mediaplayer" (:0, )
```

When I had that on my system, I needed to update qmultimedia and that fixed it. Maybe that is worth a try?

**Comment by sc0w** [comment]
thanks @deepbluev7 , after installing `libqt5multimedia5-plugins` works great!

The video doesn't work fine in nheko player (with external program is ok), seems to have some lag with no sound, but I think that is another issue.

https://stackoverflow.com/questions/47524552/qt-no-service-found-for-org-qt-project-qt-mediaplayer
