### ISSUE TITLE
Search room by name in rooms list

### ISSUE THREAD

**Issue by pravi** [Nheko-Reborn/nheko#81]
### System:

- Nheko version: 0.6.4
- Installation method: .deb (rebuilt on buster)
- Operating System: debian buster
- Qt version: 
- C++ compiler: 
- Desktop Environment: 

### Actual behavior

There is no search option for room list

### Expected behavior

You should be able to easily find a room by searching by name. Its useful when you have a long list of joined rooms.

**Comment by deepbluev7** [comment]
As an alternative, have you tried Ctrl+K? It brings up a quick switch menu, that you filter by room name.

**Comment by pravi** [comment]
@deepbluev7 thanks! that's a real life saver (I was feeling handicapped when manually finding the room from the list by scrolling). It should be made easily discoverable. Add a search bar on top of the room list or have a button at bottom that opens up the same dialogue.

**Comment by deepbluev7** [comment]
Yeah, discoverability is certainly something we need to improve, which is why I will keep this issue open, until we solve that. I have some other things to fix before that, so this may take a while until I get to it...

**Comment by subins2000** [comment]
+1 for this. Didn't know there was a CTRL + K option.

**Comment by maltee1** [comment]
This is fixed as of https://github.com/Nheko-Reborn/nheko/pull/947
