### ISSUE TITLE
Really strange behavior when trying to react to message with html in the reaction

### ISSUE THREAD

**Issue by exaCORE42** [Nheko-Reborn/nheko#810]
### Describe the bug

After reacting to a message with html tags(in the reaction!!!!) (is that the right descriptor?).... there is really weird behavior just look at this video

https://user-images.githubusercontent.com/85199808/141707463-9e8d0b00-1f77-4925-8b37-be5e0531fff2.mp4

I legitimately have no idea what is happening.  I am just clicking random reactions and either they disappear or new ones are made

### To Reproduce

1. use /react to react to a message with html tags (is that the right word?)
2. try to remove reaction
3. continue and enjoy the really weird behavior

### What happened?

I have no idea, it just acted really strangely.

### Expected behavior

Not for that to happen.  To just be able to click on the reaction and it will disappear (as does happen in element!)

### Screenshots

(See above!)

### Version

0.8.2-131c64ec

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Qt version

qt5-base 5.15.2+kde+r254

### C++ compiler

gcc 11.1.0

### Desktop Environment

KDE

### Did you use profiles?

- [ ] Profiles used?

**Comment by exaCORE42** [comment]
just realized that this happens whenever there is a '<' or '>' in the reaction (that makes more sense)

**Comment by LorenDB** [comment]
Looks like we are escaping HTML in reactions and not handling it right for removing them.
