### ISSUE TITLE
Reactions stay on redacted messages & you can add reactions to redacted messages

### ISSUE THREAD

**Issue by exaCORE42** [Nheko-Reborn/nheko#811]
### Describe the bug

Not sure if this is intentional or not, but unlike element, in nheko, reactions stay on a message even after it is redacted.  Also you can add reactions to deleted messages.

### To Reproduce

1. add a reaction on a message
2. redact (delete) it.
3. the reaction stays! you can also add new reactions to it.

### What happened?

reactions can still occur on deleted messages

### Expected behavior

You should not be able to add reactions to deleted messages

### Version

0.8.2-131c64ec

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Qt version

qt5-base 5.15.2+kde+r254

### C++ compiler

gcc 11.1.0

### Desktop Environment

KDE

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment]
Why is that an issue?

**Comment by exaCORE42** [comment]
It can just be annoying and it also shows irrelevant information (does it matter what reactions there are if you are unable to see the message?).  But either way, it isn't a big deal, just something that i noticed that seemed to be a bit out of place.

**Comment by deepbluev7** [comment]
It's not a bug imo, sometimes it makes sense to have reactions on redacted messages. I.e. to react to moderation.
