### ISSUE TITLE
Left hand side room preview has incorrect message when you change your display name

### ISSUE THREAD

**Issue by exaCORE42** [Nheko-Reborn/nheko#813]
### Describe the bug

Minor bug where the room preview feature (left hand bar), incorrectly says that you joined the room when you simply change your display name.

### To Reproduce

1. Change your display name
2. see that the room preview on the left hand bar says that you just joined the room

### What happened?

the 'room preview' left hand bar says that you joined the room when in fact you simply changed your display name

### Expected behavior

it should say 'You changed your display name' or something similar

### Screenshots

![image](https://user-images.githubusercontent.com/85199808/141714653-446f7ca7-a493-4e6c-90d4-28e8ea2801a3.png)

as you can see it says that the most recent thing is that I joined the room when in fact it is when I changed by display name

### Version

0.8.2-131c64ec

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Qt version

qt5-base 5.15.2+kde+r254

### C++ compiler

gcc 11.1.0

### Desktop Environment

KDE

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment]
This was fixed a while ago, iirc
