### ISSUE TITLE
You shouldn't get a notification for if you change your display name or avatar.

### ISSUE THREAD

**Issue by exaCORE42** [Nheko-Reborn/nheko#814]
### The Problem

Currently, if you change your global display name or avatar, you receive a notification from all your rooms.  That can be quite annoying.

### The Solution

Don't send a notification for if you changed your display name or avatar.

### Happens in the latest version

- [X] Yes, this feature is still missing.

**Comment by deepbluev7** [comment]
I think this is fixed (on master).
