### ISSUE TITLE
Resizing channel list sidebar works only once

### ISSUE THREAD

**Issue by Akselmo** [Nheko-Reborn/nheko#817]
### Describe the bug

Resizing the channel list sidebar works only once. By default I see all the text per channel, I like to minimize it so I only see the channel icons. After resizing it to only icons mode I cant drag it anymore. Restarting Nheko fixes it, but wont save sidebar size.

### To Reproduce

1. Drag Nheko sidebar to make it smaller
2. Let go of mouse 
3. Try to drag Nheko sidebar again
4. Cursor wont turn into resizing icon and you cant drag it anymore

### Screenshots

A gif of the problem

![Peek 2021-11-19 10-48](https://user-images.githubusercontent.com/13801236/142593457-02f0e8a9-f276-42e6-a15f-7d2ef7b82dc2.gif)

### Version

0.9.0

### Operating system

Linux

### Installation method

Flathub

### Desktop Environment

KDE Plasma + Kwin

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment]
Yes, this is somewhat of a known issue for now. The handle jumps to a random location, if you let it go in the wrong place. I think it fixes itself after a restart. I'll fix it at some point!

**Comment by thmo** [comment]
> The handle jumps to a random location

Actually the location doesn't seem to be random: Both handles are still there, you just have to find them: they are just a bit over the area where you can write, but displaced to the right.

So I think their locations are not properly updated - they are left behind the moment the final shrink (the discontinuous one) happens.
