### ISSUE TITLE
Font colors messed up on Aarch64

### ISSUE THREAD

**Issue by CrystalGamma** [Nheko-Reborn/nheko#818]
### Describe the bug

In certain situations the font color of much of the window gets messed up. As far as I can tell this mostly seems to affect text that is in the default color, i. e. black (but sometimes it affects colored text like nicknames as well). However, it doesn't always change the color of all default-colored text, or at least not all at once.

Situations that may, but do not always, trigger this behavior are switching channels and selecting text.

This bug has been observed on 0.8.2 (don't remember if I've also seen it on 0.8.1) and also on 0.9.0 (I haven't observed it happening on selecting text with this version yet) though, but only on my aarch64 laptop (Pinebook Pro) and not on  my ppc64le desktop (Talos II). The OS in all cases is the NixOS Linux distribution, using the master branch of nixpkgs.

### To Reproduce

1. Open nheko
2. Switch channels a couple of times, maybe select some text
3. see most text change color

### What happened?

All the text is dark blue in the screenshot below, which is the native color of Nico's nickname. In other cases I've seen everything became green or even white (particularly fun on a white background).

### Expected behavior

Most text should stay black (or whatever the theme says, I guess) as usual.

### Screenshots

![Screenshot_20211119_145209](https://user-images.githubusercontent.com/6297001/142633856-719c9f2a-830d-4e96-89ff-9776d9295347.png)

### Version

0.9.0

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Qt version

5.15.2 + KDE patches, AFAICT

### C++ compiler

GCC 9.3.0

### Desktop Environment

KDE Plasma

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment]
That's really funky o.o

**Comment by CrystalGamma** [comment]
Yeah, it smells like Undefined Behavior, but it's a bit too predictable for that, if you know what I mean.

**Comment by deepbluev7** [comment]
I have no idea, how we could trigger that. This smells like a Qt or GPU bug to me

**Comment by CrystalGamma** [comment]
Okay, since this issue has become worse for me recently, I've been doing some testing, and it seems the GPU driver is indeed the problem, running nheko (or even just an ApiTrace of it) using llvmpipe gets rid of these problems. Still surprising that nheko is the only application I have that triggers it and over how many Mesa and kernel releases the effect has pretty much the same. I'll close this and try figuring out how to report such bugs to the Mesa folks.

**Comment by deepbluev7** [comment]
It could also just be a Qt bug, although reporting it to the mesa guys probably gets this tracked down quicker, because they know better when people hold OpenGL wrong

**Comment by CrystalGamma** [comment]
If nothing else it doesn't happen with llvmpipe, so I made this: https://gitlab.freedesktop.org/mesa/mesa/-/issues/6355

If it turns out to be a bug in Qt they'll know better than we would, for sure. But I still wonder why this doesn't happen in my other Qt applications.

**Comment by deepbluev7** [comment]
For reference, this might be fixed now in the mesa development branch: https://gitlab.freedesktop.org/mesa/mesa/-/commit/80404c8b640bdc24274b67561842ebf684e741f5
