### ISSUE TITLE
nheko sometimes "misses" room state messages when syncing after being closed

### ISSUE THREAD

**Issue by darkphoenix** [Nheko-Reborn/nheko#828]
When room state changes (e.g. adjustments to permissions) while nheko is closed, these changes are missed when nheko is reopened.  This can be easily observed when changing the permissions needed to send a message, then closing nheko and changing them back.  When nheko is reopened, it still believes it does not have permission to send messages.  This can seemingly only be fixed by changing permissions back and forth while nheko is running (or presumably signing out and back in to force nheko to start over).

**Comment by deepbluev7** [comment]
I can't reproduce this and I am pretty sure I had state changes several times while offline. Maybe I fixed it by accident at some point.
