### ISSUE TITLE
Improvements to the members list

### ISSUE THREAD

**Issue by Cadair** [Nheko-Reborn/nheko#829]
### The Problem

The members list has a few usability issues which make it hard to find specific users in large rooms:

1. The list is apparently sorted by mxid not display name.
2. There is no search box

### The Solution

Add a search box to filter the list and sort by display name not mxid

### Happens in the latest version

- [X] Yes, this feature is still missing.

**Comment by deepbluev7** [comment]
If we sort by anything but the mxid, we'll have to pull out all members from the db when opening the dialog, same for searching. Probably not a deal breaker, just something to keep in mind.

**Comment by LorenDB** [comment]
Shouldn't be too hard; we can stick a QSortFilterProxyModel in there and let Qt trigger loading of more members via canLoadMore

**Comment by deepbluev7** [comment]
That will load everything, if you enable sorting ;p
