### ISSUE TITLE
Context menu randomly disappears on multi-monitor setup

### ISSUE THREAD

**Issue by ChewingBever** [Nheko-Reborn/nheko#831]
### Describe the bug

Display server: X11 (xorg-server 21.1.1-3)

The right-click menu randomly disappears when using nheko on an external monitor. On my built-in display (laptop), however, it works fine.

### To Reproduce

1. Use Nheko on X11 using a multi-monitor setup using i3.
2. Wait

That's honestly all I do, it just happens out of the blue.

### What happened?

When I use nheko on my multi-monitor setup (laptop + hdmi external display) & use the nheko client on said external display, the right-click menu disappears after a seemingly random amount of time. My WM does however recognize that I've right-clicked something, because my cursor does change.
When I then unplug my external display or move the client window to my built-in display, the right-click menu is back. However, I sometimes notice it bugging out the first time I try to right click on my internal display, meaning the right-click menu renders in the top-left corner, & only the first item (Copy) is displayed. Clicking somewhere else and re-trying fixes this issue though.

Edit: the "glitchy" behavior when I move the window over to my internal display isn't as consistent as I thought, it seems to spawn randomly anywhere on the top of my screen, but always just showing the first option. Furthermore, the status bar icon's right-click menu also doesn't work, even when the client is on my internal display, because my status bar icons are on my external display.

### Expected behavior

The right-click menu should always show up in the right place, instead of disappearing.

### Version

0.9.0-23a90f5

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Qt version

5.15.2+kde+r260-1

### C++ compiler

gcc 11.1.0

### Desktop Environment

i3wm without a DE

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment]
Can you check, if that still happens? Might be fixed on master now, although #618 should still apply.

**Comment by deepbluev7** [comment]
This should be fixed now :)
