### ISSUE TITLE
Pings/mentions do not work properly for bridged users

### ISSUE THREAD

**Issue by Cknight70** [Nheko-Reborn/nheko#832]
### Describe the bug

I have a bridge appservice hosted for discord, which gives each Discord user their own pseudo matrix account and @ for the room. 
When trying to ping/mention another user it will only send the text, which will not send a proper notification to the bridged user.

### To Reproduce

1. type @
2. select the proper account to ping
3. Enter

### What happened?

Improper mention (only text) was sent over the bridge.

### Expected behavior

A Discord ping should happen, like it does with element.

### Screenshots

![image](https://user-images.githubusercontent.com/28763729/144141441-d9ac829c-31cc-484c-8a19-8029953da2a1.png)
![image](https://user-images.githubusercontent.com/28763729/144141478-1ad8e7dc-d614-45ff-ac35-34d457393ba8.png)

### Version

0.9.0-b505fa42 | Linux

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Qt version

5.15.2

### C++ compiler

11.1.0-1

### Desktop Environment

KDE

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment]
Can you show the raw event content for both events? You can access that by right clicking the message.

**Comment by Cknight70** [comment]
element sends `https://matrix.to/#/@_discord_123456789:myserver.com`
nheko sends `https://matrix.to/#/%40_discord_123456789%3Amyserver.com`

**Comment by Cknight70** [comment]
I'm sorry, here is the full raw event for each with my homeserver redacted
```
{
    "content": {
        "body": "CK#5231: heres a ping from element",
        "format": "org.matrix.custom.html",
        "formatted_body": "<a href=\"https://matrix.to/#/@_discord_855911528808579072:myserver.com\">CK#5231</a>: heres a ping from element",
        "msgtype": "m.text"
    },
    "event_id": "$by8fC8NnbDqNAMoT9GMiFCX4anlGT1iM_8wVSF3YexA",
    "origin_server_ts": 1638312955284,
    "sender": "@ck:myserver.com",
    "type": "m.room.message",
    "unsigned": {
        "age": 80
    }
}
```
```
{
    "content": {
        "body": "CK#5231 here's a ping from nheko",
        "format": "org.matrix.custom.html",
        "formatted_body": "<a href=\"https://matrix.to/#/%40_discord_855911528808579072%3Amyserver.com\">CK#5231</a> here's a ping from nheko",
        "msgtype": "m.text"
    },
    "event_id": "$WTFeEQuMHrW-jKaQyKJOJGukUFEq__wc5WtPM9Gj6mo",
    "origin_server_ts": 1638312971258,
    "sender": "@ck:myserver.com",
    "type": "m.room.message",
    "unsigned": {
        "age": 128,
        "transaction_id": "m9XMxKI6dfUzOoHZOVSj2rpacZfGSK7Q9"
    }
}
```

**Comment by deepbluev7** [comment]
That's a bug in the bridge then. The spec actually requires the identifiers to be percent encoded, Element just doesn't do that.

> The components of the matrix.to URI (<identifier> and <extra parameter>) are to be percent-encoded as per RFC 3986.

https://spec.matrix.org/v1.1/appendices/#matrixto-navigation

**Comment by Cknight70** [comment]
I will let the bridge developer know, feel free to close this if you want. Thank you for your awesome client!
