### ISSUE TITLE
The keys get trashed if you start nheko and KeepassXC is locked

### ISSUE THREAD

**Issue by FoundOne** [Nheko-Reborn/nheko#834]
### Describe the bug

It happens when keepassxc is used as a secret service.

### To Reproduce

1. Set keepassxc as your secret service.
2. Open nheko with keepassxc locked.
3. It prompts you to unlock the key database.
4. It asks you whether to move the keys to trash.
5. Even if you deny the key deletion, nheko starts as new, with new keys.

The same happens when keepassxc is not running but it does not ask you to unlock the key database.

### What happened?

When keepassxc is used as a secret service the keys get trashed if the key database is locked or when keepassxc is not running.

### Expected behavior

It should keep track, that the keys have been made and probably to ask you if you want to create new ones.

### Version

0.9.0

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Desktop Environment

river-git (it's wlroots based) with a dbus session on Void Linux x86_64-musl (current)

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment]
That's a bug in KeepassXC 2.6.6. KeepassXC 2.7.0 handles that properly (not released yet though).
