### ISSUE TITLE
Unable to use nheko after 0.9.0 update

### ISSUE THREAD

**Issue by pravi** [Nheko-Reborn/nheko#836]
### Describe the bug

nheko just shows the logo animation after canceling key verification. this device is verified from element and was working with 0.8.2

### To Reproduce

1. Verify nheko from element
2. Upgrade nheko from 0.8.2 to 0.9
3. Start nehko
4. Press cancel on verification

### What happened?

The start up animation of the logo is never completed (Additionally entering the recovery password did not work - not sure what format it should be given, element gave xxxx xxxx format in 3 lines - tried copy pasting the whole string, removing line breaks, removing line breaks and space, none worked).

### Expected behavior

nheko should show the chats

### Screenshots

![2021-12-06 13-28-22](https://user-images.githubusercontent.com/708222/144808863-b7ef8115-7c5d-4ba3-93dc-f7db79facab7.png)

### Version

0.9.0

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Desktop Environment

GNOME

### Did you use profiles?

- [ ] Profiles used?

**Comment by pravi** [comment]
It seems, it was just taking too long to load. Closing.

**Comment by deepbluev7** [comment]
Yeah, first startup after the 0.9.0 update will take a while to load, since it recreates half the database and does a new initial sync.
