### ISSUE TITLE
Dismissing "Send a File" shows a loading spinner

### ISSUE THREAD

**Issue by fnetX** [Nheko-Reborn/nheko#837]
### Describe the bug

When dismissing the "Send a file" dialog (cancelling / closing it), nheko shows a loading spinner instead of the paper clip

### To Reproduce

1. Attach a file via the "Send a file" paper clip, next to the message input line
2. close the dialog
3. watch the loading spinner

### What happened?

loading spinner is shown

### Expected behavior

paper clip icon stays

### Version

0.9.0-f36b3836 | Linux

### Operating system

Linux

### Installation method

Flatpak nightly repo or download

### Desktop Environment

Cinnamon

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment]
For me it doesn't start with the spinner until I click send and after that you can't cancel it?

**Comment by fnetX** [comment]
Hmm weird, I can't reproduce this any more. I definitely cancelled the upload because I accidentally clicked it, I just closed the window and the spinner was there. And it appeared reproducible, although I think I only tested this in one chat and don't recall which one. Maybe that one was kinda broken ...

I'll reopen if I encounter it again, sorry for the noise.
