### ISSUE TITLE
Memory leak opening dialogs?

### ISSUE THREAD

**Issue by tastytea** [Nheko-Reborn/nheko#838]
### Describe the bug

When I scroll through the images of the room's image packs, nheko consumes memory. When I scroll through the same images again, nheko consumes even more memory.

### To Reproduce

1. Open nheko
2. Go to [#tastytea_emojis:pixie.town](https://matrix.to/#/#tastytea_emojis:pixie.town) (or any other room with lots images in packs)
3. Wait 1 minute and record nheko's memory usage
4. Scroll through all images in all image packs
5. Record nheko's memory usage
6. Scroll 10 times through the same image packs
7. Record nheko's memory usage

### What happened?

Memory consumption was ~210 MiB at first, after scrolling through all the image packs ~360 MiB, after scrolling through them 10 times more ~460 MiB, and after 10 scrolls more ~570 MiB.

### Expected behavior

No memory leak. 😊

### Screenshots

![Memory consumption over time](https://user-images.githubusercontent.com/3681516/145075815-14b80f10-1848-47d0-bddd-720623ec1f85.png)

[heaptrack.nheko.4575.gz](https://github.com/Nheko-Reborn/nheko/files/7670366/heaptrack.nheko.4575.gz) – I've gone through all images 3 times for this heaptrack.

### Version

0.9.0

### Operating system

Linux

### Qt version

5.15.2

### C++ compiler

11.2.0

### Desktop Environment

n/a with i3 as the window manager

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment]
Hm, I don't think address sanitizer reported anything like that, so this probably has to do with the caching. But that should be bounded to 100 or 300MB (I forget which is the Qt default). I'll look into that.

**Comment by tastytea** [comment]
I did get up to ~2 GiB memory usage after days of creating/updating image packs. I can't be sure if it is this issue alone that has caused it of course.

**Comment by deepbluev7** [comment]
ASAN seems to agree with you.

**Comment by deepbluev7** [comment]
Actually, no, ASAN just sees a gigantic leak in hunspell, that seems to be fairly static though...

**Comment by deepbluev7** [comment]
Your heaptrack also only seems to say, that Qt cached images...

**Comment by tastytea** [comment]
Hmm, actually it seems it has nothing to do with images after all. I tested again, this time I only opened and closed the room settings. It seems that every time around 10 MiB is leaked. I did nothing else for the duration of the test.

![nheko memory consumption over time](https://user-images.githubusercontent.com/3681516/145090969-fab58826-d733-40e2-b684-864a385b471d.png)

**Comment by tastytea** [comment]
Did some tests with other dialogs while the nheko channel was selected. Starting to think that this might be a Qt issue? 

![nheko memory consumption over time](https://user-images.githubusercontent.com/3681516/145101289-1f0ab673-586b-4a7e-ad16-60eac19e9762.png)

**Comment by deepbluev7** [comment]
It seems like the JS engine doesn't properly clean up some object trees, but I can't figure out why. Images make this most noticeable, because those are bigger, I guess? Although all the dialogs you opened also include images, I guess?

**Comment by tastytea** [comment]
The participants list contains a lot of images, but the invite dialog none… And the emoji popup didn't really leak additional memory when I opened it 20 times. :confused:

**Comment by deepbluev7** [comment]
I tried removing all required properties like here, but that doesn't seem to help much: https://bugreports.qt.io/browse/QTBUG-86615

The biggest improvement I got from emerging mesa without vaapi support, it halved the leaks, but it didn't fix them... Maybe it is related to gunterdw's issue?

**Comment by deepbluev7** [comment]
So all the analyzers say, that most of those blocks are still reachable, so it has to be something keeping a reference to them instead of an easy to find leak.

**Comment by deepbluev7** [comment]
Can you check it in massif? For me the actual allocation memory usage seems to stabilize at a bit over 200MB, even though htop shows much more, if I run massif:

![grafik](https://user-images.githubusercontent.com/16312324/145123790-2486d053-33b1-4f2b-a767-6687a260e0d7.png)

**Comment by tastytea** [comment]
Unfortunately [valgrind foesn't like my CPU](https://bugs.kde.org/show_bug.cgi?id=446669). 🙁

**Comment by deepbluev7** [comment]
Ah, the usual. I'm glad my first gen ryzen worked this time!

**Comment by redsky17** [comment]
Looks like this has been an issue since at least 2014! https://bugs.kde.org/show_bug.cgi?id=339596

**Comment by deepbluev7** [comment]
So, I don't think there is an actual leak here. At least none of my tools show it. I think this might just be the memory tracking getting confused by the mmap of the db and such. I'm going to close this for now, since nothing shows up as actually leaking. My massif all stays at 200MB of actual allocations.

**Comment by deepbluev7** [comment]
See also https://github.com/Nheko-Reborn/nheko/commit/ff4334d59e950e9f51a924e06457f21fa1bbaf2a

**Comment by tastytea** [comment]
That seems to fix it here. :tada:
