### ISSUE TITLE
Clickable URLs with emojis in them render incorrectly

### ISSUE THREAD

**Issue by DeeUnderscore** [Nheko-Reborn/nheko#839]
### Describe the bug

Links such as `https://example.com/👋` do not render correctly

### To Reproduce

1. Open a channel in Nheko
2. Send or receive a message containing `https://example.com/👋`, either in plain text or markdown-formatted. 

### What happened?

The text renders as `👋">👋">https://example.com/👋`, and the link goes to `https://example.com/%3Cfont%20face=` when clicked. 

### Expected behavior

The link should show up as https://example.com/👋 and should go there when clicked (the way Github links it here).

### Screenshots

![Link preview tooltip being incorrect](https://user-images.githubusercontent.com/156239/145261420-25c9093f-fa5c-4011-9ad9-ddac301dabd4.png)

### Version

8effdbc447f399d29d9704c556f1faa3090a4b5f

### Operating system

Linux

### Installation method

Local build

### Qt version

5.15.2

### C++ compiler

gcc 10.3.0

### Desktop Environment

KDE Plasma 5.23.3 (on X)

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment]
Yeah, that is related to the emoji workarounds we have to do because of a Qt bug as well as the html issues related to #483. Probably will only be fixed, once #483 is done.

**Comment by DeeUnderscore** [comment]
I can't reproduce this anymore on master, so I'm closing this.
