### ISSUE TITLE
Focus existing instance instead of "Another instance of Nheko is running"

### ISSUE THREAD

**Issue by sophie-h** [Nheko-Reborn/nheko#84]
I have activated "minimize to tray" to get notifications. Since Wayland doesen't have any tray support and starting the app gives "Another instance of Nheko is running," there is no way to get back to the app. Would be nice if the running instance would be opened instead of giving the error.

**Comment by fpesari** [comment]
+1, a very important feature to have

**Comment by frzifus** [comment]
agree :+1:

**Comment by deepbluev7** [comment]
So, this is definitely something I want to add, but I'm working on quite a few other things at the moment, so this may take a while, until I can get around to it. If anyone else wants to take a stab at it, I would be glad to support them however. There are quite a few tutorials on how to achieve something like this in qt afaik (something like opening a socket and checking that or so), so this should be fairly doable even for someone with less experience.

**Comment by frzifus** [comment]
ah that sounds a lot like the second post [here](https://forum.qt.io/topic/59223/qt-single-instance-application/2).

**Comment by fpesari** [comment]
Why not use D-Bus since it's already used in Nheko's codebase?

**Comment by deepbluev7** [comment]
D-Bus is only used on Linux afaik. Such a feature should work on all platforms however. If it can be made to work on all platforms with D-Bus, that would be alright too, but I think a sockets approach or similar works better on Windows and Mac, but that is a total guess.

**Comment by fpesari** [comment]
> D-Bus is only used on Linux afaik. Such a feature should work on all platforms however. If it can be made to work on all platforms with D-Bus, that would be alright too, but I think a sockets approach or similar works better on Windows and Mac, but that is a total guess.

Perhaps D-Bus should be used on compatible systems and sockets elsewhere. True, having two separate implementations is not the best thing, however D-Bus is the most natural and secure way to do things like these on systems which support it.

**Comment by deepbluev7** [comment]
I really see no reason to use multiple implementations. There are not really many benefits to using D-Bus, it would make this a lot more verbose and it would increase the testing overhead a lot. So no, I would not go that way. The proper solution is probably something like this: https://github.com/itay-grudev/SingleApplication

**Comment by deepbluev7** [comment]
This should be fixed now. Nheko may still not focus, but will only highlight the taskbar entry on some WMs, because they don't allow raising your window, to protect users from being disturbed by random popups, but I don't think we want to work around that.
