### ISSUE TITLE
Encoding issues with audio message body

### ISSUE THREAD

**Issue by tastytea** [Nheko-Reborn/nheko#840]
### Describe the bug

We sent a few audio messages back and forth as answers and the message body got messier and messier. The last message in the screenshot has this body:

``` json
"> <@REDACTED:kde.org> > <@tastytea:pixie.town> > <@REDACTED:kde.org> recording1638999829979883.m4a\n> > \n> > recording1638999887823141.m4a\n> \n> recording1638999936284790.m4a\n\nrecording1639000023205951.m4a"
```

The messages were sent via FluffyChat. FluffyChat, Element Linux and Element Android don't show the body.

### To Reproduce

1. Record a voice message in FluffyChat
2. Answer to voice message with a voice message in FC
3. Look at conversation in Nheko

### What happened?

The characters got translated into HTML character entity references.

### Expected behavior

I think the body should be shown, but with the intended characters. 😊

### Screenshots

![screenshot_2021-12-08T22:48:46](https://user-images.githubusercontent.com/3681516/145291080-444f7bd2-3b42-470c-ad19-4bfec896c20e.png)

### Version

0.9.0

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment]
Argh, stupid reply fallback! :D

**Comment by deepbluev7** [comment]
Can you show the original audio event body content as well as the last event? Feel free to remove the url or such, but I am assuming the fallback was incorrect again, which is why it didn't get stripped.

**Comment by tastytea** [comment]
### Original message

``` json
{
    "content": {
        "body": "recording1638999829979883.m4a",
        "file": {
            "hashes": {
                "sha256": "W+zHjPiqrAR6ub97YqGVSK4T6q3Ac2exkalGCisq8ok"
            },
            "iv": "WjI/X9o3HNl28mjWzdg+dA",
            "key": "REDACTED",
            "url": "REDACTED",
            "v": "v2"
        },
        "info": {
            "duration": 4900,
            "mimetype": "application/octet-stream",
            "size": 81745
        },
        "msgtype": "m.audio"
    },
    "event_id": "$9rFeEZYV7XgZqDDiQ0oh74rN7L5jKBVY1K3KDc55kpE",
    "origin_server_ts": 1638999838673,
    "room_id": "!REDACTED:pixie.town",
    "sender": "@REDACTED:kde.org",
    "type": "m.room.message",
    "unsigned": {
        "age": 239
    }
}
```

### Last message

``` json
{
    "content": {
        "body": "> <@REDACTED:kde.org> > <@tastytea:pixie.town> > <@REDACTED:kde.org> recording1638999829979883.m4a\n> > \n> > recording1638999887823141.m4a\n> \n> recording1638999936284790.m4a\n\nrecording1639000023205951.m4a",
        "file": {
            "hashes": {
                "sha256": "SWu/7A3c44rDLgbtRhbw4wWFk6TKGExGeZFytXq8T7k"
            },
            "iv": "vfdOtRcLU6MgXdS5rRHm9w",
            "key": "REDACTED",
            "url": "REDACTED",
            "v": "v2"
        },
        "info": {
            "duration": 3300,
            "mimetype": "application/octet-stream",
            "size": 55797
        },
        "m.relates_to": {
            "m.in_reply_to": {
                "event_id": "$uBqO9BW3J9qyC2_-E4NwhAsoCOWOTEKScYgzgsrWVro"
            }
        },
        "msgtype": "m.audio"
    },
    "event_id": "$xBEq2iW3iOcHlKaIxET5eLpTxhKsmEp98XbR44UrmtI",
    "origin_server_ts": 1639000027616,
    "room_id": "!REDACTED:pixie.town",
    "sender": "@tastytea:pixie.town",
    "type": "m.room.message",
    "unsigned": {
        "age": 96
    }
}
```

**Comment by deepbluev7** [comment]
Was that "Last message" sent using Nheko?

**Comment by tastytea** [comment]
No, they were all sent using FluffyChat.

**Comment by deepbluev7** [comment]
Right, that event is violating the spec in multiple ways. If a client uses m.in_reply_to, it is required to use a rich text body (but we are probably just not parsing that correctly, it might actually be in the original event). But even ignoring that, it should strip the fallback correctly and emit a correct fallback. I.e. there are newlines missing from the fallback and it nests multiple fallbacks, without stripping them first. I'm not really surprised that would show up wrong in Nheko. You should probably file an issue with the fluffy devs, that they are not stripping the fallback correctly.

I think the only issue on Nheko's side here is, that we seem to escape the rich text tags multiple times. Maybe we should also support a rich text body on those events, but that would be a spec violation, so I don't really want to do that.

**Comment by tastytea** [comment]
> Right, that event is violating the spec in multiple ways. If a client uses m.in_reply_to, it is required to use a rich text body (but we are probably just not parsing that correctly, it might actually be in the original event).

The JSON for the body looks the same in FluffyChat. but it does have a `formatted_body` with HTML in it.

> You should probably file an issue with the fluffy devs, that they are not stripping the fallback correctly.

Thanks, done: <https://gitlab.com/famedly/fluffychat/-/issues/702>.
