### ISSUE TITLE
Failed to login 

### ISSUE THREAD

**Issue by nixfreak** [Nheko-Reborn/nheko#847]
### Describe the bug

When logging into Nheko-git or Nheko 9.0 using either kwallet or KeepassXC I get the following error 

![image](https://user-images.githubusercontent.com/3707258/146845926-4915533e-fee3-40d5-9bb9-85974df20143.png)

### To Reproduce

1. Run Nheko from Krunner or terminal 
2. Login via user/password (matrix)
3. Error pops up indicating secret service 

### What happened?

Dialog box pops up 

![image](https://user-images.githubusercontent.com/3707258/146846035-5c8e3b71-6109-47fa-9558-d817f0a576bf.png)

### Expected behavior

Should be able to login via Nheko 

### Screenshots

![image](https://user-images.githubusercontent.com/3707258/146846068-d2f78bc4-9c5a-4086-9fbe-11ef7a81b2d7.png)

### Version

nheko-git 0.8.2.r786.gc40fbf42-1, nheko 0.9.0-1

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Qt version

QMake version 3.1 Using Qt version 5.15.2 in /usr/lib

### C++ compiler

gcc (GCC) 11.1.0

### Desktop Environment

Cutefish 0.4 

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment]
To use kwallet, afaik you need to set the "XDG_CURRENT_DESKTOP" variable to "KDE" or the "DESKTOP_SESSION" to "kde" or the "KDE_FULL_SESSION" to some value. (One of them is enough). In addition you need to set the "KDE_SESSION_VERSION" to "5". Otherwise it will try the secrets backend.

For Keepass, you need to enable the secrets service in the keepass settings as well as make the collection explorable. I think gnome keyring is actually the easiest to use out of the bunch atm.

**Comment by nixfreak** [comment]
I have KeypassXC set though , is there some settings I need to set in a config file somewhere ?

**Comment by nixfreak** [comment]
KeePassXC group searching 
![image](https://user-images.githubusercontent.com/3707258/146989257-8993a214-d585-4caf-8889-c32b582d1ffc.png)


KeypassXC settings Secret service 

![image](https://user-images.githubusercontent.com/3707258/146989375-7f78a2c4-4f3c-40e8-8f43-1581df8e5db3.png)


Running Nheko again 
![image](https://user-images.githubusercontent.com/3707258/146989589-84dd4bff-9edb-45dd-8ef1-2d27e05c0b99.png)

**Comment by redsky17** [comment]
Could you verify the version of qt-keychain that you're using?  (ldd on the nheko executable should show you which qt-keychain nheko is linked against)?

Also, can you verify that the the output of:
```
dbus-send --session --print-reply --dest=org.freedesktop.DBus / \
    org.freedesktop.DBus.GetConnectionUnixProcessID \
    string:org.freedesktop.secrets
```
matches the PID of your keepassxc instance?

**Comment by nixfreak** [comment]
> 

        libqt5keychain.so.1 => /usr/lib/libqt5keychain.so.1 (0x00007f351d435000)

dbus-send --session --print-reply --dest=org.freedesktop.DBus /     org.freedesktop.DBus.GetConnectionUnixProcessID     string:org.freedesktop.secrets
method return time=1640118285.309939 sender=org.freedesktop.DBus -> destination=:1.368 serial=3 reply_serial=2
   uint32 59793


![image](https://user-images.githubusercontent.com/3707258/146992960-de3cb334-e55d-41fa-b825-864afeb20f1f.png)

**Comment by redsky17** [comment]
What process is running under PID `59793` ?

Also, what is the output of `pacman -Qi qtkeychain-qt5` (since it looks like nheko is linked against a system library, this should work).

**Comment by nixfreak** [comment]
pacman -Qi qtkeychain-qt5
Name            : qtkeychain-qt5
Version         : 0.13.2-1
Description     : Provides support for secure credentials storage
Architecture    : x86_64
URL             : https://github.com/frankosterfeld/qtkeychain
Licenses        : BSD
Groups          : None
Provides        : qtkeychain
Depends On      : libsecret  qt5-base
Optional Deps   : kwallet: kwallet backend [installed]
Required By     : kldap  kmailtransport  nheko-git
Optional For    : None
Conflicts With  : qtkeychain
Replaces        : qtkeychain
Installed Size  : 207.37 KiB
Packager        : Antonio Rojas <arojas@archlinux.org>
Build Date      : Thu 18 Nov 2021 10:08:20 AM CST
Install Date    : Mon 20 Dec 2021 03:35:12 PM CST
Install Reason  : Installed as a dependency for another package
Install Script  : No
Validated By    : Signature

**Comment by redsky17** [comment]
Qt-keychain version looks good, but can you verify the other part?

**Comment by nixfreak** [comment]
KeepassXC dies after I hit ok to close Nheko

**Comment by ThisNekoGuy** [comment]
Wait, this is still a valid issue though, isn't it?
Why close it?

**Comment by deepbluev7** [comment]
> Wait, this is still a valid issue though, isn't it? Why close it?

The user who opened it and managed to get it working, so there is none left to debug it. If anyone else experiences that issue, they should open a new bug.

**Comment by ThisNekoGuy** [comment]
"Getting it working" was actually avoiding it altogether and using a different provider, but I guess :/

**Comment by deepbluev7** [comment]
> "Getting it working" was actually avoiding it altogether and using a different provider, but I guess :/

Most other users on Arch have gotten exactly that setup working with minimal effort. As such there is no way for me to tell, if this is an actual issue with Nheko or an obscure issue with their setup. It doesn't make sense to keep such issues open, if none wants to debug them. People actually affected by such an issue can just open a new issue or request to reopen this issue, if they have more details to aid debugging.

**Comment by ThisNekoGuy** [comment]
I run Arch and I have a similar problem though... :/
Probably because I have Kwallet installed and Nheko defaults to it instead of KeePassXC?

**Comment by deepbluev7** [comment]
Open an issue then and describe your issue in detail. You can just tell Nheko you are not running plasma and it ill pick something else.

**Comment by ThisNekoGuy** [comment]
> Open an issue then and describe your issue in detail.

I'll do this

> You can just tell Nheko you are not running plasma and it ill pick something else.

I don't know how to do this
