### ISSUE TITLE
Context menu on wrong monitor

### ISSUE THREAD

**Issue by tokudan** [Nheko-Reborn/nheko#849]
### Describe the bug

When starting, nheko always appears on the wrong monitor.
Context menus of messages appear seemingly randomly either on the bottom left of the correct monitor or on the wrong monitor. Apparently the further down my click is, the more likely it is that the menu appears on the correct monitor in the bottom left. The placement for each context menu seems to be consistent on retry.
Similar issues with the room options context menu.
The emoji selector when reacting to a message always is at the correct location, next to my mouse cursor.

### To Reproduce

Screen layout according to xrandr:
Screen 0: minimum 8 x 8, current 7680 x 2160, maximum 32767 x 32767
eDP1 connected 3840x2160+0+0 (normal left inverted right x axis y axis) 290mm x 170mm
DP1 connected primary 3840x2160+3840+0 (normal left inverted right x axis y axis) 600mm x 340mm
I've configured my right display as primary in KDE Plasma 5.
1. Open terminal, run nheko all with the terminal and mouse on the right (primary) display, the nheko window shows up on the left display.
2. Clicking on the options button for a message on my left display, shows the menu on the right display.
3. Moving the window over to the right display, then clicking on the options button again, shows the menu on the left display.

### What happened?

Nheko shows windows and menus on the wrong displays in a multi-monitor setup.

### Expected behavior

When starting, Nheko should either restore itself to a previous position or show up on the display with the mouse cursor or the primary display.
Context menus should appear next to the buttons, not on a different display or in a corner of a display.

### Screenshots

![Screenshot_20211221_153919](https://user-images.githubusercontent.com/692610/146948504-33efd590-d24e-4ba0-bcf0-c8faf7a6047c.png)
Red arrow shows where I clicked.

### Version

0.9.1

### Operating system

Linux

### Installation method

Local build

### Qt version

5.15.3

### C++ compiler

-- The CXX compiler identification is GNU 10.3.0 -- The C compiler identification is GNU 10.3.0

### Desktop Environment

KDE Plasma 5

### Did you use profiles?

- [ ] Profiles used?

### Relevant log output

```shell
I did not find any screen or display related output in the log.
```

**Comment by deepbluev7** [comment]
Does that sound like #831 or #618 ?

**Comment by tokudan** [comment]
I did not notice the context menu disappearing unexpectedly, but I do have set scaling to 200%, and I noticed that the context menu shows up roughly twice the distance from the top of the screen from where I clicked. Once it gets too far down, it probably falls back to "bottom left of current display" and thus explains why it suddenly shows up on the correct screen.

That still leaves the "wrong display" problem, though.

**Comment by ThisNekoGuy** [comment]
I have a similar issue (I only have one monitor) where all context menus appears somewhere else on my screen as well.
It's strange that it can happen in this case as well :/

**Comment by ThisNekoGuy** [comment]
Ah, this might be the reason for me, at least:
https://github.com/Nheko-Reborn/nheko/issues/618

**Comment by deepbluev7** [comment]
This should be fixed now on the master branch. Please reopen if it isn't!
