### ISSUE TITLE
Mention in an reply gets messed up when editing

### ISSUE THREAD

**Issue by tastytea** [Nheko-Reborn/nheko#854]
### Describe the bug

When editing a message that is a reply and has a mention, the mention gets messed up.

### To Reproduce

1. Reply to a message, mention someone in it.
2. Edit the reply.
3. The mention is messed up.

### What happened?

`[tastytea](https://matrix.to/#/%40tastytea%3Apixie.town) test` turns into `[[tastytea](https://matrix.to/#/%40tastytea%3Apixie.town)](https://matrix.to/#/%40[tastytea](https://matrix.to/#/%40tastytea%3Apixie.town)%3Apixie.town) test`

### Screenshots

I think a video makes it clearer: https://user-images.githubusercontent.com/3681516/147288703-a38954ef-84ae-40b5-90e3-cc654d329c7b.mp4

### Version

0.9.1

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Qt version

5.15.2

### C++ compiler

11.2.0

### Desktop Environment

n/a

### Did you use profiles?

- [ ] Profiles used?

**Comment by tastytea** [comment]
Oh, and `[test](http://example.org/) lala [tastytea](https://matrix.to/#/%40tastytea%3Apixie.town)` turns into `test](http://example.org/) lala [[tastytea](https://matrix.to/#/%40tastytea%3Apixie.town)`.

When the message is just `[test](http://example.org/) lala` (without mention), it doesn't get messed up.

**Comment by deepbluev7** [comment]
The bug is actually that we don't strip out the html link from the plain text in replies
