### ISSUE TITLE
Render emojis defined between colons

### ISSUE THREAD

**Issue by gvolpe** [Nheko-Reborn/nheko#859]
### The Problem

Anyone using different Matrix clients usually send emojis by writing, e.g. `:smiley:`, which is also rendered here on Github ( :smiley: ).

Nheko either ignores these messages or something is wrong with the font I use (tried a few but settled for Noto Color emoji), but these are not rendered as emojis. E.g. this is what I see:

![img](https://i.imgur.com/wpaK8jz.png)

I tried both version `0.8.2` and the latest `0.9.1`.

### The Solution

It would be great if these messages could be parsed as emojis for a better user experience. If that's already possible, please pardon my ignorance, and I would appreciate if anyone can point me in the right direction to get this working. 

### Happens in the latest version

- [X] Yes, this feature is still missing.

**Comment by deepbluev7** [comment]
Nheko does not support replacing arbitrary text with emojis in received messages. Not only is that error prone, there is also no standard for emoji names (or at least I haven't found one yet).

Instead Nheko offers you a few options. When typing `:` it opens an autocompletion for emojis. When pressing the up, down or tab keys, you can cycle between the different options and select one with Enter. Alternatively you can also define custom emojis in the room settings. Those can be accessed using ~ (in the next release ot on the master branch!). That allows you to define arbitrary emojis, that you like, i.e. Pomies, Foxes, Cats and more. There would be no way to render those on other clients, if we didn't insert the image for those into the messages.

I hope this helps. That we would ever support replacing text in received messages is very unlikely. There is no unified list of what to replace with what and it sound error prone. Is that acceptable?

**Comment by gvolpe** [comment]
I appreciate your prompt reply, and I understand if there's no plan for supporting this, given the lack of a standard. 

That said, although not a universal standard, Github's markdown seems to support a widely accepted convention of [short-codes](https://github.com/ikatyang/emoji-cheat-sheet) for emojis such as `:smiley:` :smiley: or `:partying_face:` 🥳 . 

I think this would be a great feature to have in Nheko for a better UX. It could even be made optional or marked as experimental in the first phase, WDYT? Of course, this is just a long shot of an idea, I understand if it's rejected of indefinitely postponed :)

**Comment by deepbluev7** [comment]
I don't think replacing text in received messages is a good idea. If people want to actually send that text, it would lead to issues. Instead people should just send the emoji they want to send. I actually haven't yet encountered anyone sending such text, as such such a feature would have no use for me. I won't prevent anyone from adding such a feature, but I won't add it myself. I leave this open for if anyone else comes around and wants such a feature.

**Comment by LorenDB** [comment]
I agree. We don't plan to fix this and as it is being regarded as a bad idea, I'll close it.
