### ISSUE TITLE
Make custom emojis larger if 'large emoji in timeline' setting is activated

### ISSUE THREAD

**Issue by exaCORE42** [Nheko-Reborn/nheko#861]
### The Problem

It is hard to see custom emojis because they are very small.  I think that this is especially an issue when the custom emojis are used in their own message.

### The Solution

When the 'large emoji in timeline' option is enabled, custom emoji should be scaled up like normal emoji are.

### Happens in the latest version

- [X] Yes, this feature is still missing.

**Comment by deepbluev7** [comment]
We always have them 2x the size now, because custom emoji are too detailed usually. I think that should solve this too.
