### ISSUE TITLE
Make Normal emoji larger when in a message with text

### ISSUE THREAD

**Issue by exaCORE42** [Nheko-Reborn/nheko#862]
### The Problem

Normal emoji are very small when next to text

### The Solution

make them larger (same as when custom emoji are in the same situation)

### Happens in the latest version

- [X] Yes, this feature is still missing.

**Comment by annu2803** [comment]
Hi sir @exaCORE42 ,I would like to contribute but I'm newbie in open source can you please guide me.

**Comment by deepbluev7** [comment]
The easiest is probably to change https://github.com/Nheko-Reborn/nheko/blob/master/src/Utils.cpp#L124 to also set a fontsize in the font tag and make that 2x the size of the normal font. You also need to add another setting here: https://github.com/Nheko-Reborn/nheko/blob/master/src/UserSettingsPage.h . You can probably just orient yourself by the already existing larger emoji settings. Make sure the distinction of the settings is somewhat clear. Feel free to contact us in #nheko:nheko.im, if you have any trouble building Nheko.
