### ISSUE TITLE
Install nheko-git fails because of missing asciidoc build dependency

### ISSUE THREAD

**Issue by markusressel** [Nheko-Reborn/nheko#863]
### Describe the bug

Installing the AUR package fails with the error mentioned below.
From what I can tell a build dependency is missing.

### To Reproduce

1. `yay -S nheko-git`
2. See error

### What happened?

```
CMake Error at man/CMakeLists.txt:11 (message):
  Could not find asciidoc (a2x) or asciidoctor.  Man page generation not
  possible.
```

### Expected behavior

No error.

Can be fixed by installing asciidoc using f.ex.:
```
sudo pacman -S asciidoc
```
and then reinstalling.

### Version

nheko-git 0.9.1.r7.gbccab87a-1 

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Qt version

5.15.2

### C++ compiler

gcc version 11.1.0 (GCC)

### Desktop Environment

LightDM, i3wm

### Did you use profiles?

- [ ] Profiles used?

**Comment by exaCORE42** [comment]
This was fixed I think
