### ISSUE TITLE
Everything except the background flickers intermittently.

### ISSUE THREAD

**Issue by DAMO238** [Nheko-Reborn/nheko#865]
### Describe the bug

Randomly, everything except the background disappears and then loads back in repeatedly causing a flickering effect.

### To Reproduce

To make the issue occur more often, keep sending messages (although this might only be due to me noticing it more).

### What happened?

At random intervals, everything except the background of the window disappeared and reappeared.

### Expected behavior

All elements of the window should remain visible.

### Version

0.9.1-0e9b0c80

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Qt version

5.15.2+kde+r268-1

### C++ compiler

gcc 11.1.0-3

### Desktop Environment

i3 /w picom

### Did you use profiles?

- [ ] Profiles used?

### Relevant log output

```shell
No relevant logs
```

**Comment by deepbluev7** [comment]
This is https://gitlab.freedesktop.org/mesa/mesa/-/issues/5731

Please downgrade to mesa 21.2.

**Comment by DAMO238** [comment]
I see, I did not realise this was an upstream issue. Thanks for your help!
