### ISSUE TITLE
System Theme Isn't Completely Respected by Dialogue Windows and Chatrooms

### ISSUE THREAD

**Issue by ThisNekoGuy** [Nheko-Reborn/nheko#866]
### Describe the bug

Nheko's dialogue windows don't respect the system's drop-down lists, switches, buttons, and scrollbars.
This is also the case for chatroom scrollbars as well.

-----

For reference:

- [**Link to the system color theme**](https://store.kde.org/p/1403409)
- The KDE / Qt "Application Style" theme: **Oxygen**

**System Info:**

**OS:** Arch Linux x86_64
**Host:** MS-7B93
**Kernel:** [Linux 5.14.21-230-tkg-pds-llvm](https://github.com/frogging-family/linux-tkg)
**DE:** Plasma 5.23.4
**WM:** KWin
**Board:** Micro-Star International Co., Ltd. MPG X570 GAMING PRO CARBON WIFI (MS-7B93)

### To Reproduce

1. Go to **User Settings**
2. Enable system theming
3. Observe the the applied theme, closely
4. Exit User Settings
5. Open a chatroom, if you haven't already
6. See that chatroom scrollbars don't respect the system theme
7. Open a matrix user's profile in the chatroom
8. See that buttons do not respect the system theme
9. Open the chatroom's settings
10. See that drop-downs, switches, and buttons do not respect the system's theme
11. Open the chatroom's member info
12. See that this window also doesn't respect the system theme for the mentioned UI elements

### What happened?

The UI didn't completely respect my system's Qt theming.

### Expected behavior

I expected the UI to completely respect my system's Qt theming.

### Screenshots

**Example:**
![image](https://user-images.githubusercontent.com/28468662/147789055-4fb65b8d-e13c-4e23-8485-d54fbde16447.png)

**What the UI should look more like:**
![image](https://user-images.githubusercontent.com/28468662/147789189-60d1aa67-a169-4107-b106-54a4b1ce0e02.png)

### Version

0.9.1

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Qt version

5.15.2

### C++ compiler

Clang 13.0.0-4

### Desktop Environment

KDE Plasma - Kwin Window Manager

### Did you use profiles?

- [ ] Profiles used?

### Relevant log output

```shell
https://gist.github.com/ThisNekoGuy/f144f8e1ff3618448475a336955e0edf

(The log is too large to paste here)
```

**Comment by LorenDB** [comment]
@ThisNekoGuy: I currently cannot reproduce this apart from switches not respecting the system accent color. Is this still a problem on your system?

**Comment by LorenDB** [comment]
The switch theming issue is caused by the fact that somebody built a custom switch element and hardcoded some colors into it.
