### ISSUE TITLE
Can't login using KeepassXC

### ISSUE THREAD

**Issue by b0ywearngtights** [Nheko-Reborn/nheko#870]
### Describe the bug

I'm trying to login and get the same issue described here #847 
KeepassXC has been set up following the guide linked in the issue, confirmation it is working has been done by creating an entry with `secret-tool`.

I'm on gentoo and used the [ebuild](https://data.gpo.zugaina.org/guru/net-im/nheko/nheko-0.9.1.ebuild) available in the guru repo.

### To Reproduce

1. Run Nheko
2. Login with SSO
3. The error message pops up

### Version

nheko 0.9.1

### Operating system

Linux

### Installation method

Local build
(built with portage)

### Qt version

5.15.2

### C++ compiler

Clang 13.0.0

### Desktop Environment

BSPWM

### Relevant output

`ldd /usr/bin/nheko | grep keychain`  
output **libqt5keychain.so.1 => /usr/lib64/libqt5keychain.so.1 (0x00007fbce1a37000)**  

```
dbus-send --session --print-reply --dest=org.freedesktop.DBus / \
    org.freedesktop.DBus.GetConnectionUnixProcessID \
    string:org.freedesktop.secrets
```  
and then `pidof keepassxc` output the same pid

QtKeychain version is 0.13.2

**Comment by deepbluev7** [comment]
Did you enable the gnome-keychain flag on qtkeychain?

**Comment by b0ywearngtights** [comment]
nop..
so i rebuilt with the right flag and it works, it's not super intuitive, as i don't use gnome-keyring i didn't think i should use it (reading the ebuild firstly could have helped me..)

then i have the issue #834 but i see it will be fixed with a future keepassxc release
