### ISSUE TITLE
Failed to connect to secret storage - Windows 10

### ISSUE THREAD

**Issue by matebitte** [Nheko-Reborn/nheko#872]
**How it happened:** Downloaded, installed and ran nheko. logged in with id + pw, saw some rooms loading and encountered this error:

![image](https://user-images.githubusercontent.com/73599243/147912340-c87ae5b3-d54b-4346-b550-a9728385a047.png)

After clicking "ok" nheko simply quits.

<br/>

**What I tried:** Even though I never heard of something like that on windows, upon encounter I downloaded and configured KeePassXC to see if there is a secrets service. Obviously that did not fix the issue, cause its only for Linux, duh.

I also tried the version from choco, v0.9.0, no luck either.

Ofc I looked through [other issues](https://github.com/Nheko-Reborn/nheko/issues?q=Failed+to+connect+to+secret+storage) but they are all on linux. However, [this comment](https://github.com/Nheko-Reborn/nheko/issues/705#issuecomment-995043093) mentions that it should work by default on windows.

**Platform:** Windows Pro v10.0.19042 Build 19042, nheko 0.9.1 | (+ ubuntu WSL, does nheko detect that?)
**Installation:** [direct download](https://github.com/Nheko-Reborn/nheko/releases/tag/v0.9.1), chocolatey

**Comment by deepbluev7** [comment]
Hm, I'll see if I can setup a Windows VM to test this.

**Comment by redsky17** [comment]
I’ve not encountered this issue on Windows 10 or 11… can you check if your Windows Credential Manager service is running? Basically the reverse of these steps: https://superuser.com/a/346779

**Comment by deepbluev7** [comment]
I'm pretty sure this should autostart on normal installations.

**Comment by deepbluev7** [comment]
Since afaik this only happens if someone manually has turned the credential manager off, I will close this. People should just manually turn that on, if they turned it off.
