### ISSUE TITLE
Text parts get replaced by emojis when using Fonts Awesome Free 5

### ISSUE THREAD

**Issue by gvolpe** [Nheko-Reborn/nheko#877]
### Describe the bug

Typing words that represent emojis triggers an emoji replacement, and it does not seem possible to disable it. E.g. the following text:

```
easy to get started with, but there is no map, traverse, etc
```

Gets rendered as shown below.

![bug](https://i.ibb.co/hW0xfyb/nheko-bug.png)

The same happens with incoming messages from other users.

---

I'm not sure whether this is intentional or a bug, but I figured it was worth reporting it. Note that the problem goes away if I select a different font.

### To Reproduce

1. Go to settings
2. Set Font Family to "Font Awesome Free 5" ([download link](https://fontawesome.com/v5.15/how-to-use/on-the-web/setup/hosting-font-awesome-yourself))
3. Restart Nheko
4. Type `get started with map`
5. See bug

### Version

0.9.1

### Operating system

Linux

### Installation method

Local build

### Desktop Environment

XMonad, no DE

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment]
I think this is a fontawesome feature. Fontawesome is not a normal font and as such, it is not supported as a font in Nheko. We only support fonts, that map normal unicode chars to emojis or characters.
