### ISSUE TITLE
Docker: white text on white background

### ISSUE THREAD

**Issue by hardcore-sushi** [Nheko-Reborn/nheko#880]
### Describe the bug

I compiled nheko from source and tried to run it inside a docker container. When I launch it, I got this weird UI (see screenshots). However it works fine when not run from a container. I tried to force dark theme with the `QT_STYLE_OVERRIDE` variable but it didn't work.

Here is my Dockerfile:
```
FROM archlinux:latest
RUN pacman -Syu --noconfirm
RUN pacman -S --noconfirm cmark spdlog qt5-svg qt5-multimedia qt5-quickcontrols2 qtkeychain-qt5 libolm lmdb gst-plugins-bad-libs libevent
RUN useradd -m user
COPY nheko /usr/bin/
COPY libmatrix_client.so.0.6.1 libcoeurl.so.0 /usr/local/lib/
USER user
CMD ["/usr/bin/nheko"]
```
And here is how I start the container:
```
$ touch /tmp/.docker.xauth
$ xauth nlist :0 | sed -e 's/^..../ffff/' | xauth -f /tmp/.docker.xauth nmerge -
$ docker run --rm -t \
	--cap-drop=ALL \
	-v /tmp/.X11-unix:/tmp/.X11-unix \
	-v /tmp/.docker.xauth:/tmp/.docker.xauth \
	-e XAUTHORITY=/tmp/.docker.xauth \
	-e DISPLAY \
	--device /dev/dri \
	nheko
```

### To Reproduce

1. Compile nheko
2. Run it from a docker container

### Expected behavior

The background should be dark, or the text should be black so we can read something.

### Screenshots

![nheko-1](https://user-images.githubusercontent.com/68192412/148371679-a48f67c1-b3f0-4bd7-9f43-b3ddf6c45a03.png)
![nheko-2](https://user-images.githubusercontent.com/68192412/148371681-de58a060-433f-4fe5-b1de-05947c698101.png)

### Version

v0.9.1-8d52c17

### Operating system

Linux

### Installation method

Local build

### Qt version

5.15.2

### C++ compiler

gcc 11.1.0-3

### Desktop Environment

Cinnamon (on host)

### Did you use profiles?

- [ ] Profiles used?

### Relevant log output

```shell
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-user'
[2022-01-06 10:49:45.771] [ui] [info] Restoring window size 0x0
[2022-01-06 10:49:45.890] [ui] [info] WebRTC: initialised GStreamer 1.18.5
[2022-01-06 10:49:45.910] [ui] [info] jdenticon plugin not found.
[2022-01-06 10:49:45.991] [qml] [warning] qrc:/qml/Root.qml:28:5: Type EmojiPicker unavailable 
         EmojiPicker { 
         ^ (qrc:/qml/Root.qml:28, )
[2022-01-06 10:49:45.991] [qml] [warning] qrc:/qml/emoji/EmojiPicker.qml:7:1: module "QtGraphicalEffects" is not installed 
     import QtGraphicalEffects 1.0 
     ^ (qrc:/qml/emoji/EmojiPicker.qml:7, )
[2022-01-06 10:49:45.991] [ui] [debug] Status changed to 3
[2022-01-06 10:49:46.019] [qml] [warning] QFont::setPointSize: Point size <= 0 (-1), must be greater than 0 (:0, )
[2022-01-06 10:49:46.030] [qml] [warning] QFont::setPointSize: Point size <= 0 (-1), must be greater than 0 (:0, )
[2022-01-06 10:49:46.061] [qml] [warning] QFont::setPointSize: Point size <= 0 (-1), must be greater than 0 (:0, )
[2022-01-06 10:49:46.149] [ui] [info] starting nheko 0.9.1-8d52c17
```

**Comment by deepbluev7** [comment]
You are missing at least one qml module and probably some fonts. I don't think this is a Nheko bug, but you are just missing dependencies.

**Comment by hardcore-sushi** [comment]
OK, it worked great after installing `gnu-free-fonts`. Thanks!
![nheko](https://user-images.githubusercontent.com/68192412/148432616-72bb3398-2a07-4151-9222-5e52d6dcab3c.png)
By the way, how can I set the default theme to dark theme?

**Comment by deepbluev7** [comment]
You can't really change the default theme without patching the source code or pregenerating the config file atm

**Comment by hardcore-sushi** [comment]
Oh that's strange because when running outside of the container, nheko starts in dark theme by default. Maybe I have to edit some system-wide configuration files or environment variables?

**Comment by deepbluev7** [comment]
If you have changed the theme to dark, it will persist even after logout. And if the QPA_SYSTEM_THEME or so environment variable is set, it will use your system theme, which needs to be in the container of course.

**Comment by hardcore-sushi** [comment]
OK, but I set the `QPA_SYSTEM_THEME` variable, weird things happen:
![nheko-dark](https://user-images.githubusercontent.com/68192412/148530454-fd194c7a-dbc1-4b31-91b2-ff947cdae060.png)
I get this inside and outside of the container. Do I need to install additional dependencies?

**Comment by deepbluev7** [comment]
No, that is a theming issue with Nheko :D
