### ISSUE TITLE
unable to quote messages (phone)

### ISSUE THREAD

**Issue by sc0w** [Nheko-Reborn/nheko#884]
### Describe the bug

unable to quote messages

### To Reproduce

1. do with finger twice in a message into a room

### What happened?

nothing happens

### Expected behavior

the message must be quoted

NOTE: it worked in 0.8.2, it doesn't work in 0.9.0

### Version

`0.9.0`, `0.9.1`, `0.9.3`

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Desktop Environment

pinephone with mobian phosh (bookworm)

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment]
What exactly are you trying to do? Does it only work the first time or not at all?

**Comment by sc0w** [comment]
![](https://user-images.githubusercontent.com/3681516/131397620-68d63bf3-22c7-43cc-bd59-75b8427ce2b2.png)

quote messages, like this image ^^^ (image taken from other issue), nothing happens instead

it worked with 0.8.2, and it doesn't work in 0.9.0

**Comment by deepbluev7** [comment]
How are you trying to quote the message? By long pressing the message? Or by pressing the buttons?

**Comment by deepbluev7** [comment]
And do you have mobile mode on or off?

**Comment by deepbluev7** [comment]
Does it work, if you long press the timestamp?

**Comment by sc0w** [comment]
> How are you trying to quote the message? By long pressing the message? Or by pressing the buttons?

with double click with finger (mobile) on the message



> And do you have mobile mode on or off?

I have "touchscreen mode" enabled


> Does it work, if you long press the timestamp?

nothing happens with long press, with single press I see the detailed timestamp, and with double press I see now the quote

ok, now it works with double press on timestamp, in the past it worked over the message, the behavior was changed?

**Comment by deepbluev7** [comment]
No, this is a bug, I was just trying to narrow it down. I'll fix it at some point. (It has to do with the link handling, that we fixed, but now we broke something else it seems.)
