### ISSUE TITLE
Native Notifications (Linux)

### ISSUE THREAD

**Issue by DAMO238** [Nheko-Reborn/nheko#885]
### The Problem

Enabling desktop notifications causes a Qt popup to occur for every message. My system uses notify-osd, which implements the freedesktop.org desktop notifications specification, thus if native notifications are requested, a la `notify-send`, I should receive a pretty notification in the top right that disappears after some time.

### The Solution

Implement an option to use native notifications.

### Additional context

This has been tested with libnotify and notify-osd on arch.

### Happens in the latest version

- [X] Yes, this feature is still missing.

**Comment by LorenDB** [comment]
I believe that we do use the freedesktop DBus specification.

@deepbluev7: am I missing something or am I correct?

**Comment by deepbluev7** [comment]
No, we just use the dbus API, so I don't see how that could happen. Unless you are running 2 notification daemons by accident.

**Comment by DAMO238** [comment]
Ok, that is very strange then. I double checked systemctl status to find any other notification daemons, and only found notify-osd, as I expected. Additionally, every other application that uses native notifications uses notify-osd. I don't see anything in the nheko logs either.

Having tested sending a notification via dbus manually on my side with `dbus-send --session --dest=org.freedesktop.Notifications /org/freedesktop/Notifications org.freedesktop.Notifications.Notify string:'app' uint32:0 string:'' string:'' string:'example'`, I can confirm that this is an issue on my side, and there is no issue with Nheko as far as I can tell.

**Comment by DAMO238** [comment]
I solved it by switching to dunst, which I prefer anyway because I can theme it!
