### ISSUE TITLE
Unable to download images in nheko image viewer

### ISSUE THREAD

**Issue by sc0w** [Nheko-Reborn/nheko#887]
### Describe the bug

Unable to download images in nheko image viewer

### To Reproduce

1. Receive an image into a room
2. See the image with nheko image viewer
3. Try to download, using the "arrow down" icon

### What happened?

nothing happens

### Expected behavior

ask the folder destination and download image

### Version

`0.9.0`, `0.9.1`

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Desktop Environment

pinephone with mobian phosh (bookworm)

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment]
Can you try our flatpak nightly or otherwise build the master branch? It should be fixed there.

**Comment by deepbluev7** [comment]
Works for me on master, so I consider this fixed, because I explicitly tried to fix this when I rewrote the image viewer :D
