### ISSUE TITLE
Flickering on KDE Plasma

### ISSUE THREAD

**Issue by obsidianical** [Nheko-Reborn/nheko#889]
### Describe the bug

When using the app I had severe flickering yesterday. After restarting the computer the app worked, but the severe flickering almost made the app unusable. 

### To Reproduce

1. install nheko and log in
2. run the app
3. use it (the flickering was everywhere)

### What happened?

Strong flickering, no matter what i did in the app. 

### Expected behavior

Normal, usable UI, no severe flickering.

### Version

0.9.1

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Desktop Environment

KDE with Kwin with a tiling script

### Did you use profiles?

- [ ] Profiles used?

**Comment by LorenDB** [comment]
This is a known problem with Mesa. Closing because it's not our problem to fix.

**Comment by deepbluev7** [comment]
See https://gitlab.freedesktop.org/mesa/mesa/-/issues/5731 for reference
