### ISSUE TITLE
No notifications for selected room when Nheko is not focussed on Phosh

### ISSUE THREAD

**Issue by cparich** [Nheko-Reborn/nheko#890]
### Describe the bug

The active room does not begin showing notifications when another window has focus on mobian/Phosh

### To Reproduce

1. Open a room
2. Switch to different window (firefox)
3. Receive notifying event (@ username)

### What happened?

No notification received

### Expected behavior

A notification is received

### Version

0.9.1-b9a4f36 | Linux

### Operating system

Linux

### Installation method

Flathub

### Desktop Environment

Phosh

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment]
I'm guessing that phosh just never tells us, that we are not focused, but someone should investigate that.

**Comment by cparich** [comment]
Looks like problem is fixed in phosh 0.15.0, mobian bookworm
