### ISSUE TITLE
`/snowfall <message>` does not get rendered and dated to 1970-01-01 (also applies to `/confetti <message>`, `/confetti <message>`, `/rainfall <message>`, `/spaceinvaders message`.)

### ISSUE THREAD

**Issue by dreirund** [Nheko-Reborn/nheko#894]
### Describe the bug

When I write in another client `/snowfall`, nheko does correctly displays it as `<user> sends snowfall ❄` with correct timestamp. When I write `/snowfall <message>`, nheko does display `Unretrieved event` and dates it to 1970-01-01, and shows "This message is not encrypted!" although it is an encrypted chat and shows "edited" although it has not been edited.

(Does also apply to `/confetti <message>`, `/confetti <message>`, `/rainfall <message>`, `/spaceinvaders message`. On the other side, `/ranbow <message>`, `/rainbowme <message>`, `/me <message>` and `/spoiler <message>` display correctly, althouth `/spoiler <message> is not hidden by default as it is in the clients Element and SchildiChat.)

### To Reproduce

1. Be logged in with Matrix account *A* in the client "[SchildiChat-desktop](https://github.com/SchildiChat/schildichat-desktop)" (it is based on the Matrix reference client "[Element-desktop](https://github.com/vector-im/element-desktop)"),
2. be logged in with Matrix account *B* in the client "[Nheko](https://github.com/Nheko-Reborn/nheko)",
3. have an encrypted private conversation between *A* and *B*,
4. have *A* write ```/snowfall This is a `/snowfall` message``` to *B*,
5. see the problem described above.

### What happened?

Here are details and screenshots of the situation (personal information such as user names greyed out):

1. What I have sent in SchildiChat:  
  ![00_-_element-snowfall-sent](https://user-images.githubusercontent.com/1590519/149329209-32bef3cc-6320-4121-90eb-b92419e5c21a.png)
2. The "Decrypted event source" from within SchildiChat of the ```/snowfall This is a `/snowfall` message```-message:  
   ```
   {
     "type": "m.room.message",
     "content": {
       "msgtype": "io.element.effect.snowfall",
       "body": "This is a `/snowfall` message."
     }
   }
   ```
3. What was received in Nheko:  
  ![02_-_nheko-snowfall-retrieved](https://user-images.githubusercontent.com/1590519/149329283-a4ca9cff-9b47-449e-b56a-0a39580737ab.png)
4. "View raw message" does not show up anything in Nheko.

### Expected behavior

That Nheko displays ```This is a `/snowfall` message.``` with snowfall effect.

### Screenshots

*See above at "What happened?".*

### Version

0.9.1-c59bb675

### Operating system

[Artix GNU/Linux](http://artixlinux.org).

### Installation method

[AUR package `nheko-git`](https://aur.archlinux.org/packages/nheko-git/).

### Qt version

5.15.2+kde+r289 ([Artix GNU-Linux-package `qt5-base`](https://gitea.artixlinux.org/artixlinux/packages-qt5/src/branch/master/qt5-base)).

### C++ compiler

gcc-11.1.0

### Desktop Environment

no desktop environmnt. Plain `xfwm4` window manager and standalone `xfce4-taskbar`.

### Did you use profiles?

- [ ] Profiles used?

**Comment by N07070** [comment]
Can reproduce, confirming bug.

**Comment by LorenDB** [comment]
The events are now not shown at all, which can be considered progress or regress, depending on your viewpoint.

**Comment by LorenDB** [comment]
Confetti has been implemented and I have a fix for the others in the pipeline.
