### ISSUE TITLE
Unable to import E2EE session keys: decrypt_exported_sessions: ciphertext too small

### ISSUE THREAD

**Issue by xaionaro** [Nheko-Reborn/nheko#896]
### Describe the bug

I export E2EE session keys from Element and try to import in nheko. And it returns error: `decrypt_exported_sessions: ciphertext too small`

### To Reproduce

1. In Element: go to "All Settings" -> "Security & Privacy" -> "Export E2E room keys"
2. Enter a passphrase, put it to /tmp
3. In nheko: Settings -> "IMPORT"
4. Pick the file (from /tmp), enter the passphrase.
5. See the error.

### What happened?

The keys were not exported, error `decrypt_exported_sessions: ciphertext too small` is reported instead.

### Expected behavior

Keys are exported, E2E messages becomes visible, no error reported.

### Screenshots

![Screenshot from 2022-01-14 08-24-52](https://user-images.githubusercontent.com/2349376/149475479-acb50888-9e3d-446d-819e-40e0c2fdb272.png)

### Version

0.6.4-2build2

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Qt version

5.12.8

### C++ compiler

gcc-9.3.0

### Desktop Environment

awesome

### Did you use profiles?

- [ ] Profiles used?

### Relevant log output

```shell
No relevant output provided by nheko
```

**Comment by LorenDB** [comment]
0.6.4 is practically prehistoric. Please install the latest flatpak instead. You will love the updates anyway.

**Comment by deepbluev7** [comment]
Yeah, 0.6.4 implements the format that was in the spec at the time. Then they noticed, that the format does not match what Element implements, so they changed the spec. We then had to adapt our implementation. Please update to a version released in the last 12 months (those also bring a lot of e2ee fixes).

**Comment by xaionaro** [comment]
I tried to install from flatpak, it does not connect to Xorg (and therefore does not run). I also tried to build, but it does not find `MatrixClient` cmake files (I guess because they are called `QMatrixClient` in ubuntu). But thanks :)

I guess will try next time when a new version will come to Ubuntu.

**Comment by deepbluev7** [comment]
To build, you can just enable -DUSE_BUNDLED_MTXCLIENT=ON and -DUSE_BUNDLED_COEURL=ON :3

**Comment by xaionaro** [comment]
Nah, it still does not build:
```
 * voip, GStreamer could not be found on your system.  As a consequence call support has been disabled. If you don't want that, make sure gstreamer-sdp-1.0>=1.18 gstreamer-webrtc-1.0>=1.18 can be found via pkgconfig.
```
And passing flag `-DVOIP=OFF` (mentioned in README.md) to the cmake command does not work. I tried to install all gstreamer packages which seemed to be useful.

**Comment by deepbluev7** [comment]
Hm, -DVOIP=OFF should work... we use that in our CI o.o

**Comment by xaionaro** [comment]
```
xaionaro@void:~/src/nheko$ cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Release -DUSE_BUNDLED_MTXCLIENT=ON -DUSE_BUNDLED_COEURL=ON -DVOIP=OFF
Build type set to 'Release'
-- Version: 0.8.2-d61a9c71
-- The following OPTIONAL packages have been found:

 * Qt5QuickCompiler

-- The following REQUIRED packages have been found:

 * LMDB
 * Qt5Gui (required version >= 5.12.8)
 * Qt5Widgets
 * Qt5LinguistTools
 * Qt5Concurrent
 * Qt5Svg
 * Qt5Network (required version >= 5.12.8)
 * Qt5Multimedia
 * Qt5Qml
 * Qt5Quick (required version >= 5.12.8)
 * Qt5QuickControls2
 * Qt5QuickWidgets
 * Qt5 (required version >= 5.12)
 * Qt5Core
 * Qt5DBus
 * Qt5Keychain
 * OpenSSL (required version >= 1.1.0), Open source SSL and TLS implementation and cryptographic library, <https://www.openssl.org/>
 * Olm (required version >= 3), An implementation of the Double Ratchet cryptographic ratchet, <https://git.matrix.org/git/olm/about/>
 * nlohmann_json (required version >= 3.2.0), JSON for Modern C++, a C++11 header-only JSON class, <https://nlohmann.github.io/json/>
 * PkgConfig
 * Threads
 * spdlog (required version >= 1.0.0)

-- Checking for modules 'gstreamer-sdp-1.0>=1.18;gstreamer-webrtc-1.0>=1.18'
--   Requested 'gstreamer-sdp-1.0 >= 1.18' but version of GStreamer SDP Library is 1.16.2
--   No package 'gstreamer-webrtc-1.0' found
-- The following OPTIONAL packages have been found:

 * Qt5QuickCompiler

-- The following REQUIRED packages have been found:

 * LMDB
 * Qt5Gui (required version >= 5.12.8)
 * Qt5LinguistTools
 * Qt5Concurrent
 * Qt5Svg
 * Qt5Multimedia
 * Qt5Qml
 * Qt5Quick (required version >= 5.12.8)
 * Qt5QuickControls2
 * Qt5QuickWidgets
 * Qt5DBus
 * Qt5Keychain
 * OpenSSL (required version >= 1.1.0), Open source SSL and TLS implementation and cryptographic library, <https://www.openssl.org/>
 * PkgConfig
 * Olm (required version >= 3), An implementation of the Double Ratchet cryptographic ratchet, <https://git.matrix.org/git/olm/about/>
 * Threads
 * spdlog (required version >= 1.0.0)
 * cmark
 * nlohmann_json (required version >= 3.2.0), JSON for Modern C++, a C++11 header-only JSON class, <https://nlohmann.github.io/json/>
 * Qt5Core
 * Qt5Network
 * Qt5Widgets
 * Qt5

-- The following features have been disabled:

 * voip, GStreamer could not be found on your system.  As a consequence call support has been disabled. If you don't want that, make sure gstreamer-sdp-1.0>=1.18 gstreamer-webrtc-1.0>=1.18 can be found via pkgconfig.

-- Configuring done
-- Generating done
-- Build files have been written to: /home/xaionaro/src/nheko/build
```

The version is downgraded to `0.8.2-d61a9c71`, because in Ubuntu20.04 there is only Qt5.12 (not Qt5.15).

**Comment by deepbluev7** [comment]
0.8.2 shouldn't have the voip switch and it's fine, if it can't find gstreamer. It just disables VOIP automatically.

**Comment by xaionaro** [comment]
A, OK. Sorry, misread the error.

**Comment by xaionaro** [comment]
Anyway it does not build:
```
/home/xaionaro/src/nheko/src/Cache_p.h: In member function ‘std::vector<mtx::events::StateEvent<Content> > Cache::getStateEventsWithType(lmdb::txn&, const string&)’:
/home/xaionaro/src/nheko/src/Cache_p.h:500:63: error: no matching function for call to ‘lmdb::cursor::get(std::string_view&, std::string_view&, MDB_cursor_op)’
  500 |                         if (cursor.get(typeStrV, data, MDB_SET)) {
```
Never mind. Do not waste time on me. I'll just stay on Element for now :)

**Comment by deepbluev7** [comment]
Yeah, wrong version of the lmdb++ header, but running Element is probably the easiest option :3
