### ISSUE TITLE
.well-known support to autofill server URL

### ISSUE THREAD

**Issue by aaronraimist** [Nheko-Reborn/nheko#9]
I'd love to see .well-known support to autofill the homeserver address. Right now if I enter @aaron:raim.ist, it autofills raim.ist which is a good guess but isn't actually where my server is. 

Spec: https://matrix.org/docs/spec/client_server/r0.4.0.html#well-known-uri

Example: https://raim.ist/.well-known/matrix/client

**Comment by deepbluev7** [comment]
I've implemented this in the 0.7.0 branch, so I'll close this.
