### ISSUE TITLE
Reconnecting after internet connection drop does not work

### ISSUE THREAD

**Issue by pravi** [Nheko-Reborn/nheko#90]
### System:

- Nheko version: 0.6.4
- Installation method: .deb
- Operating System: Debian buster (backports)
- Qt version: 
- C++ compiler: 
- Desktop Environment: 

### Actual behavior

Reconnect just hangs, shows reconnecting message in message typing area, greyed out, cannot type anything and cannot receive new messages (can see new messages in riot android, both sharing the same wifi).

### Expected behavior

Reconnect should work when internet connection comes back.

### Steps to reproduce

Switch off the wireless router (power interruption in India) or otherwise turn off wireless from system and turn it on after some time.

**Comment by pravi** [comment]
Finally I have to close nheko and start it again to get it working.

**Comment by pravi** [comment]
It seems the reconnection error was only when power was down for a long time and router got turned off.

**Comment by redsky17** [comment]
This is something that I've noticed can happen as well.  I believe it's related to a double free during ssl init or shutdown that we're aware of.  I also think it's probably related to the 100% cpu usage bug.  Just know that it's being investigated / worked on and hopefully we'll have a fix soon.

**Comment by deepbluev7** [comment]
We did fix those double free issues. Does anyone still have reconnection issues? I didn't have any recently, but who knows, my internet was also very stable for the last few weeks :3

**Comment by pravi** [comment]
Looks like it is fixed now. 0.7.1

**Comment by deepbluev7** [comment]
Thank you for verifying :3
