### ISSUE TITLE
start direct messages without explicitely creating a room first

### ISSUE THREAD

**Issue by maltee1** [Nheko-Reborn/nheko#904]
### The Problem

To start a direct message by entering an mxid on nheko, you have to create a room first and then invite someone to that room. While on matrix everything happens in a room so this makes sense from a protocol perspective, it's cumbersome and unintuitive.

### The Solution

I suggest an option to "start direct message" or similar when clicking the plus on the bottom left.

### Happens in the latest version

- [x] Yes, this feature is still missing.

**Comment by deepbluev7** [comment]
(Note that you can also start a DM already by clicking on someones profile and there on the chat button)

**Comment by maltee1** [comment]
I know, but I can only get someones profile from a room that account is already in. If I'm exchanging account information outside of matrix, I want to be able to type the mxid to start a dm (or scan a QR code, like on Element)

**Comment by deepbluev7** [comment]
Yeah, I plan to add that at some point, just wanted to make sure the current method was known :3

**Comment by LorenDB** [comment]
This has been implemented at some point since this issue was created.
