### ISSUE TITLE
"quit / left" room messages not line wrapped (mobian phosh pinephone)

### ISSUE THREAD

**Issue by sc0w** [Nheko-Reborn/nheko#905]
### Describe the bug

"quit / left" room messages missaligned

### To Reproduce

1. enter a room
2. wait and see the left or quit messages

### What happened?

![2022-01-23_15-49](https://user-images.githubusercontent.com/7734191/150684346-61f7e878-99b0-4c7c-a495-e74e6fa8f8e6.png)

### Expected behavior

"left / quit" messages must be properly aligned

NOTE: it worked in 0.8.2

### Version

`0.9.0` and `0.9.1`  from debian sid

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Did you use profiles?

- [ ] Profiles used?

**Comment by maltee1** [comment]
I haven't seen such issues. I suppose it's fixed.
If nobody actually tried to fix this particular issue, it's probably my changes to the layout that accidentally fixed it.
