### ISSUE TITLE
Freeze when connectivity is lost, no recovery

### ISSUE THREAD

**Issue by tastytea** [Nheko-Reborn/nheko#910]
### Describe the bug

When connectivity is lost nheko freezes. It did not recover 5 minutes after the server was up again.

### To Reproduce

1. Arrange for your homeserver to return HTTP 502
2. Use nheko until it freezes
3. Restore your homeservers connectivity
4. nheko is still frozen

(I didn't actually reproduce it because I run no server)

### What happened?

The home-server I'm on went down. HTTP error 502 was returned, according to the log. nheko continued to work for a while, I could change rooms. Then it froze. When I changed to another workspace and back to the workspace with nheko on it, the window had the contents of the window in the old workspace. It did not recover 5 minutes after the server was up again. Then I killed nheko and restarted it.

The connectivity was lost for about an hour.

### Version

0.9.1-9f31095e

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Qt version

5.15.2

### C++ compiler

gcc-11.2.0

### Desktop Environment

n/a with i3 as window manager

### Did you use profiles?

- [ ] Profiles used?

### Relevant log output

```shell
[2022-01-28 21:02:28.221] [qml] [warning] render glyph failed err=13 face=0x5631d6fc6660, glyph=569 (:0, )
[2022-01-28 21:03:40.817] [net] [warning] failed to send typing notification:
[2022-01-28 21:03:40.818] [net] [warning] failed to stop typing notifications:
[2022-01-28 21:03:40.818] [net] [warning] failed to stop typing notifications:
[2022-01-28 21:03:40.819] [net] [warning] failed to stop typing notifications:
[2022-01-28 21:03:40.819] [net] [warning] failed to stop typing notifications:
[2022-01-28 21:03:42.866] [net] [error] sync error: (http: 502, parser: [json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - invalid literal; last read: '<': <!DOCTYPE html>
<html lang="en"><head><meta charSet="UTF-8"/><meta name="viewport" content="width=device-width"/><meta name="description"/><link rel="stylesheet" href="/assets/bundle.css"/><title>502</title></head><body><div class="page"><nav id="nav1"><a href="/" class="nobg"><img id="pixie" alt="a purple pixie, drawn" src="/assets/pixie.png"/></a><h2>Services</h2><a href="/matrix">Matrix</a><a target="_blank" href="https://social.pixie.town">Mastodon</a><a target="_blank" href="https://git
.pixie.town">Gitea</a><a href="/mumble">Mumble</a><a target="_blank" href="https://write.pixie.t
own">Write</a><h2>Other</h2><a href="/about">About</a></nav><h1 class="header">502</h1><main><p>Uh oh, that service is down. Hopefully our pixies are busy fixing it, but if this is unannounced
 you can report it through the <a href="/about#contact">contact</a> links</p></main><span id="a"
>&lt;/div&gt;</span><footer>This site was made with <a href="https://shayu.it">shayu</a></footer></div></body></html>)
[2022-01-28 21:03:42.866] [net] [info] connectivity lost
[2022-01-28 21:03:42.868] [net] [info] connectivity lost
[2022-01-28 21:03:42.868] [net] [info] connectivity lost
[2022-01-28 21:03:42.868] [net] [info] connectivity lost
[2022-01-28 21:03:42.868] [net] [info] c
```

**Comment by deepbluev7** [comment]
Do you know when this started happening? I don't think it used to do that in the past...

**Comment by deepbluev7** [comment]
I can't reproduce it by shutting down my server :/

**Comment by tastytea** [comment]
> Do you know when this started happening? I don't think it used to do that in the past...

It only happened 1 time so far, on 2022-01-28.

> I can't reproduce it by shutting down my server :/

I can reproduce it by blocking the connection to my homeserver in a firewall and killing the established connection (`ss -K dst <IP> dport = 443`) with 0.9.1-df6a5aab. Nheko does not react to the close-window signal but it shuts down after sending SIGTERM.

**Comment by deepbluev7** [comment]
I tried it a lot now, I just can't reproduce it. And I tried it multiple times. I know I reproduced it in the past, but now I can't... If anyone has a good backtrace of this, I would be very grateful!

**Comment by tastytea** [comment]
I TRAPed it after it froze: [bt.txt](https://github.com/Nheko-Reborn/nheko/files/8192040/bt.txt).

**Comment by deepbluev7** [comment]
That's perfect, thanks!

**Comment by tastytea** [comment]
Fixed in <https://nheko.im/nheko-reborn/coeurl/-/commit/0a49dfe5ae0a4c5abf18fa68148477db9fc6b8b8>.
