### ISSUE TITLE
When verifying the emojis are clipped...

### ISSUE THREAD

**Issue by deepbluev7** [Nheko-Reborn/nheko#917]
### Describe the bug

I tried to verify myself on macOS. That worked, but when it came to compare the emojis, they weren't shown! I had to resize the window first!!!

### To Reproduce

Sign in to macos and hit verify

### What happened?

Emoji clipped

### Expected behavior

See emoji, that I am supposed to compare

### Version

0.9.1+ witht he qml root

### Operating system

macOS

### Did you use profiles?

- [ ] Profiles used?

**Comment by tastytea** [comment]
Similar issue with with i3 on Linux, nheko 0.9.3-cb76777f. Emojis were shown, but buttons were hidden.
