### ISSUE TITLE
Differentiate between rooms in spaces which can't be joined and can't be previewed

### ISSUE THREAD

**Issue by Cadair** [Nheko-Reborn/nheko#923]
### The Problem

When you are looking at the rooms in a space, there's no way of knowing if the room can't be previewed because it's broken or can't be previewed because you can't join it.

### The Solution

Make it clear which rooms can't be joined without an invite.

### Alternatives

Don't show rooms in the list which you can't join.

### Happens in the latest version

- [X] Yes, this feature is still missing.

**Comment by deepbluev7** [comment]
Hm, I am not sure, if we can say that in general. Because if we can't preview a room, we can't check, if we can or can not join it, I think?

**Comment by Cadair** [comment]
Yeah, I guess this might have some cases where it's hard to know. If I remember the summary API correctly it returns you stripped state for all the rooms you could join, so if it doesn't come down in the summary you can't join it?

**Comment by JeanPaulLucien** [comment]
![nheko 0 10 2 - issue - 001](https://user-images.githubusercontent.com/24779886/212485836-b1343d42-181f-46a3-b1f7-e6e82de2003e.jpg)
Do you mean that? I tried to join using nheko 0.10.2, it suggested to knock. I tried to knock but it answered "No permissions".

**Comment by deepbluev7** [comment]
Afaik this is done, since those rooms are now either not shown or for admins they have a message about being unjoinable :)
