### ISSUE TITLE
Rooms you haven't joined in a space show up as "No preview available"

### ISSUE THREAD

**Issue by lboklin** [Nheko-Reborn/nheko#929]
### Describe the bug

When a space is selected there may be several occurrences of "No preview available" sharing the same generic icon. Sometimes these are rooms that have yet to load.

### To Reproduce

Click on a space in the group sidebar that has rooms you're not already in.

### What happened?

You see a list of "No preview available" in the room panel. If you wait a while you may see (some of) them being replaced with their correct room icon and name.

### Expected behavior

Rooms that may be previewed but haven't loaded yet should have an appropriate indicator that they're still being loaded. Rooms that can't be previewed should still show up with the correct icon and name.

### Screenshots

![image](https://user-images.githubusercontent.com/6375669/153553104-72b72e26-b052-414c-a0f2-7faa68d9303f.png)

### Version

0.9.1

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Desktop Environment

KDE Plasma

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment]
This is already fixed on master :3
