### ISSUE TITLE
Unify spaces/group side panel and room list into a tree view

### ISSUE THREAD

**Issue by lboklin** [Nheko-Reborn/nheko#933]
### The Problem

Having two panels for spaces and rooms feels a bit arbitrary given the nature of spaces (that are just rooms themselves). It also wastes horizontal screen space.

### The Solution

Presenting spaces and rooms similarly to how file managers (have the option to) show a tree of directories and files would save horizontal space as well as give a better overview of what rooms are in which spaces.

If one prefers a flat list of rooms filtered by a particular space, a toggle option for choosing between tree view and list view could be offered, which would work as you'd expect from a file manager. 

In tree view, child spaces would be (recursively) expandable (ideally also with an expand/collapse all button) with increasing indentation and would be (optionally) listed first. Only the rooms directly in the currently selected space are listed at the top level, (optionally) after the subspaces.

In list view, direct child spaces of the currently selected space would be (optionally) listed first but not expandable. All rooms from all subspaces would be listed below. Selecting a subspace would enter it, making it the currently selected space.

The equivalent to a file manager's current working directory would be a space "filter" (currently selected space), presented as a navigable path on top, like "MyRootSpace > AnotherSpace > AnotherSubspace" and would apply to both views. (This path should also have little indicators for new unread messages in super-spaces of the currently selected space up to shortest relative path, making #932 redundant.)

Example of Dolphin's "details view" which is much like how I imagine the tree view would look, with spaces instead of directories and rooms as files:
![image](https://user-images.githubusercontent.com/6375669/153558902-93ac538b-fde0-48fb-a5cc-8d16682e940c.png)

#### Complementary feature: filtered room list

If you allow me to go a little crazy here: Instead of having a tree and a list view option, there would be only the unified tree view but there would also be a superpowered room-listing feature that supports filtering by certain criteria. It would be a panel that looks much like the current room list panel but it also offers optional criteria fields. Each criteria field should probably each have a negation toggle and an 'unspecified'/'unimportant' toggle/option. 

By default and with the "All rooms" quasi-space selected and given that all fields are set to default/unspecified/unimportant, all rooms would be listed. Selecting a space in the tree view would, in addition to entering that space in the tree view, automatically set as a criteria that the rooms be somewhere under that space.

Simple criteria could filter for things like
- Whether it's a space or not
- Is somewhere under a certain space (with an additional dropdown for optional max depth) - default is currently viewed space in tree view
- Room id, alias or name substring/regex
- Maybe even whether it has events/messages matching some criteria, and selecting a matching room could show its timeline filtered for only those events/messages - this would subsume typical message search

Advanced criteria could include
- Rooms where you have or don't have certain permissions (example use cases: see all rooms and spaces you moderate; list all no-participation feeds)
- Has/doesn't have a certain member username (example use cases: find a bad actor across all rooms to notify the mods; list rooms your alt account is or isn't in)
- Minimum/maximum member count (example use cases: list only your own private rooms; list big rooms) - min/max subsumes negation here
- Visibility setting (example use case: see only your private chats and communities)
- Minimum/maximum number of messages in the last X days - min/max subsumes negation here too

The filtering capabilities could be theoretically limitless if, on top of offering a set of predefined basic criteria fields, you have a field for entering arbitrary `jq` expressions that return a list of room ids.

### Happens in the latest version

- [X] Yes, this feature is still missing.

**Comment by lboklin** [comment]
Added another crazy idea as alternative to offering two viewing modes

**Comment by lboklin** [comment]
But the way it works now you only see direct children of the currently selected space anyway? And I described two ways to provide what you describe. This is an alternative to how it works when you _don't_ have "All rooms" selected, which is the only way you get what you describe currently.

**Comment by lboklin** [comment]
And to add: the way file managers work in list/grid view (which _are_ the usual defaults) is not how Nheko works now, so I don't think that's a valid point. I wouldn't mind if the list view was the default as long as the tree view is available and the spaces and room lists are unified (which is the actual point of this suggestion and you didn't comment on that aspect).

**Comment by deepbluev7** [comment]
I was thinking more of file managers like this:

![image](https://user-images.githubusercontent.com/16312324/156860255-9199d535-ad59-4af7-9fe3-63ea0d581e74.png)


Unifying spaces list and room list has the problem, that you now have rooms twice in the list and your notifications won't be at the top. I commented on multiple issues already that I don't like segmenting the roomlist, because it makes notifications a pain to manage. So I have no intention to implement that. If someone can come up with a good implementation of that, I would take a look at it, but most of the ones I have seen are not nice to use imo. So I will be closing this for now, because I don't think this is a good approach to it and I don't plan on doing it. If someone else wants to, they can implement it independent of this issue being open, I guess.
