### ISSUE TITLE
user list pops up randomly in the composer

### ISSUE THREAD

**Issue by pavlukivan** [Nheko-Reborn/nheko#935]
### Describe the bug

I don't know what exactly causes it to happen, but so far it has happened a few times after switching to the nheko window (might've happened after me pressing Alt, not sure), and one time it happened when I was attempting to use a custom emote using the `~` key, but the user list appeared instead.

### To Reproduce

????

### What happened?

The user list pops up, as if the user pressed the `@` key

### Expected behavior

Nothing happening (or a custom emote list opening in case of `~`)

### Version

0.9.1-8af50b44 ([master](https://github.com/Nheko-Reborn/nheko/commit/6854cd7e80823bf23bd4ccde77b1a4fbcb3bfca9) with this patch https://github.com/Nheko-Reborn/nheko/pull/934)

### Installation method

Local build

### Did you use profiles?

- [ ] Profiles used?

**Comment by pavlukivan** [comment]
i think that was the case. Still weird it appeared instead of the emote list

**Comment by deepbluev7** [comment]
Hm, I need some way to reproduce that, otherwise I can't fix it. Because I didn't have that happen yet and I use the completers a lot.

**Comment by pavlukivan** [comment]
well, i'll just close this for now unless i reproduce it again

**Comment by pavlukivan** [comment]
ah, this was just me being confused - if you open the user selector and type `~`, it stays open
