### ISSUE TITLE
Add SAML/SSO login capability

### ISSUE THREAD

**Issue by xvitaly** [Nheko-Reborn/nheko#94]
Synapse and Riot support SSO via SAML. This allows to use easy authentication with a central user management.

Nheko supports only username/password authentication. As those don't exist side by side an SAML-enabled synapse instance can't be used with Nheko.

Riot already supports SAML-based setups. Some details on how to configure keycloak (as SAML reference) with synapse can be found here: https://edenmal.moe/post/2019/Matrix-Synapse-SAML2-Login/

Matrix protocol standard for SSO logins can be found here: https://matrix.org/docs/spec/client_server/r0.5.0#sso-client-login

**Comment by redsky17** [comment]
I agree that this is a great thing that Nheko should support.  Not sure when we'll get to it, but thanks for the suggestion!

**Comment by deepbluev7** [comment]
So, adding SSO should be fairly straightforward. We need to start a temporary http server though to get the login token, so that probably needs wrangling a bit with beast in nheko. Then we just need to call [sso/redirect](https://matrix.org/docs/spec/client_server/latest#get-matrix-client-r0-login-sso-redirect) and parse the token from that.

**Comment by cheloveg** [comment]
Sorry for kind of a dumb question, but how to login not using SSO, but using just login and password? When im trying to log in matrix.org account it sends me to a web page where it just asks for an identity provider. How do i login without using SSO?
![image](https://user-images.githubusercontent.com/52291394/152187676-e2532775-0cfa-41ee-80de-d8a4173e377c.png)

**Comment by redsky17** [comment]
What version of nheko are you running?  As far as I remember, this is an
issue that was fixed in 0.8.2 or 0.9.0 or so.

**Comment by cheloveg** [comment]
You are right, my version was 8.0.0, i installed a newer one from Flathub and the problem was fixed. Thanks!
