### ISSUE TITLE
Clicking off of context menus doesn't close the context menu

### ISSUE THREAD

**Issue by Cadair** [Nheko-Reborn/nheko#940]
### Describe the bug

When you open a context menu there is no way to dismiss it.

### To Reproduce

1. Right click
2. click somewhere else
3. observe context menu still open

### Expected behavior

Context menu is dismissed

### Version

0.9.1-dfb8f9a1

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Desktop Environment

sway (wayland)

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment]
Probably https://bugreports.qt.io/browse/QTBUG-83972

**Comment by LorenDB** [comment]
Fixed by #1319

**Comment by deepbluev7** [comment]
Not really fixed, but probably the best workaround we can do for now and we'll fix it properly with qt6
