### ISSUE TITLE
Moving the mouse to the quick actions bar changes the message that is highlighted

### ISSUE THREAD

**Issue by Cadair** [Nheko-Reborn/nheko#941]
### Describe the bug

When you mouse over a message the message is highlighted. When you move your cursor to the quick actions bar the message above is highlighted despite the fact you are still operating on the message below. This is very confusing.

### To Reproduce

![nheko](https://user-images.githubusercontent.com/1391051/154100165-2e20d680-113c-40ee-9f63-609c7705f076.png)

### Version

0.9.1-dfb8f9a1

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment]
Hm, maybe I should just nuke that highlighting feature...
