### ISSUE TITLE
Typing an address with `www` gets converted to wrong `<a>`

### ISSUE THREAD

**Issue by HarHarLinks** [Nheko-Reborn/nheko#944]
### Describe the bug

typing something that looks like a url starting in `www` like `www.github.com` is converted to a formatted body with `<a>` tag, which is
1. the wrong assumption: e.g. what protocol?
2. done wrongly: it's given as a relative address, not absolute address

### To Reproduce

1. type an address like `www.github.com`
2. view event source

### What happened?

`"formatted_body": "<a href=\"www.github.com\">www.github.com</a>",`

### Expected behavior

`"formatted_body": "www.github.com",` since protocol can't be assumed

### Version

0.9.1.r163.g6854cd7e-1

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Desktop Environment

sway 1.6

### Did you use profiles?

- [ ] Profiles used?

**Comment by LorenDB** [comment]
Just tested - this is no longer a problem on 0.11.3
