### ISSUE TITLE
Input methods don't always work as expected

### ISSUE THREAD

**Issue by maltee1** [Nheko-Reborn/nheko#964]
### Describe the bug

when using Nheko with an input method, several things don't work:
1. search-as-you-type for preedit text (i.e. text the input method may still change) everywhere I've tried this. Disabling the input method was my first approach, but this should work without.
2. typing @, # etc in MessageInput doesn't do anything.
3. deleting text in MessageInput sometimes gets messed up, text I just deleted will just appear randomly elsewhere.
4. Last but not least: preedit text is not sent from MessageInput. I've been getting used to confirming with punctuation or space, but I really shouldn't have to.

This is mostly a problem on mobile, but I was able to reproduce all of this on Desktop using ibus-pinyin. you can switch to latin ("English") for 2., that one doesn't need prediction to be triggered.

I was trying to fix some of this today, but I didn't get anyhwere.

**Comment by deepbluev7** [comment]
The issue is probably, that we are passing all inputs through to the backend :D

**Comment by maltee1** [comment]
wanna elaborate? I'm hoping to fix this.

**Comment by deepbluev7** [comment]
https://github.com/Nheko-Reborn/nheko/blob/master/resources/qml/MessageInput.qml#L140 doesn't really handle preedit text

**Comment by maltee1** [comment]
https://github.com/Nheko-Reborn/nheko/pull/1005 fixes 2 and 4, 3 might be an issue with maliit (other applications have it, too) and 1 probably can't be fixed as long as a TextField is used, which does not provide access to the preeditText.

**Comment by maltee1** [comment]
maybe you can close this since it's sorta fixed.
