### ISSUE TITLE
libmatrix_client.so.0.6.1: cannot open shared object file

### ISSUE THREAD

**Issue by clebermatheus** [Nheko-Reborn/nheko#967]
### Describe the bug

when open nheko show this error:
```
nheko: error while loading shared libraries: libmatrix_client.so.0.6.1: cannot open shared object file: No such file or directory
```

### To Reproduce

open nheko via terminal

### Version

0.9.1-2

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Qt version

5.15.2

### C++ compiler

gcc 11.2.0

### Desktop Environment

Arch Linux with i3 as window manager

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment]
Rebuild the AUR package.

**Comment by clebermatheus** [comment]
> Rebuild the AUR package.

it's works, thanks
