### ISSUE TITLE
Cannot get past ReCaptcha when creating new account

### ISSUE THREAD

**Issue by Christian-Gibbons** [Nheko-Reborn/nheko#97]
### System:

- Nheko version: 0.6.4-1b34b53 | Linux
- Installation method: Portage Overlay
- Operating System: Gentoo
- Qt version: 5.12.5
- C++ compiler: gcc 8.3.0
- Desktop Environment: XFCE

### Actual behavior
ReCaptcha button in dialog box opens new tab in web browser with Captcha.  Completing Captcha in browser has no effect on account account creation within
### Expected behavior
Captcha works however it is intended to and account is created
### Steps to reproduce
Try to create account (on Matrix.org, if it makes a difference)
Attempt to satisfy ReCaptcha requirement.

**Comment by redsky17** [comment]
Thanks for the issue report!  I have experienced this myself.  For right now, I would recommend creating your account through riot.im or perhaps one of the other myriad of clients available that support registration.  This is something that hopefully we'll fix once we also implement additional forms of sign-in (oauth and saml and whatnot).

**Comment by deepbluev7** [comment]
So I fixed the client side issue for that, but you will still get stuck at the captcha. I think this is because of https://github.com/matrix-org/synapse/issues/6705, as the captcha never gets added to the list of completed flows in the return value.
