### ISSUE TITLE
Replies without message bubbles take up the full width

### ISSUE THREAD

**Issue by deepbluev7** [Nheko-Reborn/nheko#972]
They should leave some space on the side, if the message doesn't span the whole line.

![grafik](https://user-images.githubusercontent.com/16312324/156865059-bb8281fe-986e-4da9-8ac4-3c01f8d6ef5e.png)

Probably a regression from when message bubbles got added.

**Comment by maltee1** [comment]
I explicitly made the replies span the width of control because it looked stupid in the bubble layout when they didn't... I could undo that, but I thought not adapting anything to the message width was sort of desired if the bubble layout is off...

**Comment by deepbluev7** [comment]
Well, we used to adapt the background of replies at least, because it looks weird. But if it is too much effort, I can live with it, it just doesn't look that great imo :D

**Comment by deepbluev7** [comment]
(outside of bubbles, in Bubbles spanning full with seems right)

**Comment by maltee1** [comment]
It's just a simple condition, should be sufficient to modify a single line.
