### ISSUE TITLE
Use system mouse cursor

### ISSUE THREAD

**Issue by JulianGro** [Nheko-Reborn/nheko#973]
### Describe the bug

nheko uses a different mouse cursor instead of the system one.

### To Reproduce

Install nheko via flatpak.
Profit.

### Expected behavior

nheko should use the system mouse cursor instead.

### Version

0.9.1-b9a4f369

### Operating system

Linux

### Installation method

Flathub

### Desktop Environment

Cinnamon (GTK based)

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment]
This is probably a flatpak limitation, when the flatpak doesn't have your system theme and can't render your cursor for that reason. I don't think there is anything we can do about that, that is just normal Qt theming issues, flatpak, etc stuff. (It uses the system cursor here on KDE, Gnome and Sway.)
