### ISSUE TITLE
Login screen barely readable

### ISSUE THREAD

**Issue by JulianGro** [Nheko-Reborn/nheko#974]
### Describe the bug

The buttons on the login screen are barely readable.

### To Reproduce

Install nheko via Flatpak
Profit

### Screenshots

![Bildschirmfoto vom 2022-03-06 06-28-08](https://user-images.githubusercontent.com/11144627/156910746-8b28e959-6fd8-4340-8e54-3d512d749bb8.png)

### Version

0.9.1-b9a4f369

### Operating system

Linux

### Installation method

Flathub

### Desktop Environment

Cinnamon (GTK based)

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment]
Fixed that already for the next release, but thanks for reporting :3
