### ISSUE TITLE
Explain SSO on login screen

### ISSUE THREAD

**Issue by JulianGro** [Nheko-Reborn/nheko#975]
### The Problem

A non-technical user, or even just a user that doesn't know what SSO stands for, will not know the difference between "login" and "SSO-login" without looking it up on the internet.

### The Solution

I would suggest not having the "SSO-login" button next to the login button, but rather have something like a "Want to use SSO instead?" text underneath that a user can click on. That way it is clear to the user which login button to press if they have no idea what SSO is.

### Alternatives

A tooltip for the SSO-login button that shows up immediately.

### Additional context
Current login screen:
![Bildschirmfoto vom 2022-03-06 06-28-08](https://user-images.githubusercontent.com/11144627/156910972-d89b6c25-cb83-416c-94e0-57a860a9f6b3.png)

### Happens in the latest version

- [X] Yes, this feature is still missing.

**Comment by deepbluev7** [comment]
I changed this now to explicitly list stuff as "Login using github" "Sign in with google", etc. SSO Login should now only be the fallback, when the server has this configured incompletely. That should be good enough for most people.
