### ISSUE TITLE
Remember last user name

### ISSUE THREAD

**Issue by Mte90** [Nheko-Reborn/nheko#977]
### The Problem

So I am having issue with logging and I have to close Nheko and every time to reinsert the username and the device name.
It is possible to remember it?

### The Solution

Remember for next login

### Happens in the latest version

- [X] Yes, this feature is still missing.

**Comment by deepbluev7** [comment]
While it would be possible, I don't think it is a good feature to have. When you sign out, you want you data to be gone. You usually either want to sign into a different account or so. And the convenience of not having to type your username again is not that big compared to the possible complications. You can also change the device name after login nowadays, so I don't think the complexity is worth it.
