### ISSUE TITLE
Cancel edit button covers message that is replied to

### ISSUE THREAD

**Issue by tastytea** [Nheko-Reborn/nheko#978]
### Describe the bug

When I edit a message that is a reply, the replied to message is covered by the cancel button. This is annoying when I want to change the message that is replied to with `Alt + ↑`. It is difficult to see if I selected the right message.

### To Reproduce

1. Write message
2. Edit message
3. Change the replied to message  with `Alt + ↑`
4. Replied to message is covered

### Screenshots

![screenshot_2022-03-07T13:53](https://user-images.githubusercontent.com/3681516/157038641-3bc16887-4bd8-4d6f-9cc7-bb5bb74c230f.png)

### Version

0.9.1-ac1d6782

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Qt version

5.15.2

### C++ compiler

gcc 11.2.0

### Desktop Environment

n/a

### Did you use profiles?

- [ ] Profiles used?

**Comment by deepbluev7** [comment]
Yeah, we really need a better button for this. But everything I tried was confusing, so that's why we have this ugly button :D

**Comment by maltee1** [comment]
The best way to fix this would be to edit the message where it is and replace the input bar by the "cancel edit" button. Not sure how difficult that would be.

**Comment by deepbluev7** [comment]
That would mean we need to duplicate all the editing logic. In Element that caused a lot of bugs. I'd rather avoid that. We could put the cancel button on the message being edited, but that doesn't seem great :D

**Comment by tastytea** [comment]
Could we make the button just smaller, maybe replace the text with a cancel icon? And move the X from the reply to the highlighted area to avoid confusion.

![nheko-edit-reply](https://user-images.githubusercontent.com/3681516/157832804-57f4de25-740e-40e9-9246-89d617c72cd4.png)

**Comment by maltee1** [comment]
How about these:
- x button on the bottom right of the popup with an appropriate tooltip. The x button for the reply should be on the replied-to message anyway, rather than next to it - that way we can tell them apart
- place the x button next to the input bar along with the other buttons. Semantically, it makes most sense there, but it might just blend in with the other buttons and not be noticed.
- place it on top of the send button and make adapt the height of the message input accordingly.

**Comment by maltee1** [comment]
Since tastytea suggested my first option, I'll just implement that, unless someone has a better idea. The reply popup has been bugging me anyway.

**Comment by deepbluev7** [comment]
Fix in #989
