### ISSUE TITLE
Buttons Cut from Screen

### ISSUE THREAD

**Issue by Peter2469** [Nheko-Reborn/nheko#998]
### Describe the bug

The buttons to "Cancel" and "Send" is slightly cut off on my device (Pinephone)

### To Reproduce

1. Go to friends' DMs
2. Try to upload an image
3. The "Upload image/[file format]" buttons are cut off slightly

### What happened?

The buttons are slightly cut off requiring you to press precisely to send the image which would be fine if you don't have fat fingers :D

### Expected behavior

The buttons should be fully shown and not cut off

### Screenshots

![image](https://user-images.githubusercontent.com/48802254/158079081-c8b293ad-14da-4b5c-9b2b-c528cad9baf6.png)

### Version

0.9.2-e98145da

### Operating system

Linux

### Installation method

Some repository (AUR, homebrew, distribution repository, PPA, etc)

### Qt version

5.15.3

### C++ compiler

gcc 11.2.0

### Desktop Environment

KDE Plasma Mobile

### Did you use profiles?

- [ ] Profiles used?

**Comment by maltee1** [comment]
fixed with the new uploader
